/* Transformation Name ==>DELINQ ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='DELINQ',
		schema='',
		pre_hook ="CALL CORE_SVC.pkg_rename.truncate_load_table ( 'DELINQ' ) ",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_ACCT_LOAD_MAPPINGOut as (
	Select ACCT_NBR, 
		CONCISE_ACCT_NBR, 
		PARTIAL_ACCT_NBR, 
		SYS_OF_RECRD_NM, 
		VIN, 
		TRANSACT_ACCT_NBR, 
		APLN_NBR, 
		BKRPT_CASE_NBR, 
		LICNS_PLATE_NBR, 
		PROD_TYPE_CD, 
		COMMRCL_IND, 
		ACCT_STATUS_CD, 
		LEGAL_STATUS_CD, 
		ACCRL_STATUS_CD, 
		BKRPT_STATUS_CD, 
		CHRG_OFF_STATUS_CD, 
		REPO_STATUS_CD, 
		ACCT_CLS_DT, 
		BRANCH_NBR, 
		DLR_NBR, 
		ORIGNT_CONTRCT_DT, 
		ORIGNT_COUNTRY_CD, 
		ORIGNT_STATE_PRVNCE_CD, 
		SCHED_PMT_AMT, 
		PMT_DUE_DT, 
		LAST_PMT_AMT, 
		LAST_PMT_DT, 
		AUTOPMT_IND, 
		EFT_LAST_PMT_AMT, 
		EFT_LAST_PMT_DT, 
		EFT_NEXT_PMT_AMT, 
		EFT_NEXT_PMT_DT, 
		WEB_PMT_DECLN_CD, 
		LATE_FEE_DUE_AMT, 
		VEH_MAKE_NM, 
		VEH_MODEL_NM, 
		VEH_YR, 
		PMT_MADE_QTY, 
		DAY_PAST_DUE_QTY, 
		PAST_DUE_30_QTY, 
		PAST_DUE_60_QTY, 
		PAST_DUE_90_QTY, 
		OLDEST_UNMET_DUE_DT, 
		CHRG_OFF_AMT, 
		CHRG_OFF_DT, 
		ORIG_ACCT_MATURITY_DT, 
		ORIG_TERM_MNTH_QTY, 
		CURR_MATURITY_DT, 
		CURR_TERM_MNTH_QTY, 
		COLLAT_EXCEPTN_CD, 
		TITLE_RELEASE_DT, 
		TITLE_MAILING_DT, 
		TITLE_MAILING_ADDR_TXT, 
		COLLECT_CTR_NBR, 
		LOAN_ORIG_BAL_AMT, 
		LOAN_CURR_BAL_AMT, 
		CURR_INTRST_DUE_AMT, 
		FIRST_PMT_DUE_DT, 
		LAST_YR_INTRST_PD_AMT, 
		NEXT_PMT_AMT, 
		NEXT_PROMISE_AMT, 
		NEXT_PROMISE_DT, 
		PAST_DUE_AMT, 
		PAYOFF_IND, 
		PAYOFF_DT, 
		CONTRCT_MILE_AMT, 
		TAX_PMT_AMT, 
		SECUR_DEPOSIT_AMT, 
		BASE_RENT_AMT, 
		RECOV_STATUS_CD, 
		SINGL_PMT_IND, 
		TERM_TYPE_CD, 
		NEXT_MATURITY_DT, 
		REMAIN_PMT_QTY, 
		CREDIT_BUR_SPECL_CD, 
		CREDIT_BUR_STATUS_CD, 
		COMPLNC_CONDTN_CD, 
		CREDIT_RPT_CD, 
		SALES_TAX_AMT, 
		LAST_NSF_DT, 
		NSF_QTY, 
		CURR_AMT_DUE
 from 
{{ source ('DBConnection_SVC_INFA_ETL_CORE','ACCT_LOAD_MAPPING') }} 
 ),

exp_InitialOut as (
	
Select 
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
DAY_PAST_DUE_QTY as DAY_PAST_DUE_QTY,
PAST_DUE_30_QTY as PAST_DUE_30_QTY,
PAST_DUE_60_QTY as PAST_DUE_60_QTY,
PAST_DUE_90_QTY as PAST_DUE_90_QTY,
OLDEST_UNMET_DUE_DT as OLDEST_UNMET_DUE_DT
From SQ_ACCT_LOAD_MAPPINGOut as SQ_ACCT_LOAD_MAPPINGOut),

exp_FinalOut as (
	
Select 
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
DAY_PAST_DUE_QTY as DAY_PAST_DUE_QTY,
PAST_DUE_30_QTY as PAST_DUE_30_QTY,
PAST_DUE_60_QTY as PAST_DUE_60_QTY,
PAST_DUE_90_QTY as PAST_DUE_90_QTY,
OLDEST_UNMET_DUE_DT as OLDEST_UNMET_DUE_DT,
CURRENT_TIMESTAMP as INSERT_DT 
From exp_InitialOut as exp_InitialOut Where DAY_PAST_DUE_QTY IS NOT NULL OR PAST_DUE_30_QTY IS NOT NULL OR PAST_DUE_60_QTY IS NOT NULL OR PAST_DUE_90_QTY IS NOT NULL OR OLDEST_UNMET_DUE_DT IS NOT NULL),

DSR_DELINQOut as (
	
Select 
exp_FinalOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
exp_FinalOut.INSERT_DT as INSERT_DT,
exp_FinalOut.DAY_PAST_DUE_QTY as DAYS_PAST_DUE_NBR,
exp_FinalOut.PAST_DUE_30_QTY as PAST_DUE_30_QTY,
exp_FinalOut.PAST_DUE_60_QTY as PAST_DUE_60_QTY,
exp_FinalOut.PAST_DUE_90_QTY as PAST_DUE_90_QTY,
exp_FinalOut.OLDEST_UNMET_DUE_DT as OLDEST_UNMET_DUE_DT
From exp_FinalOut as exp_FinalOut)


Select 
	CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	INSERT_DT as INSERT_DT,
	DAYS_PAST_DUE_NBR as DAYS_PAST_DUE_NBR,
	PAST_DUE_30_QTY as PAST_DUE_30_QTY,
	PAST_DUE_60_QTY as PAST_DUE_60_QTY,
	PAST_DUE_90_QTY as PAST_DUE_90_QTY,
	OLDEST_UNMET_DUE_DT as OLDEST_UNMET_DUE_DT 
From DSR_DELINQOut as DSR_DELINQOut