version: 2

models:
  - name: int_s_ACTIVITYMAPPING_VERINT_ACTV_MAP_UPD_INS
    description: "Intermediate transformation for VERINT_ACTV_MAP_UPD_INS"
    columns:
      - name: ACTV_MAP_ID
        description: "ACTV_MAP_ID"
      - name: SOR_CD
        description: "SOR_CD"
      - name: EFF_DTTM
        description: "EFF_DTTM"
      - name: END_DTTM
        description: "END_DTTM"
      - name: UNQ_KEY_TXT
        description: "UNQ_KEY_TXT"
      - name: ACTV_ID
        description: "ACTV_ID"
      - name: MAPPED_ACTV_ID
        description: "MAPPED_ACTV_ID"
      - name: MOD_BY
        description: "MOD_BY"
      - name: AUD_CRE_BY_NM
        description: "AUD_CRE_BY_NM"
      - name: AUD_CRE_DTTM
        description: "AUD_CRE_DTTM"
      - name: ETL_BATCH_ID
        description: "ETL_BATCH_ID"
      - name: CURR_IND
        description: "CURR_IND"
  - name: int_s_ACTIVITYMAPPING_VERINT_ACTV_MAP_1
    description: "Intermediate transformation for VERINT_ACTV_MAP_1"
    columns:
      - name: ACTV_MAP_ID
        description: "ACTV_MAP_ID"
      - name: EFF_DTTM
        description: "EFF_DTTM"
      - name: END_DTTM
        description: "END_DTTM"
      - name: AUD_UPD_BY_NM
        description: "AUD_UPD_BY_NM"
      - name: AUD_UPD_DTTM
        description: "AUD_UPD_DTTM"
      - name: CURR_IND
        description: "CURR_IND"
  - name: int_s_ACTIVITYMAPPING_VERINT_ACTV_MAP_INS
    description: "Intermediate transformation for VERINT_ACTV_MAP_INS"
    columns:
      - name: ACTV_MAP_ID
        description: "ACTV_MAP_ID"
      - name: SOR_CD
        description: "SOR_CD"
      - name: EFF_DTTM
        description: "EFF_DTTM"
      - name: END_DTTM
        description: "END_DTTM"
      - name: UNQ_KEY_TXT
        description: "UNQ_KEY_TXT"
      - name: ACTV_ID
        description: "ACTV_ID"
      - name: MAPPED_ACTV_ID
        description: "MAPPED_ACTV_ID"
      - name: MOD_BY
        description: "MOD_BY"
      - name: AUD_CRE_BY_NM
        description: "AUD_CRE_BY_NM"
      - name: AUD_CRE_DTTM
        description: "AUD_CRE_DTTM"
      - name: ETL_BATCH_ID
        description: "ETL_BATCH_ID"
      - name: CURR_IND
        description: "CURR_IND"
