/* Transformation Name ==>ACCT_NBR_TIN_XREF ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='ACCT_NBR_TIN_XREF',
		schema='',
		pre_hook ="CALL CORE_SVC.pkg_rename.truncate_load_table ( 'ACCT_NBR_TIN_XREF' ) ",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_ACCT_NBR_TIN_XREFOut as (
	Select TAX_ID_NBR, 
		COUNTRY_CD, 
		ACCT_NBR, 
		TAX_ID_LAST_FOUR_NBR, 
		CONCISE_ACCT_NBR, 
		LEGACY_ACCT_NBR, 
		PARTIAL_ACCT_NBR, 
		SYS_OF_RECRD_NM, 
		TRANSACT_ACCT_NBR, 
		CUSTMR_TYPE_CD
 from 
{{ source ('DBConnection_SVC_INFA_ETL_CORE','ACCT_NBR_TIN_XREF') }} 
 ),

exp_InitialOut as (
	
Select 
TAX_ID_NBR as TAX_ID_NBR,
COUNTRY_CD as COUNTRY_CD,
ACCT_NBR as ACCT_NBR,
TAX_ID_LAST_FOUR_NBR as TAX_ID_LAST_FOUR_NBR,
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
LEGACY_ACCT_NBR as LEGACY_ACCT_NBR,
PARTIAL_ACCT_NBR as PARTIAL_ACCT_NBR,
SYS_OF_RECRD_NM as SYS_OF_RECRD_NM,
TRANSACT_ACCT_NBR as TRANSACT_ACCT_NBR,
CUSTMR_TYPE_CD as CUSTMR_TYPE_CD
From SQ_ACCT_NBR_TIN_XREFOut as SQ_ACCT_NBR_TIN_XREFOut),

exp_FinalOut as (
	
Select 
( CASE WHEN ACCT_NBR IS NOT NULL THEN LTRIM ( RTRIM ( ACCT_NBR ) ) ELSE NULL END ) as ACCT_NBR_out,
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
( CASE WHEN TRANSACT_ACCT_NBR IS NOT NULL THEN LTRIM ( RTRIM ( TRANSACT_ACCT_NBR ) ) ELSE NULL END ) as TRANSACT_ACCT_NBR_out,
( CASE WHEN PARTIAL_ACCT_NBR IS NOT NULL THEN LTRIM ( RTRIM ( PARTIAL_ACCT_NBR ) ) ELSE NULL END ) as PARTIAL_ACCT_NBR_out,
( CASE WHEN LEGACY_ACCT_NBR IS NOT NULL THEN SUBSTRING ( LTRIM ( RTRIM ( LEGACY_ACCT_NBR ) ),
1,
12 ) ELSE NULL END ) as LEGACY_ACCT_NBR_out,
( CASE WHEN SYS_OF_RECRD_NM IS NOT NULL THEN LTRIM ( RTRIM ( SYS_OF_RECRD_NM ) ) ELSE NULL END ) as SYS_OF_RECRD_NM_out,
( CASE WHEN TAX_ID_NBR IS NOT NULL THEN LTRIM ( RTRIM ( TAX_ID_NBR ) ) ELSE NULL END ) as TAX_ID_NBR_out,
( CASE WHEN TAX_ID_LAST_FOUR_NBR IS NOT NULL THEN LTRIM ( RTRIM ( TAX_ID_LAST_FOUR_NBR ) ) ELSE NULL END ) as TAX_ID_LAST_FOUR_NBR_out,
( CASE WHEN COUNTRY_CD IS NOT NULL THEN LTRIM ( RTRIM ( COUNTRY_CD ) ) ELSE NULL END ) as COUNTRY_CD_out,
( CASE WHEN CUSTMR_TYPE_CD IS NOT NULL THEN LTRIM ( RTRIM ( CUSTMR_TYPE_CD ) ) ELSE NULL END ) as COMMRCL_IND,
DATE_TRUNC ( 'DAY',
CURRENT_TIMESTAMP ) as INSERT_DT 
From exp_InitialOut as exp_InitialOut Where TAX_ID_NBR IS NOT NULL AND ACCT_NBR IS NOT NULL AND CONCISE_ACCT_NBR IS NOT NULL AND TRANSACT_ACCT_NBR IS NOT NULL AND PARTIAL_ACCT_NBR IS NOT NULL AND SYS_OF_RECRD_NM IS NOT NULL AND TAX_ID_LAST_FOUR_NBR IS NOT NULL),

DSR_ACCT_NBR_TIN_XREFOut as (
	
Select 
exp_FinalOut.TAX_ID_NBR_out as TAX_ID_NBR,
exp_FinalOut.COUNTRY_CD_out as COUNTRY_CD,
exp_FinalOut.ACCT_NBR_out as ACCT_NBR,
exp_FinalOut.TAX_ID_LAST_FOUR_NBR_out as TAX_ID_LAST_FOUR_NBR,
exp_FinalOut.TRANSACT_ACCT_NBR_out as TRANSACT_ACCT_NBR,
exp_FinalOut.PARTIAL_ACCT_NBR_out as PARTIAL_ACCT_NBR,
exp_FinalOut.LEGACY_ACCT_NBR_out as LEGACY_ACCT_NBR,
exp_FinalOut.SYS_OF_RECRD_NM_out as SYS_OF_RECRD_NM,
exp_FinalOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
exp_FinalOut.COMMRCL_IND as COMMRCL_IND,
exp_FinalOut.INSERT_DT as INSERT_DT
From exp_FinalOut as exp_FinalOut)


Select 
	TAX_ID_NBR as TAX_ID_NBR,
	COUNTRY_CD as COUNTRY_CD,
	ACCT_NBR as ACCT_NBR,
	TAX_ID_LAST_FOUR_NBR as TAX_ID_LAST_FOUR_NBR,
	TRANSACT_ACCT_NBR as TRANSACT_ACCT_NBR,
	PARTIAL_ACCT_NBR as PARTIAL_ACCT_NBR,
	LEGACY_ACCT_NBR as LEGACY_ACCT_NBR,
	SYS_OF_RECRD_NM as SYS_OF_RECRD_NM,
	CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	COMMRCL_IND as COMMRCL_IND,
	INSERT_DT as INSERT_DT 
From DSR_ACCT_NBR_TIN_XREFOut as DSR_ACCT_NBR_TIN_XREFOut