/* Transformation Name ==>VEH ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='VEH',
		schema='',
		pre_hook ="CALL CORE_SVC.pkg_rename.truncate_load_table ( 'VEH' ) ",
		post_hook ="",
		incremental_strategy='append')
}}

With VEH_COLLATOut as (
	Select UNIQUE_ID, 
		LOAD_DT, 
		ACCT_NBR, 
		ACCT_SHORT_NBR, 
		ACCT_SHORT_NBR_CD, 
		SRCE_SYS, 
		VIN_NBR, 
		VEH_YEAR, 
		VEH_NEW_USED_CD, 
		VEH_ORIG_AGE, 
		VEH_MAKE_NM, 
		VEH_MAKE_CD, 
		VEH_MODEL_NM, 
		VEH_MODEL_CD, 
		VEH_BODY_STYLE_NM, 
		VEH_INFO_DESCR, 
		VEH_LICENSE_STATE_CD, 
		VEH_COLOR, 
		VEH_DOOR_QTY, 
		VEH_TRANSMSN_TYPE, 
		VEH_DRIVE_TYPE, 
		VEH_FUEL_TYPE_CD, 
		VEH_ENG_TYPE_DESCR, 
		VEH_ORIG_MILEAGE_QTY, 
		VEH_WHOLESL_VAL_AMT, 
		VEH_TRADE_VAL_AMT, 
		VEH_BASE_MSRP_AMT, 
		VEH_MSRP_ADDS_AMT, 
		VEH_TOTL_MSRP_AMT, 
		VEH_INVC_AMT, 
		VEH_MRKP_AMT, 
		VEH_ORIG_VAL_AMT, 
		TITL_FLW_UP_IND, 
		TITL_STATUS_CD, 
		LAST_TITL_MAINT_DT, 
		CUST_ADDR_NBR, 
		COLLAT_VIN_MISSING_IND, 
		SUBST_OF_COLLAT_IND, 
		MULTI_SOC_IND, 
		PV_PRIVATE_LABEL, 
		PV_LINE_TYPE_I1, 
		PV_LINE_DATA_I1, 
		SOC_STAT, 
		NBR_OF_SOC, 
		SOC_COMPLT_DT, 
		BLN_MAX_TERM_MILE_QTY, 
		BLN_MILE_FEE_AMT, 
		EXTRA_DISTNC_CONTRCT_CHRG_AMT, 
		EXTRA_DISTNC_PURCH_CHRG_AMT, 
		EXTRA_DISTNC_CONTRCT_PURCH_QTY, 
		EXTRA_DISTNC_PURCH_QTY, 
		GARAGING_CITY_CD, 
		GARAGING_COUNTY_CD, 
		TITL_STATUS_DESCR, 
		INSUR_STATUS_CD, 
		SVCNG_SYS_MAKE_NM, 
		SVCNG_SYS_MODEL_NM, 
		SVCNG_SYS_VEH_YR, 
		SVCNG_SYS_BODY_STYLE_NM, 
		SVCNG_SYS_MAKE_CD, 
		SVCNG_SYS_MODEL_CD, 
		VEH_TYPE_CD, 
		GARAGING_STATE_CD, 
		GARAGING_COUNTRY_CD, 
		GARAGING_POST_CD, 
		GARAGING_CITY_NM, 
		GARAGING_ADDR_LINE_1_TXT, 
		GARAGING_ADDR_LINE_2_TXT, 
		FAIR_MKT_VAL_AMT, 
		DISPOSE_DT, 
		GRS_VEH_WT, 
		VEH_TRIM_DESCR, 
		AUCTN_ODOMETER_QTY, 
		AVG_MKT_VAL_AMT, 
		VEH_REGSTR_NBR, 
		COLLAT_CHNGE_DT, 
		GARAGING_STATE_GEOG_CD, 
		GM_IND, 
		GARAGING_LAST_PROCESS_DT, 
		SRCE_EFF_DT, 
		IN_ACCT_NBR
 from 
{{ source ('DBConnection_SVC_INFA_ETL_DW6','VEH_COLLAT') }}
 ),

VIN_LOOKUPOut as (
	Select VIN_KEY, 
		FUEL_TYPE_CD, 
		fuel_type_cd_VIN
 from 
{{ source ('DBConnection_SVC_INFA_ETL_DW7_1','VIN_LOOKUP') }}
 ),

SQ_ACCT_LOAD_MAPPINGOut as (
	Select ACCT_NBR, 
		CONCISE_ACCT_NBR, 
		PARTIAL_ACCT_NBR, 
		SYS_OF_RECRD_NM, 
		VIN, 
		TRANSACT_ACCT_NBR, 
		APLN_NBR, 
		BKRPT_CASE_NBR, 
		LICNS_PLATE_NBR, 
		PROD_TYPE_CD, 
		COMMRCL_IND, 
		ACCT_STATUS_CD, 
		LEGAL_STATUS_CD, 
		ACCRL_STATUS_CD, 
		BKRPT_STATUS_CD, 
		CHRG_OFF_STATUS_CD, 
		REPO_STATUS_CD, 
		ACCT_CLS_DT, 
		BRANCH_NBR, 
		DLR_NBR, 
		ORIGNT_CONTRCT_DT, 
		ORIGNT_COUNTRY_CD, 
		ORIGNT_STATE_PRVNCE_CD, 
		SCHED_PMT_AMT, 
		PMT_DUE_DT, 
		LAST_PMT_AMT, 
		LAST_PMT_DT, 
		AUTOPMT_IND, 
		EFT_LAST_PMT_AMT, 
		EFT_LAST_PMT_DT, 
		EFT_NEXT_PMT_AMT, 
		EFT_NEXT_PMT_DT, 
		WEB_PMT_DECLN_CD, 
		LATE_FEE_DUE_AMT, 
		VEH_MAKE_NM, 
		VEH_MODEL_NM, 
		VEH_YR, 
		PMT_MADE_QTY, 
		DAY_PAST_DUE_QTY, 
		PAST_DUE_30_QTY, 
		PAST_DUE_60_QTY, 
		PAST_DUE_90_QTY, 
		OLDEST_UNMET_DUE_DT, 
		CHRG_OFF_AMT, 
		CHRG_OFF_DT, 
		ORIG_ACCT_MATURITY_DT, 
		ORIG_TERM_MNTH_QTY, 
		CURR_MATURITY_DT, 
		CURR_TERM_MNTH_QTY, 
		COLLAT_EXCEPTN_CD, 
		TITLE_RELEASE_DT, 
		TITLE_MAILING_DT, 
		TITLE_MAILING_ADDR_TXT, 
		COLLECT_CTR_NBR, 
		LOAN_ORIG_BAL_AMT, 
		LOAN_CURR_BAL_AMT, 
		CURR_INTRST_DUE_AMT, 
		FIRST_PMT_DUE_DT, 
		LAST_YR_INTRST_PD_AMT, 
		NEXT_PMT_AMT, 
		NEXT_PROMISE_AMT, 
		NEXT_PROMISE_DT, 
		PAST_DUE_AMT, 
		PAYOFF_IND, 
		PAYOFF_DT, 
		CONTRCT_MILE_AMT, 
		TAX_PMT_AMT, 
		SECUR_DEPOSIT_AMT, 
		BASE_RENT_AMT, 
		RECOV_STATUS_CD, 
		SINGL_PMT_IND, 
		TERM_TYPE_CD, 
		NEXT_MATURITY_DT, 
		REMAIN_PMT_QTY, 
		CREDIT_BUR_SPECL_CD, 
		CREDIT_BUR_STATUS_CD, 
		COMPLNC_CONDTN_CD, 
		CREDIT_RPT_CD, 
		SALES_TAX_AMT, 
		LAST_NSF_DT, 
		NSF_QTY, 
		CURR_AMT_DUE, 
		INSERT_TM
 from 
{{ source ('DBConnection_SVC_INFA_ETL_CORE','ACCT_LOAD_MAPPING') }} 
 Where NOT VIN IS NULL
 ),

exp_Initial_variableOut as (
	
Select 
ACCT_NBR as ACCT_NBR,
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
VIN as VIN_in,
LICNS_PLATE_NBR as LICNS_PLATE_NBR_in,
VEH_MAKE_NM as VEH_MAKE_NM_in,
VEH_MODEL_NM as VEH_MODEL_NM_in,
VEH_YR as VEH_YR,
INSERT_TM as INSERT_TM,
( CASE WHEN VIN_in IS NOT NULL THEN LTRIM ( RTRIM ( VIN_in ) ) ELSE NULL END ) as VIN_var
From SQ_ACCT_LOAD_MAPPINGOut as SQ_ACCT_LOAD_MAPPINGOut),

exp_InitialOut as (
	
Select 
ACCT_NBR as ACCT_NBR,
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
VIN_var as VIN,
SUBSTRING ( VIN_var,
1,
8 ) || '_' || SUBSTRING ( VIN_var,
10,
1 ) as VIN_fuel_type_cd,
( CASE WHEN LICNS_PLATE_NBR_in IS NOT NULL THEN LTRIM ( RTRIM ( LICNS_PLATE_NBR_in ) ) ELSE NULL END ) as LICNS_PLATE_NBR,
( CASE WHEN VEH_MAKE_NM_in IS NOT NULL THEN LTRIM ( RTRIM ( VEH_MAKE_NM_in ) ) ELSE NULL END ) as VEH_MAKE_NM,
( CASE WHEN VEH_MODEL_NM_in IS NOT NULL THEN LTRIM ( RTRIM ( VEH_MODEL_NM_in ) ) ELSE NULL END ) as VEH_MODEL_NM,
VEH_YR as VEH_YR,
INSERT_TM as INSERT_TM
From exp_Initial_variableOut as exp_Initial_variableOut),

LKP_PIXL_VEH_COLLATOut as (
	Select 
	UNIQUE_ID as UNIQUE_ID,
	 LOAD_DT as LOAD_DT,
	 ACCT_NBR as ACCT_NBR,
	 ACCT_SHORT_NBR as ACCT_SHORT_NBR,
	 ACCT_SHORT_NBR_CD as ACCT_SHORT_NBR_CD,
	 SRCE_SYS as SRCE_SYS,
	 VIN_NBR as VIN_NBR,
	 VEH_YEAR as VEH_YEAR,
	 VEH_NEW_USED_CD as VEH_NEW_USED_CD,
	 VEH_ORIG_AGE as VEH_ORIG_AGE,
	 VEH_MAKE_NM as VEH_MAKE_NM,
	 VEH_MAKE_CD as VEH_MAKE_CD,
	 VEH_MODEL_NM as VEH_MODEL_NM,
	 VEH_MODEL_CD as VEH_MODEL_CD,
	 VEH_BODY_STYLE_NM as VEH_BODY_STYLE_NM,
	 VEH_INFO_DESCR as VEH_INFO_DESCR,
	 VEH_LICENSE_STATE_CD as VEH_LICENSE_STATE_CD,
	 VEH_COLOR as VEH_COLOR,
	 VEH_DOOR_QTY as VEH_DOOR_QTY,
	 VEH_TRANSMSN_TYPE as VEH_TRANSMSN_TYPE,
	 VEH_DRIVE_TYPE as VEH_DRIVE_TYPE,
	 VEH_FUEL_TYPE_CD as VEH_FUEL_TYPE_CD,
	 VEH_ENG_TYPE_DESCR as VEH_ENG_TYPE_DESCR,
	 VEH_ORIG_MILEAGE_QTY as VEH_ORIG_MILEAGE_QTY,
	 VEH_WHOLESL_VAL_AMT as VEH_WHOLESL_VAL_AMT,
	 VEH_TRADE_VAL_AMT as VEH_TRADE_VAL_AMT,
	 VEH_BASE_MSRP_AMT as VEH_BASE_MSRP_AMT,
	 VEH_MSRP_ADDS_AMT as VEH_MSRP_ADDS_AMT,
	 VEH_TOTL_MSRP_AMT as VEH_TOTL_MSRP_AMT,
	 VEH_INVC_AMT as VEH_INVC_AMT,
	 VEH_MRKP_AMT as VEH_MRKP_AMT,
	 VEH_ORIG_VAL_AMT as VEH_ORIG_VAL_AMT,
	 TITL_FLW_UP_IND as TITL_FLW_UP_IND,
	 TITL_STATUS_CD as TITL_STATUS_CD,
	 LAST_TITL_MAINT_DT as LAST_TITL_MAINT_DT,
	 CUST_ADDR_NBR as CUST_ADDR_NBR,
	 COLLAT_VIN_MISSING_IND as COLLAT_VIN_MISSING_IND,
	 SUBST_OF_COLLAT_IND as SUBST_OF_COLLAT_IND,
	 MULTI_SOC_IND as MULTI_SOC_IND,
	 PV_PRIVATE_LABEL as PV_PRIVATE_LABEL,
	 PV_LINE_TYPE_I1 as PV_LINE_TYPE_I1,
	 PV_LINE_DATA_I1 as PV_LINE_DATA_I1,
	 SOC_STAT as SOC_STAT,
	 NBR_OF_SOC as NBR_OF_SOC,
	 SOC_COMPLT_DT as SOC_COMPLT_DT,
	 BLN_MAX_TERM_MILE_QTY as BLN_MAX_TERM_MILE_QTY,
	 BLN_MILE_FEE_AMT as BLN_MILE_FEE_AMT,
	 EXTRA_DISTNC_CONTRCT_CHRG_AMT as EXTRA_DISTNC_CONTRCT_CHRG_AMT,
	 EXTRA_DISTNC_PURCH_CHRG_AMT as EXTRA_DISTNC_PURCH_CHRG_AMT,
	 EXTRA_DISTNC_CONTRCT_PURCH_QTY as EXTRA_DISTNC_CONTRCT_PURCH_QTY,
	 EXTRA_DISTNC_PURCH_QTY as EXTRA_DISTNC_PURCH_QTY,
	 GARAGING_CITY_CD as GARAGING_CITY_CD,
	 GARAGING_COUNTY_CD as GARAGING_COUNTY_CD,
	 TITL_STATUS_DESCR as TITL_STATUS_DESCR,
	 INSUR_STATUS_CD as INSUR_STATUS_CD,
	 SVCNG_SYS_MAKE_NM as SVCNG_SYS_MAKE_NM,
	 SVCNG_SYS_MODEL_NM as SVCNG_SYS_MODEL_NM,
	 SVCNG_SYS_VEH_YR as SVCNG_SYS_VEH_YR,
	 SVCNG_SYS_BODY_STYLE_NM as SVCNG_SYS_BODY_STYLE_NM,
	 SVCNG_SYS_MAKE_CD as SVCNG_SYS_MAKE_CD,
	 SVCNG_SYS_MODEL_CD as SVCNG_SYS_MODEL_CD,
	 VEH_TYPE_CD as VEH_TYPE_CD,
	 GARAGING_STATE_CD as GARAGING_STATE_CD,
	 GARAGING_COUNTRY_CD as GARAGING_COUNTRY_CD,
	 GARAGING_POST_CD as GARAGING_POST_CD,
	 GARAGING_CITY_NM as GARAGING_CITY_NM,
	 GARAGING_ADDR_LINE_1_TXT as GARAGING_ADDR_LINE_1_TXT,
	 GARAGING_ADDR_LINE_2_TXT as GARAGING_ADDR_LINE_2_TXT,
	 FAIR_MKT_VAL_AMT as FAIR_MKT_VAL_AMT,
	 DISPOSE_DT as DISPOSE_DT,
	 GRS_VEH_WT as GRS_VEH_WT,
	 VEH_TRIM_DESCR as VEH_TRIM_DESCR,
	 AUCTN_ODOMETER_QTY as AUCTN_ODOMETER_QTY,
	 AVG_MKT_VAL_AMT as AVG_MKT_VAL_AMT,
	 VEH_REGSTR_NBR as VEH_REGSTR_NBR,
	 COLLAT_CHNGE_DT as COLLAT_CHNGE_DT,
	 GARAGING_STATE_GEOG_CD as GARAGING_STATE_GEOG_CD,
	 GM_IND as GM_IND,
	 GARAGING_LAST_PROCESS_DT as GARAGING_LAST_PROCESS_DT,
	 SRCE_EFF_DT as SRCE_EFF_DT,
	 exp_InitialOut.IN_ACCT_NBR as IN_ACCT_NBR_1,
	 exp_Initial.ACCT_NBR AS IN_ACCT_NBR_2 
FROM
	exp_InitialOut as exp_InitialOut 
 LEFT JOIN VEH_COLLATOut
ON
	ACCT_NBR = IN_ACCT_NBR
 
),

dsJoiner_flt_NULLS22Out as (
Select 
	exp_InitialOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	 exp_InitialOut.LICNS_PLATE_NBR as LICNS_PLATE_NBR,
	 exp_InitialOut.VEH_MAKE_NM as VEH_MAKE_NM,
	 exp_InitialOut.VEH_MODEL_NM as VEH_MODEL_NM,
	 exp_InitialOut.VEH_YR as VEH_YR,
	 exp_InitialOut.INSERT_TM as INSERT_TM,
	 exp_InitialOut.VIN as VIN,
	 exp_InitialOut.VIN_fuel_type_cd as VIN_fuel_type_cd,
	 LKP_PIXL_VEH_COLLATOut.VEH_NEW_USED_CD as VEH_NEW_USED_CD,
	 exp_InitialOut.jkey as jkey 
From
exp_InitialOut as exp_InitialOut inner JOIN LKP_PIXL_VEH_COLLATOut as LKP_PIXL_VEH_COLLATOut 
ON
LKP_PIXL_VEH_COLLATOut.jkey = exp_InitialOut.jkey 
),

exp_FinalOut as (
	
Select 
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
VIN as VIN,
LICNS_PLATE_NBR as LICNS_PLATE_NBR,
VEH_MAKE_NM as VEH_MAKE_NM,
VEH_MODEL_NM as VEH_MODEL_NM,
VEH_YR as VEH_YR,
INSERT_TM as INSERT_TM,
VEH_NEW_USED_CD as VEH_NEW_USED_CD,
VIN_fuel_type_cd as VIN_fuel_type_cd 
From dsJoiner_flt_NULLS22Out as dsJoiner_flt_NULLS22Out Where VIN IS NOT NULL),

srt_ACCTOut as (
	Select 
	CONCISE_ACCT_NBR,
	 VIN,
	 VIN_fuel_type_cd,
	 LICNS_PLATE_NBR,
	 VEH_MAKE_NM,
	 VEH_MODEL_NM,
	 VEH_YR,
	 INSERT_TM,
	 VEH_NEW_USED_CD 
From exp_FinalOut as exp_FinalOut Order By CONCISE_ACCT_NBR ASC, VIN ASC, VIN_fuel_type_cd ASC),

agg_ACCTOut as (
	with 
agg_ACCT_Out as (
 select 
	CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	 VIN as VIN,
	 VIN_fuel_type_cd as VIN_fuel_type_cd
 from srt_ACCTOut
 group by CONCISE_ACCT_NBR, VIN, VIN_fuel_type_cd
),
agg_ACCT_NonGroupBy as (
 select 
  	CONCISE_ACCT_NBR,
	 VIN,
	 LICNS_PLATE_NBR,
	 VEH_MAKE_NM,
	 VEH_MODEL_NM,
	 VEH_YR,
	 INSERT_TM,
	 VEH_NEW_USED_CD,
	 VIN_fuel_type_cd
 from (
  select 
   	CONCISE_ACCT_NBR,
	 VIN,
	 LICNS_PLATE_NBR,
	 VEH_MAKE_NM,
	 VEH_MODEL_NM,
	 VEH_YR,
	 INSERT_TM,
	 VEH_NEW_USED_CD,
	 VIN_fuel_type_cd,
   ROW_NUMBER() OVER (
    PARTITION BY CONCISE_ACCT_NBR, VIN, VIN_fuel_type_cd
    ORDER BY CONCISE_ACCT_NBR, VIN, VIN_fuel_type_cd
   ) as rnk_lst
  from srt_ACCTOut
 ) t
 where rnk_lst = 1
),
agg_ACCTOut as (
 select 
	dsf_1.CONCISE_ACCT_NBR,
	 dsf_1.VIN,
	 dsf_1.VIN_fuel_type_cd,
	 dsf_2.LICNS_PLATE_NBR,
	 dsf_2.VEH_MAKE_NM,
	 dsf_2.VEH_MODEL_NM,
	 dsf_2.VEH_YR,
	 dsf_2.INSERT_TM,
	 dsf_2.VEH_NEW_USED_CD
 from agg_ACCT_Out dsf_1
 inner join agg_ACCT_NonGroupBy dsf_2 on dsf_1.CONCISE_ACCT_NBR = dsf_2.CONCISE_ACCT_NBR AND dsf_1.VIN = dsf_2.VIN AND dsf_1.VIN_fuel_type_cd = dsf_2.VIN_fuel_type_cd
)
select * from agg_final),

LKP_VIN_LOOKUPOut as (
	Select 
	VIN_KEY as VIN_KEY,
	 FUEL_TYPE_CD as FUEL_TYPE_CD,
	 agg_ACCTOut.fuel_type_cd_VIN as fuel_type_cd_VIN_1,
	 agg_ACCT.VIN_fuel_type_cd AS fuel_type_cd_VIN_2 
FROM
	agg_ACCTOut as agg_ACCTOut 
 LEFT JOIN ( select * from (
select 
*,VIN_KEY,row_number() over(partition by VIN_KEY order by rnk_fst desc nulls last) as rnk_lst
from
(
select *,VIN_KEY,row_number() over(partition by VIN_KEY order by VIN_KEY nulls last) as rnk_fst
from ( SELECT
    SUBSTR(VIN_KEY,1,10) as VIN_KEY,
    FUEL_TYPE_CD as FUEL_TYPE_CD
 FROM
    {{ source ('SHARED', 'VIN_LOOKUP') }}
 GROUP BY
    VIN_KEY,
    FUEL_TYPE_CD
 ORDER BY
    VIN_KEY ASC - )
) lkp_inner
) lkp_outer
where rnk_lst=1 ) 
ON
	VIN_KEY = fuel_type_cd_VIN
 
),

dsJoiner_EXP_PASS22Out as (
Select 
	LKP_VIN_LOOKUPOut.FUEL_TYPE_CD as FUEL_TYPE_CD,
	 agg_ACCTOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	 agg_ACCTOut.VIN as VIN,
	 agg_ACCTOut.LICNS_PLATE_NBR as LICNS_PLATE_NBR,
	 agg_ACCTOut.VEH_MAKE_NM as VEH_MAKE_NM,
	 agg_ACCTOut.VEH_MODEL_NM as VEH_MODEL_NM,
	 agg_ACCTOut.VEH_YR as VEH_YR,
	 agg_ACCTOut.INSERT_TM as INSERT_TM,
	 agg_ACCTOut.VEH_NEW_USED_CD as VEH_NEW_USED_CD,
	 agg_ACCTOut.jkey as jkey 
From
agg_ACCTOut as agg_ACCTOut inner JOIN LKP_VIN_LOOKUPOut as LKP_VIN_LOOKUPOut 
ON
LKP_VIN_LOOKUPOut.jkey = agg_ACCTOut.jkey 
),

EXP_PASSOut as (
	
Select 
FUEL_TYPE_CD as FUEL_TYPE_CD,
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
VIN as VIN,
LICNS_PLATE_NBR as LICNS_PLATE_NBR,
VEH_MAKE_NM as VEH_MAKE_NM,
VEH_MODEL_NM as VEH_MODEL_NM,
VEH_YR as VEH_YR,
INSERT_TM as INSERT_TM,
VEH_NEW_USED_CD as VEH_NEW_USED_CD
From dsJoiner_EXP_PASS22Out as dsJoiner_EXP_PASS22Out),

DSR_VEHOut as (
	
Select 
EXP_PASSOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
EXP_PASSOut.VIN as VIN,
EXP_PASSOut.VEH_MAKE_NM as VEH_MAKE_NM,
EXP_PASSOut.VEH_MODEL_NM as VEH_MODEL_NM,
EXP_PASSOut.VEH_YR as VEH_YR,
EXP_PASSOut.INSERT_TM as INSERT_DT,
EXP_PASSOut.LICNS_PLATE_NBR as VEH_LICNS_PLATE_NUM,
EXP_PASSOut.VEH_NEW_USED_CD as VEH_NEW_USED_CD,
EXP_PASSOut.FUEL_TYPE_CD as FUEL_TYPE_CD
From EXP_PASSOut as EXP_PASSOut)


Select 
	CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	VIN as VIN,
	VEH_MAKE_NM as VEH_MAKE_NM,
	VEH_MODEL_NM as VEH_MODEL_NM,
	VEH_YR as VEH_YR,
	INSERT_DT as INSERT_DT,
	VEH_LICNS_PLATE_NUM as VEH_LICNS_PLATE_NUM,
	VEH_NEW_USED_CD as VEH_NEW_USED_CD,
	FUEL_TYPE_CD as FUEL_TYPE_CD 
From DSR_VEHOut as DSR_VEHOut