name: informatica_json_project
version: '1.0'
config-version: 2

profile: my_project

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  informatica_json_project:
    +materialized: view
    +database: FIVETRAN_DATABASE
