name: informatica_json_project
version: '1.0'
config-version: 2

profile: my_project

model-paths: ["models"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  informatica_json_project:
    models:
  informatica_json_project:
    sample_1:
      +schema: sample_schema_1
    sample_2:
      +schema: sample_schema_2

