my_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: VKAJTRK-DV04149    
      user: BHARATHI
      password: Bharathi123456789
      role: ACCOUNTADMIN                  
      database: FIVETRAN_database
      warehouse: COMPUTE_WH
      schema: public
      threads: 4
