my_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: HJZXKHV-EA71750
      user: Surya
      password: Surya@123456789
      role: ACCOUNTADMIN                
      database: FIVETRAN_DATABASE
      warehouse: COMPUTE_WH
      schema: CONN_SNOWFLAKE_14_DEMO_SCHEMA
      threads: 4


