my_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: VKAJTRK-DV04149     # ✅ No .snowflakecomputing.com
      user: BHARATHI
      password: Bharathi123456789
      role: ACCOUNTADMIN                  # Optional, based on your setup
      database: FIVETRAN_DATABASE
      warehouse: COMPUTE_WH
      schema: TEST_PD_CONN
      threads: 4
