dbt_core_databricks:
  outputs:
    dev:
      catalog: null
      host:dbc-fa32949d-b800.cloud.databricks.com
      http_path: /sql/1.0/warehouses/d0f6417961aee586
      schema: default
      threads: 1
      token: dapib312cc05d940e029aee272bfce48b2af
      type: databricks
  target: dev

      
