my_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: GHTGEWC-BZ77114  
      user: Ramkumar
      password: Ramkumar@123456789
      role: ACCOUNTADMIN                
      database: SNOWFLAKE_LEARNING_DB
      warehouse: COMPUTE_WH
      schema: SNF_SNF_DATABRICKS_CONN_SNF_SNOWFLAKE_DATA__PUBLIC_
      threads: 4
