version: 2

sources:
  - name: tMSSqlInput_1
    tables:
      - name: ACTIVITYMAPPING
  - name: tMSSqlInput_2
    tables:
      - name: VERINT_ACTV_MAP
  - name: tMSSqlInput_3
    tables:
      - name: tMSSqlInput_3

models:
  - name: stg_VERINT_ACTV_MAPOut
    description: "Staging model for VERINT_ACTV_MAP"
    columns:
      - name: ACTV_MAP_ID
        description: "ACTV_MAP_ID"
      - name: EFF_DTTM
        description: "EFF_DTTM"
      - name: ACTV_ID
        description: "ACTV_ID"
      - name: MAPPED_ACTV_ID
        description: "MAPPED_ACTV_ID"
      - name: MOD_BY
        description: "MOD_BY"
  - name: stg_CURRENT_TIMESTAMPOut
    description: "Staging model for CURRENT_TIMESTAMP"
    columns:
      - name: UPDT_END_DTTM
        description: "UPDT_END_DTTM"
      - name: EFF_DTTM
        description: "EFF_DTTM"
      - name: AUD_CRE_DTTM
        description: "AUD_CRE_DTTM"
  - name: stg_ACTIVITYMAPPINGOut
    description: "Staging model for ACTIVITYMAPPING"
    columns:
      - name: ACTV_MAP_ID
        description: "ACTV_MAP_ID"
      - name: ACTV_ID
        description: "ACTV_ID"
      - name: MAPPED_ACTV_ID
        description: "MAPPED_ACTV_ID"
      - name: MOD_BY
        description: "MOD_BY"
