version: 2

sources:
  - name: tFileInputDelimited_2
    tables:
      - name: {{ TEMP_DIR }}+VERINT_ACTV_MAP_UPD_INS
  - name: tFileInputDelimited_3
    tables:
      - name: {{ TEMP_DIR }}+VERINT_ACTV_MAP_INS

models:
  - name: stg_tFileInputDelimited_2Out
    description: "Staging model for tFileInputDelimited_2"
    columns:
      - name: ACTV_MAP_ID
        description: "ACTV_MAP_ID"
      - name: SOR_CD
        description: "SOR_CD"
      - name: EFF_DTTM
        description: "EFF_DTTM"
      - name: END_DTTM
        description: "END_DTTM"
      - name: UNQ_KEY_TXT
        description: "UNQ_KEY_TXT"
      - name: ACTV_ID
        description: "ACTV_ID"
      - name: MAPPED_ACTV_ID
        description: "MAPPED_ACTV_ID"
      - name: MOD_BY
        description: "MOD_BY"
      - name: AUD_CRE_BY_NM
        description: "AUD_CRE_BY_NM"
      - name: AUD_CRE_DTTM
        description: "AUD_CRE_DTTM"
      - name: ETL_BATCH_ID
        description: "ETL_BATCH_ID"
      - name: CURR_IND
        description: "CURR_IND"
  - name: stg_tFileInputDelimited_3Out
    description: "Staging model for tFileInputDelimited_3"
    columns:
      - name: ACTV_MAP_ID
        description: "ACTV_MAP_ID"
      - name: SOR_CD
        description: "SOR_CD"
      - name: EFF_DTTM
        description: "EFF_DTTM"
      - name: END_DTTM
        description: "END_DTTM"
      - name: UNQ_KEY_TXT
        description: "UNQ_KEY_TXT"
      - name: ACTV_ID
        description: "ACTV_ID"
      - name: MAPPED_ACTV_ID
        description: "MAPPED_ACTV_ID"
      - name: MOD_BY
        description: "MOD_BY"
      - name: AUD_CRE_BY_NM
        description: "AUD_CRE_BY_NM"
      - name: AUD_CRE_DTTM
        description: "AUD_CRE_DTTM"
      - name: ETL_BATCH_ID
        description: "ETL_BATCH_ID"
      - name: CURR_IND
        description: "CURR_IND"
