{{ config(materialized='view') }}

/* SubQuery FROM Source ==>CURRENT_TIMESTAMP */
 /* transType: "Source" */
 SELECT
  TO_VARCHAR(
   CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP())(),
   'YYYY-MM-DD HH24:MI:SS.FF3'
  ) AS UPDT_END_DTTM,
  TO_VARCHAR(
   DATEADD(SS, 1, CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()))(),
   'YYYY-MM-DD HH24:MI:SS.FF3'
  ) AS EFF_DTTM,
  TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYY-MM-DD HH24:MI:SS.FF3') AS AUD_CRE_DTTM