/* Transformation Name ==>DEFNCY ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='DEFNCY',
		schema='',
		pre_hook ="CALL CORE_SVC.pkg_rename.truncate_load_table ( 'DEFNCY' ) ",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_DEFNCY_ACCTOut as (
	Select UNIQUE_ID, 
		DEFNCY_LOAD_DT, 
		ACCT_NBR, 
		ACCT_SHORT_NBR, 
		ACCT_SHORT_NBR_CD, 
		ORIG_DEFNCY_BAL_AMT, 
		ORIG_DEFNCY_PI_AMT, 
		ORIG_DEFNCY_NON_ACR_INTRST_AMT, 
		ORIG_DEFNCY_EXPENSE_FEE_AMT, 
		ORIG_DEFNCY_LATE_FEE_AMT, 
		ORIG_DEFNCY_MISC_FEE_AMT, 
		ORIG_DEFNCY_TAX_AMT, 
		ORIG_DEFNCY_SALE_AMT, 
		CURR_DEFNCY_BAL_AMT, 
		CURR_DEFNCY_RECOV_AMT, 
		CURR_DEFNCY_INTRST_AMT, 
		CURR_DEFNCY_EXPENSE_FEE_AMT, 
		CURR_DEFNCY_LATE_FEE_AMT, 
		CURR_DEFNCY_MISC_FEE_AMT, 
		CURR_DEFNCY_TAX_AMT, 
		CURR_DEFNCY_SALE_AMT, 
		CURR_DEFNCY_ADJ_AMT
 from 
{{ source ('DBConnection_SVC_INFA_ETL_DW6','DEFNCY_ACCT') }} 
 ),

EXP_SRCEOut as (
	
Select 
DEFNCY_LOAD_DT as DEFNCY_LOAD_DT,
ACCT_NBR as ACCT_NBR,
ORIG_DEFNCY_BAL_AMT as ORIG_DEFNCY_BAL_AMT,
ORIG_DEFNCY_PI_AMT as ORIG_DEFNCY_PI_AMT,
ORIG_DEFNCY_NON_ACR_INTRST_AMT as ORIG_DEFNCY_NON_ACR_INTRST_AMT,
ORIG_DEFNCY_EXPENSE_FEE_AMT as ORIG_DEFNCY_EXPENSE_FEE_AMT,
ORIG_DEFNCY_LATE_FEE_AMT as ORIG_DEFNCY_LATE_FEE_AMT,
ORIG_DEFNCY_MISC_FEE_AMT as ORIG_DEFNCY_MISC_FEE_AMT,
ORIG_DEFNCY_TAX_AMT as ORIG_DEFNCY_TAX_AMT,
ORIG_DEFNCY_SALE_AMT as ORIG_DEFNCY_SALE_AMT,
CURR_DEFNCY_BAL_AMT as CURR_DEFNCY_BAL_AMT,
CURR_DEFNCY_RECOV_AMT as CURR_DEFNCY_RECOV_AMT,
CURR_DEFNCY_INTRST_AMT as CURR_DEFNCY_INTRST_AMT,
CURR_DEFNCY_EXPENSE_FEE_AMT as CURR_DEFNCY_EXPENSE_FEE_AMT,
CURR_DEFNCY_LATE_FEE_AMT as CURR_DEFNCY_LATE_FEE_AMT,
CURR_DEFNCY_MISC_FEE_AMT as CURR_DEFNCY_MISC_FEE_AMT,
CURR_DEFNCY_TAX_AMT as CURR_DEFNCY_TAX_AMT,
CURR_DEFNCY_SALE_AMT as CURR_DEFNCY_SALE_AMT,
CURR_DEFNCY_ADJ_AMT as CURR_DEFNCY_ADJ_AMT
From SQ_DEFNCY_ACCTOut as SQ_DEFNCY_ACCTOut)


Select 
	ACCT_NBR as ACCT_NBR,
	DEFNCY_LOAD_DT as DEFNCY_LOAD_DT,
	ORIG_DEFNCY_PI_AMT as ORIG_DEFNCY_PI_AMT,
	ORIG_DEFNCY_NON_ACR_INTRST_AMT as ORIG_DEFNCY_NON_ACR_INTRST_AMT,
	ORIG_DEFNCY_EXPENSE_FEE_AMT as ORIG_DEFNCY_EXPENSE_FEE_AMT,
	ORIG_DEFNCY_LATE_FEE_AMT as ORIG_DEFNCY_LATE_FEE_AMT,
	ORIG_DEFNCY_MISC_FEE_AMT as ORIG_DEFNCY_MISC_FEE_AMT,
	ORIG_DEFNCY_TAX_AMT as ORIG_DEFNCY_TAX_AMT,
	ORIG_DEFNCY_SALE_AMT as ORIG_DEFNCY_SALE_AMT,
	ORIG_DEFNCY_BAL_AMT as ORIG_DEFNCY_BAL_AMT,
	CURR_DEFNCY_RECOV_AMT as CURR_DEFNCY_RECOV_AMT,
	CURR_DEFNCY_INTRST_AMT as CURR_DEFNCY_INTRST_AMT,
	CURR_DEFNCY_EXPENSE_FEE_AMT as CURR_DEFNCY_EXPENSE_FEE_AMT,
	CURR_DEFNCY_LATE_FEE_AMT as CURR_DEFNCY_LATE_FEE_AMT,
	CURR_DEFNCY_MISC_FEE_AMT as CURR_DEFNCY_MISC_FEE_AMT,
	CURR_DEFNCY_TAX_AMT as CURR_DEFNCY_TAX_AMT,
	CURR_DEFNCY_SALE_AMT as CURR_DEFNCY_SALE_AMT,
	CURR_DEFNCY_ADJ_AMT as CURR_DEFNCY_ADJ_AMT,
	CURR_DEFNCY_BAL_AMT as CURR_DEFNCY_BAL_AMT 
From EXP_SRCEOut as EXP_SRCEOut