/* Transformation Name ==>DM_ACCT_STATUS ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='DM_ACCT_STATUS',
		schema='',
		pre_hook ="CALL CORE_SVC.pkg_rename.truncate_load_table ( 'DM_ACCT_STATUS' ) ",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_DEFLT_ACCT_STATUSOut as (
	/* SubQuery from Source ==>SQ_SQ_DEFLT_ACCT_STATUS */
Select 
SRCE_EFF_DT,
ACCT_UNIQ_ID,
ACCT_NBR,
DEFLT_ACCT_STATUS_CD,
DEFLT_ACCT_STATUS_DESCR,
CREATE_USER_ID,
CREATE_DT,
UPDATE_USER_ID,
UPDATE_DT,
DEFLT_ACCT_STATUS_TYPE_DESCR,
NEXT_FOLLOW_UP_DT,
NOTICE_EXPIRE_DT,
COLLECTN_TYPE_CD,
COLLECTN_ACTV_DT,
LAST_CONTCT_DT,
COLLECTN_INACTV_DT,
LAST_PTP_AMT,
PTP_PEND_IND,
LAST_PTP_DT,
LAST_ACTVTY_DT,
LAST_PTP_TAKEN_DT,
COLLECTN_STATUS_CD,
LAST_TRANSACT_DT
 from 
(SELECT
    DEFLT_ACCT_STATUS.ACCT_NBR,
    DEFLT_ACCT_STATUS.DEFLT_ACCT_STATUS_CD,
    DEFLT_ACCT_STATUS.DEFLT_ACCT_STATUS_DESCR,
    DEFLT_ACCT_STATUS.DEFLT_ACCT_STATUS_TYPE_DESCR
 FROM {{ source('yml_Source_Name','{{ source ('PIXL', 'DEFLT_ACCT_STATUS') }}') }} DEFLT_ACCT_STATUS
 WHERE 
  NOT DEFLT_ACCT_STATUS.DEFLT_ACCT_STATUS_CD IS NULL)
 ),

exp_INITIALOut as (
	
Select 
TO_DECIMAL ( SUBSTRING ( ACCT_NBR,
-14 ) ) as ACCT_NBR_out,
DEFLT_ACCT_STATUS_CD as DEFLT_ACCT_STATUS_CD,
LTRIM ( RTRIM ( SUBSTRING ( DEFLT_ACCT_STATUS_DESCR,
1,
64 ) ) ) as DEFLT_ACCT_STATUS_DESCR_out,
LTRIM ( RTRIM ( SUBSTRING ( DEFLT_ACCT_STATUS_TYPE_DESCR,
1,
32 ) ) ) as DEFLT_ACCT_STATUS_TYPE_DESCR_out
From SQ_DEFLT_ACCT_STATUSOut as SQ_DEFLT_ACCT_STATUSOut),

DSR_DM_ACCT_STATUSOut as (
	
Select 
exp_INITIALOut.ACCT_NBR_out as CONCISE_ACCT_NBR,
exp_INITIALOut.DEFLT_ACCT_STATUS_CD as ACCT_STATUS_ID,
exp_INITIALOut.DEFLT_ACCT_STATUS_DESCR_out as ACCT_STATUS_DESCR,
exp_INITIALOut.DEFLT_ACCT_STATUS_TYPE_DESCR_out as ACCT_STATUS_TYPE_DESCR
From exp_INITIALOut as exp_INITIALOut)


Select 
	CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	ACCT_STATUS_ID as ACCT_STATUS_ID,
	ACCT_STATUS_DESCR as ACCT_STATUS_DESCR,
	ACCT_STATUS_TYPE_DESCR as ACCT_STATUS_TYPE_DESCR 
From DSR_DM_ACCT_STATUSOut as DSR_DM_ACCT_STATUSOut