/* Transformation Name ==>COMP_TIME_DAILY_TBL ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='COMP_TIME_DAILY_TBL',
		schema='',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_U0287D01Out AS ( SELECT SSN, NAME, CURRENT_ACCT, CURRENT_ORG, FLSA_STATUS, COMP_TIME_CUR_BAL, COMP_TIME_YEAR_EARNED, PP_END_DATE, DAILY_DATE_EARNED, COMP_TIME_RATE, COMP_TIME_HOURS, COMP_TIME_UNDEF FROM {{ source ('FlatFile_catalog_1','U0287D01') }} ),

PAY_PERIODOut AS ( SELECT in_CURR_PP_FLAG, PP_NUM, PP_END_YEAR, PP_START_DTE, PP_END_DTE, LV_NUM, LV_YEAR, PAY_DTE, CURR_PP_FLAG FROM {{ source ('lkpSource_1_1','PAY_PERIOD') }} ),

exp_InitialOut AS ( SELECT SSN AS SSN, NAME AS NAME, CURRENT_ACCT AS CURRENT_ACCT, CURRENT_ORG AS CURRENT_ORG, FLSA_STATUS AS FLSA_STATUS, COMP_TIME_CUR_BAL AS COMP_TIME_CUR_BAL, COMP_TIME_YEAR_EARNED AS COMP_TIME_YEAR_EARNED, PP_END_DATE AS PP_END_DATE, DAILY_DATE_EARNED AS DAILY_DATE_EARNED, COMP_TIME_RATE AS COMP_TIME_RATE, COMP_TIME_HOURS AS COMP_TIME_HOURS, COMP_TIME_UNDEF AS COMP_TIME_UNDEF, 'Y' AS o_CURR_PP_FLAG, DECODE ( TRUE, TRY_TO_NUMBER ( SSN ) IS NOT NULL, 1, 0 ) AS o_VALID_RECORD_FLAG FROM SQ_U0287D01Out AS SQ_U0287D01Out),

DSR_fil_Valid_RecordsOut AS ( SELECT exp_InitialOut.SSN AS SSN, exp_InitialOut.NAME AS NAME, exp_InitialOut.CURRENT_ACCT AS CURRENT_ACCT, exp_InitialOut.CURRENT_ORG AS CURRENT_ORG, exp_InitialOut.FLSA_STATUS AS FLSA_STATUS, exp_InitialOut.COMP_TIME_CUR_BAL AS COMP_TIME_CUR_BAL, exp_InitialOut.COMP_TIME_YEAR_EARNED AS COMP_TIME_YEAR_EARNED, exp_InitialOut.PP_END_DATE AS PP_END_DATE, exp_InitialOut.DAILY_DATE_EARNED AS DAILY_DATE_EARNED, exp_InitialOut.COMP_TIME_RATE AS COMP_TIME_RATE, exp_InitialOut.COMP_TIME_HOURS AS COMP_TIME_HOURS, exp_InitialOut.COMP_TIME_UNDEF AS COMP_TIME_UNDEF, exp_InitialOut.o_CURR_PP_FLAG AS CURR_PP_FLAG, exp_InitialOut.o_VALID_RECORD_FLAG AS VALID_RECORD_FLAG FROM exp_InitialOut AS exp_InitialOut),

fil_Valid_RecordsOut AS ( SELECT * FROM DSR_fil_Valid_RecordsOut AS DSR_fil_Valid_RecordsOut WHERE VALID_RECORD_FLAG = TRUE),

lkp_PAY_PERIODOut AS ( SELECT PP_NUM AS PP_NUM, PP_END_YEAR AS PP_END_YEAR, fil_Valid_Records.CURR_PP_FLAG AS in_CURR_PP_FLAG FROM fil_Valid_RecordsOut AS fil_Valid_RecordsOut LEFT JOIN PAY_PERIODOut ON CURR_PP_FLAG = in_CURR_PP_FLAG ),

lkp_PAY_PERIOD_details AS ( SELECT lkp_PAY_PERIODOut.PP_NUM AS lkp_PP_NUM, lkp_PAY_PERIODOut.PP_END_YEAR AS lkp_PP_END_YEAR FROM lkp_PAY_PERIODOut AS lkp_PAY_PERIODOut ), dsJoiner_exp_ConvertOut AS ( SELECT fil_Valid_RecordsOut.SSN AS SSN, fil_Valid_RecordsOut.NAME AS NAME, fil_Valid_RecordsOut.CURRENT_ACCT AS CURRENT_ACCT, fil_Valid_RecordsOut.CURRENT_ORG AS CURRENT_ORG, fil_Valid_RecordsOut.FLSA_STATUS AS FLSA_STATUS, fil_Valid_RecordsOut.COMP_TIME_CUR_BAL AS COMP_TIME_CUR_BAL, fil_Valid_RecordsOut.COMP_TIME_YEAR_EARNED AS COMP_TIME_YEAR_EARNED, fil_Valid_RecordsOut.PP_END_DATE AS PP_END_DATE, fil_Valid_RecordsOut.DAILY_DATE_EARNED AS DAILY_DATE_EARNED, fil_Valid_RecordsOut.COMP_TIME_RATE AS COMP_TIME_RATE, fil_Valid_RecordsOut.COMP_TIME_HOURS AS COMP_TIME_HOURS, fil_Valid_RecordsOut.COMP_TIME_UNDEF AS COMP_TIME_UNDEF, lkp_PAY_PERIOD_details.lkp_PP_NUM AS lkp_PP_NUM, lkp_PAY_PERIOD_details.lkp_PP_END_YEAR AS lkp_PP_END_YEAR, fil_Valid_RecordsOut.jkey AS jkey FROM fil_Valid_RecordsOut AS fil_Valid_RecordsOut INNER JOIN lkp_PAY_PERIOD_details AS lkp_PAY_PERIOD_details ON lkp_PAY_PERIOD_details.jkey = fil_Valid_RecordsOut.jkey ),

exp_ConvertOut AS ( SELECT SSN AS SSN, NAME AS NAME, CURRENT_ACCT AS CURRENT_ACCT, CURRENT_ORG AS CURRENT_ORG, FLSA_STATUS AS FLSA_STATUS, COMP_TIME_CUR_BAL AS COMP_TIME_CUR_BAL, COMP_TIME_YEAR_EARNED AS COMP_TIME_YEAR_EARNED, ( CASE WHEN TO_DATE ( PP_END_DATE, 'YYYYMMDD' ) THEN TO_DATE ( PP_END_DATE, 'YYYYMMDD' ) ELSE NULL END ) AS o_PP_END_DATE, ( CASE WHEN TO_DATE ( DAILY_DATE_EARNED, 'YYYYMMDD' ) THEN TO_DATE ( DAILY_DATE_EARNED, 'YYYYMMDD' ) ELSE NULL END ) AS o_DAILY_DATE_EARNED, COMP_TIME_RATE AS COMP_TIME_RATE, COMP_TIME_HOURS AS COMP_TIME_HOURS, COMP_TIME_UNDEF AS COMP_TIME_UNDEF, lkp_PP_END_YEAR AS o_PP_END_YEAR, lkp_PP_NUM AS o_PP_NUM, TO_DECIMAL ( TO_VARCHAR ( lkp_PP_END_YEAR ) || LPAD ( TO_VARCHAR ( lkp_PP_NUM ), 2, '0' ) AS o_PP_YEAR_NUM FROM dsJoiner_exp_ConvertOut AS dsJoiner_exp_ConvertOut),

DSR_exp_FinalOut AS ( SELECT exp_ConvertOut.o_PP_END_YEAR AS PP_END_YEAR, exp_ConvertOut.o_PP_NUM AS PP_NUM, exp_ConvertOut.o_PP_YEAR_NUM AS PP_YEAR_NUM, exp_ConvertOut.SSN AS SSN, exp_ConvertOut.NAME AS NAME, exp_ConvertOut.CURRENT_ACCT AS CURRENT_ACCT, exp_ConvertOut.CURRENT_ORG AS CURRENT_ORG, exp_ConvertOut.FLSA_STATUS AS FLSA_STATUS, exp_ConvertOut.COMP_TIME_CUR_BAL AS COMP_TIME_CUR_BAL, exp_ConvertOut.COMP_TIME_YEAR_EARNED AS COMP_TIME_YEAR_EARNED, exp_ConvertOut.o_PP_END_DATE AS PP_END_DATE, exp_ConvertOut.o_DAILY_DATE_EARNED AS DAILY_DATE_EARNED, exp_ConvertOut.COMP_TIME_RATE AS COMP_TIME_RATE, exp_ConvertOut.COMP_TIME_HOURS AS COMP_TIME_HOURS, exp_ConvertOut.COMP_TIME_UNDEF AS COMP_TIME_UNDEF FROM exp_ConvertOut AS exp_ConvertOut),

exp_FinalOut AS ( SELECT PP_END_YEAR AS PP_END_YEAR, PP_NUM AS PP_NUM, PP_YEAR_NUM AS PP_YEAR_NUM, SSN AS SSN, NAME AS NAME, CURRENT_ACCT AS CURRENT_ACCT, CURRENT_ORG AS CURRENT_ORG, FLSA_STATUS AS FLSA_STATUS, COMP_TIME_CUR_BAL AS COMP_TIME_CUR_BAL, COMP_TIME_YEAR_EARNED AS COMP_TIME_YEAR_EARNED, PP_END_DATE AS PP_END_DATE, DAILY_DATE_EARNED AS DAILY_DATE_EARNED, COMP_TIME_RATE AS COMP_TIME_RATE, COMP_TIME_HOURS AS COMP_TIME_HOURS, COMP_TIME_UNDEF AS COMP_TIME_UNDEF FROM DSR_exp_FinalOut AS DSR_exp_FinalOut)


Select 
	PP_END_YEAR as PP_END_YEAR,
	PP_NUM as PP_NUM,
	PP_YEAR_NUM as PP_YEAR_NUM,
	SSN as SSN,
	NAME as NAME,
	CURRENT_ACCT as CURRENT_ACCT,
	CURRENT_ORG as CURRENT_ORG,
	FLSA_STATUS as FLSA_STATUS,
	COMP_TIME_CUR_BAL as COMP_TIME_CUR_BAL,
	COMP_TIME_YEAR_EARNED as COMP_TIME_YEAR_EARNED,
	PP_END_DATE as PP_END_DATE,
	DAILY_DATE_EARNED as DAILY_DATE_EARNED,
	COMP_TIME_RATE as COMP_TIME_RATE,
	COMP_TIME_HOURS as COMP_TIME_HOURS,
	COMP_TIME_UNDEF as COMP_TIME_UNDEF 
From exp_FinalOut as exp_FinalOut