/* Transformation Name ==>REPO ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='REPO',
		schema='',
		pre_hook ="CALL CORE_SVC.pkg_rename.truncate_load_table ( 'REPO' ) ",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_ACCT_LOAD_MAPPINGOut as (
	Select CONCISE_ACCT_NBR, 
		TRANSACT_ACCT_NBR, 
		ACCT_NBR, 
		PARTIAL_ACCT_NBR, 
		APLN_NBR, 
		PROD_TYPE_CD, 
		COMMRCL_IND, 
		ACCT_STATUS_CD, 
		LEGAL_STATUS_CD, 
		ACCRL_STATUS_CD, 
		ACCT_CLS_DT, 
		BRANCH_NBR, 
		DLR_NBR, 
		ORIGNT_CONTRCT_DT, 
		ORIGNT_COUNTRY_CD, 
		ORIGNT_STATE_PRVNCE_CD, 
		CURR_AMT_DUE, 
		SCHED_PMT_AMT, 
		NEXT_PMT_AMT, 
		PMT_DUE_DT, 
		LAST_PMT_AMT, 
		LAST_PMT_DT, 
		AUTOPMT_IND, 
		EFT_LAST_PMT_AMT, 
		EFT_LAST_PMT_DT, 
		EFT_NEXT_PMT_AMT, 
		EFT_NEXT_PMT_DT, 
		LATE_FEE_DUE_AMT, 
		UNPD_MISC_FEE_AMT, 
		PAST_DUE_AMT, 
		PMT_MADE_QTY, 
		LAST_NSF_DT, 
		NSF_QTY, 
		ORIG_ACCT_MATURITY_DT, 
		ORIG_TERM_MNTH_QTY, 
		CURR_MATURITY_DT, 
		CURR_TERM_MNTH_QTY, 
		COLLAT_EXCEPTN_CD, 
		COLLECT_CTR_NBR, 
		TERM_STATUS_CD, 
		NEXT_PROMISE_AMT, 
		NEXT_PROMISE_DT, 
		LOAN_ORIG_BAL_AMT, 
		LOAN_CURR_BAL_AMT, 
		CURR_INTRST_DUE_AMT, 
		FIRST_PMT_DUE_DT, 
		LAST_YR_INTRST_PD_AMT, 
		PAYOFF_IND, 
		PAYOFF_DT, 
		PRINCPL_BAL_AMT, 
		VEH_SALES_AMT, 
		CONTRCT_MILE_AMT, 
		TAX_PMT_AMT, 
		SECUR_DEPOSIT_AMT, 
		CREDIT_BAL_AMT, 
		BASE_RENT_AMT, 
		RECOV_STATUS_CD, 
		SINGL_PMT_IND, 
		SALES_TAX_AMT, 
		TERM_TYPE_CD, 
		NEXT_MATURITY_DT, 
		REMAIN_PMT_QTY, 
		GRS_CAPITAL_COST_AMT, 
		VEH_MAKE_NM, 
		VEH_MODEL_NM, 
		VEH_YR, 
		VIN, 
		LICNS_PLATE_NBR, 
		CREDIT_BUR_SPECL_CD, 
		CREDIT_BUR_STATUS_CD, 
		COMPLNC_CONDTN_CD, 
		CREDIT_RPT_CD, 
		DAY_PAST_DUE_QTY, 
		PAST_DUE_30_QTY, 
		PAST_DUE_60_QTY, 
		PAST_DUE_90_QTY, 
		OLDEST_UNMET_DUE_DT, 
		DEFNCY_BAL_AMT, 
		TITLE_RELEASE_DT, 
		TITLE_MAILING_DT, 
		BKRPT_STATUS_CD, 
		BKRPT_CASE_NBR, 
		REPO_STATUS_CD, 
		REPO_RSN_CD, 
		OUT_FOR_REPO_IND, 
		REPO_HLD_IND, 
		CHRG_OFF_STATUS_CD, 
		CHRG_OFF_AMT, 
		CHRG_OFF_DT, 
		INSERT_TM
 from 
{{ source ('DBConnection_SVC_INFA_ETL_CORE','ACCT_LOAD_MAPPING') }} 
 ),

exp_InitialOut as (
	
Select 
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
REPO_STATUS_CD as REPO_STATUS_CD,
REPO_RSN_CD as REPO_RSN_CD,
OUT_FOR_REPO_IND as OUT_FOR_REPO_IND,
REPO_HLD_IND as REPO_HLD_IND
From SQ_ACCT_LOAD_MAPPINGOut as SQ_ACCT_LOAD_MAPPINGOut),

DSR_exp_FinalOut as (
	
Select 
exp_InitialOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
exp_InitialOut.REPO_STATUS_CD as REPO_STATUS_CD_in,
exp_InitialOut.REPO_RSN_CD as REPO_RSN_CD_in,
exp_InitialOut.OUT_FOR_REPO_IND as OUT_FOR_REPO_IND_in,
exp_InitialOut.REPO_HLD_IND as REPO_HLD_IND_in
From exp_InitialOut as exp_InitialOut),

exp_FinalOut as (
	
Select 
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
( CASE WHEN REPO_STATUS_CD_in IS NOT NULL THEN RTRIM ( LTRIM ( REPO_STATUS_CD_in ) ) ELSE NULL END ) as REPO_STATUS_CD,
( CASE WHEN REPO_RSN_CD_in IS NOT NULL THEN SUBSTRING ( RTRIM ( LTRIM ( REPO_RSN_CD_in ) ),
1,
1 ) ELSE NULL END ) as REPO_RSN_CD,
( CASE WHEN OUT_FOR_REPO_IND_in IS NOT NULL THEN RTRIM ( LTRIM ( OUT_FOR_REPO_IND_in ) ) ELSE NULL END ) as OUT_FOR_REPO_IND,
( CASE WHEN REPO_HLD_IND_in IS NOT NULL THEN RTRIM ( LTRIM ( REPO_HLD_IND_in ) ) ELSE NULL END ) as REPO_HLD_IND
From DSR_exp_FinalOut as DSR_exp_FinalOut),

DSR_REPOOut as (
	
Select 
exp_FinalOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
exp_FinalOut.REPO_STATUS_CD as REPO_STAT_CD,
exp_FinalOut.REPO_RSN_CD as REPO_RSN_CD,
exp_FinalOut.OUT_FOR_REPO_IND as OUT_FOR_REPO_IND,
exp_FinalOut.REPO_HLD_IND as REPO_HOLD_IND
From exp_FinalOut as exp_FinalOut)


Select 
	CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	REPO_STAT_CD as REPO_STAT_CD,
	REPO_RSN_CD as REPO_RSN_CD,
	OUT_FOR_REPO_IND as OUT_FOR_REPO_IND,
	REPO_HOLD_IND as REPO_HOLD_IND 
From DSR_REPOOut as DSR_REPOOut