/* Transformation Name ==>LOAN ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='LOAN',
		schema='',
		pre_hook ="CALL CORE_SVC.pkg_rename.truncate_load_table ( 'LOAN' ) ",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_ACCT_LOAD_MAPPINGOut as (
	Select ACCT_NBR, 
		CONCISE_ACCT_NBR, 
		PARTIAL_ACCT_NBR, 
		SYS_OF_RECRD_NM, 
		VIN, 
		TRANSACT_ACCT_NBR, 
		APLN_NBR, 
		BKRPT_CASE_NBR, 
		LICNS_PLATE_NBR, 
		PROD_TYPE_CD, 
		COMMRCL_IND, 
		ACCT_STATUS_CD, 
		LEGAL_STATUS_CD, 
		ACCRL_STATUS_CD, 
		BKRPT_STATUS_CD, 
		CHRG_OFF_STATUS_CD, 
		REPO_STATUS_CD, 
		ACCT_CLS_DT, 
		BRANCH_NBR, 
		DLR_NBR, 
		ORIGNT_CONTRCT_DT, 
		ORIGNT_COUNTRY_CD, 
		ORIGNT_STATE_PRVNCE_CD, 
		SCHED_PMT_AMT, 
		PMT_DUE_DT, 
		LAST_PMT_AMT, 
		LAST_PMT_DT, 
		AUTOPMT_IND, 
		EFT_LAST_PMT_AMT, 
		EFT_LAST_PMT_DT, 
		EFT_NEXT_PMT_AMT, 
		EFT_NEXT_PMT_DT, 
		WEB_PMT_DECLN_CD, 
		LATE_FEE_DUE_AMT, 
		VEH_MAKE_NM, 
		VEH_MODEL_NM, 
		VEH_YR, 
		PMT_MADE_QTY, 
		DAY_PAST_DUE_QTY, 
		PAST_DUE_30_QTY, 
		PAST_DUE_60_QTY, 
		PAST_DUE_90_QTY, 
		OLDEST_UNMET_DUE_DT, 
		CHRG_OFF_AMT, 
		CHRG_OFF_DT, 
		ORIG_ACCT_MATURITY_DT, 
		ORIG_TERM_MNTH_QTY, 
		CURR_MATURITY_DT, 
		CURR_TERM_MNTH_QTY, 
		COLLAT_EXCEPTN_CD, 
		TITLE_RELEASE_DT, 
		TITLE_MAILING_DT, 
		TITLE_MAILING_ADDR_TXT, 
		COLLECT_CTR_NBR, 
		LOAN_ORIG_BAL_AMT, 
		LOAN_CURR_BAL_AMT, 
		CURR_INTRST_DUE_AMT, 
		FIRST_PMT_DUE_DT, 
		LAST_YR_INTRST_PD_AMT, 
		NEXT_PMT_AMT, 
		NEXT_PROMISE_AMT, 
		NEXT_PROMISE_DT, 
		PAST_DUE_AMT, 
		PAYOFF_IND, 
		PAYOFF_DT, 
		PRINCPL_BAL_AMT, 
		VEH_SALES_AMT, 
		CONTRCT_MILE_AMT, 
		TAX_PMT_AMT, 
		SECUR_DEPOSIT_AMT, 
		BASE_RENT_AMT, 
		RECOV_STATUS_CD, 
		SINGL_PMT_IND, 
		TERM_TYPE_CD, 
		NEXT_MATURITY_DT, 
		REMAIN_PMT_QTY, 
		CREDIT_BUR_SPECL_CD, 
		CREDIT_BUR_STATUS_CD, 
		COMPLNC_CONDTN_CD, 
		CREDIT_RPT_CD, 
		SALES_TAX_AMT, 
		LAST_NSF_DT, 
		NSF_QTY, 
		CURR_AMT_DUE
 from 
{{ source ('DBConnection_SVC_INFA_ETL_CORE','ACCT_LOAD_MAPPING') }} 
 Where PROD_TYPE_CD LIKE 'R%'
 ),

DSR_exp_InitialOut as (
	
Select 
SQ_ACCT_LOAD_MAPPINGOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
SQ_ACCT_LOAD_MAPPINGOut.LOAN_ORIG_BAL_AMT as LOAN_ORIG_BAL_AMT,
SQ_ACCT_LOAD_MAPPINGOut.LOAN_CURR_BAL_AMT as LOAN_CURR_BAL_AMT,
SQ_ACCT_LOAD_MAPPINGOut.FIRST_PMT_DUE_DT as FIRST_PMT_DUE_DT,
SQ_ACCT_LOAD_MAPPINGOut.LAST_YR_INTRST_PD_AMT as LAST_YR_INTRST_PD_AMT,
SQ_ACCT_LOAD_MAPPINGOut.PAYOFF_IND as PAYOFF_IND_in,
SQ_ACCT_LOAD_MAPPINGOut.PAYOFF_DT as PAYOFF_DT,
SQ_ACCT_LOAD_MAPPINGOut.PRINCPL_BAL_AMT as PRINCPL_BAL_AMT,
SQ_ACCT_LOAD_MAPPINGOut.CURR_INTRST_DUE_AMT as CURR_INTRST_DUE_AMT,
SQ_ACCT_LOAD_MAPPINGOut.VEH_SALES_AMT as VEH_SALES_AMT
From SQ_ACCT_LOAD_MAPPINGOut as SQ_ACCT_LOAD_MAPPINGOut),

exp_InitialOut as (
	
Select 
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
LOAN_ORIG_BAL_AMT as LOAN_ORIG_BAL_AMT,
LOAN_CURR_BAL_AMT as LOAN_CURR_BAL_AMT,
FIRST_PMT_DUE_DT as FIRST_PMT_DUE_DT,
LAST_YR_INTRST_PD_AMT as LAST_YR_INTRST_PD_AMT,
( CASE WHEN PAYOFF_IND_in IS NOT NULL THEN LTRIM ( RTRIM ( PAYOFF_IND_in ) ) ELSE NULL END ) as PAYOFF_IND,
PAYOFF_DT as PAYOFF_DT,
PRINCPL_BAL_AMT as PRINCPL_BAL_AMT,
CURR_INTRST_DUE_AMT as CURR_INTRST_DUE_AMT,
VEH_SALES_AMT as VEH_SALES_AMT
From DSR_exp_InitialOut as DSR_exp_InitialOut),

exp_FinalOut as (
	
Select 
CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
LOAN_ORIG_BAL_AMT as LOAN_ORIG_BAL_AMT,
LOAN_CURR_BAL_AMT as LOAN_CURR_BAL_AMT,
FIRST_PMT_DUE_DT as FIRST_PMT_DUE_DT,
LAST_YR_INTRST_PD_AMT as LAST_YR_INTRST_PD_AMT,
PAYOFF_IND as PAYOFF_IND,
PAYOFF_DT as PAYOFF_DT,
PRINCPL_BAL_AMT as PRINCPL_BAL_AMT,
CURRENT_TIMESTAMP as INSERT_DT,
CURR_INTRST_DUE_AMT as CURR_INTRST_DUE_AMT,
VEH_SALES_AMT as VEH_SALES_AMT 
From exp_InitialOut as exp_InitialOut Where CONCISE_ACCT_NBR IS NOT NULL),

DSR_LOANOut as (
	
Select 
exp_FinalOut.CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
exp_FinalOut.LOAN_ORIG_BAL_AMT as ORIG_BAL_AMT,
exp_FinalOut.LOAN_CURR_BAL_AMT as CURR_BAL_AMT,
exp_FinalOut.FIRST_PMT_DUE_DT as FIRST_PMT_DUE_DT,
exp_FinalOut.LAST_YR_INTRST_PD_AMT as LAST_YR_INTRST_PD_AMT,
exp_FinalOut.PAYOFF_IND as PAYOFF_IND,
exp_FinalOut.PAYOFF_DT as PAYOFF_DT,
exp_FinalOut.PRINCPL_BAL_AMT as PRINCPL_BAL_AMT,
exp_FinalOut.INSERT_DT as INSERT_DT,
exp_FinalOut.CURR_INTRST_DUE_AMT as CURR_INTRST_DUE_AMT,
exp_FinalOut.VEH_SALES_AMT as VEH_SALES_AMT
From exp_FinalOut as exp_FinalOut)


Select 
	CONCISE_ACCT_NBR as CONCISE_ACCT_NBR,
	ORIG_BAL_AMT as ORIG_BAL_AMT,
	CURR_BAL_AMT as CURR_BAL_AMT,
	FIRST_PMT_DUE_DT as FIRST_PMT_DUE_DT,
	LAST_YR_INTRST_PD_AMT as LAST_YR_INTRST_PD_AMT,
	PAYOFF_IND as PAYOFF_IND,
	PAYOFF_DT as PAYOFF_DT,
	PRINCPL_BAL_AMT as PRINCPL_BAL_AMT,
	INSERT_DT as INSERT_DT,
	CURR_INTRST_DUE_AMT as CURR_INTRST_DUE_AMT,
	VEH_SALES_AMT as VEH_SALES_AMT 
From DSR_LOANOut as DSR_LOANOut