{{
	config(
		materialized='incremental',
		alias='TEMP_DIR+VERINT_EMP_INS',
		schema='tFileOutputDelimited_1',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='overwrite')
}}

Select 
	EMP_ID as EMP_ID,
	SOR_CD as SOR_CD,
	EFF_DTTM as EFF_DTTM,
	END_DTTM as END_DTTM,
	UNQ_KEY_TXT as UNQ_KEY_TXT,
	EMP_TYPE_ID as EMP_TYPE_ID,
	ASGN_PNT as ASGN_PNT,
	EMP_NBR as EMP_NBR,
	EMP_STRT_DTTM as EMP_STRT_DTTM,
	EMP_END_DTTM as EMP_END_DTTM,
	CHG_CNTR as CHG_CNTR,
	MOD_BY as MOD_BY,
	SPVSR_FLG as SPVSR_FLG,
	TEAM_LEAD_FLG as TEAM_LEAD_FLG,
	PREF_STRT_FLG as PREF_STRT_FLG,
	FRST_NM as FRST_NM,
	LAST_NM as LAST_NM,
	MDL_INITL as MDL_INITL,
	SUFX as SUFX,
	BRTH_DT as BRTH_DT,
	USR_NM as USR_NM,
	USR_STS as USR_STS,
	PROFILE_MOD_BY as PROFILE_MOD_BY,
	PROFILE_MOD_DTTM as PROFILE_MOD_DTTM,
	FAIL_LOGIN_CNT as FAIL_LOGIN_CNT,
	LAST_LOGIN_DTTM as LAST_LOGIN_DTTM,
	AUD_CRE_BY_NM as AUD_CRE_BY_NM,
	AUD_CRE_DTTM as AUD_CRE_DTTM,
	CURR_IND as CURR_IND,
	ETL_BATCH_ID as ETL_BATCH_ID 
FROM {{ ref('int_context.TEMP_DIR+VERINT_EMP_INS') }} AS lnk_insertOut