{{
  config(
    materialized='incremental',
    alias='BOE_VENUE_OF_EXECUTION_DIM',
    schema='',
    pre_hook="",
    post_hook="",
    incremental_strategy='merge',
    unique_key=['ID'],
    merge_update_columns=['EXPIRATION_DATE']
  )
}}
With SQ_SC_STG_SWP_INDEX_TENOROut as (
	/* SubQuery from Source ==>SQ_SQ_SC_STG_SWP_INDEX_TENOR */
/* transType: "Source" */
Select 
VENUE,
ISDA_PRODUCT_TYPE,
INDEX_1_MUREX_ID,
INDEX_2_MUREX_ID,
INDEX_1_CURRENCY_CODE,
INDEX_2_CURRENCY_CODE,
INDEX_1_PAY_FREQ,
INDEX_2_PAY_FREQ,
INDEX_1_DAY_COUNT,
INDEX_2_DAY_COUNT,
TENOR_KEY,
INDEX_2_PAY_FREQ_CHR,
INDEX_2_PAY_FREQ_NUM,
INDEX_1_PAY_FREQ_CHR,
INDEX_1_PAY_FREQ_NUM,
EXECUTION_VENUE_NAME,
EXECUTION_SOURCE_NAME,
EXECUTION_VENUE_TYPE,
ORIGINATING_EVENT,
MIC,
EXECUTION_VENUE_LEI
 from 
(WITH 
 TB as (
 SELECT
 distinct
    STD.FIXED_FLOAT_TYPE,
    STD.DAY_COUNT_FRACTION,
    SI.PERIOD_NAME_DISPLAY,
    STD.TRADE_ID as STD_TRADE_ID,
    SI.MUREX_INDEX_NAME,
    STD.PAY_RECEIVE_TYPE,
    STD.PAY_PERIOD_NAME_DISPLAY,
    SI.CURRENCY_CODE
 FROM
    STG_SWP_TRADE_DETAILS as STD
 LEFT OUTER JOIN 
 (SELECT
    *
 FROM
    STG_SWP_INDEX_TENOR
 WHERE  
  BUSINESS_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  ACTIVE_FLAG= 1) SI
 ON
  STD.INDEX_TENOR_ID= SI.INDEX_TENOR_ID
 WHERE  
  STD.BUSINESS_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  STD.ACTIVE_FLAG= 1)
 
 SELECT
    VENUE,
    ISDA_PRODUCT_TYPE,
    INDEX_1_MUREX_ID,
    INDEX_2_MUREX_ID,
    INDEX_1_CURRENCY_CODE,
    INDEX_2_CURRENCY_CODE,
    INDEX_1_PAY_FREQ,
    INDEX_2_PAY_FREQ,
    INDEX_1_DAY_COUNT,
    INDEX_2_DAY_COUNT,
    TENOR_KEY,
    TRIM(REPLACE(INDEX_2_PAY_FREQ,'0123456789',' ')) as INDEX_2_PAY_FREQ_CHR,
    TO_NUMBER(TRIM(REGEXP_REPLACE(INDEX_2_PAY_FREQ,'[^0-9]','','[^A-Za-z0-9_]',''))) as INDEX_2_PAY_FREQ_NUM,
    TRIM(REPLACE(INDEX_1_PAY_FREQ,'0123456789',' ')) as INDEX_1_PAY_FREQ_CHR,
    TO_NUMBER(TRIM(REGEXP_REPLACE(INDEX_1_PAY_FREQ,'[^0-9]','','[^A-Za-z0-9_]',''))) as INDEX_1_PAY_FREQ_NUM,
    EXECUTION_VENUE_NAME,
    EXECUTION_SOURCE_NAME,
    EXECUTION_VENUE_TYPE,
    ORIGINATING_EVENT,
    MIC,
    EXECUTION_VENUE_LEI
 FROM(
 SELECT
 distinct
    '' as VENUE,
    X.PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
    DECODE(X.LEG_ORDER,'P',X.PAY_MUREX_INDEX_NAME,X.REC_MUREX_INDEX_NAME) as INDEX_1_MUREX_ID,
    DECODE(X.LEG_ORDER,'P',X.REC_MUREX_INDEX_NAME,X.PAY_MUREX_INDEX_NAME) as INDEX_2_MUREX_ID,
    DECODE(X.LEG_ORDER,'P',X.PAY_CURRENCY_CODE,X.REC_CURRENCY_CODE) as INDEX_1_CURRENCY_CODE,
    DECODE(X.LEG_ORDER,'P',X.REC_CURRENCY_CODE,X.PAY_CURRENCY_CODE) as INDEX_2_CURRENCY_CODE,
    DECODE(DECODE(X.LEG_ORDER,'P',X.PAY_PAY_FREQ,X.REC_PAY_FREQ),'1Y','12M',DECODE(X.LEG_ORDER,'P',X.PAY_PAY_FREQ,X.REC_PAY_FREQ)) as INDEX_1_PAY_FREQ,
    DECODE(DECODE(X.LEG_ORDER,'P',DECODE(X.REC_FIXED_FLOAT_TYPE,'FLT',X.REC_PAY_FREQ),DECODE(X.PAY_FIXED_FLOAT_TYPE,'FLT',X.PAY_PAY_FREQ)),'1Y','12M',DECODE(X.LEG_ORDER,'P',DECODE(X.REC_FIXED_FLOAT_TYPE,'FLT',X.REC_PAY_FREQ),DECODE(X.PAY_FIXED_FLOAT_TYPE,'FLT',X.PAY_PAY_FREQ))) as INDEX_2_PAY_FREQ,
    DECODE(X.LEG_ORDER,'P',X.PAY_DAY_COUNT,X.REC_DAY_COUNT) as INDEX_1_DAY_COUNT,
    DECODE(X.LEG_ORDER,'P',DECODE(X.REC_FIXED_FLOAT_TYPE,'FLT',X.REC_DAY_COUNT),DECODE(X.PAY_FIXED_FLOAT_TYPE,'FLT',X.PAY_DAY_COUNT)) as INDEX_2_DAY_COUNT,
    X.TENOR_KEY,
    EXECUTION_VENUE_NAME,
    EXECUTION_SOURCE_NAME,
    EXECUTION_VENUE_TYPE,
    ORIGINATING_EVENT,
    MIC,
    EXECUTION_VENUE_LEI
 FROM
 (SELECT
    T.CURRENCY_CODE,
    T.LCH_PRODUCT_TYPE,
    T.PRODUCT_TYPE,
    T.CURRENCY_CODE || '_' || CASE WHEN T.LCH_PRODUCT_TYPE = 'Inflation ZC' THEN 'Inflation' WHEN T.LCH_PRODUCT_TYPE = 'Inflation SC_ParPar' THEN 'Inflation' WHEN T.LCH_PRODUCT_TYPE = 'Inflation SC_Proceeds' THEN 'Inflation' WHEN T.LCH_PRODUCT_TYPE = 'FRA' THEN 'FRA' WHEN T.LCH_PRODUCT_TYPE = 'OIS' THEN 'OIS' WHEN T.LCH_PRODUCT_TYPE = 'IRSND' THEN 'IRS' WHEN T.LCH_PRODUCT_TYPE = 'OISND' THEN 'OIS' WHEN T.LCH_PRODUCT_TYPE = 'ZCND' THEN 'Inflation' WHEN T.LCH_PRODUCT_TYPE = 'Basis Swap' AND(PAY.PERIOD_NAME_DISPLAY = '1D' OR REC.PERIOD_NAME_DISPLAY = '1D') THEN 'ONBS' WHEN T.PRODUCT_TYPE = 'InterestRate:IRSwap:OIS' AND T.LCH_PRODUCT_TYPE = 'VNS' THEN 'OIS' ELSE 'IRS' END as TENOR_KEY,
    PAY.FIXED_FLOAT_TYPE as PAY_FIXED_FLOAT_TYPE,
    PAY.MUREX_INDEX_NAME as PAY_MUREX_INDEX_NAME,
    PAY.CURRENCY_CODE as PAY_CURRENCY_CODE,
    NVL(PAY.PAY_PERIOD_NAME_DISPLAY,PAY.PERIOD_NAME_DISPLAY) as PAY_PAY_FREQ,
    PAY.DAY_COUNT_FRACTION as PAY_DAY_COUNT,
    REC.FIXED_FLOAT_TYPE as REC_FIXED_FLOAT_TYPE,
    REC.MUREX_INDEX_NAME as REC_MUREX_INDEX_NAME,
    REC.CURRENCY_CODE as REC_CURRENCY_CODE,
    NVL(REC.PAY_PERIOD_NAME_DISPLAY,REC.PERIOD_NAME_DISPLAY) as REC_PAY_FREQ,
    REC.DAY_COUNT_FRACTION as REC_DAY_COUNT,
    CASE
 WHEN PAY.MUREX_INDEX_NAME is null 
    THEN
    'R' WHEN REC.MUREX_INDEX_NAME is null 
    THEN
    'P' WHEN PAY.MUREX_INDEX_NAME || NVL(PAY.PAY_PERIOD_NAME_DISPLAY,PAY.PERIOD_NAME_DISPLAY) || PAY.DAY_COUNT_FRACTION < REC.MUREX_INDEX_NAME || NVL(REC.PAY_PERIOD_NAME_DISPLAY,REC.PERIOD_NAME_DISPLAY) || REC.DAY_COUNT_FRACTION 
    THEN
    'P' 
    ELSE
    'R' END as LEG_ORDER,
    EXECUTION_VENUE_NAME,
    EXECUTION_SOURCE_NAME,
    EXECUTION_VENUE_TYPE,
    ORIGINATING_EVENT,
    APPLICATION_VARIABLES.STRING_VALUE3 as MIC,
    EXECUTION_VENUE_LEI
 FROM
    STG_SWP_TRADE as T
 LEFT OUTER JOIN 
  APPLICATION_VARIABLES
 ON
  STRING_VALUE= 'SWP' AND 
  VARIABLE_NAME= 'EMIR_VENUE_OF_EXECUTION' AND 
  NVL(UPPER(EXECUTION_SOURCE_NAME),-2)= NVL(UPPER(STRING_VALUE4),-2) AND 
  NVL(UPPER(EXECUTION_VENUE_TYPE),-2)= NVL(UPPER(STRING_VALUE5),-2) AND 
  NVL(UPPER(ORIGINATING_EVENT),-2)= NVL(UPPER(STRING_VALUE7),-2) AND 
  NVL(UPPER(EXECUTION_VENUE_NAME),-2)= NVL(UPPER(STRING_VALUE2),-2)
 INNER JOIN 
  TB as PAY
 ON
  T.TRADE_ID= PAY.STD_TRADE_ID AND 
  T.ACTIVE_FLAG= 1 AND 
  PAY.PAY_RECEIVE_TYPE= 'P'
 INNER JOIN 
  TB as REC
 ON
  T.TRADE_ID= REC.STD_TRADE_ID AND 
  REC.PAY_RECEIVE_TYPE= 'R'
 WHERE 
  T.BUSINESS_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD')) X))
 ),

BOE_VENUE_OF_EXECUTION_DIMOut as (
	/* transType: "LookupSource" */
Select ID, 
		BATCH_ID, 
		BATCH_DETAILS_ID, 
		EFFECTIVE_DATE, 
		EXPIRATION_DATE, 
		EXCHANGE, 
		EXCHANGE_ID, 
		PRODUCT_ID, 
		MARKET_IDENTIFIER_CODE, 
		EXECUTION_SOURCE_NAME, 
		EXECUTION_VENUE_TYPE, 
		ORIGINATING_EVENT, 
		EXECUTION_VENUE_NAME, 
		i_PRODUCT_ID, 
		i_EXCHANGE_ID, 
		i_EXECUTION_SOURCE_NAME, 
		i_EXECUTION_VENUE_TYPE, 
		i_ORIGINATING_EVENT, 
		i_EXECUTION_VENUE_NAME, 
		i_MARKET_IDENTIFIER_CODE
 from 
{{ source ('LKP_TY2_BOE_VENUE_OF_EXEC_1','BOE_VENUE_OF_EXECUTION_DIM') }}
 ),

DSR_EXPTRANS_CODEOut as (
	/* transType: "Expression" */
Select 
	SQ_SC_STG_SWP_INDEX_TENOROut.VENUE as VENUE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 SQ_SC_STG_SWP_INDEX_TENOROut.TENOR_KEY as TENOR_KEY,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_PAY_FREQ_CHR as INDEX_2_PAY_FREQ_CHR,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_PAY_FREQ_NUM as INDEX_2_PAY_FREQ_NUM,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_PAY_FREQ_CHR as INDEX_1_PAY_FREQ_CHR,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_PAY_FREQ_NUM as INDEX_1_PAY_FREQ_NUM,
	 SQ_SC_STG_SWP_INDEX_TENOROut.EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME,
	 SQ_SC_STG_SWP_INDEX_TENOROut.EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 SQ_SC_STG_SWP_INDEX_TENOROut.EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.ORIGINATING_EVENT as ORIGINATING_EVENT,
	 SQ_SC_STG_SWP_INDEX_TENOROut.MIC as i_MARKET_IDENTIFIER_CODE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.EXECUTION_VENUE_LEI as EXECUTION_VENUE_LEI
From SQ_SC_STG_SWP_INDEX_TENOROut as SQ_SC_STG_SWP_INDEX_TENOROut),

EXPTRANS_CODEOut1 as (
	/* transType: "Expression" */
Select 
	'XXXX' as O_VENUE,
	 ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 TENOR_KEY as TENOR_KEY,
	 'DAY_COUNT_FRACTION' as DAY_COUNT_FRACTION_Name,
	 'SWP_TENOR_KEY' as SWP_TENOR_KEY_Name,
	 INDEX_2_PAY_FREQ_CHR as INDEX_2_PAY_FREQ_CHR,
	 INDEX_2_PAY_FREQ_NUM as INDEX_2_PAY_FREQ_NUM,
	 INDEX_1_PAY_FREQ_CHR as INDEX_1_PAY_FREQ_CHR,
	 INDEX_1_PAY_FREQ_NUM as INDEX_1_PAY_FREQ_NUM,
	 TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ) as v_BUSINESS_DATE,
	 dsf_1.ID as EXCHANGE_ID,
	 ISDA_PRODUCT_TYPE || INDEX_1_MUREX_ID || INDEX_1_PAY_FREQ || INDEX_1_DAY_COUNT || INDEX_2_MUREX_ID || INDEX_2_PAY_FREQ || INDEX_2_DAY_COUNT as PRODUCT_ID,
	 EXECUTION_VENUE_LEI as EXECUTION_VENUE_LEI,
	 dsf_2.STRING_VALUE3 as V_EXECUTION_VENUE_LEI_1,
	 dsf_3.STRING_VALUE3 as V_EXECUTION_VENUE_LEI_2,
	 ( CASE WHEN V_EXECUTION_VENUE_LEI_1 IS NULL THEN V_EXECUTION_VENUE_LEI_2 ELSE V_EXECUTION_VENUE_LEI_1 END ) as V_EXECUTION_VENUE_LEI,
	 ( CASE WHEN V_EXECUTION_VENUE_LEI IS NULL THEN ( CASE WHEN i_MARKET_IDENTIFIER_CODE IS NULL THEN 'XXXX' ELSE i_MARKET_IDENTIFIER_CODE END ) ELSE V_EXECUTION_VENUE_LEI END ) as MARKET_IDENTIFIER_CODE,
	 ( CASE WHEN UPPER ( EXECUTION_SOURCE_NAME ) IS NULL THEN TO_VARCHAR ( -2 ) ELSE UPPER ( EXECUTION_SOURCE_NAME ) END ) as o_EXECUTION_SOURCE_NAME,
	 ( CASE WHEN UPPER ( EXECUTION_VENUE_TYPE ) IS NULL THEN TO_VARCHAR ( -2 ) ELSE UPPER ( EXECUTION_VENUE_TYPE ) END ) as o_EXECUTION_VENUE_TYPE,
	 ( CASE WHEN UPPER ( ORIGINATING_EVENT ) IS NULL THEN TO_VARCHAR ( -2 ) ELSE UPPER ( ORIGINATING_EVENT ) END ) as o_ORIGINATING_EVENT,
	 ( CASE WHEN EXECUTION_VENUE_LEI IS NULL THEN EXECUTION_VENUE_NAME ELSE EXECUTION_VENUE_LEI END ) as V_EXECUTION_VENUE_NAME,
	 ( CASE WHEN UPPER ( V_EXECUTION_VENUE_NAME ) IS NULL THEN TO_VARCHAR ( -2 ) ELSE UPPER ( V_EXECUTION_VENUE_NAME ) END ) as o_EXECUTION_VENUE_NAME
From DSR_EXPTRANS_CODEOut as DSR_EXPTRANS_CODEOut
LEFT JOIN (
SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    EXCHANGE_DIM.ID as ID,    EXCHANGE_DIM.EXCHANGE_MNEMONIC as EXCHANGE_MNEMONIC,    EXCHANGE_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(EXCHANGE_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    EXCHANGE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.EXCHANGE_MNEMONIC = 'SWP' AND dsf_1.EFFECTIVE_DATE <= v_BUSINESS_DATE AND dsf_1.EXPIRATION_DATE >= v_BUSINESS_DATE
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE2 FROM (  SELECT STRING_VALUE3, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE3, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE3 as STRING_VALUE3,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    APPLICATION_VARIABLES.STRING_VALUE= 'SWP' AND   APPLICATION_VARIABLES.VARIABLE_NAME= 'SWP_VENUE_OF_EXECUTION' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.STRING_VALUE2 = UPPER(EXECUTION_VENUE_LEI)
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE2, STRING_VALUE4 FROM (  SELECT STRING_VALUE3, STRING_VALUE2, STRING_VALUE4,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2, STRING_VALUE4 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE3, STRING_VALUE2, STRING_VALUE4,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2, STRING_VALUE4 ORDER BY STRING_VALUE2, STRING_VALUE4 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE2 = UPPER(EXECUTION_VENUE_LEI) AND dsf_3.STRING_VALUE4 = UPPER(EXECUTION_VENUE_TYPE)
),

DSR_EXP_BVOEOut as (
	/* transType: "Expression" */
Select 
	EXPTRANS_CODEOut1.EXCHANGE_ID as EXCHANGE_ID,
	 EXPTRANS_CODEOut1.PRODUCT_ID as PRODUCT_ID,
	 EXPTRANS_CODEOut1.MARKET_IDENTIFIER_CODE as MARKET_IDENTIFIER_CODE,
	 EXPTRANS_CODEOut1.o_EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 EXPTRANS_CODEOut1.o_EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 EXPTRANS_CODEOut1.o_ORIGINATING_EVENT as ORIGINATING_EVENT,
	 EXPTRANS_CODEOut1.o_EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME
From EXPTRANS_CODEOut as EXPTRANS_CODEOut),

EXP_BVOEOut as (
	/* transType: "Expression" */
Select 
	EXCHANGE_ID as EXCHANGE_ID,
	 PRODUCT_ID as PRODUCT_ID,
	 MARKET_IDENTIFIER_CODE as MARKET_IDENTIFIER_CODE,
	 EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 ORIGINATING_EVENT as ORIGINATING_EVENT,
	 EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME
From DSR_EXP_BVOEOut as DSR_EXP_BVOEOut),

EXP_BVOEOut1 as (
	/* transType: "Expression" */
Select 
	EXCHANGE_ID as EXCHANGE_ID,
	 PRODUCT_ID as PRODUCT_ID,
	 MARKET_IDENTIFIER_CODE as MARKET_IDENTIFIER_CODE,
	 EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 ORIGINATING_EVENT as ORIGINATING_EVENT,
	 EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME
From DSR_EXP_BVOEOut as DSR_EXP_BVOEOut),

LKP_TY2_BOE_VENUE_OF_EXECOut as (
	/* transType: "Lookup Procedure" */
Select 
	ID as ID,
	 BATCH_ID as BATCH_ID,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EFFECTIVE_DATE as EFFECTIVE_DATE,
	 EXPIRATION_DATE as EXPIRATION_DATE,
	 EXCHANGE as EXCHANGE,
	 EXCHANGE_ID as EXCHANGE_ID,
	 PRODUCT_ID as PRODUCT_ID,
	 MARKET_IDENTIFIER_CODE as MARKET_IDENTIFIER_CODE,
	 EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 ORIGINATING_EVENT as ORIGINATING_EVENT,
	 EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME,
	 EXP_BVOEOut.i_MARKET_IDENTIFIER_CODE as i_MARKET_IDENTIFIER_CODE_1,
	 EXP_BVOE.PRODUCT_ID AS i_PRODUCT_ID,
	 EXP_BVOE.EXCHANGE_ID AS i_EXCHANGE_ID,
	 EXP_BVOE.EXECUTION_SOURCE_NAME AS i_EXECUTION_SOURCE_NAME,
	 EXP_BVOE.EXECUTION_VENUE_TYPE AS i_EXECUTION_VENUE_TYPE,
	 EXP_BVOE.ORIGINATING_EVENT AS i_ORIGINATING_EVENT,
	 EXP_BVOE.EXECUTION_VENUE_NAME AS i_EXECUTION_VENUE_NAME,
	 EXP_BVOE.MARKET_IDENTIFIER_CODE AS i_MARKET_IDENTIFIER_CODE_2 
FROM
	EXP_BVOEOut1 as EXP_BVOEOut1 
 LEFT JOIN BOE_VENUE_OF_EXECUTION_DIMOut
ON
	PRODUCT_ID = i_PRODUCT_ID
	AND EXECUTION_SOURCE_NAME = i_EXECUTION_SOURCE_NAME
	AND EXECUTION_VENUE_TYPE = i_EXECUTION_VENUE_TYPE
	AND ORIGINATING_EVENT = i_ORIGINATING_EVENT
	AND EXECUTION_VENUE_NAME = i_EXECUTION_VENUE_NAME
 
 Where to_date('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') between EFFECTIVE_DATE AND NVL(EXPIRATION_DATE,TO_DATE('99991231','YYYYMMDD')) and EXCHANGE='SWP'),

LKP_TY2_BOE_VENUE_OF_EXEC_master as (
  Select
  	LKP_TY2_BOE_VENUE_OF_EXECOut.ID as LKP_ID,
	 LKP_TY2_BOE_VENUE_OF_EXECOut.EXCHANGE_ID as LKP_EXCHANGE_ID,
	 LKP_TY2_BOE_VENUE_OF_EXECOut.PRODUCT_ID as LKP_PRODUCT_ID,
	 LKP_TY2_BOE_VENUE_OF_EXECOut.MARKET_IDENTIFIER_CODE as LKP_MARKET_IDENTIFIER_CODE,
	 LKP_TY2_BOE_VENUE_OF_EXECOut.EXECUTION_SOURCE_NAME as LKP_EXECUTION_SOURCE_NAME,
	 LKP_TY2_BOE_VENUE_OF_EXECOut.EXECUTION_VENUE_TYPE as LKP_EXECUTION_VENUE_TYPE,
	 LKP_TY2_BOE_VENUE_OF_EXECOut.ORIGINATING_EVENT as LKP_ORIGINATING_EVENT,
	 LKP_TY2_BOE_VENUE_OF_EXECOut.EXECUTION_VENUE_NAME as LKP_EXECUTION_VENUE_NAME
  From LKP_TY2_BOE_VENUE_OF_EXECOut as LKP_TY2_BOE_VENUE_OF_EXECOut
),
dsJoiner_EXP_LKP_SORT_PORTS10Out as (
	/* transType: "Joiner" */
Select 
	LKP_TY2_BOE_VENUE_OF_EXEC_master.LKP_ID as LKP_ID,
	 LKP_TY2_BOE_VENUE_OF_EXEC_master.LKP_EXCHANGE_ID as LKP_EXCHANGE_ID,
	 LKP_TY2_BOE_VENUE_OF_EXEC_master.LKP_PRODUCT_ID as LKP_PRODUCT_ID,
	 LKP_TY2_BOE_VENUE_OF_EXEC_master.LKP_MARKET_IDENTIFIER_CODE as LKP_MARKET_IDENTIFIER_CODE,
	 LKP_TY2_BOE_VENUE_OF_EXEC_master.LKP_EXECUTION_SOURCE_NAME as LKP_EXECUTION_SOURCE_NAME,
	 LKP_TY2_BOE_VENUE_OF_EXEC_master.LKP_EXECUTION_VENUE_TYPE as LKP_EXECUTION_VENUE_TYPE,
	 LKP_TY2_BOE_VENUE_OF_EXEC_master.LKP_ORIGINATING_EVENT as LKP_ORIGINATING_EVENT,
	 LKP_TY2_BOE_VENUE_OF_EXEC_master.LKP_EXECUTION_VENUE_NAME as LKP_EXECUTION_VENUE_NAME,
	 EXP_BVOEOut.EXCHANGE_ID as EXCHANGE_ID,
	 EXP_BVOEOut.PRODUCT_ID as PRODUCT_ID,
	 EXP_BVOEOut.MARKET_IDENTIFIER_CODE as MARKET_IDENTIFIER_CODE,
	 EXP_BVOEOut.EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 EXP_BVOEOut.EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 EXP_BVOEOut.ORIGINATING_EVENT as ORIGINATING_EVENT,
	 EXP_BVOEOut.EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
LKP_TY2_BOE_VENUE_OF_EXEC_master as LKP_TY2_BOE_VENUE_OF_EXEC_master inner JOIN EXP_BVOEOut as EXP_BVOEOut 
ON
EXP_BVOEOut.jkey = LKP_TY2_BOE_VENUE_OF_EXEC_master.jkey 
),

EXP_LKP_SORT_PORTS1Out as (
	/* transType: "Expression" */
Select 
	LKP_ID as LKP_ID,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 dsf_1.ID as BATCH_DETAILS_ID,
	 TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ) as EFFECTIVE_DATE,
	 TO_DATE ( '01-JAN-99',
	 'DD-MON-YY' ) as EXPIRATION_DATE,
	 'SWP' as EXCHANGE,
	 EXCHANGE_ID as EXCHANGE_ID,
	 PRODUCT_ID as PRODUCT_ID,
	 MARKET_IDENTIFIER_CODE as MARKET_IDENTIFIER_CODE,
	 EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 ORIGINATING_EVENT as ORIGINATING_EVENT,
	 EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME,
	 ( CASE WHEN LKP_ID IS NULL THEN 'Y' ELSE 'N' END ) as v_NN_CHECK_LKP_COLS,
	 ( CASE WHEN v_NN_CHECK_LKP_COLS = 'N' AND ( EXCHANGE_ID  !=  LKP_EXCHANGE_ID OR PRODUCT_ID  !=  LKP_PRODUCT_ID OR MARKET_IDENTIFIER_CODE  !=  LKP_MARKET_IDENTIFIER_CODE OR EXECUTION_SOURCE_NAME  !=  LKP_EXECUTION_SOURCE_NAME OR EXECUTION_VENUE_TYPE  !=  LKP_EXECUTION_VENUE_TYPE OR ORIGINATING_EVENT  !=  LKP_ORIGINATING_EVENT OR EXECUTION_VENUE_NAME  !=  LKP_EXECUTION_VENUE_NAME ) THEN 'Y' ELSE 'N' END ) as v_CHNG_FLAG,
	 v_CHNG_FLAG as o_CHNG_FLAG,
	 ( CASE WHEN LKP_ID IS NULL OR ( LKP_ID IS NOT NULL AND v_CHNG_FLAG = 'Y' ) THEN v_TOT_REC_COUNT + 1 ELSE v_TOT_REC_COUNT END ) as v_TOT_REC_COUNT
From dsJoiner_EXP_LKP_SORT_PORTS10Out as dsJoiner_EXP_LKP_SORT_PORTS10Out
LEFT JOIN (
SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME FROM (  SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, BATCH_ID, TARGET_TABLE_NAME, FILE_NAME,  ROW_NUMBER() OVER (PARTITION BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME ORDER BY BATCH_ID, TARGET_TABLE_NAME, FILE_NAME NULLS LAST) AS rnk_fst   FROM ( SELECT    BATCH_DETAILS.ID as ID,    BATCH_DETAILS.BATCH_ID as BATCH_ID,    BATCH_DETAILS.TARGET_TABLE_NAME as TARGET_TABLE_NAME,    BATCH_DETAILS.FILE_NAME as FILE_NAME,    BATCH_DETAILS.STATUS as STATUS FROM (SELECT    id,    TARGET_TABLE_NAME,    BATCH_ID,    STATUS,    ACTIVE_FLAG,    BATCH_DETAILS_START_TIME,    FILE_NAME,    RANK() OVER(partition by batch_id,TARGET_TABLE_NAME,FILE_NAME order by BATCH_DETAILS_START_TIME DESC) as RANK FROM    BATCH_DETAILS) BATCH_DETAILS WHERE    RANK= 1 AND   STATUS= 'I' AND   ACTIVE_FLAG= 1 )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_1.TARGET_TABLE_NAME = '{{ var("TARGET_NAME_VOE") }}' AND dsf_1.FILE_NAME = '{{ var("SOURCE_NAME_VOE") }}'
),

DSR_RTR_IN_UPD_BVOEOut as (
	/* transType: "Expression" */
Select 
	EXP_LKP_SORT_PORTS1Out.LKP_ID as LKP_ID,
	 EXP_LKP_SORT_PORTS1Out.BATCH_ID as BATCH_ID,
	 EXP_LKP_SORT_PORTS1Out.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_LKP_SORT_PORTS1Out.EFFECTIVE_DATE as EFFECTIVE_DATE,
	 EXP_LKP_SORT_PORTS1Out.EXPIRATION_DATE as EXPIREDATE,
	 EXP_LKP_SORT_PORTS1Out.EXCHANGE as EXCHANGE,
	 EXP_LKP_SORT_PORTS1Out.EXCHANGE_ID as EXCHANGE_ID,
	 EXP_LKP_SORT_PORTS1Out.PRODUCT_ID as PRODUCT_ID,
	 EXP_LKP_SORT_PORTS1Out.MARKET_IDENTIFIER_CODE as MARKET_IDENTIFIER_CODE,
	 EXP_LKP_SORT_PORTS1Out.EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 EXP_LKP_SORT_PORTS1Out.EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 EXP_LKP_SORT_PORTS1Out.ORIGINATING_EVENT as ORIGINATING_EVENT,
	 EXP_LKP_SORT_PORTS1Out.EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME,
	 EXP_LKP_SORT_PORTS1Out.o_CHNG_FLAG as CHNG_FLAG
From EXP_LKP_SORT_PORTS1Out as EXP_LKP_SORT_PORTS1Out),

DSR_EXP_UPDATE1Out as (
	/* transType: "Expression" */
Select 
	RTR_IN_UPD_BVOEOut2.LKP_ID3 as LKP_ID
From DSR_RTR_IN_UPD_BVOEOut as DSR_RTR_IN_UPD_BVOEOut
WHERE ISNULL(LKP_ID)),

EXP_UPDATE1Out as (
	/* transType: "Expression" */
Select 
	LKP_ID as LKP_ID,
	 DATEADD ( '-1',
	 'DD',
	 TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ) ) as EXPIREDATE
From DSR_EXP_UPDATE1Out as DSR_EXP_UPDATE1Out),

DSR_SC_BOE_VENUE_OF_EXECUTION_DIM_CHG_UPDOut as (
	/* transType: "Expression" */
Select 
	EXP_UPDATE1Out.LKP_ID as LKP_ID,
	 EXP_UPDATE1Out.EXPIREDATE as EXPIREDATE3
From EXP_UPDATE1Out as EXP_UPDATE1Out)

Select 
	LKP_ID as ID,
	EXPIREDATE3 as EXPIRATION_DATE 
From DSR_SC_BOE_VENUE_OF_EXECUTION_DIM_CHG_UPDOut as DSR_SC_BOE_VENUE_OF_EXECUTION_DIM_CHG_UPDOut