{{
  config(
    materialized='incremental',
    alias='SWP_CLEARED_PRODUCTS_DIM',
    schema='',
    pre_hook="",
    post_hook="",
    incremental_strategy='merge',
    unique_key=['ID'],
    merge_update_columns=['EXPIRATION_DATE']
  )
}}
With APPLICATION_VARIABLESOut as (
	/* transType: "LookupSource" */
Select ID, 
		VARIABLE_NAME, 
		STRING_VALUE, 
		STRING_VALUE2, 
		STRING_VALUE3, 
		i_STRING_VALUE, 
		i_VARIABLE_NAME
 from 
{{ source ('SC_LKP_APPLICATION_VARIABLES_BOE_1','APPLICATION_VARIABLES') }}
 ),

SQ_SC_STG_SWP_INDEX_TENOROut as (
	/* SubQuery from Source ==>SQ_SQ_SC_STG_SWP_INDEX_TENOR */
/* transType: "Source" */
Select 
VENUE,
ISDA_PRODUCT_TYPE,
INDEX_1_MUREX_ID,
INDEX_2_MUREX_ID,
INDEX_1_CURRENCY_CODE,
INDEX_2_CURRENCY_CODE,
INDEX_1_PAY_FREQ,
INDEX_2_PAY_FREQ,
INDEX_1_DAY_COUNT,
INDEX_2_DAY_COUNT,
TENOR_KEY,
INDEX_2_PAY_FREQ_CHR,
INDEX_2_PAY_FREQ_NUM,
INDEX_1_PAY_FREQ_CHR,
INDEX_1_PAY_FREQ_NUM,
EXECUTION_VENUE_NAME,
EXECUTION_SOURCE_NAME,
EXECUTION_VENUE_TYPE,
ORIGINATING_EVENT,
MIC,
EXECUTION_VENUE_LEI
 from 
(WITH 
 TB as (
 SELECT
 distinct
    STD.FIXED_FLOAT_TYPE,
    STD.DAY_COUNT_FRACTION,
    SI.PERIOD_NAME_DISPLAY,
    STD.TRADE_ID as STD_TRADE_ID,
    SI.MUREX_INDEX_NAME,
    STD.PAY_RECEIVE_TYPE,
    STD.PAY_PERIOD_NAME_DISPLAY,
    SI.CURRENCY_CODE
 FROM
    STG_SWP_TRADE_DETAILS as STD
 LEFT OUTER JOIN 
 (SELECT
    *
 FROM
    STG_SWP_INDEX_TENOR
 WHERE  
  BUSINESS_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  ACTIVE_FLAG= 1) SI
 ON
  STD.INDEX_TENOR_ID= SI.INDEX_TENOR_ID
 WHERE  
  STD.BUSINESS_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  STD.ACTIVE_FLAG= 1)
 
 SELECT
    VENUE,
    ISDA_PRODUCT_TYPE,
    INDEX_1_MUREX_ID,
    INDEX_2_MUREX_ID,
    INDEX_1_CURRENCY_CODE,
    INDEX_2_CURRENCY_CODE,
    INDEX_1_PAY_FREQ,
    INDEX_2_PAY_FREQ,
    INDEX_1_DAY_COUNT,
    INDEX_2_DAY_COUNT,
    TENOR_KEY,
    TRIM(REPLACE(INDEX_2_PAY_FREQ,'0123456789',' ')) as INDEX_2_PAY_FREQ_CHR,
    TO_NUMBER(TRIM(REGEXP_REPLACE(INDEX_2_PAY_FREQ,'[^0-9]','','[^A-Za-z0-9_]',''))) as INDEX_2_PAY_FREQ_NUM,
    TRIM(REPLACE(INDEX_1_PAY_FREQ,'0123456789',' ')) as INDEX_1_PAY_FREQ_CHR,
    TO_NUMBER(TRIM(REGEXP_REPLACE(INDEX_1_PAY_FREQ,'[^0-9]','','[^A-Za-z0-9_]',''))) as INDEX_1_PAY_FREQ_NUM,
    EXECUTION_VENUE_NAME,
    EXECUTION_SOURCE_NAME,
    EXECUTION_VENUE_TYPE,
    ORIGINATING_EVENT,
    MIC,
    EXECUTION_VENUE_LEI
 FROM(
 SELECT
 distinct
    '' as VENUE,
    X.PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
    DECODE(X.LEG_ORDER,'P',X.PAY_MUREX_INDEX_NAME,X.REC_MUREX_INDEX_NAME) as INDEX_1_MUREX_ID,
    DECODE(X.LEG_ORDER,'P',X.REC_MUREX_INDEX_NAME,X.PAY_MUREX_INDEX_NAME) as INDEX_2_MUREX_ID,
    DECODE(X.LEG_ORDER,'P',X.PAY_CURRENCY_CODE,X.REC_CURRENCY_CODE) as INDEX_1_CURRENCY_CODE,
    DECODE(X.LEG_ORDER,'P',X.REC_CURRENCY_CODE,X.PAY_CURRENCY_CODE) as INDEX_2_CURRENCY_CODE,
    DECODE(DECODE(X.LEG_ORDER,'P',X.PAY_PAY_FREQ,X.REC_PAY_FREQ),'1Y','12M',DECODE(X.LEG_ORDER,'P',X.PAY_PAY_FREQ,X.REC_PAY_FREQ)) as INDEX_1_PAY_FREQ,
    DECODE(DECODE(X.LEG_ORDER,'P',DECODE(X.REC_FIXED_FLOAT_TYPE,'FLT',X.REC_PAY_FREQ),DECODE(X.PAY_FIXED_FLOAT_TYPE,'FLT',X.PAY_PAY_FREQ)),'1Y','12M',DECODE(X.LEG_ORDER,'P',DECODE(X.REC_FIXED_FLOAT_TYPE,'FLT',X.REC_PAY_FREQ),DECODE(X.PAY_FIXED_FLOAT_TYPE,'FLT',X.PAY_PAY_FREQ))) as INDEX_2_PAY_FREQ,
    DECODE(X.LEG_ORDER,'P',X.PAY_DAY_COUNT,X.REC_DAY_COUNT) as INDEX_1_DAY_COUNT,
    DECODE(X.LEG_ORDER,'P',DECODE(X.REC_FIXED_FLOAT_TYPE,'FLT',X.REC_DAY_COUNT),DECODE(X.PAY_FIXED_FLOAT_TYPE,'FLT',X.PAY_DAY_COUNT)) as INDEX_2_DAY_COUNT,
    X.TENOR_KEY,
    EXECUTION_VENUE_NAME,
    EXECUTION_SOURCE_NAME,
    EXECUTION_VENUE_TYPE,
    ORIGINATING_EVENT,
    MIC,
    EXECUTION_VENUE_LEI
 FROM
 (SELECT
    T.CURRENCY_CODE,
    T.LCH_PRODUCT_TYPE,
    T.PRODUCT_TYPE,
    T.CURRENCY_CODE || '_' || CASE WHEN T.LCH_PRODUCT_TYPE = 'Inflation ZC' THEN 'Inflation' WHEN T.LCH_PRODUCT_TYPE = 'Inflation SC_ParPar' THEN 'Inflation' WHEN T.LCH_PRODUCT_TYPE = 'Inflation SC_Proceeds' THEN 'Inflation' WHEN T.LCH_PRODUCT_TYPE = 'FRA' THEN 'FRA' WHEN T.LCH_PRODUCT_TYPE = 'OIS' THEN 'OIS' WHEN T.LCH_PRODUCT_TYPE = 'IRSND' THEN 'IRS' WHEN T.LCH_PRODUCT_TYPE = 'OISND' THEN 'OIS' WHEN T.LCH_PRODUCT_TYPE = 'ZCND' THEN 'Inflation' WHEN T.LCH_PRODUCT_TYPE = 'Basis Swap' AND(PAY.PERIOD_NAME_DISPLAY = '1D' OR REC.PERIOD_NAME_DISPLAY = '1D') THEN 'ONBS' WHEN T.PRODUCT_TYPE = 'InterestRate:IRSwap:OIS' AND T.LCH_PRODUCT_TYPE = 'VNS' THEN 'OIS' ELSE 'IRS' END as TENOR_KEY,
    PAY.FIXED_FLOAT_TYPE as PAY_FIXED_FLOAT_TYPE,
    PAY.MUREX_INDEX_NAME as PAY_MUREX_INDEX_NAME,
    PAY.CURRENCY_CODE as PAY_CURRENCY_CODE,
    NVL(PAY.PAY_PERIOD_NAME_DISPLAY,PAY.PERIOD_NAME_DISPLAY) as PAY_PAY_FREQ,
    PAY.DAY_COUNT_FRACTION as PAY_DAY_COUNT,
    REC.FIXED_FLOAT_TYPE as REC_FIXED_FLOAT_TYPE,
    REC.MUREX_INDEX_NAME as REC_MUREX_INDEX_NAME,
    REC.CURRENCY_CODE as REC_CURRENCY_CODE,
    NVL(REC.PAY_PERIOD_NAME_DISPLAY,REC.PERIOD_NAME_DISPLAY) as REC_PAY_FREQ,
    REC.DAY_COUNT_FRACTION as REC_DAY_COUNT,
    CASE
 WHEN PAY.MUREX_INDEX_NAME is null 
    THEN
    'R' WHEN REC.MUREX_INDEX_NAME is null 
    THEN
    'P' WHEN PAY.MUREX_INDEX_NAME || NVL(PAY.PAY_PERIOD_NAME_DISPLAY,PAY.PERIOD_NAME_DISPLAY) || PAY.DAY_COUNT_FRACTION < REC.MUREX_INDEX_NAME || NVL(REC.PAY_PERIOD_NAME_DISPLAY,REC.PERIOD_NAME_DISPLAY) || REC.DAY_COUNT_FRACTION 
    THEN
    'P' 
    ELSE
    'R' END as LEG_ORDER,
    EXECUTION_VENUE_NAME,
    EXECUTION_SOURCE_NAME,
    EXECUTION_VENUE_TYPE,
    ORIGINATING_EVENT,
    APPLICATION_VARIABLES.STRING_VALUE3 as MIC,
    EXECUTION_VENUE_LEI
 FROM
    STG_SWP_TRADE as T
 LEFT OUTER JOIN 
  APPLICATION_VARIABLES
 ON
  STRING_VALUE= 'SWP' AND 
  VARIABLE_NAME= 'EMIR_VENUE_OF_EXECUTION' AND 
  NVL(UPPER(EXECUTION_SOURCE_NAME),-2)= NVL(UPPER(STRING_VALUE4),-2) AND 
  NVL(UPPER(EXECUTION_VENUE_TYPE),-2)= NVL(UPPER(STRING_VALUE5),-2) AND 
  NVL(UPPER(ORIGINATING_EVENT),-2)= NVL(UPPER(STRING_VALUE7),-2) AND 
  NVL(UPPER(EXECUTION_VENUE_NAME),-2)= NVL(UPPER(STRING_VALUE2),-2)
 INNER JOIN 
  TB as PAY
 ON
  T.TRADE_ID= PAY.STD_TRADE_ID AND 
  T.ACTIVE_FLAG= 1 AND 
  PAY.PAY_RECEIVE_TYPE= 'P'
 INNER JOIN 
  TB as REC
 ON
  T.TRADE_ID= REC.STD_TRADE_ID AND 
  REC.PAY_RECEIVE_TYPE= 'R'
 WHERE 
  T.BUSINESS_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD')) X))
 ),

SWP_CLEARED_PRODUCTS_DIMOut as (
	/* transType: "LookupSource" */
Select ID, 
		BATCH_ID, 
		BATCH_DETAILS_ID, 
		EFFECTIVE_DATE, 
		EXPIRATION_DATE, 
		VENUE, 
		ASSET_CLASS, 
		BASE_PRODUCT, 
		SUB_PRODUCT, 
		ISDA_PRODUCT_TYPE, 
		INDEX_1_MUREX_NAME, 
		INDEX_1_PAY_FREQ, 
		INDEX_1_TENOR_CCY, 
		INDEX_1_DAY_COUNT, 
		INDEX_2_MUREX_NAME, 
		INDEX_2_PAY_FREQ, 
		INDEX_2_TENOR_CCY, 
		INDEX_2_DAY_COUNT, 
		MAX_CONTRACT_TENOR_VALUE, 
		MAX_CONTRACT_TENOR_UNIT, 
		PROPAGATE_INDICATOR, 
		ERROR_INDICATOR, 
		TENOR_KEY, 
		i_VENUE, 
		i_ISDA_PRODUCT_TYPE, 
		i_ASSET_CLASS, 
		i_BASE_PRODUCT, 
		i_SUB_PRODUCT, 
		i_INDEX_1_MUREX_ID, 
		i_INDEX_2_MUREX_ID, 
		in_INDEX_1_PAY_FREQ, 
		in_INDEX_2_PAY_FREQ, 
		in_INDEX_1_DAY_COUNT, 
		in_INDEX_2_DAY_COUNT, 
		in_INDEX_1_TENOR_CCY, 
		in_INDEX_2_TENOR_CCY, 
		in_TENOR_KEY
 from 
{{ source ('LKP_CLEARED_PRODUCTS_1','SWP_CLEARED_PRODUCTS_DIM') }}
 ),

DSR_EXPTRANS_CODEOut as (
	/* transType: "Expression" */
Select 
	SQ_SC_STG_SWP_INDEX_TENOROut.VENUE as VENUE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 SQ_SC_STG_SWP_INDEX_TENOROut.TENOR_KEY as TENOR_KEY,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_PAY_FREQ_CHR as INDEX_2_PAY_FREQ_CHR,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_2_PAY_FREQ_NUM as INDEX_2_PAY_FREQ_NUM,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_PAY_FREQ_CHR as INDEX_1_PAY_FREQ_CHR,
	 SQ_SC_STG_SWP_INDEX_TENOROut.INDEX_1_PAY_FREQ_NUM as INDEX_1_PAY_FREQ_NUM,
	 SQ_SC_STG_SWP_INDEX_TENOROut.EXECUTION_VENUE_NAME as EXECUTION_VENUE_NAME,
	 SQ_SC_STG_SWP_INDEX_TENOROut.EXECUTION_SOURCE_NAME as EXECUTION_SOURCE_NAME,
	 SQ_SC_STG_SWP_INDEX_TENOROut.EXECUTION_VENUE_TYPE as EXECUTION_VENUE_TYPE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.ORIGINATING_EVENT as ORIGINATING_EVENT,
	 SQ_SC_STG_SWP_INDEX_TENOROut.MIC as i_MARKET_IDENTIFIER_CODE,
	 SQ_SC_STG_SWP_INDEX_TENOROut.EXECUTION_VENUE_LEI as EXECUTION_VENUE_LEI
From SQ_SC_STG_SWP_INDEX_TENOROut as SQ_SC_STG_SWP_INDEX_TENOROut),

EXPTRANS_CODEOut as (
	/* transType: "Expression" */
Select 
	'XXXX' as O_VENUE,
	 ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 TENOR_KEY as TENOR_KEY,
	 'DAY_COUNT_FRACTION' as DAY_COUNT_FRACTION_Name,
	 'SWP_TENOR_KEY' as SWP_TENOR_KEY_Name,
	 INDEX_2_PAY_FREQ_CHR as INDEX_2_PAY_FREQ_CHR,
	 INDEX_2_PAY_FREQ_NUM as INDEX_2_PAY_FREQ_NUM,
	 INDEX_1_PAY_FREQ_CHR as INDEX_1_PAY_FREQ_CHR,
	 INDEX_1_PAY_FREQ_NUM as INDEX_1_PAY_FREQ_NUM,
	 TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ) as v_BUSINESS_DATE,
	 dsf_1.ID as EXCHANGE_ID,
	 ISDA_PRODUCT_TYPE || INDEX_1_MUREX_ID || INDEX_1_PAY_FREQ || INDEX_1_DAY_COUNT || INDEX_2_MUREX_ID || INDEX_2_PAY_FREQ || INDEX_2_DAY_COUNT as PRODUCT_ID,
	 EXECUTION_VENUE_LEI as EXECUTION_VENUE_LEI,
	 dsf_2.STRING_VALUE3 as V_EXECUTION_VENUE_LEI_1,
	 dsf_3.STRING_VALUE3 as V_EXECUTION_VENUE_LEI_2,
	 ( CASE WHEN V_EXECUTION_VENUE_LEI_1 IS NULL THEN V_EXECUTION_VENUE_LEI_2 ELSE V_EXECUTION_VENUE_LEI_1 END ) as V_EXECUTION_VENUE_LEI,
	 ( CASE WHEN V_EXECUTION_VENUE_LEI IS NULL THEN ( CASE WHEN i_MARKET_IDENTIFIER_CODE IS NULL THEN 'XXXX' ELSE i_MARKET_IDENTIFIER_CODE END ) ELSE V_EXECUTION_VENUE_LEI END ) as MARKET_IDENTIFIER_CODE,
	 ( CASE WHEN UPPER ( EXECUTION_SOURCE_NAME ) IS NULL THEN TO_VARCHAR ( -2 ) ELSE UPPER ( EXECUTION_SOURCE_NAME ) END ) as o_EXECUTION_SOURCE_NAME,
	 ( CASE WHEN UPPER ( EXECUTION_VENUE_TYPE ) IS NULL THEN TO_VARCHAR ( -2 ) ELSE UPPER ( EXECUTION_VENUE_TYPE ) END ) as o_EXECUTION_VENUE_TYPE,
	 ( CASE WHEN UPPER ( ORIGINATING_EVENT ) IS NULL THEN TO_VARCHAR ( -2 ) ELSE UPPER ( ORIGINATING_EVENT ) END ) as o_ORIGINATING_EVENT,
	 ( CASE WHEN EXECUTION_VENUE_LEI IS NULL THEN EXECUTION_VENUE_NAME ELSE EXECUTION_VENUE_LEI END ) as V_EXECUTION_VENUE_NAME,
	 ( CASE WHEN UPPER ( V_EXECUTION_VENUE_NAME ) IS NULL THEN TO_VARCHAR ( -2 ) ELSE UPPER ( V_EXECUTION_VENUE_NAME ) END ) as o_EXECUTION_VENUE_NAME
From DSR_EXPTRANS_CODEOut as DSR_EXPTRANS_CODEOut
LEFT JOIN (
SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    EXCHANGE_DIM.ID as ID,    EXCHANGE_DIM.EXCHANGE_MNEMONIC as EXCHANGE_MNEMONIC,    EXCHANGE_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(EXCHANGE_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    EXCHANGE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.EXCHANGE_MNEMONIC = 'SWP' AND dsf_1.EFFECTIVE_DATE <= v_BUSINESS_DATE AND dsf_1.EXPIRATION_DATE >= v_BUSINESS_DATE
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE2 FROM (  SELECT STRING_VALUE3, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE3, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2 ORDER BY STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE3 as STRING_VALUE3,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2 FROM    APPLICATION_VARIABLES WHERE    APPLICATION_VARIABLES.STRING_VALUE= 'SWP' AND   APPLICATION_VARIABLES.VARIABLE_NAME= 'SWP_VENUE_OF_EXECUTION' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.STRING_VALUE2 = UPPER(EXECUTION_VENUE_LEI)
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE2, STRING_VALUE4 FROM (  SELECT STRING_VALUE3, STRING_VALUE2, STRING_VALUE4,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2, STRING_VALUE4 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE3, STRING_VALUE2, STRING_VALUE4,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE2, STRING_VALUE4 ORDER BY STRING_VALUE2, STRING_VALUE4 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE2 = UPPER(EXECUTION_VENUE_LEI) AND dsf_3.STRING_VALUE4 = UPPER(EXECUTION_VENUE_TYPE)
),

DSR_SRT_SWP_CLRPDT_DIMOut as (
	/* transType: "Expression" */
Select 
	EXPTRANS_CODEOut.O_VENUE as VENUE,
	 EXPTRANS_CODEOut.ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 EXPTRANS_CODEOut.INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 EXPTRANS_CODEOut.INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 EXPTRANS_CODEOut.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 EXPTRANS_CODEOut.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 EXPTRANS_CODEOut.INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 EXPTRANS_CODEOut.INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 EXPTRANS_CODEOut.INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 EXPTRANS_CODEOut.INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 EXPTRANS_CODEOut.TENOR_KEY as TENOR_KEY,
	 EXPTRANS_CODEOut.DAY_COUNT_FRACTION_Name as DAY_COUNT_FRACTION_Name,
	 EXPTRANS_CODEOut.SWP_TENOR_KEY_Name as SWP_TENOR_KEY_Name,
	 EXPTRANS_CODEOut.INDEX_2_PAY_FREQ_CHR as INDEX_2_PAY_FREQ_CHR,
	 EXPTRANS_CODEOut.INDEX_2_PAY_FREQ_NUM as INDEX_2_PAY_FREQ_NUM,
	 EXPTRANS_CODEOut.INDEX_1_PAY_FREQ_CHR as INDEX_1_PAY_FREQ_CHR,
	 EXPTRANS_CODEOut.INDEX_1_PAY_FREQ_NUM as INDEX_1_PAY_FREQ_NUM
From EXPTRANS_CODEOut as EXPTRANS_CODEOut),

SRT_SWP_CLRPDT_DIMOut as (
	/* transType: "Sorter" */
Select 
	VENUE,
	 ISDA_PRODUCT_TYPE,
	 INDEX_1_MUREX_ID,
	 INDEX_2_MUREX_ID,
	 INDEX_1_CURRENCY_CODE,
	 INDEX_2_CURRENCY_CODE,
	 INDEX_1_PAY_FREQ,
	 INDEX_2_PAY_FREQ,
	 INDEX_1_DAY_COUNT,
	 INDEX_2_DAY_COUNT,
	 TENOR_KEY,
	 DAY_COUNT_FRACTION_Name,
	 SWP_TENOR_KEY_Name,
	 INDEX_2_PAY_FREQ_CHR,
	 INDEX_2_PAY_FREQ_NUM,
	 INDEX_1_PAY_FREQ_CHR,
	 INDEX_1_PAY_FREQ_NUM 
From DSR_SRT_SWP_CLRPDT_DIMOut as DSR_SRT_SWP_CLRPDT_DIMOut Order By O_VENUE ASC, ISDA_PRODUCT_TYPE ASC, INDEX_1_MUREX_ID ASC, INDEX_2_MUREX_ID ASC, INDEX_1_CURRENCY_CODE ASC, INDEX_2_CURRENCY_CODE ASC, INDEX_1_PAY_FREQ ASC, INDEX_2_PAY_FREQ ASC, INDEX_1_DAY_COUNT ASC, INDEX_2_DAY_COUNT ASC, TENOR_KEY ASC, DAY_COUNT_FRACTION_Name ASC, SWP_TENOR_KEY_Name ASC, INDEX_2_PAY_FREQ_CHR ASC, INDEX_2_PAY_FREQ_NUM ASC, INDEX_1_PAY_FREQ_CHR ASC, INDEX_1_PAY_FREQ_NUM ASC),

SRT_SWP_CLRPDT_DIMOut1 as (
	/* transType: "Sorter" */
Select 
	VENUE,
	 ISDA_PRODUCT_TYPE,
	 INDEX_1_MUREX_ID,
	 INDEX_2_MUREX_ID,
	 INDEX_1_CURRENCY_CODE,
	 INDEX_2_CURRENCY_CODE,
	 INDEX_1_PAY_FREQ,
	 INDEX_2_PAY_FREQ,
	 INDEX_1_DAY_COUNT,
	 INDEX_2_DAY_COUNT,
	 TENOR_KEY,
	 DAY_COUNT_FRACTION_Name,
	 SWP_TENOR_KEY_Name,
	 INDEX_2_PAY_FREQ_CHR,
	 INDEX_2_PAY_FREQ_NUM,
	 INDEX_1_PAY_FREQ_CHR,
	 INDEX_1_PAY_FREQ_NUM 
From DSR_SRT_SWP_CLRPDT_DIMOut as DSR_SRT_SWP_CLRPDT_DIMOut Order By O_VENUE ASC, ISDA_PRODUCT_TYPE ASC, INDEX_1_MUREX_ID ASC, INDEX_2_MUREX_ID ASC, INDEX_1_CURRENCY_CODE ASC, INDEX_2_CURRENCY_CODE ASC, INDEX_1_PAY_FREQ ASC, INDEX_2_PAY_FREQ ASC, INDEX_1_DAY_COUNT ASC, INDEX_2_DAY_COUNT ASC, TENOR_KEY ASC, DAY_COUNT_FRACTION_Name ASC, SWP_TENOR_KEY_Name ASC, INDEX_2_PAY_FREQ_CHR ASC, INDEX_2_PAY_FREQ_NUM ASC, INDEX_1_PAY_FREQ_CHR ASC, INDEX_1_PAY_FREQ_NUM ASC),

SRT_SWP_CLRPDT_DIMOut2 as (
	/* transType: "Sorter" */
Select 
	VENUE,
	 ISDA_PRODUCT_TYPE,
	 INDEX_1_MUREX_ID,
	 INDEX_2_MUREX_ID,
	 INDEX_1_CURRENCY_CODE,
	 INDEX_2_CURRENCY_CODE,
	 INDEX_1_PAY_FREQ,
	 INDEX_2_PAY_FREQ,
	 INDEX_1_DAY_COUNT,
	 INDEX_2_DAY_COUNT,
	 TENOR_KEY,
	 DAY_COUNT_FRACTION_Name,
	 SWP_TENOR_KEY_Name,
	 INDEX_2_PAY_FREQ_CHR,
	 INDEX_2_PAY_FREQ_NUM,
	 INDEX_1_PAY_FREQ_CHR,
	 INDEX_1_PAY_FREQ_NUM 
From DSR_SRT_SWP_CLRPDT_DIMOut as DSR_SRT_SWP_CLRPDT_DIMOut Order By O_VENUE ASC, ISDA_PRODUCT_TYPE ASC, INDEX_1_MUREX_ID ASC, INDEX_2_MUREX_ID ASC, INDEX_1_CURRENCY_CODE ASC, INDEX_2_CURRENCY_CODE ASC, INDEX_1_PAY_FREQ ASC, INDEX_2_PAY_FREQ ASC, INDEX_1_DAY_COUNT ASC, INDEX_2_DAY_COUNT ASC, TENOR_KEY ASC, DAY_COUNT_FRACTION_Name ASC, SWP_TENOR_KEY_Name ASC, INDEX_2_PAY_FREQ_CHR ASC, INDEX_2_PAY_FREQ_NUM ASC, INDEX_1_PAY_FREQ_CHR ASC, INDEX_1_PAY_FREQ_NUM ASC),

SRT_SWP_CLRPDT_DIMOut3 as (
	/* transType: "Sorter" */
Select 
	VENUE,
	 ISDA_PRODUCT_TYPE,
	 INDEX_1_MUREX_ID,
	 INDEX_2_MUREX_ID,
	 INDEX_1_CURRENCY_CODE,
	 INDEX_2_CURRENCY_CODE,
	 INDEX_1_PAY_FREQ,
	 INDEX_2_PAY_FREQ,
	 INDEX_1_DAY_COUNT,
	 INDEX_2_DAY_COUNT,
	 TENOR_KEY,
	 DAY_COUNT_FRACTION_Name,
	 SWP_TENOR_KEY_Name,
	 INDEX_2_PAY_FREQ_CHR,
	 INDEX_2_PAY_FREQ_NUM,
	 INDEX_1_PAY_FREQ_CHR,
	 INDEX_1_PAY_FREQ_NUM 
From DSR_SRT_SWP_CLRPDT_DIMOut as DSR_SRT_SWP_CLRPDT_DIMOut Order By O_VENUE ASC, ISDA_PRODUCT_TYPE ASC, INDEX_1_MUREX_ID ASC, INDEX_2_MUREX_ID ASC, INDEX_1_CURRENCY_CODE ASC, INDEX_2_CURRENCY_CODE ASC, INDEX_1_PAY_FREQ ASC, INDEX_2_PAY_FREQ ASC, INDEX_1_DAY_COUNT ASC, INDEX_2_DAY_COUNT ASC, TENOR_KEY ASC, DAY_COUNT_FRACTION_Name ASC, SWP_TENOR_KEY_Name ASC, INDEX_2_PAY_FREQ_CHR ASC, INDEX_2_PAY_FREQ_NUM ASC, INDEX_1_PAY_FREQ_CHR ASC, INDEX_1_PAY_FREQ_NUM ASC),

SC_APPLICATION_VARIABLES_INDX2_DAY_CNTOut as (
	/* transType: "Lookup Procedure" */
Select 
	ID as ID,
	 VARIABLE_NAME as VARIABLE_NAME,
	 VARIABLE_DATA_TYPE as VARIABLE_DATA_TYPE,
	 NUMBER_VALUE as NUMBER_VALUE,
	 DATE_VALUE as DATE_VALUE,
	 STRING_VALUE as STRING_VALUE,
	 CREATED_DATETIME as CREATED_DATETIME,
	 CREATED_BY as CREATED_BY,
	 UPDATED_DATETIME as UPDATED_DATETIME,
	 UPDATED_BY as UPDATED_BY,
	 STRING_VALUE2 as STRING_VALUE2,
	 STRING_VALUE3 as STRING_VALUE3,
	 DATE_VALUE2 as DATE_VALUE2,
	 DATE_VALUE3 as DATE_VALUE3,
	 NUMBER_VALUE2 as NUMBER_VALUE2,
	 NUMBER_VALUE3 as NUMBER_VALUE3,
	 ACTIVE_Y_N as ACTIVE_Y_N,
	 STRING_VALUE4 as STRING_VALUE4,
	 STRING_VALUE5 as STRING_VALUE5,
	 STRING_VALUE6 as STRING_VALUE6,
	 STRING_VALUE7 as STRING_VALUE7,
	 NUMBER_VALUE4 as NUMBER_VALUE4,
	 NUMBER_VALUE5 as NUMBER_VALUE5,
	 NUMBER_VALUE6 as NUMBER_VALUE6,
	 NUMBER_VALUE7 as NUMBER_VALUE7,
	 SRT_SWP_CLRPDT_DIMOut.i_VARIABLE_NAME as i_VARIABLE_NAME_1,
	 SRT_SWP_CLRPDT_DIMOut.i_STRING_VALUE as i_STRING_VALUE_1,
	 SRT_SWP_CLRPDT_DIM.DAY_COUNT_FRACTION_Name AS i_VARIABLE_NAME_2,
	 SRT_SWP_CLRPDT_DIM.INDEX_2_DAY_COUNT AS i_STRING_VALUE_2 
FROM
	SRT_SWP_CLRPDT_DIMOut as SRT_SWP_CLRPDT_DIMOut 
 LEFT JOIN APPLICATION_VARIABLESOut
ON
	VARIABLE_NAME = i_VARIABLE_NAME
	AND STRING_VALUE = i_STRING_VALUE
 
 Where ACTIVE_Y_N = 'Y'),

SC_APPLICATION_VARIABLES_INDX1_DAY_CNTOut as (
	/* transType: "Lookup Procedure" */
Select 
	ID as ID,
	 VARIABLE_NAME as VARIABLE_NAME,
	 VARIABLE_DATA_TYPE as VARIABLE_DATA_TYPE,
	 NUMBER_VALUE as NUMBER_VALUE,
	 DATE_VALUE as DATE_VALUE,
	 STRING_VALUE as STRING_VALUE,
	 CREATED_DATETIME as CREATED_DATETIME,
	 CREATED_BY as CREATED_BY,
	 UPDATED_DATETIME as UPDATED_DATETIME,
	 UPDATED_BY as UPDATED_BY,
	 STRING_VALUE2 as STRING_VALUE2,
	 STRING_VALUE3 as STRING_VALUE3,
	 DATE_VALUE2 as DATE_VALUE2,
	 DATE_VALUE3 as DATE_VALUE3,
	 NUMBER_VALUE2 as NUMBER_VALUE2,
	 NUMBER_VALUE3 as NUMBER_VALUE3,
	 ACTIVE_Y_N as ACTIVE_Y_N,
	 STRING_VALUE4 as STRING_VALUE4,
	 STRING_VALUE5 as STRING_VALUE5,
	 STRING_VALUE6 as STRING_VALUE6,
	 STRING_VALUE7 as STRING_VALUE7,
	 NUMBER_VALUE4 as NUMBER_VALUE4,
	 NUMBER_VALUE5 as NUMBER_VALUE5,
	 NUMBER_VALUE6 as NUMBER_VALUE6,
	 NUMBER_VALUE7 as NUMBER_VALUE7,
	 SRT_SWP_CLRPDT_DIMOut.i_VARIABLE_NAME as i_VARIABLE_NAME_1,
	 SRT_SWP_CLRPDT_DIMOut.i_STRING_VALUE as i_STRING_VALUE_1,
	 SRT_SWP_CLRPDT_DIM.DAY_COUNT_FRACTION_Name AS i_VARIABLE_NAME_2,
	 SRT_SWP_CLRPDT_DIM.INDEX_1_DAY_COUNT AS i_STRING_VALUE_2 
FROM
	SRT_SWP_CLRPDT_DIMOut as SRT_SWP_CLRPDT_DIMOut 
 LEFT JOIN APPLICATION_VARIABLESOut1
ON
	VARIABLE_NAME = i_VARIABLE_NAME
	AND STRING_VALUE = i_STRING_VALUE
 
 Where ACTIVE_Y_N = 'Y'),

SC_LKP_APPLICATION_VARIABLES_BOEOut as (
	/* transType: "Lookup Procedure" */
Select 
	ID as ID,
	 VARIABLE_NAME as VARIABLE_NAME,
	 STRING_VALUE as STRING_VALUE,
	 STRING_VALUE2 as STRING_VALUE2,
	 STRING_VALUE3 as STRING_VALUE3,
	 SRT_SWP_CLRPDT_DIM.TENOR_KEY AS i_STRING_VALUE,
	 SRT_SWP_CLRPDT_DIM.SWP_TENOR_KEY_Name AS i_VARIABLE_NAME 
FROM
	SRT_SWP_CLRPDT_DIMOut as SRT_SWP_CLRPDT_DIMOut 
 LEFT JOIN APPLICATION_VARIABLESOut2
ON
	STRING_VALUE = i_STRING_VALUE
	AND VARIABLE_NAME = i_VARIABLE_NAME
 
),

SC_APPLICATION_VARIABLES_INDX2_DAY_CNT_master as (
  Select
  	SC_APPLICATION_VARIABLES_INDX2_DAY_CNTOut.STRING_VALUE2 as STRING_VALUE2_IDX2
  From SC_APPLICATION_VARIABLES_INDX2_DAY_CNTOut as SC_APPLICATION_VARIABLES_INDX2_DAY_CNTOut
),

SC_LKP_APPLICATION_VARIABLES_BOE_details as (
  Select
  	SC_LKP_APPLICATION_VARIABLES_BOEOut.STRING_VALUE2 as MAX_CONTRACT_TENOR_VALUE,
	 SC_LKP_APPLICATION_VARIABLES_BOEOut.STRING_VALUE3 as MAX_CONTRACT_TENOR_UNIT
  From SC_LKP_APPLICATION_VARIABLES_BOEOut as SC_LKP_APPLICATION_VARIABLES_BOEOut
),

SC_APPLICATION_VARIABLES_INDX1_DAY_CNT_details as (
  Select
  	SC_APPLICATION_VARIABLES_INDX1_DAY_CNTOut.STRING_VALUE2 as STRING_VALUE2_IDX1
  From SC_APPLICATION_VARIABLES_INDX1_DAY_CNTOut as SC_APPLICATION_VARIABLES_INDX1_DAY_CNTOut
),

SRT_SWP_CLRPDT_DIM_details as (
  Select
  	SRT_SWP_CLRPDT_DIMOut.VENUE as VENUE,
	 SRT_SWP_CLRPDT_DIMOut.ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_1_MUREX_ID as i_INDEX_1_MUREX_ID,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_2_MUREX_ID as i_INDEX_2_MUREX_ID,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_1_PAY_FREQ as i_INDEX_1_PAY_FREQ,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_2_PAY_FREQ as i_INDEX_2_PAY_FREQ,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_1_DAY_COUNT as i_INDEX_1_DAY_COUNT,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_2_DAY_COUNT as i_INDEX_2_DAY_COUNT,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 SRT_SWP_CLRPDT_DIMOut.TENOR_KEY as TENOR_KEY,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_2_PAY_FREQ_CHR as i_INDEX_2_PAY_FREQ_CHR,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_2_PAY_FREQ_NUM as i_INDEX_2_PAY_FREQ_NUM,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_1_PAY_FREQ_CHR as i_INDEX_1_PAY_FREQ_CHR,
	 SRT_SWP_CLRPDT_DIMOut.INDEX_1_PAY_FREQ_NUM as i_INDEX_1_PAY_FREQ_NUM
  From SRT_SWP_CLRPDT_DIMOut as SRT_SWP_CLRPDT_DIMOut
),
dsJoiner_EXP_TRIM0Out as (
	/* transType: "Joiner" */
Select 
	SC_APPLICATION_VARIABLES_INDX1_DAY_CNT_details.STRING_VALUE2_IDX1 as STRING_VALUE2_IDX1,
	 SC_APPLICATION_VARIABLES_INDX2_DAY_CNT_master.STRING_VALUE2_IDX2 as STRING_VALUE2_IDX2,
	 SRT_SWP_CLRPDT_DIMOut2.VENUE as VENUE,
	 SRT_SWP_CLRPDT_DIMOut2.ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_1_MUREX_ID as i_INDEX_1_MUREX_ID,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_2_MUREX_ID as i_INDEX_2_MUREX_ID,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_1_PAY_FREQ as i_INDEX_1_PAY_FREQ,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_2_PAY_FREQ as i_INDEX_2_PAY_FREQ,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_1_DAY_COUNT as i_INDEX_1_DAY_COUNT,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_2_DAY_COUNT as i_INDEX_2_DAY_COUNT,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 SC_LKP_APPLICATION_VARIABLES_BOE_details.MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 SC_LKP_APPLICATION_VARIABLES_BOE_details.MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 SRT_SWP_CLRPDT_DIMOut2.TENOR_KEY as TENOR_KEY,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_2_PAY_FREQ_CHR as i_INDEX_2_PAY_FREQ_CHR,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_2_PAY_FREQ_NUM as i_INDEX_2_PAY_FREQ_NUM,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_1_PAY_FREQ_CHR as i_INDEX_1_PAY_FREQ_CHR,
	 SRT_SWP_CLRPDT_DIMOut2.INDEX_1_PAY_FREQ_NUM as i_INDEX_1_PAY_FREQ_NUM,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
SC_APPLICATION_VARIABLES_INDX2_DAY_CNT_master as SC_APPLICATION_VARIABLES_INDX2_DAY_CNT_master INNER JOIN SC_LKP_APPLICATION_VARIABLES_BOE_details as SC_LKP_APPLICATION_VARIABLES_BOE_details 
ON
SC_APPLICATION_VARIABLES_INDX2_DAY_CNT_master.jkey = SC_LKP_APPLICATION_VARIABLES_BOE_details.jkey
 INNER JOIN SC_APPLICATION_VARIABLES_INDX1_DAY_CNT_details as SC_APPLICATION_VARIABLES_INDX1_DAY_CNT_details 
ON
SC_APPLICATION_VARIABLES_INDX2_DAY_CNT_master.jkey = SC_APPLICATION_VARIABLES_INDX1_DAY_CNT_details.jkey
 INNER JOIN SRT_SWP_CLRPDT_DIMOut2 as SRT_SWP_CLRPDT_DIMOut2 
ON
SC_APPLICATION_VARIABLES_INDX2_DAY_CNT_master.jkey = SRT_SWP_CLRPDT_DIMOut2.jkey
 
),

EXP_TRIMOut as (
	/* transType: "Expression" */
Select 
	VENUE as VENUE,
	 ISDA_PRODUCT_TYPE as O_ISDA_PRODUCT_TYPE,
	 SUBSTRING ( ISDA_PRODUCT_TYPE,
	 1,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) -1 ) as ASSET_CLASS,
	 ( CASE WHEN REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':',
	 1,
	 2 ) = 0 THEN SUBSTRING ( ISDA_PRODUCT_TYPE,
	 IFF ( REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) > 0,
	 length ( ISDA_PRODUCT_TYPE ) - REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) + 1,
	 0 ) + 1 ) ELSE SUBSTRING ( ISDA_PRODUCT_TYPE,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) + 1,
	 REGEXP_INSTR ( SUBSTRING ( ISDA_PRODUCT_TYPE,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) + 1 ),
	 ':' ) -1 ) END ) as BASE_PRODUCT,
	 ( CASE WHEN REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':',
	 1,
	 2 ) = 0 THEN NULL ELSE SUBSTRING ( ISDA_PRODUCT_TYPE,
	 IFF ( REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) > 0,
	 length ( ISDA_PRODUCT_TYPE ) - REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) + 1,
	 0 ) + 1 ) END ) as SUB_PRODUCT,
	 i_INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 i_INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 i_INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 i_INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 i_INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 i_INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 TENOR_KEY as TENOR_KEY,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 '{{ var("TARGET_NAME_CPD") }}' as O_TARGET_NAME,
	 '{{ var("SOURCE_NAME_CPD") }}' as O_SOURCE_NAME,
	 1 as EN_IND,
	 TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ) as EFFECTIVE_DATE,
	 ( CASE WHEN STRING_VALUE2_IDX1 IS NULL THEN 'OTHR' ELSE STRING_VALUE2_IDX1 END ) as BOE_INDEX_1_DAY_COUNT,
	 STRING_VALUE2_IDX1 as BOE_INDEX_1_DAY_COUNT_VALIDATION,
	 DECODE ( 0,
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 12 ),
	 'Y',
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 6 ),
	 '6M',
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 3 ),
	 '3M',
	 'M' ) as v_INDEX1_LKP_STRING,
	 ( CASE WHEN i_INDEX_1_PAY_FREQ_CHR = 'M' THEN dsf_2.STRING_VALUE2 ELSE :LKP.SC_LKP_APPLICATION_VARIABLES_PAY_FREQ ( i_INDEX_1_PAY_FREQ_CHR ) END ) as BOE_INDEX_1_PAY_FREQ,
	 DECODE ( 0,
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 12 ),
	 'Y',
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 6 ),
	 '6M',
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 3 ),
	 '3M',
	 'M' ) as v_INDEX2_LKP_STRING,
	 ( CASE WHEN i_INDEX_2_PAY_FREQ_CHR = 'M' THEN dsf_3.STRING_VALUE2 ELSE :LKP.SC_LKP_APPLICATION_VARIABLES_PAY_FREQ ( i_INDEX_2_PAY_FREQ_CHR ) END ) as BOE_INDEX_2_PAY_FREQ,
	 ( CASE WHEN STRING_VALUE2_IDX2 IS NULL THEN 'OTHR' ELSE STRING_VALUE2_IDX2 END ) as BOE_INDEX_2_DAY_COUNT,
	 STRING_VALUE2_IDX2 as BOE_INDEX_2_DAY_COUNT_VALIDATION,
	 ( CASE WHEN TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) > 999 AND MAX_CONTRACT_TENOR_UNIT = 'DAYS' THEN FLOOR ( TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) / 30.5 ) ELSE TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) END ) as BOE_CONTRACT_TENOR_VALUE,
	 ( CASE WHEN TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) > 999 AND MAX_CONTRACT_TENOR_UNIT = 'DAYS' THEN 'MNTH' ELSE MAX_CONTRACT_TENOR_UNIT END ) as BOE_CONTRACT_TENOR_UNIT
From dsJoiner_EXP_TRIM0Out as dsJoiner_EXP_TRIM0Out
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE = i_INDEX_1_PAY_FREQ_CHR
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.STRING_VALUE = v_INDEX1_LKP_STRING
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = v_INDEX2_LKP_STRING
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = i_INDEX_2_PAY_FREQ_CHR
),

EXP_TRIMOut1 as (
	/* transType: "Expression" */
Select 
	VENUE as VENUE,
	 ISDA_PRODUCT_TYPE as O_ISDA_PRODUCT_TYPE,
	 SUBSTRING ( ISDA_PRODUCT_TYPE,
	 1,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) -1 ) as ASSET_CLASS,
	 ( CASE WHEN REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':',
	 1,
	 2 ) = 0 THEN SUBSTRING ( ISDA_PRODUCT_TYPE,
	 IFF ( REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) > 0,
	 length ( ISDA_PRODUCT_TYPE ) - REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) + 1,
	 0 ) + 1 ) ELSE SUBSTRING ( ISDA_PRODUCT_TYPE,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) + 1,
	 REGEXP_INSTR ( SUBSTRING ( ISDA_PRODUCT_TYPE,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) + 1 ),
	 ':' ) -1 ) END ) as BASE_PRODUCT,
	 ( CASE WHEN REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':',
	 1,
	 2 ) = 0 THEN NULL ELSE SUBSTRING ( ISDA_PRODUCT_TYPE,
	 IFF ( REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) > 0,
	 length ( ISDA_PRODUCT_TYPE ) - REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) + 1,
	 0 ) + 1 ) END ) as SUB_PRODUCT,
	 i_INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 i_INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 i_INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 i_INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 i_INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 i_INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 TENOR_KEY as TENOR_KEY,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 '{{ var("TARGET_NAME_CPD") }}' as O_TARGET_NAME,
	 '{{ var("SOURCE_NAME_CPD") }}' as O_SOURCE_NAME,
	 1 as EN_IND,
	 TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ) as EFFECTIVE_DATE,
	 ( CASE WHEN STRING_VALUE2_IDX1 IS NULL THEN 'OTHR' ELSE STRING_VALUE2_IDX1 END ) as BOE_INDEX_1_DAY_COUNT,
	 STRING_VALUE2_IDX1 as BOE_INDEX_1_DAY_COUNT_VALIDATION,
	 DECODE ( 0,
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 12 ),
	 'Y',
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 6 ),
	 '6M',
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 3 ),
	 '3M',
	 'M' ) as v_INDEX1_LKP_STRING,
	 ( CASE WHEN i_INDEX_1_PAY_FREQ_CHR = 'M' THEN dsf_2.STRING_VALUE2 ELSE :LKP.SC_LKP_APPLICATION_VARIABLES_PAY_FREQ ( i_INDEX_1_PAY_FREQ_CHR ) END ) as BOE_INDEX_1_PAY_FREQ,
	 DECODE ( 0,
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 12 ),
	 'Y',
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 6 ),
	 '6M',
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 3 ),
	 '3M',
	 'M' ) as v_INDEX2_LKP_STRING,
	 ( CASE WHEN i_INDEX_2_PAY_FREQ_CHR = 'M' THEN dsf_3.STRING_VALUE2 ELSE :LKP.SC_LKP_APPLICATION_VARIABLES_PAY_FREQ ( i_INDEX_2_PAY_FREQ_CHR ) END ) as BOE_INDEX_2_PAY_FREQ,
	 ( CASE WHEN STRING_VALUE2_IDX2 IS NULL THEN 'OTHR' ELSE STRING_VALUE2_IDX2 END ) as BOE_INDEX_2_DAY_COUNT,
	 STRING_VALUE2_IDX2 as BOE_INDEX_2_DAY_COUNT_VALIDATION,
	 ( CASE WHEN TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) > 999 AND MAX_CONTRACT_TENOR_UNIT = 'DAYS' THEN FLOOR ( TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) / 30.5 ) ELSE TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) END ) as BOE_CONTRACT_TENOR_VALUE,
	 ( CASE WHEN TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) > 999 AND MAX_CONTRACT_TENOR_UNIT = 'DAYS' THEN 'MNTH' ELSE MAX_CONTRACT_TENOR_UNIT END ) as BOE_CONTRACT_TENOR_UNIT
From dsJoiner_EXP_TRIM0Out as dsJoiner_EXP_TRIM0Out
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE = i_INDEX_1_PAY_FREQ_CHR
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.STRING_VALUE = v_INDEX1_LKP_STRING
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = v_INDEX2_LKP_STRING
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = i_INDEX_2_PAY_FREQ_CHR
),

EXP_TRIMOut2 as (
	/* transType: "Expression" */
Select 
	VENUE as VENUE,
	 ISDA_PRODUCT_TYPE as O_ISDA_PRODUCT_TYPE,
	 SUBSTRING ( ISDA_PRODUCT_TYPE,
	 1,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) -1 ) as ASSET_CLASS,
	 ( CASE WHEN REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':',
	 1,
	 2 ) = 0 THEN SUBSTRING ( ISDA_PRODUCT_TYPE,
	 IFF ( REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) > 0,
	 length ( ISDA_PRODUCT_TYPE ) - REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) + 1,
	 0 ) + 1 ) ELSE SUBSTRING ( ISDA_PRODUCT_TYPE,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) + 1,
	 REGEXP_INSTR ( SUBSTRING ( ISDA_PRODUCT_TYPE,
	 REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':' ) + 1 ),
	 ':' ) -1 ) END ) as BASE_PRODUCT,
	 ( CASE WHEN REGEXP_INSTR ( ISDA_PRODUCT_TYPE,
	 ':',
	 1,
	 2 ) = 0 THEN NULL ELSE SUBSTRING ( ISDA_PRODUCT_TYPE,
	 IFF ( REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) > 0,
	 length ( ISDA_PRODUCT_TYPE ) - REGEXP_INSTR ( REVERSE ( ISDA_PRODUCT_TYPE ),
	 ':',
	 -1 ) + 1,
	 0 ) + 1 ) END ) as SUB_PRODUCT,
	 i_INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 i_INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 i_INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 i_INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 i_INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 i_INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 TENOR_KEY as TENOR_KEY,
	 '{{ var("BATCH_ID") }}' as BATCH_ID,
	 '{{ var("TARGET_NAME_CPD") }}' as O_TARGET_NAME,
	 '{{ var("SOURCE_NAME_CPD") }}' as O_SOURCE_NAME,
	 1 as EN_IND,
	 TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ) as EFFECTIVE_DATE,
	 ( CASE WHEN STRING_VALUE2_IDX1 IS NULL THEN 'OTHR' ELSE STRING_VALUE2_IDX1 END ) as BOE_INDEX_1_DAY_COUNT,
	 STRING_VALUE2_IDX1 as BOE_INDEX_1_DAY_COUNT_VALIDATION,
	 DECODE ( 0,
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 12 ),
	 'Y',
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 6 ),
	 '6M',
	 MOD ( i_INDEX_1_PAY_FREQ_NUM,
	 3 ),
	 '3M',
	 'M' ) as v_INDEX1_LKP_STRING,
	 ( CASE WHEN i_INDEX_1_PAY_FREQ_CHR = 'M' THEN dsf_2.STRING_VALUE2 ELSE :LKP.SC_LKP_APPLICATION_VARIABLES_PAY_FREQ ( i_INDEX_1_PAY_FREQ_CHR ) END ) as BOE_INDEX_1_PAY_FREQ,
	 DECODE ( 0,
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 12 ),
	 'Y',
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 6 ),
	 '6M',
	 MOD ( i_INDEX_2_PAY_FREQ_NUM,
	 3 ),
	 '3M',
	 'M' ) as v_INDEX2_LKP_STRING,
	 ( CASE WHEN i_INDEX_2_PAY_FREQ_CHR = 'M' THEN dsf_3.STRING_VALUE2 ELSE :LKP.SC_LKP_APPLICATION_VARIABLES_PAY_FREQ ( i_INDEX_2_PAY_FREQ_CHR ) END ) as BOE_INDEX_2_PAY_FREQ,
	 ( CASE WHEN STRING_VALUE2_IDX2 IS NULL THEN 'OTHR' ELSE STRING_VALUE2_IDX2 END ) as BOE_INDEX_2_DAY_COUNT,
	 STRING_VALUE2_IDX2 as BOE_INDEX_2_DAY_COUNT_VALIDATION,
	 ( CASE WHEN TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) > 999 AND MAX_CONTRACT_TENOR_UNIT = 'DAYS' THEN FLOOR ( TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) / 30.5 ) ELSE TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) END ) as BOE_CONTRACT_TENOR_VALUE,
	 ( CASE WHEN TO_DECIMAL ( MAX_CONTRACT_TENOR_VALUE ) > 999 AND MAX_CONTRACT_TENOR_UNIT = 'DAYS' THEN 'MNTH' ELSE MAX_CONTRACT_TENOR_UNIT END ) as BOE_CONTRACT_TENOR_UNIT
From dsJoiner_EXP_TRIM0Out as dsJoiner_EXP_TRIM0Out
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.STRING_VALUE = i_INDEX_1_PAY_FREQ_CHR
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.STRING_VALUE = v_INDEX1_LKP_STRING
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = v_INDEX2_LKP_STRING
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (  SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE2, STRING_VALUE,  ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst   FROM ( SELECT    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE   VARIABLE_NAME= 'BOE_STATIC_VAL' )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = i_INDEX_2_PAY_FREQ_CHR
),

LKP_CLEARED_PRODUCTSOut1 as (
	/* transType: "Lookup Procedure" */
Select 
	ID as ID,
	 BATCH_ID as BATCH_ID,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EFFECTIVE_DATE as EFFECTIVE_DATE,
	 EXPIRATION_DATE as EXPIRATION_DATE,
	 VENUE as VENUE,
	 ASSET_CLASS as ASSET_CLASS,
	 BASE_PRODUCT as BASE_PRODUCT,
	 SUB_PRODUCT as SUB_PRODUCT,
	 ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 INDEX_1_MUREX_NAME as INDEX_1_MUREX_NAME,
	 INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 INDEX_1_TENOR_CCY as INDEX_1_TENOR_CCY,
	 INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 INDEX_2_MUREX_NAME as INDEX_2_MUREX_NAME,
	 INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 INDEX_2_TENOR_CCY as INDEX_2_TENOR_CCY,
	 INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 PROPAGATE_INDICATOR as PROPAGATE_INDICATOR,
	 ERROR_INDICATOR as ERROR_INDICATOR,
	 TENOR_KEY as TENOR_KEY,
	 EXP_TRIMOut.i_VENUE as i_VENUE_1,
	 EXP_TRIMOut.i_ISDA_PRODUCT_TYPE as i_ISDA_PRODUCT_TYPE_1,
	 EXP_TRIMOut.i_ASSET_CLASS as i_ASSET_CLASS_1,
	 EXP_TRIMOut.i_BASE_PRODUCT as i_BASE_PRODUCT_1,
	 EXP_TRIMOut.i_SUB_PRODUCT as i_SUB_PRODUCT_1,
	 EXP_TRIMOut.i_INDEX_1_MUREX_ID as i_INDEX_1_MUREX_ID_1,
	 EXP_TRIMOut.i_INDEX_2_MUREX_ID as i_INDEX_2_MUREX_ID_1,
	 EXP_TRIMOut.in_INDEX_1_PAY_FREQ as in_INDEX_1_PAY_FREQ_1,
	 EXP_TRIMOut.in_INDEX_2_PAY_FREQ as in_INDEX_2_PAY_FREQ_1,
	 EXP_TRIMOut.in_INDEX_1_DAY_COUNT as in_INDEX_1_DAY_COUNT_1,
	 EXP_TRIMOut.in_INDEX_2_DAY_COUNT as in_INDEX_2_DAY_COUNT_1,
	 EXP_TRIMOut.in_INDEX_1_TENOR_CCY as in_INDEX_1_TENOR_CCY_1,
	 EXP_TRIMOut.in_INDEX_2_TENOR_CCY as in_INDEX_2_TENOR_CCY_1,
	 EXP_TRIMOut.in_TENOR_KEY as in_TENOR_KEY_1,
	 EXP_TRIM.VENUE AS i_VENUE_2,
	 EXP_TRIM.O_ISDA_PRODUCT_TYPE AS i_ISDA_PRODUCT_TYPE_2,
	 EXP_TRIM.ASSET_CLASS AS i_ASSET_CLASS_2,
	 EXP_TRIM.BASE_PRODUCT AS i_BASE_PRODUCT_2,
	 EXP_TRIM.SUB_PRODUCT AS i_SUB_PRODUCT_2,
	 EXP_TRIM.INDEX_1_MUREX_ID AS i_INDEX_1_MUREX_ID_2,
	 EXP_TRIM.INDEX_2_MUREX_ID AS i_INDEX_2_MUREX_ID_2,
	 EXP_TRIM.INDEX_1_PAY_FREQ AS in_INDEX_1_PAY_FREQ_2,
	 EXP_TRIM.INDEX_2_PAY_FREQ AS in_INDEX_2_PAY_FREQ_2,
	 EXP_TRIM.INDEX_1_DAY_COUNT AS in_INDEX_1_DAY_COUNT_2,
	 EXP_TRIM.INDEX_2_DAY_COUNT AS in_INDEX_2_DAY_COUNT_2,
	 EXP_TRIM.INDEX_1_CURRENCY_CODE AS in_INDEX_1_TENOR_CCY_2,
	 EXP_TRIM.INDEX_2_CURRENCY_CODE AS in_INDEX_2_TENOR_CCY_2,
	 EXP_TRIM.TENOR_KEY AS in_TENOR_KEY_2 
FROM
	EXP_TRIMOut1 as EXP_TRIMOut1 
 LEFT JOIN SWP_CLEARED_PRODUCTS_DIMOut
ON
	VENUE = i_VENUE
	AND ISDA_PRODUCT_TYPE = i_ISDA_PRODUCT_TYPE
	AND INDEX_1_MUREX_NAME = i_INDEX_1_MUREX_ID
	AND INDEX_2_MUREX_NAME = i_INDEX_2_MUREX_ID
	AND INDEX_1_PAY_FREQ = in_INDEX_1_PAY_FREQ
	AND INDEX_2_PAY_FREQ = in_INDEX_2_PAY_FREQ
	AND INDEX_1_DAY_COUNT = in_INDEX_1_DAY_COUNT
	AND INDEX_2_DAY_COUNT = in_INDEX_2_DAY_COUNT
	AND INDEX_1_TENOR_CCY = in_INDEX_1_TENOR_CCY
	AND INDEX_2_TENOR_CCY = in_INDEX_2_TENOR_CCY
	AND TENOR_KEY = in_TENOR_KEY
 
 Where to_date('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') between EFFECTIVE_DATE AND NVL(EXPIRATION_DATE,TO_DATE('99991231','YYYYMMDD'))),

DSR_SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut as (
	/* transType: "Expression" */
Select 
	EXP_TRIMOut.EN_IND as SUB_PRODUCT_EN_IND,
	 EXP_TRIMOut.EN_IND as INDEX_2_MUREX_ID_EN_IND,
	 EXP_TRIMOut.BOE_INDEX_2_DAY_COUNT_VALIDATION as INDEX_DAY_COUNT_2,
	 EXP_TRIMOut.EN_IND as TENOR_KEY_IND,
	 EXP_TRIMOut.TENOR_KEY as TENOR_KEY,
	 EXP_TRIMOut.O_ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 EXP_TRIMOut.EN_IND as BASE_PRODUCT_EN_IND,
	 EXP_TRIMOut.EN_IND as VENUE_EN_IND,
	 EXP_TRIMOut.EN_IND as INDEX_DAY_COUNT_1_EN_IND,
	 EXP_TRIMOut.BOE_CONTRACT_TENOR_VALUE as TENOR_VALUE,
	 EXP_TRIMOut.EN_IND as TENOR_VALUE_EN_IND,
	 EXP_TRIMOut.EN_IND as INDEX_DAY_COUNT_2_EN_IND,
	 EXP_TRIMOut.EN_IND as ISDA_PRODUCT_TYPE_EN_IND,
	 EXP_TRIMOut.EN_IND as INDEX_1_MUREX_ID_EN_IND,
	 EXP_TRIMOut.ASSET_CLASS as ASSET_CLASS,
	 EXP_TRIMOut.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_TRIMOut.O_TARGET_NAME as TARGET_TABLE_NAME,
	 EXP_TRIMOut.EN_IND as ASSET_CLASS_EN_IND,
	 EXP_TRIMOut.VENUE as VENUE,
	 EXP_TRIMOut.BATCH_ID as BATCH_ID,
	 EXP_TRIMOut.O_SOURCE_NAME as SRC_FILE_NAME,
	 EXP_TRIMOut.INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 EXP_TRIMOut.INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 EXP_TRIMOut.SUB_PRODUCT as SUB_PRODUCT,
	 EXP_TRIMOut.INDEX_2_DAY_COUNT as INDEX_DAY_COUNT_2_VALUE,
	 EXP_TRIMOut.BOE_INDEX_1_DAY_COUNT_VALIDATION as INDEX_DAY_COUNT_1,
	 EXP_TRIMOut.INDEX_1_DAY_COUNT as INDEX_DAY_COUNT_1_VALUE
From EXP_TRIMOut as EXP_TRIMOut),

SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut as (
	/* transType: "MAPPLET" */
Select 
	TENOR_VALUE_LKP_FAIL as TENOR_VALUE_LKP_FAIL,
	 o_INDEX_DAY_COUNT_1_LKP_FAIL as INDEX_DAY_COUNT_1_LKP_FAIL,
	 v_INDEX_DAY_COUNT_2_LKP_FAIL as INDEX_DAY_COUNT_2_LKP_FAIL,
	 SUB_PRODUCT_LKP_FAIL as SUB_PRODUCT_LKP_FAIL,
	 VENUE_LKP_FAIL as VENUE_LKP_FAIL,
	 ISDA_PRODUCT_TYPE_LKP_FAIL as ISDA_PRODUCT_TYPE_LKP_FAIL,
	 INDEX_1_MUREX_ID_LKP_FAIL as INDEX_1_MUREX_ID_LKP_FAIL,
	 INDEX_2_MUREX_ID_LKP_FAIL as INDEX_2_MUREX_ID_LKP_FAIL,
	 ASSET_CLASS_LKP_FAIL as ASSET_CLASS_LKP_FAIL,
	 BASE_PRODUCT_LKP_FAIL as BASE_PRODUCT_LKP_FAIL,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 TENOR_KEY_LKP_FAIL as TENOR_KEY_LKP_FAIL,
	 EN_IND as SUB_PRODUCT_EN_IND,
	 EN_IND as INDEX_2_MUREX_ID_EN_IND,
	 BOE_INDEX_2_DAY_COUNT_VALIDATION as INDEX_DAY_COUNT_2,
	 EN_IND as TENOR_KEY_IND,
	 TENOR_KEY as TENOR_KEY,
	 O_ISDA_PRODUCT_TYPE as ISDA_PRODUCT_TYPE,
	 EN_IND as BASE_PRODUCT_EN_IND,
	 EN_IND as VENUE_EN_IND,
	 EN_IND as INDEX_DAY_COUNT_1_EN_IND,
	 BOE_CONTRACT_TENOR_VALUE as TENOR_VALUE,
	 EN_IND as TENOR_VALUE_EN_IND,
	 EN_IND as INDEX_DAY_COUNT_2_EN_IND,
	 EN_IND as ISDA_PRODUCT_TYPE_EN_IND,
	 EN_IND as INDEX_1_MUREX_ID_EN_IND,
	 ASSET_CLASS as ASSET_CLASS,
	 BASE_PRODUCT as BASE_PRODUCT,
	 O_TARGET_NAME as TARGET_TABLE_NAME,
	 EN_IND as ASSET_CLASS_EN_IND,
	 VENUE as VENUE,
	 BATCH_ID as BATCH_ID,
	 O_SOURCE_NAME as SRC_FILE_NAME,
	 INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 SUB_PRODUCT as SUB_PRODUCT,
	 INDEX_2_DAY_COUNT as INDEX_DAY_COUNT_2_VALUE,
	 BOE_INDEX_1_DAY_COUNT_VALIDATION as INDEX_DAY_COUNT_1,
	 INDEX_1_DAY_COUNT as INDEX_DAY_COUNT_1_VALUE,
	 ASSET_CLASS_IN_STR as ASSET_CLASS_IN_STR,
	 ASSET_CLASS_ERROR_CODE as ASSET_CLASS_ERROR_CODE,
	 o_INDEX_DAY_COUNT_1_NAME as o_INDEX_DAY_COUNT_1_NAME,
	 o_INDEX_DAY_COUNT_1_ERROR_CODE as o_INDEX_DAY_COUNT_1_ERROR_CODE,
	 o_INDEX_DAY_COUNT_2_ERROR_CODE as o_INDEX_DAY_COUNT_2_ERROR_CODE,
	 o_INDEX_DAY_COUNT_1_LKP_FAIL as INDEX_DAY_COUNT_1_LKP_FAIL,
	 VENUE_IN_STR as VENUE_IN_STR,
	 o_VENUE_NAME as o_VENUE_NAME,
	 VENUE_ERROR_CODE as VENUE_ERROR_CODE,
	 VENUE_LKP_FAIL as VENUE_LKP_FAIL,
	 INDEX_1_MUREX_ID_LKP_FAIL as INDEX_1_MUREX_ID_LKP_FAIL,
	 o_INDEX_1_MUREX_ID_NAME as o_INDEX_1_MUREX_ID_NAME,
	 SUB_PRODUCT_ERROR_CODE as SUB_PRODUCT_ERROR_CODE,
	 INDEX_2_MUREX_ID1 as INDEX_2_MUREX_ID1,
	 o_INDEX_2_MUREX_ID_NAME as o_INDEX_2_MUREX_ID_NAME,
	 INDEX_1_MUREX_ID_ERROR_CODE as INDEX_1_MUREX_ID_ERROR_CODE,
	 o_ASSET_CLASS_NAME as o_ASSET_CLASS_NAME,
	 VENUE1 as VENUE1,
	 TENOR_KEY1 as TENOR_KEY1,
	 o_TENOR_KEY_NAME as o_TENOR_KEY_NAME,
	 TENOR_KEY_IN_STR as TENOR_KEY_IN_STR,
	 TENOR_KEY_ERROR_CODE as TENOR_KEY_ERROR_CODE,
	 TENOR_KEY_LKP_FAIL as TENOR_KEY_LKP_FAIL,
	 o_INDEX_DAY_COUNT_2_STR as INDEX_DAY_COUNT_2_STR,
	 o_INDEX_DAY_COUNT_1_STR as INDEX_DAY_COUNT_1_STR,
	 o_INDEX_DAY_COUNT_2_NAME as o_INDEX_DAY_COUNT_2_NAME,
	 v_INDEX_DAY_COUNT_2_LKP_FAIL as INDEX_DAY_COUNT_2_LKP_FAIL,
	 INDEX_2_MUREX_ID_IN_STR as INDEX_2_MUREX_ID_IN_STR,
	 TENOR_VALUE_STR as TENOR_VALUE_STR,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 ASSET_CLASS_LKP_FAIL as ASSET_CLASS_LKP_FAIL,
	 o_TENOR_VALUE_NAME as o_TENOR_VALUE_NAME,
	 INDEX_2_MUREX_ID_ERROR_CODE as INDEX_2_MUREX_ID_ERROR_CODE,
	 SUB_PRODUCT_LKP_FAIL as SUB_PRODUCT_LKP_FAIL,
	 o_SUB_PRODUCT_NAME as o_SUB_PRODUCT_NAME,
	 SUB_PRODUCT_IN_STR as SUB_PRODUCT_IN_STR,
	 INDEX_2_MUREX_ID_LKP_FAIL as INDEX_2_MUREX_ID_LKP_FAIL,
	 ASSET_CLASS1 as ASSET_CLASS1,
	 BASE_PRODUCT_ERROR_CODE as BASE_PRODUCT_ERROR_CODE,
	 BASE_PRODUCT1 as BASE_PRODUCT1,
	 o_BASE_PRODUCT_NAME as o_BASE_PRODUCT_NAME,
	 BASE_PRODUCT_IN_STR as BASE_PRODUCT_IN_STR,
	 BASE_PRODUCT_LKP_FAIL as BASE_PRODUCT_LKP_FAIL,
	 SUB_PRODUCT1 as SUB_PRODUCT1,
	 o_TENOR_VALUE_ERROR_CODE as o_TENOR_VALUE_ERROR_CODE,
	 TENOR_VALUE_LKP_FAIL as TENOR_VALUE_LKP_FAIL,
	 ISDA_PRODUCT_TYPE1 as ISDA_PRODUCT_TYPE1,
	 TENOR_VALUE1 as TENOR_VALUE1,
	 INDEX_DAY_COUNT_11 as INDEX_DAY_COUNT_11,
	 INDEX_DAY_COUNT_21 as INDEX_DAY_COUNT_2,
	 o_ISDA_PRODUCT_TYPE_NAME as o_ISDA_PRODUCT_TYPE_NAME,
	 ISDA_PRODUCT_TYPE_IN_STR as ISDA_PRODUCT_TYPE_IN_STR,
	 ISDA_PRODUCT_TYPE_ERROR_CODE as ISDA_PRODUCT_TYPE_ERROR_CODE,
	 ISDA_PRODUCT_TYPE_LKP_FAIL as ISDA_PRODUCT_TYPE_LKP_FAIL,
	 INDEX_1_MUREX_ID_IN_STR as INDEX_1_MUREX_ID_IN_STR,
	 INDEX_1_MUREX_ID1 as INDEX_1_MUREX_ID1 
From DSR_SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut as DSR_SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut),

LKP_CLEARED_PRODUCTS_master as (
  Select
  	LKP_CLEARED_PRODUCTSOut.ID as LKP_ID,
	 LKP_CLEARED_PRODUCTSOut.VENUE as lkp_VENUE,
	 LKP_CLEARED_PRODUCTSOut.ASSET_CLASS as lkp_ASSET_CLASS,
	 LKP_CLEARED_PRODUCTSOut.BASE_PRODUCT as lkp_BASE_PRODUCT,
	 LKP_CLEARED_PRODUCTSOut.SUB_PRODUCT as lkp_SUB_PRODUCT,
	 LKP_CLEARED_PRODUCTSOut.ISDA_PRODUCT_TYPE as lkp_ISDA_PRODUCT_TYPE,
	 LKP_CLEARED_PRODUCTSOut.INDEX_1_MUREX_NAME as lkp_INDEX_1_MUREX_NAME,
	 LKP_CLEARED_PRODUCTSOut.INDEX_1_PAY_FREQ as lkp_INDEX_1_PAY_FREQ,
	 LKP_CLEARED_PRODUCTSOut.INDEX_1_TENOR_CCY as lkp_INDEX_1_TENOR_CCY,
	 LKP_CLEARED_PRODUCTSOut.INDEX_1_DAY_COUNT as lkp_INDEX_1_DAY_COUNT,
	 LKP_CLEARED_PRODUCTSOut.INDEX_2_MUREX_NAME as lkp_INDEX_2_MUREX_NAME,
	 LKP_CLEARED_PRODUCTSOut.INDEX_2_PAY_FREQ as lkp_INDEX_2_PAY_FREQ,
	 LKP_CLEARED_PRODUCTSOut.INDEX_2_TENOR_CCY as lkp_INDEX_2_TENOR_CCY,
	 LKP_CLEARED_PRODUCTSOut.INDEX_2_DAY_COUNT as lkp_INDEX_2_DAY_COUNT,
	 LKP_CLEARED_PRODUCTSOut.MAX_CONTRACT_TENOR_VALUE as lkp_MAX_CONTRACT_TENOR_VALUE,
	 LKP_CLEARED_PRODUCTSOut.MAX_CONTRACT_TENOR_UNIT as lkp_MAX_CONTRACT_TENOR_UNIT
  From LKP_CLEARED_PRODUCTSOut as LKP_CLEARED_PRODUCTSOut
),

SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details as (
  Select
  	SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.VENUE_LKP_FAIL as VENUE_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.TENOR_KEY_LKP_FAIL as TENOR_KEY_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.INDEX_1_MUREX_ID_LKP_FAIL as INDEX_1_MUREX_ID_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.INDEX_2_MUREX_ID_LKP_FAIL as INDEX_2_MUREX_ID_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.ASSET_CLASS_LKP_FAIL as ASSET_CLASS_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.BASE_PRODUCT_LKP_FAIL as BASE_PRODUCT_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.SUB_PRODUCT_LKP_FAIL as SUB_PRODUCT_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.TENOR_VALUE_LKP_FAIL as TENOR_VALUE_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.ISDA_PRODUCT_TYPE_LKP_FAIL as ISDA_PRODUCT_TYPE_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.o_INDEX_DAY_COUNT_1_LKP_FAIL as INDEX_DAY_COUNT_1_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.v_INDEX_DAY_COUNT_2_LKP_FAIL as INDEX_DAY_COUNT_2_LKP_FAIL
  From SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut as SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut
),

EXP_TRIM_details as (
  Select
  	EXP_TRIMOut.BATCH_ID as O_BATCH_ID,
	 EXP_TRIMOut.EFFECTIVE_DATE as EFFECTIVE_DATE,
	 EXP_TRIMOut.VENUE as O_VENUE,
	 EXP_TRIMOut.O_ISDA_PRODUCT_TYPE as O_ISDA_PRODUCT_TYPE,
	 EXP_TRIMOut.ASSET_CLASS as ASSET_CLASS,
	 EXP_TRIMOut.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_TRIMOut.SUB_PRODUCT as SUB_PRODUCT,
	 EXP_TRIMOut.INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 EXP_TRIMOut.INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 EXP_TRIMOut.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 EXP_TRIMOut.INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 EXP_TRIMOut.INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 EXP_TRIMOut.INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 EXP_TRIMOut.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 EXP_TRIMOut.INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 EXP_TRIMOut.MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 EXP_TRIMOut.MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 EXP_TRIMOut.TENOR_KEY as TENOR_KEY,
	 EXP_TRIMOut.BOE_INDEX_1_DAY_COUNT as BOE_INDEX_1_DAY_COUNT,
	 EXP_TRIMOut.BOE_INDEX_1_PAY_FREQ as BOE_INDEX_1_PAY_FREQ,
	 EXP_TRIMOut.BOE_INDEX_2_PAY_FREQ as BOE_INDEX_2_PAY_FREQ,
	 EXP_TRIMOut.BOE_INDEX_2_DAY_COUNT as BOE_INDEX_2_DAY_COUNT,
	 EXP_TRIMOut.BOE_CONTRACT_TENOR_VALUE as BOE_CONTRACT_TENOR_VALUE,
	 EXP_TRIMOut.BOE_CONTRACT_TENOR_UNIT as BOE_CONTRACT_TENOR_UNIT
  From EXP_TRIMOut as EXP_TRIMOut
),
dsJoiner_EXP_LKP_SORT_PORTS0Out as (
	/* transType: "Joiner" */
Select 
	LKP_CLEARED_PRODUCTSOut1.ID as LKP_ID,
	 EXP_TRIMOut2.BATCH_ID as O_BATCH_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_TRIMOut2.EFFECTIVE_DATE as EFFECTIVE_DATE,
	 EXP_TRIMOut2.VENUE as O_VENUE,
	 EXP_TRIMOut2.O_ISDA_PRODUCT_TYPE as O_ISDA_PRODUCT_TYPE,
	 EXP_TRIMOut2.ASSET_CLASS as ASSET_CLASS,
	 EXP_TRIMOut2.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_TRIMOut2.SUB_PRODUCT as SUB_PRODUCT,
	 EXP_TRIMOut2.INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 EXP_TRIMOut2.INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 EXP_TRIMOut2.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 EXP_TRIMOut2.INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 EXP_TRIMOut2.INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 EXP_TRIMOut2.INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 EXP_TRIMOut2.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 EXP_TRIMOut2.INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 EXP_TRIMOut2.MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 EXP_TRIMOut2.MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 EXP_TRIMOut2.TENOR_KEY as TENOR_KEY,
	 LKP_CLEARED_PRODUCTSOut1.VENUE as lkp_VENUE,
	 LKP_CLEARED_PRODUCTSOut1.ASSET_CLASS as lkp_ASSET_CLASS,
	 LKP_CLEARED_PRODUCTSOut1.BASE_PRODUCT as lkp_BASE_PRODUCT,
	 LKP_CLEARED_PRODUCTSOut1.SUB_PRODUCT as lkp_SUB_PRODUCT,
	 LKP_CLEARED_PRODUCTSOut1.ISDA_PRODUCT_TYPE as lkp_ISDA_PRODUCT_TYPE,
	 LKP_CLEARED_PRODUCTSOut1.INDEX_1_MUREX_NAME as lkp_INDEX_1_MUREX_NAME,
	 LKP_CLEARED_PRODUCTSOut1.INDEX_1_PAY_FREQ as lkp_INDEX_1_PAY_FREQ,
	 LKP_CLEARED_PRODUCTSOut1.INDEX_1_TENOR_CCY as lkp_INDEX_1_TENOR_CCY,
	 LKP_CLEARED_PRODUCTSOut1.INDEX_1_DAY_COUNT as lkp_INDEX_1_DAY_COUNT,
	 LKP_CLEARED_PRODUCTSOut1.INDEX_2_MUREX_NAME as lkp_INDEX_2_MUREX_NAME,
	 LKP_CLEARED_PRODUCTSOut1.INDEX_2_PAY_FREQ as lkp_INDEX_2_PAY_FREQ,
	 LKP_CLEARED_PRODUCTSOut1.INDEX_2_TENOR_CCY as lkp_INDEX_2_TENOR_CCY,
	 LKP_CLEARED_PRODUCTSOut1.INDEX_2_DAY_COUNT as lkp_INDEX_2_DAY_COUNT,
	 LKP_CLEARED_PRODUCTSOut1.MAX_CONTRACT_TENOR_VALUE as lkp_MAX_CONTRACT_TENOR_VALUE,
	 LKP_CLEARED_PRODUCTSOut1.MAX_CONTRACT_TENOR_UNIT as lkp_MAX_CONTRACT_TENOR_UNIT,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.VENUE_LKP_FAIL as VENUE_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.TENOR_KEY_LKP_FAIL as TENOR_KEY_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.INDEX_1_MUREX_ID_LKP_FAIL as INDEX_1_MUREX_ID_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.INDEX_2_MUREX_ID_LKP_FAIL as INDEX_2_MUREX_ID_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.ASSET_CLASS_LKP_FAIL as ASSET_CLASS_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.BASE_PRODUCT_LKP_FAIL as BASE_PRODUCT_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.SUB_PRODUCT_LKP_FAIL as SUB_PRODUCT_LKP_FAIL,
	 EXP_TRIMOut2.BOE_INDEX_1_DAY_COUNT as BOE_INDEX_1_DAY_COUNT,
	 EXP_TRIMOut2.BOE_INDEX_1_PAY_FREQ as BOE_INDEX_1_PAY_FREQ,
	 EXP_TRIMOut2.BOE_INDEX_2_PAY_FREQ as BOE_INDEX_2_PAY_FREQ,
	 EXP_TRIMOut2.BOE_INDEX_2_DAY_COUNT as BOE_INDEX_2_DAY_COUNT,
	 EXP_TRIMOut2.BOE_CONTRACT_TENOR_VALUE as BOE_CONTRACT_TENOR_VALUE,
	 EXP_TRIMOut2.BOE_CONTRACT_TENOR_UNIT as BOE_CONTRACT_TENOR_UNIT,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.TENOR_VALUE_LKP_FAIL as TENOR_VALUE_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.ISDA_PRODUCT_TYPE_LKP_FAIL as ISDA_PRODUCT_TYPE_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.INDEX_DAY_COUNT_1_LKP_FAIL as INDEX_DAY_COUNT_1_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.INDEX_DAY_COUNT_2_LKP_FAIL as INDEX_DAY_COUNT_2_LKP_FAIL,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
LKP_CLEARED_PRODUCTSOut1 as LKP_CLEARED_PRODUCTSOut1 INNER JOIN SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut1 as SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut1 
ON
LKP_CLEARED_PRODUCTSOut1.jkey = SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut1.jkey
 INNER JOIN EXP_TRIMOut2 as EXP_TRIMOut2 
ON
LKP_CLEARED_PRODUCTSOut1.jkey = EXP_TRIMOut2.jkey
 
),

EXP_LKP_SORT_PORTSOut as (
	/* transType: "Expression" */
Select 
	LKP_ID as LKP_ID,
	 O_BATCH_ID as O_BATCH_ID,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EFFECTIVE_DATE as EFFECTIVE_DATE,
	 TO_DATE ( '01-JAN-99',
	 'DD-MON-YY' ) as O_EXPIREDATE,
	 TO_TIMESTAMP ( '12-DEC-2300 00:00:00',
	 'DD-MON-YYYY HH24:SS:MI' ) as O_EXPIREDATE_UPD,
	 O_VENUE as O_VENUE,
	 O_ISDA_PRODUCT_TYPE as O_ISDA_PRODUCT_TYPE,
	 ASSET_CLASS as ASSET_CLASS,
	 BASE_PRODUCT as BASE_PRODUCT,
	 SUB_PRODUCT as SUB_PRODUCT,
	 INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 TENOR_KEY as TENOR_KEY,
	 lkp_VENUE as lkp_VENUE,
	 lkp_ASSET_CLASS as lkp_ASSET_CLASS,
	 lkp_BASE_PRODUCT as lkp_BASE_PRODUCT,
	 lkp_SUB_PRODUCT as lkp_SUB_PRODUCT,
	 lkp_ISDA_PRODUCT_TYPE as lkp_ISDA_PRODUCT_TYPE,
	 lkp_INDEX_1_MUREX_NAME as lkp_INDEX_1_MUREX_NAME,
	 lkp_INDEX_1_PAY_FREQ as lkp_INDEX_1_PAY_FREQ,
	 lkp_INDEX_1_TENOR_CCY as lkp_INDEX_1_TENOR_CCY,
	 lkp_INDEX_1_DAY_COUNT as lkp_INDEX_1_DAY_COUNT,
	 lkp_INDEX_2_MUREX_NAME as lkp_INDEX_2_MUREX_NAME,
	 lkp_INDEX_2_PAY_FREQ as lkp_INDEX_2_PAY_FREQ,
	 lkp_INDEX_2_TENOR_CCY as lkp_INDEX_2_TENOR_CCY,
	 lkp_INDEX_2_DAY_COUNT as lkp_INDEX_2_DAY_COUNT,
	 lkp_MAX_CONTRACT_TENOR_VALUE as lkp_MAX_CONTRACT_TENOR_VALUE,
	 lkp_MAX_CONTRACT_TENOR_UNIT as lkp_MAX_CONTRACT_TENOR_UNIT,
	 lkp_LCH_PRODUCT_TYPE as lkp_LCH_PRODUCT_TYPE,
	 ( CASE WHEN LKP_ID IS NULL THEN 'Y' ELSE 'N' END ) as v_NN_CHECK_LKP_COLS,
	 ( CASE WHEN v_NN_CHECK_LKP_COLS = 'N' AND ( MAX_CONTRACT_TENOR_UNIT  !=  lkp_MAX_CONTRACT_TENOR_UNIT OR MAX_CONTRACT_TENOR_VALUE  !=  lkp_MAX_CONTRACT_TENOR_VALUE ) THEN 'Y' ELSE 'N' END ) as v_CHNG_FLAG,
	 v_CHNG_FLAG as o_CHNG_FLAG,
	 1 as PROPAGATE_INDICATOR,
	 BOE_INDEX_1_DAY_COUNT as BOE_INDEX_1_DAY_COUNT,
	 BOE_INDEX_1_PAY_FREQ as BOE_INDEX_1_PAY_FREQ,
	 BOE_INDEX_2_PAY_FREQ as BOE_INDEX_2_PAY_FREQ,
	 BOE_INDEX_2_DAY_COUNT as BOE_INDEX_2_DAY_COUNT,
	 BOE_CONTRACT_TENOR_VALUE as BOE_CONTRACT_TENOR_VALUE,
	 BOE_CONTRACT_TENOR_UNIT as BOE_CONTRACT_TENOR_UNIT,
	 ( CASE WHEN VENUE_LKP_FAIL  !=  0 OR ISDA_PRODUCT_TYPE_LKP_FAIL  !=  0 OR INDEX_1_MUREX_ID_LKP_FAIL  !=  0 OR INDEX_2_MUREX_ID_LKP_FAIL  !=  0 OR ASSET_CLASS_LKP_FAIL  !=  0 OR BASE_PRODUCT_LKP_FAIL  !=  0 OR SUB_PRODUCT_LKP_FAIL  !=  0 OR TENOR_VALUE_LKP_FAIL  !=  0 OR INDEX_DAY_COUNT_1_LKP_FAIL  !=  0 OR INDEX_DAY_COUNT_2_LKP_FAIL  !=  0 OR TENOR_KEY_LKP_FAIL  !=  0 THEN 'Y' ELSE 'N' END ) as ERROR_INDICATOR,
	 ( CASE WHEN LKP_ID IS NULL OR ( LKP_ID IS NOT NULL AND v_CHNG_FLAG = 'Y' ) THEN v_TOT_REC_COUNT + 1 ELSE v_TOT_REC_COUNT END ) as v_TOT_REC_COUNT
From dsJoiner_EXP_LKP_SORT_PORTS0Out as dsJoiner_EXP_LKP_SORT_PORTS0Out),

DSR_RTR_INSERT_UPDATEOut as (
	/* transType: "Expression" */
Select 
	EXP_LKP_SORT_PORTSOut.LKP_ID as LKP_ID,
	 EXP_LKP_SORT_PORTSOut.O_BATCH_ID as O_BATCH_ID,
	 EXP_LKP_SORT_PORTSOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_LKP_SORT_PORTSOut.EFFECTIVE_DATE as O_EFFECTIVE_DATE,
	 EXP_LKP_SORT_PORTSOut.O_EXPIREDATE as O_EXPIREDATE,
	 EXP_LKP_SORT_PORTSOut.O_VENUE as O_VENUE,
	 EXP_LKP_SORT_PORTSOut.O_ISDA_PRODUCT_TYPE as O_ISDA_PRODUCT_TYPE,
	 EXP_LKP_SORT_PORTSOut.ASSET_CLASS as ASSET_CLASS,
	 EXP_LKP_SORT_PORTSOut.BASE_PRODUCT as BASE_PRODUCT,
	 EXP_LKP_SORT_PORTSOut.SUB_PRODUCT as SUB_PRODUCT,
	 EXP_LKP_SORT_PORTSOut.INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 EXP_LKP_SORT_PORTSOut.INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 EXP_LKP_SORT_PORTSOut.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 EXP_LKP_SORT_PORTSOut.INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 EXP_LKP_SORT_PORTSOut.INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 EXP_LKP_SORT_PORTSOut.INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 EXP_LKP_SORT_PORTSOut.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 EXP_LKP_SORT_PORTSOut.INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 EXP_LKP_SORT_PORTSOut.MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 EXP_LKP_SORT_PORTSOut.MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 EXP_LKP_SORT_PORTSOut.o_CHNG_FLAG as CHNG_FLAG,
	 EXP_LKP_SORT_PORTSOut.PROPAGATE_INDICATOR as PROPAGATE_INDICATOR,
	 EXP_LKP_SORT_PORTSOut.ERROR_INDICATOR as ERROR_INDICATOR,
	 EXP_LKP_SORT_PORTSOut.TENOR_KEY as TENOR_KEY,
	 EXP_LKP_SORT_PORTSOut.BOE_INDEX_1_DAY_COUNT as BOE_INDEX_1_DAY_COUNT,
	 EXP_LKP_SORT_PORTSOut.BOE_INDEX_1_PAY_FREQ as BOE_INDEX_1_PAY_FREQ,
	 EXP_LKP_SORT_PORTSOut.BOE_INDEX_2_PAY_FREQ as BOE_INDEX_2_PAY_FREQ,
	 EXP_LKP_SORT_PORTSOut.BOE_INDEX_2_DAY_COUNT as BOE_INDEX_2_DAY_COUNT,
	 EXP_LKP_SORT_PORTSOut.BOE_CONTRACT_TENOR_VALUE as BOE_CONTRACT_TENOR_VALUE,
	 EXP_LKP_SORT_PORTSOut.BOE_CONTRACT_TENOR_UNIT as BOE_CONTRACT_TENOR_UNIT,
	 EXP_LKP_SORT_PORTSOut.O_EXPIREDATE_UPD as O_EXPIREDATE_UPD
From EXP_LKP_SORT_PORTSOut as EXP_LKP_SORT_PORTSOut),

RTR_INSERT_UPDATEOut as (
	/* transType: "Router" */
Select 
	DSR_RTR_INSERT_UPDATEOut.LKP_ID as LKP_ID,
	 DSR_RTR_INSERT_UPDATEOut.O_BATCH_ID as O_BATCH_ID,
	 DSR_RTR_INSERT_UPDATEOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 DSR_RTR_INSERT_UPDATEOut.EFFECTIVE_DATE as O_EFFECTIVE_DATE,
	 DSR_RTR_INSERT_UPDATEOut.O_EXPIREDATE as O_EXPIREDATE,
	 DSR_RTR_INSERT_UPDATEOut.O_VENUE as O_VENUE,
	 DSR_RTR_INSERT_UPDATEOut.O_ISDA_PRODUCT_TYPE as O_ISDA_PRODUCT_TYPE,
	 DSR_RTR_INSERT_UPDATEOut.ASSET_CLASS as ASSET_CLASS,
	 DSR_RTR_INSERT_UPDATEOut.BASE_PRODUCT as BASE_PRODUCT,
	 DSR_RTR_INSERT_UPDATEOut.SUB_PRODUCT as SUB_PRODUCT,
	 DSR_RTR_INSERT_UPDATEOut.INDEX_1_MUREX_ID as INDEX_1_MUREX_ID,
	 DSR_RTR_INSERT_UPDATEOut.INDEX_1_PAY_FREQ as INDEX_1_PAY_FREQ,
	 DSR_RTR_INSERT_UPDATEOut.INDEX_1_CURRENCY_CODE as INDEX_1_CURRENCY_CODE,
	 DSR_RTR_INSERT_UPDATEOut.INDEX_1_DAY_COUNT as INDEX_1_DAY_COUNT,
	 DSR_RTR_INSERT_UPDATEOut.INDEX_2_MUREX_ID as INDEX_2_MUREX_ID,
	 DSR_RTR_INSERT_UPDATEOut.INDEX_2_PAY_FREQ as INDEX_2_PAY_FREQ,
	 DSR_RTR_INSERT_UPDATEOut.INDEX_2_CURRENCY_CODE as INDEX_2_CURRENCY_CODE,
	 DSR_RTR_INSERT_UPDATEOut.INDEX_2_DAY_COUNT as INDEX_2_DAY_COUNT,
	 DSR_RTR_INSERT_UPDATEOut.MAX_CONTRACT_TENOR_VALUE as MAX_CONTRACT_TENOR_VALUE,
	 DSR_RTR_INSERT_UPDATEOut.MAX_CONTRACT_TENOR_UNIT as MAX_CONTRACT_TENOR_UNIT,
	 DSR_RTR_INSERT_UPDATEOut.o_CHNG_FLAG as CHNG_FLAG,
	 DSR_RTR_INSERT_UPDATEOut.PROPAGATE_INDICATOR as PROPAGATE_INDICATOR,
	 DSR_RTR_INSERT_UPDATEOut.ERROR_INDICATOR as ERROR_INDICATOR,
	 DSR_RTR_INSERT_UPDATEOut.TENOR_KEY as TENOR_KEY,
	 DSR_RTR_INSERT_UPDATEOut.BOE_INDEX_1_DAY_COUNT as BOE_INDEX_1_DAY_COUNT,
	 DSR_RTR_INSERT_UPDATEOut.BOE_INDEX_1_PAY_FREQ as BOE_INDEX_1_PAY_FREQ,
	 DSR_RTR_INSERT_UPDATEOut.BOE_INDEX_2_PAY_FREQ as BOE_INDEX_2_PAY_FREQ,
	 DSR_RTR_INSERT_UPDATEOut.BOE_INDEX_2_DAY_COUNT as BOE_INDEX_2_DAY_COUNT,
	 DSR_RTR_INSERT_UPDATEOut.BOE_CONTRACT_TENOR_VALUE as BOE_CONTRACT_TENOR_VALUE,
	 DSR_RTR_INSERT_UPDATEOut.BOE_CONTRACT_TENOR_UNIT as BOE_CONTRACT_TENOR_UNIT,
	 DSR_RTR_INSERT_UPDATEOut.O_EXPIREDATE_UPD as O_EXPIREDATE_UPD
 FROM DSR_RTR_INSERT_UPDATEOut as DSR_RTR_INSERT_UPDATEOut Where LKP_ID IS NULL ),

EXP_UPDATEOut as (
	/* transType: "Expression" */
Select 
	LKP_ID3 as LKP_ID3,
	 DATEADD ( '-1',
	 'DD',
	 TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ) ) as O_EXPIREDATE3
From DSR_RTR_INSERT_UPDATEOut as DSR_RTR_INSERT_UPDATEOut
WHERE ISNULL(LKP_ID))

Select 
	LKP_ID3 as ID,
	O_EXPIREDATE3 as EXPIRATION_DATE 
From EXP_UPDATEOut as EXP_UPDATEOut