/* Transformation Name ==>SC_PROCESS_ERROR_DETAILS_DSRO ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='PROCESS_ERROR_DETAILS',
		schema='EMIR_SHARED',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_SC_RR_BNK_DSRO_SEC_BALANCES_FACTOut as (
	/* SubQuery from Source ==>SQ_SQ_SC_RR_BNK_DSRO_SEC_BALANCES_FACT */
/* transType: "Source" */
Select 
ID,
BUSINESS_DATE,
MNEMONIC,
SUB_ACCOUNT,
SECURITY_CURRENCY_ID,
SECURITY_PRODUCT_CODE,
MARKET_VALUE,
ENTITY_ID,
MARKET_VALUE_POST_HAIRCUT,
HAIRCUT,
SECURITY_TYPE,
BOE_SECURITY_TYPE
 from 
(SELECT
    DSB.ID,
    DSB.BUSINESS_DATE,
    DSB.MNEMONIC,
    DSB.SUB_ACCOUNT,
    DSB.SECURITY_CURRENCY_ID,
    DSB.SECURITY_PRODUCT_CODE,
    DSB.MARKET_VALUE,
    DSB.ENTITY_ID,
    DSB.MARKET_VALUE_POST_HAIRCUT,
    DSB.HAIRCUT,
    DSB.SECURITY_TYPE,
    DSB.BOE_SECURITY_TYPE
 FROM
    RR_BNK_DSRO_SEC_BALANCES_FACT as DSB
 INNER JOIN 
  BATCH_MASTER as BM
 ON
  DSB.BATCH_ID= BM.BATCH_ID
 WHERE  
  BM.BATCH_FEED_INFO LIKE '%BNK%' AND 
  BM.BATCH_STATUS= 'C' AND 
  BM.BATCH_BUSINESS_FROM_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  DSB.MARKET_VALUE > 0 AND 
  DSB.SUB_ACCOUNT  !=  'Q' AND 
  (NVL(UPPER(DSB.SECURITY_TYPE),'NA') NOT IN('TRIPARTY COLLATERAL') OR DSB.BUSINESS_DATE <(SELECT TO_DATE(STRING_VALUE,'YYYYMMDD') FROM APPLICATION_VARIABLES WHERE VARIABLE_NAME= 'BOE_COLTRL_RPT_MBR_GOLIVE_DATE' AND ACTIVE_Y_N = 'Y')) AND 
  DSB.ERROR_INDICATOR  != (DECODE((SELECT STRING_VALUE3 FROM
{{ source('DW_MART', 'APPLICATION_VARIABLES') }} WHERE VARIABLE_NAME= 'BOE_STATIC_DSRO_ERROR_IND_VAL' AND ACTIVE_Y_N = 'Y'),'ALL','A','Y'))
 UNION ALL 
 SELECT
    TRI.ID,
    TRI.BUSINESS_DATE,
    TRI.MNEMONIC,
    TRI.SUB_ACCOUNT,
    TRI.CURRENCY_ID,
    NULL as SECURITY_PRODUCT_CODE,
    TRI.PRE_HC_MV_COLL_CCY_AMT as MARKET_VALUE,
    TRI.ENTITY_ID,
    TRI.POST_HC_MV_COLL_CCY_AMT as MARKET_VALUE_POST_HAIRCUT,
    TRI.HAIRCUT,
    'Triparty Collateral' as SECURITY_TYPE,
    NULL as BOE_SECURITY_TYPE
 FROM
    RR_BNK_TRIPTYALC_INVST_FACT as TRI
 INNER JOIN 
  BATCH_MASTER as BM
 ON
  TRI.BATCH_ID= BM.BATCH_ID
 WHERE  
  BM.BATCH_FEED_INFO LIKE '%BNK%' AND 
  BM.BATCH_STATUS= 'C' AND 
  BM.BATCH_BUSINESS_FROM_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  ( TRI.MNEMONIC IS NOT NULL AND TRI.BUSINESS_DATE >= ( SELECT TO_DATE ( STRING_VALUE,'YYYYMMDD') FROM APPLICATION_VARIABLES WHERE VARIABLE_NAME = 'BOE_COLTRL_RPT_MBR_GOLIVE_DATE' AND ACTIVE_Y_N = 'Y' ) ) AND 
  TRI.PRE_HC_MV_COLL_CCY_AMT > 0 AND 
  TRI.ERROR_INDICATOR  != (DECODE((SELECT STRING_VALUE3 FROM
{{ source('DW_MART', 'APPLICATION_VARIABLES') }} WHERE VARIABLE_NAME= 'BOE_STATIC_DSRO_ERROR_IND_VAL' AND ACTIVE_Y_N = 'Y'),'ALL','A','Y')) AND 
   TRI.ENTITY_ID IN
 (SELECT
    ID
 FROM
{{ source('DW_MART', 'ENTITY_DIM') }}
 WHERE 
  NAME= 'LCH.LTD'))
 ),

EXP_PASS_THROUGHOut as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 BUSINESS_DATE as BUSINESS_DATE,
	 MNEMONIC as MNEMONIC,
	 SUB_ACCOUNT as SUB_ACCOUNT,
	 SECURITY_CURRENCY_ID as SECURITY_CURRENCY_ID,
	 SECURITY_PRODUCT_CODE as SECURITY_PRODUCT_CODE,
	 MARKET_VALUE as MARKET_VALUE,
	 ENTITY_ID as ENTITY_ID,
	 MARKET_VALUE_POST_HAIRCUT as MARKET_VALUE_POST_HAIRCUT,
	 HAIRCUT as HAIRCUT,
	 SECURITY_TYPE as SECURITY_TYPE,
	 dsf_1.PRIMARY_EXCHANGE as v_EXCHANGE_1,
	 ( CASE WHEN v_EXCHANGE_1 IS NULL THEN dsf_2.SERVICE ELSE v_EXCHANGE_1 END ) as v_EXCHANGE_2,
	 dsf_3.ID as v_EXCHANGE_ID,
	 DECODE ( v_EXCHANGE_2,
	 'TQD',
	 'ED2',
	 v_EXCHANGE_2 ) as o_EXCHANGE,
	 v_EXCHANGE_ID as o_EXCHANGE_ID,
	 ( CASE WHEN v_EXCHANGE_ID IS NOT NULL THEN 'Y' ELSE 'N' END ) as o_VALID_EXCHANGE,
	 'BOE_DSRO_SECURITY_TYPE' as BOE_SECURITY_TYPE_NAME,
	 dsf_4.STRING_VALUE3 as o_BOE_SECURITY_TYPE
From SQ_SC_RR_BNK_DSRO_SEC_BALANCES_FACTOut as SQ_SC_RR_BNK_DSRO_SEC_BALANCES_FACTOut
LEFT JOIN (
SELECT PRIMARY_EXCHANGE, MNEMONIC FROM (  SELECT PRIMARY_EXCHANGE, MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT PRIMARY_EXCHANGE, MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY MNEMONIC ORDER BY MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    VW_PRIM_EXCH_SHAREDMNEMONIC )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.MNEMONIC = MNEMONIC
LEFT JOIN (
SELECT SERVICE, MRG_MNEMONIC FROM (  SELECT SERVICE, MRG_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY MRG_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT SERVICE, MRG_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY MRG_MNEMONIC ORDER BY MRG_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    VW_RDR_MEMBER_DTLS.SERVICE as SERVICE,    VW_RDR_MEMBER_DTLS.MEM_EXCHANGE_ID as MEM_EXCHANGE_ID,    VW_RDR_MEMBER_DTLS.MEM_MNEMONIC as MEM_MNEMONIC,    VW_RDR_MEMBER_DTLS.GO_LIVE_DATE as GO_LIVE_DATE,    VW_RDR_MEMBER_DTLS.RESIGNATION_DATE as RESIGNATION_DATE,    VW_RDR_MEMBER_DTLS.MEM_LEI as MEM_LEI,    VW_RDR_MEMBER_DTLS.MEM_NAME as MEM_NAME,    VW_RDR_MEMBER_DTLS.CLEARING_CATEGORY_ID as CLEARING_CATEGORY_ID,    VW_RDR_MEMBER_DTLS.ULTIMATE_PARENT_ID as ULTIMATE_PARENT_ID,    VW_RDR_MEMBER_DTLS.INTERNAL_CREDIT_SCORE as INTERNAL_CREDIT_SCORE,    VW_RDR_MEMBER_DTLS.SM_AGENT_MNEMONIC as SM_AGENT_MNEMONIC,    VW_RDR_MEMBER_DTLS.SM_AGENT_NAME as SM_AGENT_NAME,    VW_RDR_MEMBER_DTLS.SM_AGENT_LEI as SM_AGENT_LEI,    VW_RDR_MEMBER_DTLS.REC as REC,    VW_RDR_MEMBER_DTLS.SUB_ACCOUNT as SUB_ACCOUNT,    VW_RDR_MEMBER_DTLS.HOUSE_CLIENT_FLAG as HOUSE_CLIENT_FLAG,    VW_RDR_MEMBER_DTLS.CLIENT_ACCOUNT_TYPE as CLIENT_ACCOUNT_TYPE,    VW_RDR_MEMBER_DTLS.MRG_MNEMONIC as MRG_MNEMONIC FROM    VW_RDR_MEMBER_DTLS ORDER BY    VW_RDR_MEMBER_DTLS.MRG_MNEMONIC,    NVL ( VW_RDR_MEMBER_DTLS.RESIGNATION_DATE,TO_DATE ( '31-DEC-2099','DD-MON-YYYY' ) ) - - )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.MRG_MNEMONIC = MNEMONIC
LEFT JOIN (
SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    EXCHANGE_DIM.ID as ID,    EXCHANGE_DIM.EXCHANGE_MNEMONIC as EXCHANGE_MNEMONIC,    EXCHANGE_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(EXCHANGE_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    EXCHANGE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.EXCHANGE_MNEMONIC = v_EXCHANGE_2 AND dsf_3.EFFECTIVE_DATE <= BUSINESS_DATE AND dsf_3.EXPIRATION_DATE >= BUSINESS_DATE
LEFT JOIN (
SELECT STRING_VALUE3, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 FROM (  SELECT STRING_VALUE3, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT STRING_VALUE3, VARIABLE_NAME, STRING_VALUE, STRING_VALUE2,  ROW_NUMBER() OVER (PARTITION BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 ORDER BY VARIABLE_NAME, STRING_VALUE, STRING_VALUE2 NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    APPLICATION_VARIABLES )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.VARIABLE_NAME = 'BOE_VALIDATION_VALUE' AND dsf_4.STRING_VALUE = 'BOE_DSRO_SECURITY_TYPE' AND dsf_4.STRING_VALUE2 = BOE_SECURITY_TYPE
),

DSR_FIL_VALID_EXCHANGE_RECSOut as (
	/* transType: "Expression" */
Select 
	EXP_PASS_THROUGHOut.MARKET_VALUE as MARKET_VALUE,
	 EXP_PASS_THROUGHOut.o_BOE_SECURITY_TYPE as BOE_SECURITY_TYPE,
	 EXP_PASS_THROUGHOut.HAIRCUT as HAIRCUT,
	 EXP_PASS_THROUGHOut.BOE_SECURITY_TYPE_NAME as BOE_SECURITY_TYPE_NAME,
	 EXP_PASS_THROUGHOut.ENTITY_ID as ENTITY_ID,
	 EXP_PASS_THROUGHOut.MARKET_VALUE_POST_HAIRCUT as MARKET_VALUE_POST_HAIRCUT,
	 EXP_PASS_THROUGHOut.SECURITY_TYPE as SECURITY_TYPE,
	 EXP_PASS_THROUGHOut.o_EXCHANGE_ID as EXCHANGE_ID,
	 EXP_PASS_THROUGHOut.o_EXCHANGE as EXCHANGE,
	 EXP_PASS_THROUGHOut.o_VALID_EXCHANGE as VALID_EXCHANGE,
	 EXP_PASS_THROUGHOut.ID as ID,
	 EXP_PASS_THROUGHOut.BUSINESS_DATE as BUSINESS_DATE,
	 EXP_PASS_THROUGHOut.MNEMONIC as MNEMONIC,
	 EXP_PASS_THROUGHOut.SUB_ACCOUNT as SUB_ACCOUNT,
	 EXP_PASS_THROUGHOut.SECURITY_CURRENCY_ID as SECURITY_CURRENCY_ID,
	 EXP_PASS_THROUGHOut.SECURITY_PRODUCT_CODE as SECURITY_PRODUCT_CODE
From EXP_PASS_THROUGHOut as EXP_PASS_THROUGHOut),

DSR_EXP_BNK_DSRO_SECOut as (
	/* transType: "Expression" */
Select 
	FIL_VALID_EXCHANGE_RECSOut.ID as ID,
	 FIL_VALID_EXCHANGE_RECSOut.BUSINESS_DATE as BUSINESS_DATE,
	 FIL_VALID_EXCHANGE_RECSOut.MNEMONIC as MNEMONIC,
	 FIL_VALID_EXCHANGE_RECSOut.SUB_ACCOUNT as SUB_ACCOUNT,
	 FIL_VALID_EXCHANGE_RECSOut.SECURITY_CURRENCY_ID as SECURITY_CURRENCY_ID,
	 FIL_VALID_EXCHANGE_RECSOut.SECURITY_PRODUCT_CODE as SECURITY_PRODUCT_CODE,
	 FIL_VALID_EXCHANGE_RECSOut.MARKET_VALUE as MARKET_VALUE,
	 FIL_VALID_EXCHANGE_RECSOut.ENTITY_ID as ENTITY_ID,
	 FIL_VALID_EXCHANGE_RECSOut.MARKET_VALUE_POST_HAIRCUT as MARKET_VALUE_POST_HAIRCUT,
	 FIL_VALID_EXCHANGE_RECSOut.HAIRCUT as HAIRCUT,
	 FIL_VALID_EXCHANGE_RECSOut.SECURITY_TYPE as SECURITY_TYPE,
	 FIL_VALID_EXCHANGE_RECSOut.EXCHANGE as EXCHANGE,
	 FIL_VALID_EXCHANGE_RECSOut.EXCHANGE_ID as i_EXCHANGE_ID,
	 FIL_VALID_EXCHANGE_RECSOut.BOE_SECURITY_TYPE_NAME as BOE_SECURITY_TYPE_NAME,
	 FIL_VALID_EXCHANGE_RECSOut.BOE_SECURITY_TYPE as BOE_SECURITY_TYPE 
From DSR_FIL_VALID_EXCHANGE_RECSOut as DSR_FIL_VALID_EXCHANGE_RECSOut Where VALID_EXCHANGE = 'Y'),

EXP_BNK_DSRO_SECOut1 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 BUSINESS_DATE as BUSINESS_DATE,
	 MNEMONIC as MNEMONIC,
	 SUB_ACCOUNT as SUB_ACCOUNT,
	 SECURITY_CURRENCY_ID as SECURITY_CURRENCY_ID,
	 SECURITY_PRODUCT_CODE as SECURITY_PRODUCT_CODE,
	 MARKET_VALUE as MARKET_VALUE,
	 ENTITY_ID as ENTITY_ID,
	 MARKET_VALUE_POST_HAIRCUT as MARKET_VALUE_POST_HAIRCUT,
	 EXCHANGE as EXCHANGE,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_NM as DSRO_WATERFALL_NM,
	 v_WATERFALL_SRVC as DSRO_WATERFALL_SRVC,
	 1 as ENABLE_IND,
	 dsf_2.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 dsf_3.HOUSE_CLIENT_FLAG as v_HOUSE_CLIENT_FLAG,
	 ( CASE WHEN IN ( SUBSTRING ( SUB_ACCOUNT,
	 1,
	 1 ),
	 'S',
	 'O',
	 'V',
	 'F',
	 'R' ) THEN SUB_ACCOUNT ELSE v_HOUSE_CLIENT_FLAG END ) as v_SUB_ACCOUNT_CHK,
	 MNEMONIC || '_' || v_SUB_ACCOUNT_CHK as v_DSRO_SUB_ACC,
	 v_SUB_ACCOUNT_CHK as o_SUB_ACCOUNT,
	 v_DSRO_SUB_ACC as DSRO_CollateralAccountID,
	 ( CASE WHEN IN ( SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as DSRO_CollateralRequirement,
	 ( CASE WHEN SECURITY_TYPE = 'Triparty Collateral' THEN 'TripartyRepo' ELSE 'Security' END ) as v_AssetType,
	 v_AssetType as AssetType,
	 ( CASE WHEN v_AssetType = 'TripartyRepo' THEN MARKET_VALUE ELSE NULL END ) as TripartyRepo_Value,
	 ( CASE WHEN v_AssetType = 'TripartyRepo' THEN v_Ccy ELSE NULL END ) as TripartyRepo_Value_Ccy,
	 ( CASE WHEN v_AssetType = 'Security' THEN SECURITY_PRODUCT_CODE ELSE NULL END ) as SecurityIdentifier,
	 ( CASE WHEN v_AssetType = 'Security' THEN MARKET_VALUE ELSE NULL END ) as v_MarketValue,
	 v_MarketValue as MarketValue,
	 ( CASE WHEN v_AssetType = 'Security' THEN v_Ccy ELSE NULL END ) as MarketValue_Ccy,
	 ( CASE WHEN IN ( v_AssetType,
	 'Security',
	 'TripartyRepo' ) THEN MARKET_VALUE_POST_HAIRCUT ELSE NULL END ) as v_ValuePostHairCut,
	 v_ValuePostHairCut as ValuePostHairCut,
	 ( CASE WHEN IN ( v_AssetType,
	 'Security',
	 'TripartyRepo' ) THEN v_Ccy ELSE null END ) as ValuePostHairCut_Ccy,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 dsf_6.ID as FILE_GEN_DETAILS_ID,
	 BOE_SECURITY_TYPE_NAME as BOE_SECURITY_TYPE_NAME,
	 BOE_SECURITY_TYPE as BOE_SECURITY_TYPE,
	 ( CASE WHEN SECURITY_TYPE  !=  'Triparty Collateral' THEN 1 ELSE 0 END ) as BOE_SEC_TYPE_EI
From DSR_EXP_BNK_DSRO_SECOut as DSR_EXP_BNK_DSRO_SECOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = i_EXCHANGE_ID
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.ID = SECURITY_CURRENCY_ID
LEFT JOIN (
SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT FROM (   SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY SUB_ACCOUNT NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        VW_ML_CALYP_SUB_ACCOUNT )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.SUB_ACCOUNT = SUB_ACCOUNT
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_4.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_5.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_6
ON dsf_6.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_6.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
),

EXP_BNK_DSRO_SECOut2 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 BUSINESS_DATE as BUSINESS_DATE,
	 MNEMONIC as MNEMONIC,
	 SUB_ACCOUNT as SUB_ACCOUNT,
	 SECURITY_CURRENCY_ID as SECURITY_CURRENCY_ID,
	 SECURITY_PRODUCT_CODE as SECURITY_PRODUCT_CODE,
	 MARKET_VALUE as MARKET_VALUE,
	 ENTITY_ID as ENTITY_ID,
	 MARKET_VALUE_POST_HAIRCUT as MARKET_VALUE_POST_HAIRCUT,
	 EXCHANGE as EXCHANGE,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_NM as DSRO_WATERFALL_NM,
	 v_WATERFALL_SRVC as DSRO_WATERFALL_SRVC,
	 1 as ENABLE_IND,
	 dsf_2.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 dsf_3.HOUSE_CLIENT_FLAG as v_HOUSE_CLIENT_FLAG,
	 ( CASE WHEN IN ( SUBSTRING ( SUB_ACCOUNT,
	 1,
	 1 ),
	 'S',
	 'O',
	 'V',
	 'F',
	 'R' ) THEN SUB_ACCOUNT ELSE v_HOUSE_CLIENT_FLAG END ) as v_SUB_ACCOUNT_CHK,
	 MNEMONIC || '_' || v_SUB_ACCOUNT_CHK as v_DSRO_SUB_ACC,
	 v_SUB_ACCOUNT_CHK as o_SUB_ACCOUNT,
	 v_DSRO_SUB_ACC as DSRO_CollateralAccountID,
	 ( CASE WHEN IN ( SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as DSRO_CollateralRequirement,
	 ( CASE WHEN SECURITY_TYPE = 'Triparty Collateral' THEN 'TripartyRepo' ELSE 'Security' END ) as v_AssetType,
	 v_AssetType as AssetType,
	 ( CASE WHEN v_AssetType = 'TripartyRepo' THEN MARKET_VALUE ELSE NULL END ) as TripartyRepo_Value,
	 ( CASE WHEN v_AssetType = 'TripartyRepo' THEN v_Ccy ELSE NULL END ) as TripartyRepo_Value_Ccy,
	 ( CASE WHEN v_AssetType = 'Security' THEN SECURITY_PRODUCT_CODE ELSE NULL END ) as SecurityIdentifier,
	 ( CASE WHEN v_AssetType = 'Security' THEN MARKET_VALUE ELSE NULL END ) as v_MarketValue,
	 v_MarketValue as MarketValue,
	 ( CASE WHEN v_AssetType = 'Security' THEN v_Ccy ELSE NULL END ) as MarketValue_Ccy,
	 ( CASE WHEN IN ( v_AssetType,
	 'Security',
	 'TripartyRepo' ) THEN MARKET_VALUE_POST_HAIRCUT ELSE NULL END ) as v_ValuePostHairCut,
	 v_ValuePostHairCut as ValuePostHairCut,
	 ( CASE WHEN IN ( v_AssetType,
	 'Security',
	 'TripartyRepo' ) THEN v_Ccy ELSE null END ) as ValuePostHairCut_Ccy,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 dsf_6.ID as FILE_GEN_DETAILS_ID,
	 BOE_SECURITY_TYPE_NAME as BOE_SECURITY_TYPE_NAME,
	 BOE_SECURITY_TYPE as BOE_SECURITY_TYPE,
	 ( CASE WHEN SECURITY_TYPE  !=  'Triparty Collateral' THEN 1 ELSE 0 END ) as BOE_SEC_TYPE_EI
From DSR_EXP_BNK_DSRO_SECOut as DSR_EXP_BNK_DSRO_SECOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = i_EXCHANGE_ID
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.ID = SECURITY_CURRENCY_ID
LEFT JOIN (
SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT FROM (   SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY SUB_ACCOUNT NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        VW_ML_CALYP_SUB_ACCOUNT )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.SUB_ACCOUNT = SUB_ACCOUNT
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_4.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_5.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_6
ON dsf_6.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_6.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
),

EXP_BNK_DSRO_SECOut3 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 BUSINESS_DATE as BUSINESS_DATE,
	 MNEMONIC as MNEMONIC,
	 SUB_ACCOUNT as SUB_ACCOUNT,
	 SECURITY_CURRENCY_ID as SECURITY_CURRENCY_ID,
	 SECURITY_PRODUCT_CODE as SECURITY_PRODUCT_CODE,
	 MARKET_VALUE as MARKET_VALUE,
	 ENTITY_ID as ENTITY_ID,
	 MARKET_VALUE_POST_HAIRCUT as MARKET_VALUE_POST_HAIRCUT,
	 EXCHANGE as EXCHANGE,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_NM as DSRO_WATERFALL_NM,
	 v_WATERFALL_SRVC as DSRO_WATERFALL_SRVC,
	 1 as ENABLE_IND,
	 dsf_2.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 dsf_3.HOUSE_CLIENT_FLAG as v_HOUSE_CLIENT_FLAG,
	 ( CASE WHEN IN ( SUBSTRING ( SUB_ACCOUNT,
	 1,
	 1 ),
	 'S',
	 'O',
	 'V',
	 'F',
	 'R' ) THEN SUB_ACCOUNT ELSE v_HOUSE_CLIENT_FLAG END ) as v_SUB_ACCOUNT_CHK,
	 MNEMONIC || '_' || v_SUB_ACCOUNT_CHK as v_DSRO_SUB_ACC,
	 v_SUB_ACCOUNT_CHK as o_SUB_ACCOUNT,
	 v_DSRO_SUB_ACC as DSRO_CollateralAccountID,
	 ( CASE WHEN IN ( SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as DSRO_CollateralRequirement,
	 ( CASE WHEN SECURITY_TYPE = 'Triparty Collateral' THEN 'TripartyRepo' ELSE 'Security' END ) as v_AssetType,
	 v_AssetType as AssetType,
	 ( CASE WHEN v_AssetType = 'TripartyRepo' THEN MARKET_VALUE ELSE NULL END ) as TripartyRepo_Value,
	 ( CASE WHEN v_AssetType = 'TripartyRepo' THEN v_Ccy ELSE NULL END ) as TripartyRepo_Value_Ccy,
	 ( CASE WHEN v_AssetType = 'Security' THEN SECURITY_PRODUCT_CODE ELSE NULL END ) as SecurityIdentifier,
	 ( CASE WHEN v_AssetType = 'Security' THEN MARKET_VALUE ELSE NULL END ) as v_MarketValue,
	 v_MarketValue as MarketValue,
	 ( CASE WHEN v_AssetType = 'Security' THEN v_Ccy ELSE NULL END ) as MarketValue_Ccy,
	 ( CASE WHEN IN ( v_AssetType,
	 'Security',
	 'TripartyRepo' ) THEN MARKET_VALUE_POST_HAIRCUT ELSE NULL END ) as v_ValuePostHairCut,
	 v_ValuePostHairCut as ValuePostHairCut,
	 ( CASE WHEN IN ( v_AssetType,
	 'Security',
	 'TripartyRepo' ) THEN v_Ccy ELSE null END ) as ValuePostHairCut_Ccy,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 dsf_6.ID as FILE_GEN_DETAILS_ID,
	 BOE_SECURITY_TYPE_NAME as BOE_SECURITY_TYPE_NAME,
	 BOE_SECURITY_TYPE as BOE_SECURITY_TYPE,
	 ( CASE WHEN SECURITY_TYPE  !=  'Triparty Collateral' THEN 1 ELSE 0 END ) as BOE_SEC_TYPE_EI
From DSR_EXP_BNK_DSRO_SECOut as DSR_EXP_BNK_DSRO_SECOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = i_EXCHANGE_ID
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.ID = SECURITY_CURRENCY_ID
LEFT JOIN (
SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT FROM (   SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY SUB_ACCOUNT NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        VW_ML_CALYP_SUB_ACCOUNT )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.SUB_ACCOUNT = SUB_ACCOUNT
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_4.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_5.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_6
ON dsf_6.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_6.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
),

DSR_SC_mplt_DV_BOE_FIXML1Out as (
	/* transType: "Expression" */
Select 
	EXP_BNK_DSRO_SECOut2.ENABLE_IND as GenericIdentificationType1Code_T1_I_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.BOE_SECURITY_TYPE as I_SECURITY_TYPE,
	 EXP_BNK_DSRO_SECOut2.BOE_SECURITY_TYPE_NAME as I_SECURITY_TYPE_NAME,
	 EXP_BNK_DSRO_SECOut2.o_Ccy as ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as ZeroValCheck_T1_I_TripartyRepo_Value_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.SecurityIdentifier as PatternCheck_T1_I_ISIN_NC,
	 EXP_BNK_DSRO_SECOut2.ValuePostHairCut as AssetTypeCheck_T1_I_ValuePostHaircut,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as ActiveCurrencyCode_T8_I_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.DSRO_CollateralAccountID as CollateralReport_T1_ACCT_ID,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as CollateralReport_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.TripartyRepo_Value as AssetTypeCheck_T1_I_TripartyRepo_Value,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as AssetTypeCheck_T1_I_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.DSRO_WATERFALL_NM as I_WATERFALL_NM,
	 EXP_BNK_DSRO_SECOut2.ValuePostHairCut as ZeroValCheck_T1_I_ValuePostHaircut,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as I_WATERFALL_NM_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as PatternCheck_T1_I_ISIN_NC_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as COL_RPT_VAL_EN_IND,
	 EXP_BNK_DSRO_SECOut2.MarketValue as AssetTypeCheck_T1_I_MarketValue,
	 EXP_BNK_DSRO_SECOut2.EXCHANGE as COL_RPT_VAL_SERVICE,
	 EXP_BNK_DSRO_SECOut2.MNEMONIC as COL_RPT_VAL_MNE,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as ZeroValCheck_T1_I_MarketValue_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.MarketValue as ZeroValCheck_T1_I_MarketValue,
	 EXP_BNK_DSRO_SECOut2.o_SUB_ACCOUNT as COL_RPT_VAL_SUB_ACC,
	 EXP_BNK_DSRO_SECOut2.BOE_SEC_TYPE_EI as I_SECURITY_TYPE_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as I_WATERFALL_SRVC_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.DSRO_WATERFALL_SRVC as I_WATERFALL_SRVC,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as ZeroValCheck_T1_I_ValuePostHaircut_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.ENABLE_IND as CollateralRequirementType1Code_T1_I_ENABLE_IND,
	 EXP_BNK_DSRO_SECOut2.AssetType as AssetTypeCheck_T1_I_ASSET_TYPE,
	 EXP_BNK_DSRO_SECOut2.DSRO_CollateralRequirement as CollateralRequirementType1Code_T1_I_COLL_REQ_TYPE
From EXP_BNK_DSRO_SECOut as EXP_BNK_DSRO_SECOut),

SC_mplt_DV_BOE_FIXML1Out as (
	/* transType: "MAPPLET" */
Select 
	WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 ZeroValCheck_MARKETVALUE_ERROR_CODE as ZeroValCheck_MARKETVALUE_ERROR_CODE,
	 ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE as ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE,
	 ZeroValCheck_MARKETVALUE_I_COMB_INPUT as ZeroValCheck_MARKETVALUE_I_COMB_INPUT,
	 ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT as ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT,
	 o_ZeroValCheck_MARKETVALUE_FAIL as o_ZeroValCheck_MARKETVALUE_FAIL,
	 O_AccountIDScheme as DSRO_CollateralAccountIDType,
	 ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 Receiver_LEI as Receiver_LEI,
	 WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 Sender_Scheme_Name as Sender_Scheme_Name,
	 o_PatternCheck_ISIN_VALUE_NAME as o_PatternCheck_ISIN_VALUE_NAME,
	 PatternCheck_ISIN_VALUE_I_COMB_INPUT as PatternCheck_ISIN_VALUE_I_COMB_INPUT,
	 o_PatternCheck_ISIN_VALUE_VAL_FAIL as o_PatternCheck_ISIN_VALUE_VAL_FAIL,
	 SECURITY_TYPE_VAL as SECURITY_TYPE_VAL,
	 SECURITY_TYPE_NAME as SECURITY_TYPE_NAME,
	 SECURITY_TYPE_ERROR_CODE as SECURITY_TYPE_ERROR_CODE,
	 SECURITY_TYPE_COMB_INPUT as SECURITY_TYPE_COMB_INPUT,
	 SECURITY_TYPE_LKP_FAIL as SECURITY_TYPE_LKP_FAIL,
	 ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE as ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 AssetTypeCheck_T1_O_ASSET_TYPE as AssetTypeCheck_T1_O_ASSET_TYPE,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL as o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 o_ZeroValCheck_TRIPARTY_VALUE_NAME as o_ZeroValCheck_TRIPARTY_VALUE_NAME,
	 ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT as ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT,
	 WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL as o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL,
	 o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME as o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1 as ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1,
	 ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH as ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH,
	 ActiveCurrencyCode_T8_I_ENABLE_IND1 as ActiveCurrencyCode_T8_I_ENABLE_IND1,
	 ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT,
	 o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL,
	 Msg_Def_Id as Msg_Def_Id,
	 Receiver_Scheme_Name as Receiver_Scheme_Name,
	 Sender_LEI as Sender_LEI,
	 o_ZeroValCheck_MARKETVALUE_NAME as o_ZeroValCheck_MARKETVALUE_NAME,
	 o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME as o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME,
	 WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 PatternCheck_ISIN_VALUE_NAME_ERROR_CODE as PatternCheck_ISIN_VALUE_NAME_ERROR_CODE,
	 ENABLE_IND as GenericIdentificationType1Code_T1_I_ENABLE_IND,
	 BOE_SECURITY_TYPE as I_SECURITY_TYPE,
	 BOE_SECURITY_TYPE_NAME as I_SECURITY_TYPE_NAME,
	 o_Ccy as ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH,
	 ENABLE_IND as ZeroValCheck_T1_I_TripartyRepo_Value_ENABLE_IND,
	 SecurityIdentifier as PatternCheck_T1_I_ISIN_NC,
	 ValuePostHairCut as AssetTypeCheck_T1_I_ValuePostHaircut,
	 ENABLE_IND as ActiveCurrencyCode_T8_I_ENABLE_IND,
	 DSRO_CollateralAccountID as CollateralReport_T1_ACCT_ID,
	 ENABLE_IND as CollateralReport_ENABLE_IND,
	 TripartyRepo_Value as AssetTypeCheck_T1_I_TripartyRepo_Value,
	 ENABLE_IND as AssetTypeCheck_T1_I_ENABLE_IND,
	 DSRO_WATERFALL_NM as I_WATERFALL_NM,
	 ValuePostHairCut as ZeroValCheck_T1_I_ValuePostHaircut,
	 ENABLE_IND as I_WATERFALL_NM_ENABLE_IND,
	 ENABLE_IND as PatternCheck_T1_I_ISIN_NC_ENABLE_IND,
	 ENABLE_IND as COL_RPT_VAL_EN_IND,
	 MarketValue as AssetTypeCheck_T1_I_MarketValue,
	 EXCHANGE as COL_RPT_VAL_SERVICE,
	 MNEMONIC as COL_RPT_VAL_MNE,
	 ENABLE_IND as ZeroValCheck_T1_I_MarketValue_ENABLE_IND,
	 MarketValue as ZeroValCheck_T1_I_MarketValue,
	 o_SUB_ACCOUNT as COL_RPT_VAL_SUB_ACC,
	 BOE_SEC_TYPE_EI as I_SECURITY_TYPE_ENABLE_IND,
	 ENABLE_IND as I_WATERFALL_SRVC_ENABLE_IND,
	 DSRO_WATERFALL_SRVC as I_WATERFALL_SRVC,
	 ENABLE_IND as ZeroValCheck_T1_I_ValuePostHaircut_ENABLE_IND,
	 ENABLE_IND as CollateralRequirementType1Code_T1_I_ENABLE_IND,
	 AssetType as AssetTypeCheck_T1_I_ASSET_TYPE,
	 DSRO_CollateralRequirement as CollateralRequirementType1Code_T1_I_COLL_REQ_TYPE 
From DSR_SC_mplt_DV_BOE_FIXML1Out as DSR_SC_mplt_DV_BOE_FIXML1Out),

SC_mplt_DV_BOE_FIXML1_master as (
  Select
  	SC_mplt_DV_BOE_FIXML1Out.o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME as o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1 as ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1,
	 SC_mplt_DV_BOE_FIXML1Out.ActiveCurrencyCode_T8_I_ENABLE_IND1 as ActiveCurrencyCode_T8_I_ENABLE_IND1,
	 SC_mplt_DV_BOE_FIXML1Out.ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH as ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH,
	 SC_mplt_DV_BOE_FIXML1Out.Msg_Def_Id as Msg_Def_Id,
	 SC_mplt_DV_BOE_FIXML1Out.Receiver_Scheme_Name as Receiver_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML1Out.Receiver_LEI as Receiver_LEI,
	 SC_mplt_DV_BOE_FIXML1Out.Sender_Scheme_Name as Sender_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML1Out.Sender_LEI as Sender_LEI,
	 SC_mplt_DV_BOE_FIXML1Out.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.AssetTypeCheck_T1_O_ASSET_TYPE as AssetTypeCheck_T1_O_ASSET_TYPE,
	 SC_mplt_DV_BOE_FIXML1Out.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.O_AccountIDScheme as DSRO_CollateralAccountIDType,
	 SC_mplt_DV_BOE_FIXML1Out.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.o_ZeroValCheck_TRIPARTY_VALUE_NAME as o_ZeroValCheck_TRIPARTY_VALUE_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE as ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT as ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL as o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.o_ZeroValCheck_MARKETVALUE_NAME as o_ZeroValCheck_MARKETVALUE_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.ZeroValCheck_MARKETVALUE_ERROR_CODE as ZeroValCheck_MARKETVALUE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.ZeroValCheck_MARKETVALUE_I_COMB_INPUT as ZeroValCheck_MARKETVALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.o_ZeroValCheck_MARKETVALUE_FAIL as o_ZeroValCheck_MARKETVALUE_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME as o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE as ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT as ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL as o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.o_PatternCheck_ISIN_VALUE_NAME as o_PatternCheck_ISIN_VALUE_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.PatternCheck_ISIN_VALUE_NAME_ERROR_CODE as PatternCheck_ISIN_VALUE_NAME_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.PatternCheck_ISIN_VALUE_I_COMB_INPUT as PatternCheck_ISIN_VALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.o_PatternCheck_ISIN_VALUE_VAL_FAIL as o_PatternCheck_ISIN_VALUE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 SC_mplt_DV_BOE_FIXML1Out.SECURITY_TYPE_VAL as SECURITY_TYPE_VAL,
	 SC_mplt_DV_BOE_FIXML1Out.SECURITY_TYPE_NAME as SECURITY_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML1Out.SECURITY_TYPE_ERROR_CODE as SECURITY_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1Out.SECURITY_TYPE_COMB_INPUT as SECURITY_TYPE_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1Out.SECURITY_TYPE_LKP_FAIL as SECURITY_TYPE_LKP_FAIL
  From SC_mplt_DV_BOE_FIXML1Out as SC_mplt_DV_BOE_FIXML1Out
),

EXP_BNK_DSRO_SEC_details as (
  Select
  	EXP_BNK_DSRO_SECOut.ID as ID_DSROSEC,
	 EXP_BNK_DSRO_SECOut.TripartyRepo_Value_Ccy as TripartyRepo_Value_Ccy,
	 EXP_BNK_DSRO_SECOut.AssetType as AssetType,
	 EXP_BNK_DSRO_SECOut.SecurityIdentifier as SecurityIdentifier,
	 EXP_BNK_DSRO_SECOut.MarketValue_Ccy as MarketValue_Ccy,
	 EXP_BNK_DSRO_SECOut.FILENAME as FILENAME,
	 EXP_BNK_DSRO_SECOut.DSRO_CollateralAccountID as DSRO_CollateralAccountID,
	 EXP_BNK_DSRO_SECOut.DSRO_CollateralRequirement as DSRO_CollateralRequirement,
	 EXP_BNK_DSRO_SECOut.ValuePostHairCut_Ccy as ValuePostHairCut_Ccy
  From EXP_BNK_DSRO_SECOut as EXP_BNK_DSRO_SECOut
),
dsJoiner_EXP_DSRO_SEC0Out as (
	/* transType: "Joiner" */
Select 
	SC_mplt_DV_BOE_FIXML1_master.o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME as o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1 as ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1,
	 SC_mplt_DV_BOE_FIXML1_master.ActiveCurrencyCode_T8_I_ENABLE_IND1 as ActiveCurrencyCode_T8_I_ENABLE_IND1,
	 SC_mplt_DV_BOE_FIXML1_master.ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH as ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH,
	 EXP_BNK_DSRO_SECOut1.ID as ID_DSROSEC,
	 SC_mplt_DV_BOE_FIXML1_master.Msg_Def_Id as Msg_Def_Id,
	 SC_mplt_DV_BOE_FIXML1_master.Receiver_Scheme_Name as Receiver_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML1_master.Receiver_LEI as Receiver_LEI,
	 SC_mplt_DV_BOE_FIXML1_master.Sender_Scheme_Name as Sender_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML1_master.Sender_LEI as Sender_LEI,
	 SC_mplt_DV_BOE_FIXML1_master.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.AssetTypeCheck_T1_O_ASSET_TYPE as AssetTypeCheck_T1_O_ASSET_TYPE,
	 SC_mplt_DV_BOE_FIXML1_master.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 EXP_BNK_DSRO_SECOut1.TripartyRepo_Value_Ccy as TripartyRepo_Value_Ccy,
	 EXP_BNK_DSRO_SECOut1.AssetType as AssetType,
	 EXP_BNK_DSRO_SECOut1.SecurityIdentifier as SecurityIdentifier,
	 EXP_BNK_DSRO_SECOut1.MarketValue_Ccy as MarketValue_Ccy,
	 EXP_BNK_DSRO_SECOut1.FILENAME as FILENAME,
	 EXP_BNK_DSRO_SECOut1.DSRO_CollateralAccountID as DSRO_CollateralAccountID,
	 SC_mplt_DV_BOE_FIXML1_master.DSRO_CollateralAccountIDType as DSRO_CollateralAccountIDType,
	 EXP_BNK_DSRO_SECOut1.DSRO_CollateralRequirement as DSRO_CollateralRequirement,
	 EXP_BNK_DSRO_SECOut1.ValuePostHairCut_Ccy as ValuePostHairCut_Ccy,
	 SC_mplt_DV_BOE_FIXML1_master.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.o_ZeroValCheck_TRIPARTY_VALUE_NAME as o_ZeroValCheck_TRIPARTY_VALUE_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE as ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT as ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL as o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.o_ZeroValCheck_MARKETVALUE_NAME as o_ZeroValCheck_MARKETVALUE_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.ZeroValCheck_MARKETVALUE_ERROR_CODE as ZeroValCheck_MARKETVALUE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.ZeroValCheck_MARKETVALUE_I_COMB_INPUT as ZeroValCheck_MARKETVALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.o_ZeroValCheck_MARKETVALUE_FAIL as o_ZeroValCheck_MARKETVALUE_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME as o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE as ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT as ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL as o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.o_PatternCheck_ISIN_VALUE_NAME as o_PatternCheck_ISIN_VALUE_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.PatternCheck_ISIN_VALUE_NAME_ERROR_CODE as PatternCheck_ISIN_VALUE_NAME_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.PatternCheck_ISIN_VALUE_I_COMB_INPUT as PatternCheck_ISIN_VALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.o_PatternCheck_ISIN_VALUE_VAL_FAIL as o_PatternCheck_ISIN_VALUE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 SC_mplt_DV_BOE_FIXML1_master.SECURITY_TYPE_VAL as SECURITY_TYPE_VAL,
	 SC_mplt_DV_BOE_FIXML1_master.SECURITY_TYPE_NAME as SECURITY_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML1_master.SECURITY_TYPE_ERROR_CODE as SECURITY_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML1_master.SECURITY_TYPE_COMB_INPUT as SECURITY_TYPE_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML1_master.SECURITY_TYPE_LKP_FAIL as SECURITY_TYPE_LKP_FAIL,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
SC_mplt_DV_BOE_FIXML1_master as SC_mplt_DV_BOE_FIXML1_master inner JOIN EXP_BNK_DSRO_SECOut1 as EXP_BNK_DSRO_SECOut1 
ON
EXP_BNK_DSRO_SECOut1.jkey = SC_mplt_DV_BOE_FIXML1_master.jkey 
),

EXP_DSRO_SECOut1 as (
	/* transType: "Expression" */
Select 
	o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME as o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME,
	 ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE,
	 ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT,
	 o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL,
	 ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1 as ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1,
	 ActiveCurrencyCode_T8_I_ENABLE_IND1 as ActiveCurrencyCode_T8_I_ENABLE_IND1,
	 ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH as ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH,
	 ID_DSROSEC as ID_DSROSEC,
	 Msg_Def_Id as Msg_Def_Id,
	 Receiver_Scheme_Name as Receiver_Scheme_Name,
	 Receiver_LEI as Receiver_LEI,
	 Sender_Scheme_Name as Sender_Scheme_Name,
	 Sender_LEI as Sender_LEI,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 AssetTypeCheck_T1_O_ASSET_TYPE as AssetTypeCheck_T1_O_ASSET_TYPE,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 TripartyRepo_Value_Ccy as TripartyRepo_Value_Ccy,
	 AssetType as AssetType,
	 SecurityIdentifier as SecurityIdentifier,
	 MarketValue_Ccy as MarketValue_Ccy,
	 FILENAME as FILENAME,
	 DSRO_CollateralAccountID as DSRO_CollateralAccountID,
	 DSRO_CollateralAccountIDType as DSRO_CollateralAccountIDType,
	 DSRO_CollateralRequirement as DSRO_CollateralRequirement,
	 ValuePostHairCut_Ccy as ValuePostHairCut_Ccy,
	 CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 CollateralReport_T1_O_ACCT_ID as CollateralReport_T1_O_ACCT_ID,
	 o_ZeroValCheck_TRIPARTY_VALUE_NAME as o_ZeroValCheck_TRIPARTY_VALUE_NAME,
	 ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE as ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE,
	 ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT as ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT,
	 o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL as o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL,
	 o_ZeroValCheck_MARKETVALUE_NAME as o_ZeroValCheck_MARKETVALUE_NAME,
	 ZeroValCheck_MARKETVALUE_ERROR_CODE as ZeroValCheck_MARKETVALUE_ERROR_CODE,
	 ZeroValCheck_MARKETVALUE_I_COMB_INPUT as ZeroValCheck_MARKETVALUE_I_COMB_INPUT,
	 o_ZeroValCheck_MARKETVALUE_FAIL as o_ZeroValCheck_MARKETVALUE_FAIL,
	 o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME as o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME,
	 ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE as ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE,
	 ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT as ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT,
	 o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL as o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL,
	 o_PatternCheck_ISIN_VALUE_NAME as o_PatternCheck_ISIN_VALUE_NAME,
	 PatternCheck_ISIN_VALUE_NAME_ERROR_CODE as PatternCheck_ISIN_VALUE_NAME_ERROR_CODE,
	 PatternCheck_ISIN_VALUE_I_COMB_INPUT as PatternCheck_ISIN_VALUE_I_COMB_INPUT,
	 o_PatternCheck_ISIN_VALUE_VAL_FAIL as o_PatternCheck_ISIN_VALUE_VAL_FAIL,
	 WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 SECURITY_TYPE_VAL as SECURITY_TYPE_VAL,
	 SECURITY_TYPE_NAME as SECURITY_TYPE_NAME,
	 SECURITY_TYPE_ERROR_CODE as SECURITY_TYPE_ERROR_CODE,
	 SECURITY_TYPE_COMB_INPUT as SECURITY_TYPE_COMB_INPUT,
	 SECURITY_TYPE_LKP_FAIL as SECURITY_TYPE_LKP_FAIL,
	 ( CASE WHEN o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL = 1 OR o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL = 1 OR o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL = 1 OR o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL = 1 OR o_CollateralReportVal_T1_VAL_FAIL = 1 OR o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL = 1 OR o_PatternCheck_ISIN_VALUE_VAL_FAIL = 1 OR WATERFALL_NM_FAIL = 1 OR WATERFALL_SRVC_FAIL = 1 OR o_ZeroValCheck_MARKETVALUE_FAIL = 1 OR o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL OR SECURITY_TYPE_LKP_FAIL = 1 THEN 'Y' ELSE 'N' END ) as ERROR_IND,
	 '{{ var("PMWorkflowName") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName") }}' as MAPPING_NAME,
	 '{{ var("BATCH_ID") }}' as o_BATCH_ID,
	 TO_DATE ( LTRIM ( RTRIM ( '{{ var("BATCH_BUSINESS_DATE") }}' ) ),
	 'YYYYMMDD' ) as o_BATCH_BUSINESS_DATE
From dsJoiner_EXP_DSRO_SEC0Out as dsJoiner_EXP_DSRO_SEC0Out),

EXP_BNK_DSRO_SEC_master as (
  Select
  	EXP_BNK_DSRO_SECOut.FILE_GEN_DETAILS_ID as FILE_DATE_ID
  From EXP_BNK_DSRO_SECOut as EXP_BNK_DSRO_SECOut
),

EXP_DSRO_SEC_details as (
  Select
  	EXP_DSRO_SECOut.ZeroValCheck_MARKETVALUE_ERROR_CODE as ZeroValCheck_MARKETVALUE_ERROR_CODE,
	 EXP_DSRO_SECOut.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 EXP_DSRO_SECOut.o_ZeroValCheck_MARKETVALUE_FAIL as o_ZeroValCheck_MARKETVALUE_FAIL,
	 EXP_DSRO_SECOut.ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE as ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE,
	 EXP_DSRO_SECOut.ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT as ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT,
	 EXP_DSRO_SECOut.ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE,
	 EXP_DSRO_SECOut.o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL as o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL,
	 EXP_DSRO_SECOut.o_ZeroValCheck_TRIPARTY_VALUE_NAME as o_ZeroValCheck_TRIPARTY_VALUE_NAME,
	 EXP_DSRO_SECOut.ID_DSROSEC as ID_NONCASH,
	 EXP_DSRO_SECOut.o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL as o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL,
	 EXP_DSRO_SECOut.o_PatternCheck_ISIN_VALUE_NAME as o_PatternCheck_ISIN_VALUE_NAME,
	 EXP_DSRO_SECOut.ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT as ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT,
	 EXP_DSRO_SECOut.FILENAME as FILENAME,
	 EXP_DSRO_SECOut.PatternCheck_ISIN_VALUE_I_COMB_INPUT as PatternCheck_ISIN_VALUE_I_COMB_INPUT,
	 EXP_DSRO_SECOut.ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE as ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE,
	 EXP_DSRO_SECOut.PatternCheck_ISIN_VALUE_NAME_ERROR_CODE as PatternCheck_ISIN_VALUE_NAME_ERROR_CODE,
	 EXP_DSRO_SECOut.o_PatternCheck_ISIN_VALUE_VAL_FAIL as o_PatternCheck_ISIN_VALUE_VAL_FAIL,
	 EXP_DSRO_SECOut.MAPPING_NAME as MAPPING_NAME,
	 EXP_DSRO_SECOut.o_BATCH_ID as o_BATCH_ID,
	 EXP_DSRO_SECOut.ERROR_IND as ERROR_IND,
	 EXP_DSRO_SECOut.o_BATCH_BUSINESS_DATE as o_BATCH_BUSINESS_DATE,
	 EXP_DSRO_SECOut.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 EXP_DSRO_SECOut.SECURITY_TYPE_NAME as SECURITY_TYPE_NAME,
	 EXP_DSRO_SECOut.SECURITY_TYPE_ERROR_CODE as SECURITY_TYPE_ERROR_CODE,
	 EXP_DSRO_SECOut.SECURITY_TYPE_COMB_INPUT as SECURITY_TYPE_COMB_INPUT,
	 EXP_DSRO_SECOut.SECURITY_TYPE_LKP_FAIL as SECURITY_TYPE_LKP_FAIL,
	 EXP_DSRO_SECOut.o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME as o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME,
	 EXP_DSRO_SECOut.ActiveCurrencyCode_T8_I_ENABLE_IND1 as ActiveCurrencyCode_T8_I_ENABLE_IND1,
	 EXP_DSRO_SECOut.o_ZeroValCheck_MARKETVALUE_NAME as o_ZeroValCheck_MARKETVALUE_NAME,
	 EXP_DSRO_SECOut.ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT,
	 EXP_DSRO_SECOut.o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL,
	 EXP_DSRO_SECOut.ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1 as ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1,
	 EXP_DSRO_SECOut.ZeroValCheck_MARKETVALUE_I_COMB_INPUT as ZeroValCheck_MARKETVALUE_I_COMB_INPUT,
	 EXP_DSRO_SECOut.o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME as o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME,
	 EXP_DSRO_SECOut.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 EXP_DSRO_SECOut.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 EXP_DSRO_SECOut.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 EXP_DSRO_SECOut.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 EXP_DSRO_SECOut.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 EXP_DSRO_SECOut.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 EXP_DSRO_SECOut.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 EXP_DSRO_SECOut.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 EXP_DSRO_SECOut.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 EXP_DSRO_SECOut.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 EXP_DSRO_SECOut.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 EXP_DSRO_SECOut.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 EXP_DSRO_SECOut.ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH as ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH,
	 EXP_DSRO_SECOut.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_DSRO_SECOut.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 EXP_DSRO_SECOut.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 EXP_DSRO_SECOut.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 EXP_DSRO_SECOut.AssetTypeCheck_T1_O_ASSET_TYPE as AssetTypeCheck_T1_O_ASSET_TYPE,
	 EXP_DSRO_SECOut.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 EXP_DSRO_SECOut.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 EXP_DSRO_SECOut.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 EXP_DSRO_SECOut.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 EXP_DSRO_SECOut.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 EXP_DSRO_SECOut.CollateralReport_T1_O_ACCT_ID as CollateralReport_T1_O_ACCT_ID,
	 EXP_DSRO_SECOut.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 EXP_DSRO_SECOut.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT
  From EXP_DSRO_SECOut as EXP_DSRO_SECOut
),
dsJoiner_FIL_DSROSEC_ERR_RECS0Out as (
	/* transType: "Joiner" */
Select 
	EXP_DSRO_SEC_details.ZeroValCheck_MARKETVALUE_ERROR_CODE as ZeroValCheck_MARKETVALUE_ERROR_CODE,
	 EXP_DSRO_SEC_details.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 EXP_DSRO_SEC_details.o_ZeroValCheck_MARKETVALUE_FAIL as o_ZeroValCheck_MARKETVALUE_FAIL,
	 EXP_DSRO_SEC_details.ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE as ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE,
	 EXP_DSRO_SEC_details.ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT as ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT,
	 EXP_DSRO_SEC_details.ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE,
	 EXP_DSRO_SEC_details.o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL as o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL,
	 EXP_DSRO_SEC_details.o_ZeroValCheck_TRIPARTY_VALUE_NAME as o_ZeroValCheck_TRIPARTY_VALUE_NAME,
	 EXP_DSRO_SEC_details.ID_NONCASH as ID_NONCASH,
	 EXP_DSRO_SEC_details.o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL as o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL,
	 EXP_DSRO_SEC_details.o_PatternCheck_ISIN_VALUE_NAME as o_PatternCheck_ISIN_VALUE_NAME,
	 EXP_DSRO_SEC_details.ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT as ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT,
	 EXP_DSRO_SEC_details.FILENAME as FILENAME,
	 EXP_DSRO_SEC_details.PatternCheck_ISIN_VALUE_I_COMB_INPUT as PatternCheck_ISIN_VALUE_I_COMB_INPUT,
	 EXP_DSRO_SEC_details.ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE as ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE,
	 EXP_DSRO_SEC_details.PatternCheck_ISIN_VALUE_NAME_ERROR_CODE as PatternCheck_ISIN_VALUE_NAME_ERROR_CODE,
	 EXP_DSRO_SEC_details.o_PatternCheck_ISIN_VALUE_VAL_FAIL as o_PatternCheck_ISIN_VALUE_VAL_FAIL,
	 EXP_DSRO_SEC_details.MAPPING_NAME as MAPPING_NAME,
	 EXP_DSRO_SEC_details.o_BATCH_ID as o_BATCH_ID,
	 EXP_DSRO_SEC_details.ERROR_IND as ERROR_IND,
	 EXP_DSRO_SEC_details.o_BATCH_BUSINESS_DATE as o_BATCH_BUSINESS_DATE,
	 EXP_DSRO_SEC_details.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 EXP_DSRO_SEC_details.SECURITY_TYPE_NAME as SECURITY_TYPE_NAME,
	 EXP_DSRO_SEC_details.SECURITY_TYPE_ERROR_CODE as SECURITY_TYPE_ERROR_CODE,
	 EXP_DSRO_SEC_details.SECURITY_TYPE_COMB_INPUT as SECURITY_TYPE_COMB_INPUT,
	 EXP_DSRO_SEC_details.SECURITY_TYPE_LKP_FAIL as SECURITY_TYPE_LKP_FAIL,
	 EXP_DSRO_SEC_details.o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME as o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME,
	 EXP_DSRO_SEC_details.ActiveCurrencyCode_T8_I_ENABLE_IND1 as ActiveCurrencyCode_T8_I_ENABLE_IND1,
	 EXP_DSRO_SEC_details.o_ZeroValCheck_MARKETVALUE_NAME as o_ZeroValCheck_MARKETVALUE_NAME,
	 EXP_DSRO_SEC_details.ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT,
	 EXP_DSRO_SEC_details.o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL,
	 EXP_DSRO_SEC_details.ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1 as ActiveCurrencyCode_T8_I_CURR_MNE_NONCASH1,
	 EXP_DSRO_SEC_details.ZeroValCheck_MARKETVALUE_I_COMB_INPUT as ZeroValCheck_MARKETVALUE_I_COMB_INPUT,
	 EXP_DSRO_SEC_details.o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME as o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME,
	 EXP_DSRO_SEC_details.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 EXP_DSRO_SEC_details.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 EXP_DSRO_SEC_details.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 EXP_DSRO_SEC_details.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 EXP_DSRO_SEC_details.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 EXP_DSRO_SEC_details.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 EXP_DSRO_SEC_details.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 EXP_DSRO_SEC_details.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 EXP_DSRO_SEC_details.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 EXP_DSRO_SEC_details.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 EXP_DSRO_SEC_details.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 EXP_DSRO_SEC_details.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 EXP_DSRO_SEC_details.ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH as ActiveCurrencyCode_T8_O_CURR_MNE_NONCASH,
	 EXP_DSRO_SEC_details.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_DSRO_SEC_details.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 EXP_DSRO_SEC_details.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 EXP_DSRO_SEC_details.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 EXP_DSRO_SEC_details.AssetTypeCheck_T1_O_ASSET_TYPE as AssetTypeCheck_T1_O_ASSET_TYPE,
	 EXP_DSRO_SEC_details.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 EXP_DSRO_SEC_details.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 EXP_DSRO_SEC_details.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 EXP_DSRO_SEC_details.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 EXP_DSRO_SEC_details.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 EXP_DSRO_SEC_details.CollateralReport_T1_O_ACCT_ID as CollateralReport_T1_O_ACCT_ID,
	 EXP_DSRO_SEC_details.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 EXP_DSRO_SEC_details.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 EXP_BNK_DSRO_SEC_master.FILE_DATE_ID as FILE_DATE_ID,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXP_BNK_DSRO_SECOut3 as EXP_BNK_DSRO_SECOut3 inner JOIN EXP_DSRO_SECOut1 as EXP_DSRO_SECOut1 
ON
EXP_DSRO_SECOut1.jkey = EXP_BNK_DSRO_SECOut3.jkey 
),

DSR_SC_mplt_DV_PROCESS_ERROR_DETAILS1Out as (
	/* transType: "Expression" */
Select 
	FIL_DSROSEC_ERR_RECSOut.o_PatternCheck_ISIN_VALUE_VAL_FAIL as INPUT_ERROR_SEVERITY_7,
	 FIL_DSROSEC_ERR_RECSOut.SECURITY_TYPE_LKP_FAIL as INPUT_ERROR_SEVERITY_12,
	 FIL_DSROSEC_ERR_RECSOut.ID_NONCASH as INPUT_REFERENCE_RECORD_ID,
	 FIL_DSROSEC_ERR_RECSOut.WATERFALL_SRVC_FAIL as INPUT_ERROR_SEVERITY_9,
	 FIL_DSROSEC_ERR_RECSOut.MAPPING_NAME as INPUT_MAPPING_NAME,
	 FIL_DSROSEC_ERR_RECSOut.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as INPUT_ERROR_CODE_2,
	 FIL_DSROSEC_ERR_RECSOut.ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE as INPUT_ERROR_CODE_1,
	 FIL_DSROSEC_ERR_RECSOut.ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_1,
	 FIL_DSROSEC_ERR_RECSOut.o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL as INPUT_ERROR_SEVERITY_1,
	 FIL_DSROSEC_ERR_RECSOut.o_AssetTypeCheck_ASSET_TYPE_NAME as INPUT_ATTRIBUTE_NAME_2,
	 FIL_DSROSEC_ERR_RECSOut.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_2,
	 FIL_DSROSEC_ERR_RECSOut.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_2,
	 FIL_DSROSEC_ERR_RECSOut.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as INPUT_ERROR_CODE_3,
	 FIL_DSROSEC_ERR_RECSOut.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as INPUT_ATTRIBUTE_NAME_3,
	 FIL_DSROSEC_ERR_RECSOut.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_3,
	 FIL_DSROSEC_ERR_RECSOut.o_ZeroValCheck_MARKETVALUE_NAME as INPUT_ATTRIBUTE_NAME_10,
	 FIL_DSROSEC_ERR_RECSOut.ZeroValCheck_MARKETVALUE_ERROR_CODE as INPUT_ERROR_CODE_10,
	 FIL_DSROSEC_ERR_RECSOut.ZeroValCheck_MARKETVALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_10,
	 FIL_DSROSEC_ERR_RECSOut.o_ZeroValCheck_MARKETVALUE_FAIL as INPUT_ERROR_SEVERITY_10,
	 FIL_DSROSEC_ERR_RECSOut.o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME as INPUT_ATTRIBUTE_NAME_11,
	 FIL_DSROSEC_ERR_RECSOut.ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_11,
	 FIL_DSROSEC_ERR_RECSOut.SECURITY_TYPE_NAME as INPUT_ATTRIBUTE_NAME_12,
	 FIL_DSROSEC_ERR_RECSOut.ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE as INPUT_ERROR_CODE_11,
	 FIL_DSROSEC_ERR_RECSOut.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_3,
	 FIL_DSROSEC_ERR_RECSOut.o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL as INPUT_ERROR_SEVERITY_11,
	 FIL_DSROSEC_ERR_RECSOut.SECURITY_TYPE_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_12,
	 FIL_DSROSEC_ERR_RECSOut.SECURITY_TYPE_ERROR_CODE as INPUT_ERROR_CODE_12,
	 FIL_DSROSEC_ERR_RECSOut.o_BATCH_BUSINESS_DATE as INPUT_BATCH_BUSINESS_DATE,
	 FIL_DSROSEC_ERR_RECSOut.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_4,
	 FIL_DSROSEC_ERR_RECSOut.CollateralReportVal_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_5,
	 FIL_DSROSEC_ERR_RECSOut.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as INPUT_ERROR_CODE_4,
	 FIL_DSROSEC_ERR_RECSOut.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as INPUT_ATTRIBUTE_NAME_4,
	 FIL_DSROSEC_ERR_RECSOut.o_CollateralReportVal_T1_VAL_FAIL as INPUT_ERROR_SEVERITY_5,
	 FIL_DSROSEC_ERR_RECSOut.o_BATCH_ID as INPUT_BATCH_ID,
	 FIL_DSROSEC_ERR_RECSOut.FILENAME as INPUT_TARGET_NAME,
	 FIL_DSROSEC_ERR_RECSOut.WORKFLOW_NAME as INPUT_WORKFLOW_NAME,
	 FIL_DSROSEC_ERR_RECSOut.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_4,
	 FIL_DSROSEC_ERR_RECSOut.o_ZeroValCheck_TRIPARTY_VALUE_NAME as INPUT_ATTRIBUTE_NAME_6,
	 FIL_DSROSEC_ERR_RECSOut.o_PatternCheck_ISIN_VALUE_NAME as INPUT_ATTRIBUTE_NAME_7,
	 FIL_DSROSEC_ERR_RECSOut.CollateralReportVal_ERROR_CODE as INPUT_ERROR_CODE_5,
	 FIL_DSROSEC_ERR_RECSOut.o_CollateralReportVal_NAME as INPUT_ATTRIBUTE_NAME_5,
	 FIL_DSROSEC_ERR_RECSOut.ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_6,
	 FIL_DSROSEC_ERR_RECSOut.PatternCheck_ISIN_VALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_7,
	 FIL_DSROSEC_ERR_RECSOut.ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE as INPUT_ERROR_CODE_6,
	 FIL_DSROSEC_ERR_RECSOut.o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL as INPUT_ERROR_SEVERITY_6,
	 FIL_DSROSEC_ERR_RECSOut.WATERFALL_NM_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_8,
	 FIL_DSROSEC_ERR_RECSOut.PatternCheck_ISIN_VALUE_NAME_ERROR_CODE as INPUT_ERROR_CODE_7,
	 FIL_DSROSEC_ERR_RECSOut.WATERFALL_NM_NAME as INPUT_ATTRIBUTE_NAME_8,
	 FIL_DSROSEC_ERR_RECSOut.WATERFALL_NM_ERROR_CODE as INPUT_ERROR_CODE_8,
	 FIL_DSROSEC_ERR_RECSOut.WATERFALL_NM_FAIL as INPUT_ERROR_SEVERITY_8,
	 FIL_DSROSEC_ERR_RECSOut.WATERFALL_SRVC_NAME as INPUT_ATTRIBUTE_NAME_9,
	 FIL_DSROSEC_ERR_RECSOut.FILE_DATE_ID as INPUT_BATCH_DETAILS_ID,
	 FIL_DSROSEC_ERR_RECSOut.WATERFALL_SRVC_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_9,
	 FIL_DSROSEC_ERR_RECSOut.WATERFALL_SRVC_ERROR_CODE as INPUT_ERROR_CODE_9,
	 FIL_DSROSEC_ERR_RECSOut.o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME as INPUT_ATTRIBUTE_NAME_1 
From dsJoiner_FIL_DSROSEC_ERR_RECS0Out as dsJoiner_FIL_DSROSEC_ERR_RECS0Out Where ERROR_IND = 'N'),

SC_mplt_DV_PROCESS_ERROR_DETAILS1Out as (
	/* transType: "MAPPLET" */
Select 
	REFERENCE_BATCH_ID as REFERENCE_BATCH_ID,
	 ERROR_CODE as ERROR_CODE,
	 REFERENCE_BUSINESS_KEY as REFERENCE_BUSINESS_KEY,
	 ID as ID,
	 REFERENCE_SUB_PROCESS as REFERENCE_SUB_PROCESS,
	 REFERENCE_RECORD_ID as REFERENCE_RECORD_ID,
	 ERROR_SEVERITY as ERROR_SEVERITY,
	 REFERENCE_PROCESS as REFERENCE_PROCESS,
	 ADDITIONAL_DETAILS as ADDITIONAL_DETAILS,
	 REFERENCE_ATTRIBUTE_VALUE as REFERENCE_ATTRIBUTE_VALUE,
	 PROCESS_DATE as PROCESS_DATE,
	 REFERENCE_BATCH_DETAILS_ID as REFERENCE_BATCH_DETAILS_ID,
	 REFERENCE_ATTRIBUTE_NAME as REFERENCE_ATTRIBUTE_NAME,
	 REFERENCE_TARGET_NAME as REFERENCE_TARGET_NAME,
	 o_PatternCheck_ISIN_VALUE_VAL_FAIL as INPUT_ERROR_SEVERITY_7,
	 SECURITY_TYPE_LKP_FAIL as INPUT_ERROR_SEVERITY_12,
	 ID_NONCASH as INPUT_REFERENCE_RECORD_ID,
	 WATERFALL_SRVC_FAIL as INPUT_ERROR_SEVERITY_9,
	 MAPPING_NAME as INPUT_MAPPING_NAME,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as INPUT_ERROR_CODE_2,
	 ActiveCurrencyCode_CURR_MNE_NONCASH_ERROR_CODE as INPUT_ERROR_CODE_1,
	 ActiveCurrencyCode_CURR_MNE_T8_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_1,
	 o_ActiveCurrencyCode_T8_CURR_MNE_VAL_FAIL as INPUT_ERROR_SEVERITY_1,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as INPUT_ATTRIBUTE_NAME_2,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_2,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_2,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as INPUT_ERROR_CODE_3,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as INPUT_ATTRIBUTE_NAME_3,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_3,
	 o_ZeroValCheck_MARKETVALUE_NAME as INPUT_ATTRIBUTE_NAME_10,
	 ZeroValCheck_MARKETVALUE_ERROR_CODE as INPUT_ERROR_CODE_10,
	 ZeroValCheck_MARKETVALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_10,
	 o_ZeroValCheck_MARKETVALUE_FAIL as INPUT_ERROR_SEVERITY_10,
	 o_ZeroValCheck_VALUEPOSTHAIRCUT_NAME as INPUT_ATTRIBUTE_NAME_11,
	 ZeroValCheck_VALUEPOSTHAIRCUT_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_11,
	 SECURITY_TYPE_NAME as INPUT_ATTRIBUTE_NAME_12,
	 ZeroValCheck_VALUEPOSTHAIRCUT_ERROR_CODE as INPUT_ERROR_CODE_11,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_3,
	 o_ZeroValCheck_VALUEPOSTHAIRCUT_VAL_FAIL as INPUT_ERROR_SEVERITY_11,
	 SECURITY_TYPE_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_12,
	 SECURITY_TYPE_ERROR_CODE as INPUT_ERROR_CODE_12,
	 o_BATCH_BUSINESS_DATE as INPUT_BATCH_BUSINESS_DATE,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_4,
	 CollateralReportVal_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_5,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as INPUT_ERROR_CODE_4,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as INPUT_ATTRIBUTE_NAME_4,
	 o_CollateralReportVal_T1_VAL_FAIL as INPUT_ERROR_SEVERITY_5,
	 o_BATCH_ID as INPUT_BATCH_ID,
	 FILENAME as INPUT_TARGET_NAME,
	 WORKFLOW_NAME as INPUT_WORKFLOW_NAME,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_4,
	 o_ZeroValCheck_TRIPARTY_VALUE_NAME as INPUT_ATTRIBUTE_NAME_6,
	 o_PatternCheck_ISIN_VALUE_NAME as INPUT_ATTRIBUTE_NAME_7,
	 CollateralReportVal_ERROR_CODE as INPUT_ERROR_CODE_5,
	 o_CollateralReportVal_NAME as INPUT_ATTRIBUTE_NAME_5,
	 ZeroValCheck_TRIPARTY_VALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_6,
	 PatternCheck_ISIN_VALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_7,
	 ZeroValCheck_TRIPARTY_VALUE_NAME_ERROR_CODE as INPUT_ERROR_CODE_6,
	 o_ZeroValCheck_TRIPARTY_VALUE_VAL_FAIL as INPUT_ERROR_SEVERITY_6,
	 WATERFALL_NM_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_8,
	 PatternCheck_ISIN_VALUE_NAME_ERROR_CODE as INPUT_ERROR_CODE_7,
	 WATERFALL_NM_NAME as INPUT_ATTRIBUTE_NAME_8,
	 WATERFALL_NM_ERROR_CODE as INPUT_ERROR_CODE_8,
	 WATERFALL_NM_FAIL as INPUT_ERROR_SEVERITY_8,
	 WATERFALL_SRVC_NAME as INPUT_ATTRIBUTE_NAME_9,
	 FILE_DATE_ID as INPUT_BATCH_DETAILS_ID,
	 WATERFALL_SRVC_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_9,
	 WATERFALL_SRVC_ERROR_CODE as INPUT_ERROR_CODE_9,
	 o_ActiveCurrencyCode_CURR_MNE_NONCASH_NAME as INPUT_ATTRIBUTE_NAME_1 
From DSR_SC_mplt_DV_PROCESS_ERROR_DETAILS1Out as DSR_SC_mplt_DV_PROCESS_ERROR_DETAILS1Out)

Select 
	ID as ID,
	PROCESS_DATE as PROCESS_DATE,
	REFERENCE_BATCH_ID as REFERENCE_BATCH_ID,
	REFERENCE_PROCESS as REFERENCE_PROCESS,
	REFERENCE_SUB_PROCESS as REFERENCE_SUB_PROCESS,
	REFERENCE_TARGET_NAME as REFERENCE_TARGET_NAME,
	REFERENCE_RECORD_ID as REFERENCE_RECORD_ID,
	REFERENCE_BUSINESS_KEY as REFERENCE_BUSINESS_KEY,
	REFERENCE_ATTRIBUTE_NAME as REFERENCE_ATTRIBUTE_NAME,
	REFERENCE_ATTRIBUTE_VALUE as REFERENCE_ATTRIBUTE_VALUE,
	ERROR_CODE as ERROR_CODE,
	ERROR_SEVERITY as ERROR_SEVERITY,
	ADDITIONAL_DETAILS as ADDITIONAL_DETAILS,
	REFERENCE_BATCH_DETAILS_ID as REFERENCE_BATCH_DETAILS_ID 
From SC_mplt_DV_PROCESS_ERROR_DETAILS1Out as SC_mplt_DV_PROCESS_ERROR_DETAILS1Out