/* Transformation Name ==>SC_PROCESS_ERROR_DETAILS_BNKLIAB ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='PROCESS_ERROR_DETAILS',
		schema='EMIR_SHARED',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_SC_RR_BNK_LIABILITY_COVER_FACTOut as (
	/* SubQuery from Source ==>SQ_SQ_SC_RR_BNK_LIABILITY_COVER_FACT */
/* transType: "Source" */
Select 
ID,
MNEMONIC,
SUB_ACCOUNT,
EXCHANGE,
EXCHANGE_ID,
ASSET_CURRENCY_ID,
ASSET_AMOUNT,
ENTITY_ID
 from 
(SELECT
    BNKLIAB.ID,
    BNKLIAB.MNEMONIC,
    BNKLIAB.SUB_ACCOUNT,
    EXCHN.EXCHANGE_MNEMONIC as EXCHANGE,
    BNKLIAB.EXCHANGE_ID as EXCHANGE_ID,
    BNKLIAB.ASSET_CURRENCY_ID,
    BNKLIAB.ASSET_AMOUNT,
    BNKLIAB.ENTITY_ID
 FROM
    RR_BNK_LIABILITY_COVER_FACT as BNKLIAB
 JOIN
  BATCH_MASTER as BM
 ON
  BNKLIAB.BATCH_ID= BM.BATCH_ID
 JOIN
  DW_MART.EXCHANGE_DIM as EXCHN
 ON
  BNKLIAB.EXCHANGE_ID= EXCHN.ID
 JOIN
  DW_MART.VW_ML_CALYP_SUB_ACCOUNT as SACT
 ON
  BNKLIAB.SUB_ACCOUNT= SACT.SUB_ACCOUNT
 WHERE  
  BM.BATCH_FEED_INFO LIKE '%BNK%' AND 
  BM.BATCH_STATUS= 'C' AND 
  BM.BATCH_BUSINESS_FROM_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  ( SYSDATE BETWEEN EXCHN.EFFECTIVE_DATE AND NVL ( EXCHN.EXPIRATION_DATE,TO_DATE ( '31-DEC-2099','DD-MON-YYYY') ) ) AND 
  EXCHN.ENTITY= 'LTD' AND 
   BNKLIAB.BUSINESS_DATE_ID =
 (SELECT
 distinct
    (ID)
 FROM
{{ source('DW_MART', 'CALENDAR_DIM') }}
 WHERE  
  CAL_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  TYPE= 'LTD_STD') AND 
   BNKLIAB.MNEMONIC NOT IN
 (SELECT
    STRING_VALUE
 FROM
    APPLICATION_VARIABLES
 WHERE 
  VARIABLE_NAME IN('BOE_INTEROP_MNEMONIC','BOE_DMO_MNEMONIC')) AND 
  BNKLIAB.ASSET_AMOUNT > 0 AND 
  BNKLIAB.SUB_ACCOUNT  !=  'Q' AND 
  BNKLIAB.ERROR_INDICATOR  != (DECODE((SELECT STRING_VALUE3 FROM
{{ source('DW_MART', 'APPLICATION_VARIABLES') }} WHERE VARIABLE_NAME= 'BOE_STATIC_BNKLIAB_ERROR_IND_VAL' AND ACTIVE_Y_N = 'Y'),'ALL','A','Y')) AND 
  BNKLIAB.SUB_ACCOUNT IN('F','R') AND 
  SACT.IN_DEFAULT_WATERFALL= 'TRUE' AND 
   EXCHN.EXCHANGE_MNEMONIC NOT IN
 (SELECT
    STRING_VALUE3
 FROM
    APPLICATION_VARIABLES
 WHERE  
  VARIABLE_NAME= 'BOE_STATIC_EXCHANGE_VAL' AND 
  ACTIVE_Y_N= 'Y') AND EXISTS 
 (SELECT
 distinct
    MRG_MNEMONIC
 FROM
{{ source('GRR', 'VW_RDR_MEMBER_DTLS') }}
 WHERE  
  VW_RDR_MEMBER_DTLS.MRG_MNEMONIC= BNKLIAB.MNEMONIC AND 
   VW_RDR_MEMBER_DTLS.SERVICE IN
 (SELECT
    A.EXCHANGE_MNEMONIC
 FROM
    EXCHANGE_DIM as A
 WHERE  
  GO_LIVE_DATE <= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  A.DEFAULT_FUND= EXCHN.DEFAULT_FUND)))
 ),

EXMP_BNK_LIAB_COLOut as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 MNEMONIC as MNEMONIC,
	 SUB_ACCOUNT as SUB_ACCOUNT,
	 EXCHANGE as EXCHANGE,
	 EXCHANGE_ID as EXCHANGE_ID,
	 ASSET_CURRENCY_ID as ASSET_CURRENCY_ID,
	 ASSET_AMOUNT as ASSET_AMOUNT,
	 ENTITY_ID as ENTITY_ID,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 v_WATERFALL_NM as o_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_SRVC as o_WATERFALL_SRVC,
	 MNEMONIC || '_' || SUB_ACCOUNT as BLC_CollateralAccountID,
	 'Cash' as v_Asset_Type,
	 v_Asset_Type as Asset_Type,
	 dsf_2.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN ASSET_AMOUNT ELSE NULL END ) as Cash_Value,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN v_Ccy ELSE null END ) as Cash_Value_Ccy,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN ASSET_AMOUNT ELSE NULL END ) as ValuePostHaircut,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN v_Ccy ELSE null END ) as ValuePostHaircut_ccy,
	 ( CASE WHEN IN ( SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as CollateralRequirement,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 1 as ENABLE_IND,
	 dsf_5.ID as FILE_GEN_DETAILS_ID
From SQ_SC_RR_BNK_LIABILITY_COVER_FACTOut as SQ_SC_RR_BNK_LIABILITY_COVER_FACTOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = EXCHANGE_ID
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.ID = ASSET_CURRENCY_ID
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_3.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_4.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_5.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
),

EXMP_BNK_LIAB_COLOut2 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 MNEMONIC as MNEMONIC,
	 SUB_ACCOUNT as SUB_ACCOUNT,
	 EXCHANGE as EXCHANGE,
	 EXCHANGE_ID as EXCHANGE_ID,
	 ASSET_CURRENCY_ID as ASSET_CURRENCY_ID,
	 ASSET_AMOUNT as ASSET_AMOUNT,
	 ENTITY_ID as ENTITY_ID,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 v_WATERFALL_NM as o_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_SRVC as o_WATERFALL_SRVC,
	 MNEMONIC || '_' || SUB_ACCOUNT as BLC_CollateralAccountID,
	 'Cash' as v_Asset_Type,
	 v_Asset_Type as Asset_Type,
	 dsf_2.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN ASSET_AMOUNT ELSE NULL END ) as Cash_Value,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN v_Ccy ELSE null END ) as Cash_Value_Ccy,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN ASSET_AMOUNT ELSE NULL END ) as ValuePostHaircut,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN v_Ccy ELSE null END ) as ValuePostHaircut_ccy,
	 ( CASE WHEN IN ( SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as CollateralRequirement,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 1 as ENABLE_IND,
	 dsf_5.ID as FILE_GEN_DETAILS_ID
From SQ_SC_RR_BNK_LIABILITY_COVER_FACTOut as SQ_SC_RR_BNK_LIABILITY_COVER_FACTOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = EXCHANGE_ID
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.ID = ASSET_CURRENCY_ID
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_3.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_4.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_5.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
),

EXMP_BNK_LIAB_COLOut3 as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 MNEMONIC as MNEMONIC,
	 SUB_ACCOUNT as SUB_ACCOUNT,
	 EXCHANGE as EXCHANGE,
	 EXCHANGE_ID as EXCHANGE_ID,
	 ASSET_CURRENCY_ID as ASSET_CURRENCY_ID,
	 ASSET_AMOUNT as ASSET_AMOUNT,
	 ENTITY_ID as ENTITY_ID,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 v_WATERFALL_NM as o_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_SRVC as o_WATERFALL_SRVC,
	 MNEMONIC || '_' || SUB_ACCOUNT as BLC_CollateralAccountID,
	 'Cash' as v_Asset_Type,
	 v_Asset_Type as Asset_Type,
	 dsf_2.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN ASSET_AMOUNT ELSE NULL END ) as Cash_Value,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN v_Ccy ELSE null END ) as Cash_Value_Ccy,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN ASSET_AMOUNT ELSE NULL END ) as ValuePostHaircut,
	 ( CASE WHEN v_Asset_Type = 'Cash' THEN v_Ccy ELSE null END ) as ValuePostHaircut_ccy,
	 ( CASE WHEN IN ( SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as CollateralRequirement,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 1 as ENABLE_IND,
	 dsf_5.ID as FILE_GEN_DETAILS_ID
From SQ_SC_RR_BNK_LIABILITY_COVER_FACTOut as SQ_SC_RR_BNK_LIABILITY_COVER_FACTOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = EXCHANGE_ID
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.ID = ASSET_CURRENCY_ID
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_3.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_4.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_5.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
),

DSR_SC_mplt_DV_BOE_FIXML11Out as (
	/* transType: "Expression" */
Select 
	EXMP_BNK_LIAB_COLOut2.o_Ccy as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 EXMP_BNK_LIAB_COLOut2.Asset_Type as AssetTypeCheck_T1_I_ASSET_TYPE,
	 EXMP_BNK_LIAB_COLOut2.BLC_CollateralAccountID as CollateralReport_T1_ACCT_ID,
	 EXMP_BNK_LIAB_COLOut2.ValuePostHaircut as AssetTypeCheck_T1_I_ValuePostHaircut,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as AssetTypeCheck_T1_I_ENABLE_IND,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as CollateralReport_ENABLE_IND,
	 EXMP_BNK_LIAB_COLOut2.SUB_ACCOUNT as COL_RPT_VAL_SUB_ACC,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as COL_RPT_VAL_EN_IND,
	 EXMP_BNK_LIAB_COLOut2.MNEMONIC as COL_RPT_VAL_MNE,
	 EXMP_BNK_LIAB_COLOut2.ASSET_AMOUNT as ZeroValCheck_T1_I_Cash_Value,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as ZeroValCheck_T1_I_Cash_Value_ENABLE_IND,
	 EXMP_BNK_LIAB_COLOut2.o_WATERFALL_NM as I_WATERFALL_NM,
	 EXMP_BNK_LIAB_COLOut2.o_WATERFALL_SRVC as I_WATERFALL_SRVC,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as ActiveCurrencyCode_T7_I_ENABLE_IND,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as I_WATERFALL_NM_ENABLE_IND,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as CollateralRequirementType1Code_T1_I_ENABLE_IND,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as I_WATERFALL_SRVC_ENABLE_IND,
	 EXMP_BNK_LIAB_COLOut2.ENABLE_IND as GenericIdentificationType1Code_T1_I_ENABLE_IND,
	 EXMP_BNK_LIAB_COLOut2.Cash_Value as AssetTypeCheck_T1_I_Cash_Value,
	 EXMP_BNK_LIAB_COLOut2.CollateralRequirement as CollateralRequirementType1Code_T1_I_COLL_REQ_TYPE,
	 EXMP_BNK_LIAB_COLOut2.EXCHANGE as COL_RPT_VAL_SERVICE
From EXMP_BNK_LIAB_COLOut as EXMP_BNK_LIAB_COLOut),

SC_mplt_DV_BOE_FIXML11Out as (
	/* transType: "MAPPLET" */
Select 
	AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 Receiver_Scheme_Name as Receiver_Scheme_Name,
	 o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 Sender_Scheme_Name as Sender_Scheme_Name,
	 ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 Receiver_LEI as Receiver_LEI,
	 Sender_LEI as Sender_LEI,
	 O_AccountIDScheme as CollateralAccountIDType,
	 WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 Msg_Def_Id as Msg_Def_Id,
	 ActiveCurrencyCode_T7_I_CURR_MNE_CASH1 as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 Asset_Type as AssetTypeCheck_T1_I_ASSET_TYPE,
	 BLC_CollateralAccountID as CollateralReport_T1_ACCT_ID,
	 ValuePostHaircut as AssetTypeCheck_T1_I_ValuePostHaircut,
	 ENABLE_IND as AssetTypeCheck_T1_I_ENABLE_IND,
	 ENABLE_IND as CollateralReport_ENABLE_IND,
	 SUB_ACCOUNT as COL_RPT_VAL_SUB_ACC,
	 ENABLE_IND as COL_RPT_VAL_EN_IND,
	 MNEMONIC as COL_RPT_VAL_MNE,
	 ASSET_AMOUNT as ZeroValCheck_T1_I_Cash_Value,
	 ENABLE_IND as ZeroValCheck_T1_I_Cash_Value_ENABLE_IND,
	 o_WATERFALL_NM as I_WATERFALL_NM,
	 o_WATERFALL_SRVC as I_WATERFALL_SRVC,
	 ENABLE_IND as ActiveCurrencyCode_T7_I_ENABLE_IND,
	 ENABLE_IND as I_WATERFALL_NM_ENABLE_IND,
	 ENABLE_IND as CollateralRequirementType1Code_T1_I_ENABLE_IND,
	 ENABLE_IND as I_WATERFALL_SRVC_ENABLE_IND,
	 o_Ccy as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 ENABLE_IND as GenericIdentificationType1Code_T1_I_ENABLE_IND,
	 Cash_Value as AssetTypeCheck_T1_I_Cash_Value,
	 CollateralRequirement as CollateralRequirementType1Code_T1_I_COLL_REQ_TYPE,
	 EXCHANGE as COL_RPT_VAL_SERVICE 
From DSR_SC_mplt_DV_BOE_FIXML11Out as DSR_SC_mplt_DV_BOE_FIXML11Out),

EXMP_BNK_LIAB_COL_master as (
  Select
  	EXMP_BNK_LIAB_COLOut.BLC_CollateralAccountID as CollateralAccountID,
	 EXMP_BNK_LIAB_COLOut.Asset_Type as AssetType,
	 EXMP_BNK_LIAB_COLOut.Cash_Value_Ccy as Cash_Value_Ccy,
	 EXMP_BNK_LIAB_COLOut.CollateralRequirement as CollateralRequirement,
	 EXMP_BNK_LIAB_COLOut.FILENAME as FILENAME,
	 EXMP_BNK_LIAB_COLOut.ID as ID_BNKLIAB,
	 EXMP_BNK_LIAB_COLOut.ValuePostHaircut_ccy as ValuePostHaircut_Ccy
  From EXMP_BNK_LIAB_COLOut as EXMP_BNK_LIAB_COLOut
),

SC_mplt_DV_BOE_FIXML11_details as (
  Select
  	SC_mplt_DV_BOE_FIXML11Out.Msg_Def_Id as Msg_Def_Id,
	 SC_mplt_DV_BOE_FIXML11Out.Receiver_Scheme_Name as Receiver_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML11Out.Receiver_LEI as Receiver_LEI,
	 SC_mplt_DV_BOE_FIXML11Out.Sender_Scheme_Name as Sender_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML11Out.Sender_LEI as Sender_LEI,
	 SC_mplt_DV_BOE_FIXML11Out.O_AccountIDScheme as CollateralAccountIDType,
	 SC_mplt_DV_BOE_FIXML11Out.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11Out.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11Out.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML11Out.AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 SC_mplt_DV_BOE_FIXML11Out.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11Out.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11Out.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 SC_mplt_DV_BOE_FIXML11Out.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11Out.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11Out.ActiveCurrencyCode_T7_I_CURR_MNE_CASH1 as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 SC_mplt_DV_BOE_FIXML11Out.ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 SC_mplt_DV_BOE_FIXML11Out.ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 SC_mplt_DV_BOE_FIXML11Out.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11Out.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11Out.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML11Out.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11Out.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11Out.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML11Out.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11Out.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11Out.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11Out.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11Out.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 SC_mplt_DV_BOE_FIXML11Out.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11Out.o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 SC_mplt_DV_BOE_FIXML11Out.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11Out.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11Out.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11Out.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL
  From SC_mplt_DV_BOE_FIXML11Out as SC_mplt_DV_BOE_FIXML11Out
),
dsJoiner_EXP_BNK_LIAB0Out as (
	/* transType: "Joiner" */
Select 
	SC_mplt_DV_BOE_FIXML11_details.Msg_Def_Id as Msg_Def_Id,
	 SC_mplt_DV_BOE_FIXML11_details.Receiver_Scheme_Name as Receiver_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML11_details.Receiver_LEI as Receiver_LEI,
	 SC_mplt_DV_BOE_FIXML11_details.Sender_Scheme_Name as Sender_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML11_details.Sender_LEI as Sender_LEI,
	 EXMP_BNK_LIAB_COLOut3.BLC_CollateralAccountID as CollateralAccountID,
	 SC_mplt_DV_BOE_FIXML11_details.CollateralAccountIDType as CollateralAccountIDType,
	 EXMP_BNK_LIAB_COLOut3.Asset_Type as AssetType,
	 EXMP_BNK_LIAB_COLOut3.Cash_Value_Ccy as Cash_Value_Ccy,
	 EXMP_BNK_LIAB_COLOut3.CollateralRequirement as CollateralRequirement,
	 EXMP_BNK_LIAB_COLOut3.FILENAME as FILENAME,
	 SC_mplt_DV_BOE_FIXML11_details.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11_details.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11_details.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML11_details.AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 SC_mplt_DV_BOE_FIXML11_details.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11_details.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11_details.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 SC_mplt_DV_BOE_FIXML11_details.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11_details.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11_details.ActiveCurrencyCode_T7_I_CURR_MNE_CASH as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 SC_mplt_DV_BOE_FIXML11_details.ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 SC_mplt_DV_BOE_FIXML11_details.ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 SC_mplt_DV_BOE_FIXML11_details.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11_details.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11_details.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML11_details.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11_details.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11_details.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML11_details.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11_details.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11_details.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11_details.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11_details.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 SC_mplt_DV_BOE_FIXML11_details.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11_details.o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 SC_mplt_DV_BOE_FIXML11_details.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11_details.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11_details.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML11_details.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 EXMP_BNK_LIAB_COLOut3.ID as ID_BNKLIAB,
	 EXMP_BNK_LIAB_COLOut3.ValuePostHaircut_ccy as ValuePostHaircut_Ccy,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXMP_BNK_LIAB_COLOut3 as EXMP_BNK_LIAB_COLOut3 inner JOIN SC_mplt_DV_BOE_FIXML11_details as SC_mplt_DV_BOE_FIXML11_details 
ON
SC_mplt_DV_BOE_FIXML11_details.jkey = EXMP_BNK_LIAB_COLOut3.jkey 
),

EXP_BNK_LIABOut as (
	/* transType: "Expression" */
Select 
	Msg_Def_Id as Msg_Def_Id,
	 Receiver_Scheme_Name as Receiver_Scheme_Name,
	 Receiver_LEI as Receiver_LEI,
	 Sender_Scheme_Name as Sender_Scheme_Name,
	 Sender_LEI as Sender_LEI,
	 CollateralAccountID as CollateralAccountID,
	 CollateralAccountIDType as CollateralAccountIDType,
	 AssetType as AssetType,
	 Cash_Value_Ccy as Cash_Value_Ccy,
	 CollateralRequirement as CollateralRequirement,
	 FILENAME as FILENAME,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 ActiveCurrencyCode_T7_I_CURR_MNE_CASH as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 ( CASE WHEN o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL = 1 OR o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL = 1 OR o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL = 1 OR o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL = 1 OR o_ZeroValCheck_CASH_VALUE_VAL_FAIL = 1 OR o_CollateralReportVal_T1_VAL_FAIL = 1 OR WATERFALL_NM_FAIL = 1 OR WATERFALL_SRVC_FAIL = 1 THEN 'Y' ELSE 'N' END ) as ERROR_IND,
	 '{{ var("PMWorkflowName") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName") }}' as MAPPING_NAME,
	 '{{ var("BATCH_ID") }}' as O_BATCH_ID,
	 TO_DATE ( LTRIM ( RTRIM ( '{{ var("BATCH_BUSINESS_DATE") }}' ) ),
	 'YYYYMMDD' ) as O_BATCH_BUSINESS_DATE,
	 ID_BNKLIAB as ID_BNKLIAB,
	 ValuePostHaircut_Ccy as ValuePostHaircut_Ccy
From dsJoiner_EXP_BNK_LIAB0Out as dsJoiner_EXP_BNK_LIAB0Out),

EXMP_BNK_LIAB_COL_master as (
  Select
  	EXMP_BNK_LIAB_COLOut.FILE_GEN_DETAILS_ID as FILE_GEN_ID
  From EXMP_BNK_LIAB_COLOut as EXMP_BNK_LIAB_COLOut
),
dsJoiner_FIL_BNKLIAB_ERR_RECS0Out as (
	/* transType: "Joiner" */
Select 
	EXP_BNK_LIABOut.FILENAME as FILENAME,
	 EXP_BNK_LIABOut.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 EXP_BNK_LIABOut.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 EXP_BNK_LIABOut.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 EXP_BNK_LIABOut.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 EXP_BNK_LIABOut.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 EXP_BNK_LIABOut.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 EXP_BNK_LIABOut.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 EXP_BNK_LIABOut.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 EXP_BNK_LIABOut.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 EXP_BNK_LIABOut.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 EXP_BNK_LIABOut.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 EXP_BNK_LIABOut.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 EXP_BNK_LIABOut.AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 EXP_BNK_LIABOut.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 EXP_BNK_LIABOut.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 EXP_BNK_LIABOut.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 EXP_BNK_LIABOut.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 EXP_BNK_LIABOut.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 EXP_BNK_LIABOut.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 EXP_BNK_LIABOut.ActiveCurrencyCode_T7_I_CURR_MNE_CASH as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 EXP_BNK_LIABOut.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 EXP_BNK_LIABOut.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 EXP_BNK_LIABOut.ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 EXP_BNK_LIABOut.ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 EXP_BNK_LIABOut.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 EXP_BNK_LIABOut.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 EXP_BNK_LIABOut.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 EXP_BNK_LIABOut.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 EXP_BNK_LIABOut.ID_BNKLIAB as ID_BNKLIAB,
	 EXP_BNK_LIABOut.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 EXP_BNK_LIABOut.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 EXP_BNK_LIABOut.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 EXP_BNK_LIABOut.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 EXP_BNK_LIABOut.o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 EXP_BNK_LIABOut.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 EXP_BNK_LIABOut.O_BATCH_BUSINESS_DATE as O_BATCH_BUSINESS_DATE,
	 EXP_BNK_LIABOut.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 EXP_BNK_LIABOut.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 EXP_BNK_LIABOut.ERROR_IND as ERROR_IND,
	 EXP_BNK_LIABOut.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_BNK_LIABOut.MAPPING_NAME as MAPPING_NAME,
	 EXP_BNK_LIABOut.O_BATCH_ID as O_BATCH_ID,
	 EXMP_BNK_LIAB_COL_master.FILE_GEN_ID as FILE_GEN_ID,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXMP_BNK_LIAB_COL_master as EXMP_BNK_LIAB_COL_master inner JOIN EXP_BNK_LIABOut as EXP_BNK_LIABOut 
ON
EXP_BNK_LIABOut.jkey = EXMP_BNK_LIAB_COL_master.jkey 
),

DSR_SC_mplt_DV_PROCESS_ERROR_DETAILS11Out as (
	/* transType: "Expression" */
Select 
	FIL_BNKLIAB_ERR_RECSOut.FILENAME as INPUT_TARGET_NAME,
	 FIL_BNKLIAB_ERR_RECSOut.WATERFALL_NM_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_7,
	 FIL_BNKLIAB_ERR_RECSOut.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_1,
	 FIL_BNKLIAB_ERR_RECSOut.o_AssetTypeCheck_ASSET_TYPE_NAME as INPUT_ATTRIBUTE_NAME_1,
	 FIL_BNKLIAB_ERR_RECSOut.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as INPUT_ATTRIBUTE_NAME_4,
	 FIL_BNKLIAB_ERR_RECSOut.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_3,
	 FIL_BNKLIAB_ERR_RECSOut.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_4,
	 FIL_BNKLIAB_ERR_RECSOut.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as INPUT_ERROR_CODE_4,
	 FIL_BNKLIAB_ERR_RECSOut.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_4,
	 FIL_BNKLIAB_ERR_RECSOut.CollateralReportVal_ERROR_CODE as INPUT_ERROR_CODE_5,
	 FIL_BNKLIAB_ERR_RECSOut.o_CollateralReportVal_NAME as INPUT_ATTRIBUTE_NAME_5,
	 FIL_BNKLIAB_ERR_RECSOut.CollateralReportVal_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_5,
	 FIL_BNKLIAB_ERR_RECSOut.o_CollateralReportVal_T1_VAL_FAIL as INPUT_ERROR_SEVERITY_5,
	 FIL_BNKLIAB_ERR_RECSOut.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_1,
	 FIL_BNKLIAB_ERR_RECSOut.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_6,
	 FIL_BNKLIAB_ERR_RECSOut.o_ZeroValCheck_CASH_VALUE_NAME as INPUT_ATTRIBUTE_NAME_6,
	 FIL_BNKLIAB_ERR_RECSOut.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as INPUT_ERROR_SEVERITY_6,
	 FIL_BNKLIAB_ERR_RECSOut.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as INPUT_ERROR_CODE_6,
	 FIL_BNKLIAB_ERR_RECSOut.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as INPUT_ATTRIBUTE_NAME_3,
	 FIL_BNKLIAB_ERR_RECSOut.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as INPUT_ERROR_CODE_2,
	 FIL_BNKLIAB_ERR_RECSOut.WATERFALL_NM_NAME as INPUT_ATTRIBUTE_NAME_7,
	 FIL_BNKLIAB_ERR_RECSOut.WATERFALL_NM_ERROR_CODE as INPUT_ERROR_CODE_7,
	 FIL_BNKLIAB_ERR_RECSOut.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as INPUT_ATTRIBUTE_NAME_2,
	 FIL_BNKLIAB_ERR_RECSOut.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_2,
	 FIL_BNKLIAB_ERR_RECSOut.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as INPUT_ERROR_SEVERITY_2,
	 FIL_BNKLIAB_ERR_RECSOut.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_3,
	 FIL_BNKLIAB_ERR_RECSOut.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as INPUT_ERROR_CODE_3,
	 FIL_BNKLIAB_ERR_RECSOut.WATERFALL_SRVC_ERROR_CODE as INPUT_ERROR_CODE_8,
	 FIL_BNKLIAB_ERR_RECSOut.WATERFALL_SRVC_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_8,
	 FIL_BNKLIAB_ERR_RECSOut.WATERFALL_SRVC_FAIL as INPUT_ERROR_SEVERITY_8,
	 FIL_BNKLIAB_ERR_RECSOut.WATERFALL_SRVC_NAME as INPUT_ATTRIBUTE_NAME_8,
	 FIL_BNKLIAB_ERR_RECSOut.ID_BNKLIAB as INPUT_REFERENCE_RECORD_ID,
	 FIL_BNKLIAB_ERR_RECSOut.WORKFLOW_NAME as INPUT_WORKFLOW_NAME,
	 FIL_BNKLIAB_ERR_RECSOut.MAPPING_NAME as INPUT_MAPPING_NAME,
	 FIL_BNKLIAB_ERR_RECSOut.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as INPUT_ERROR_CODE_1,
	 FIL_BNKLIAB_ERR_RECSOut.FILE_GEN_ID as INPUT_BATCH_DETAILS_ID,
	 FIL_BNKLIAB_ERR_RECSOut.O_BATCH_BUSINESS_DATE as INPUT_BATCH_BUSINESS_DATE,
	 FIL_BNKLIAB_ERR_RECSOut.WATERFALL_NM_FAIL as INPUT_ERROR_SEVERITY_7,
	 FIL_BNKLIAB_ERR_RECSOut.O_BATCH_ID as INPUT_BATCH_ID 
From dsJoiner_FIL_BNKLIAB_ERR_RECS0Out as dsJoiner_FIL_BNKLIAB_ERR_RECS0Out Where ERROR_IND = 'N'),

SC_mplt_DV_PROCESS_ERROR_DETAILS11Out as (
	/* transType: "MAPPLET" */
Select 
	REFERENCE_ATTRIBUTE_VALUE as REFERENCE_ATTRIBUTE_VALUE,
	 REFERENCE_BATCH_DETAILS_ID as REFERENCE_BATCH_DETAILS_ID,
	 REFERENCE_SUB_PROCESS as REFERENCE_SUB_PROCESS,
	 PROCESS_DATE as PROCESS_DATE,
	 ERROR_CODE as ERROR_CODE,
	 REFERENCE_RECORD_ID as REFERENCE_RECORD_ID,
	 REFERENCE_BUSINESS_KEY as REFERENCE_BUSINESS_KEY,
	 REFERENCE_ATTRIBUTE_NAME as REFERENCE_ATTRIBUTE_NAME,
	 ERROR_SEVERITY as ERROR_SEVERITY,
	 ADDITIONAL_DETAILS as ADDITIONAL_DETAILS,
	 REFERENCE_BATCH_ID as REFERENCE_BATCH_ID,
	 REFERENCE_PROCESS as REFERENCE_PROCESS,
	 REFERENCE_TARGET_NAME as REFERENCE_TARGET_NAME,
	 ID as ID,
	 FILENAME as INPUT_TARGET_NAME,
	 WATERFALL_NM_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_7,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_1,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as INPUT_ATTRIBUTE_NAME_1,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as INPUT_ATTRIBUTE_NAME_4,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_3,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_4,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as INPUT_ERROR_CODE_4,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_4,
	 CollateralReportVal_ERROR_CODE as INPUT_ERROR_CODE_5,
	 o_CollateralReportVal_NAME as INPUT_ATTRIBUTE_NAME_5,
	 CollateralReportVal_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_5,
	 o_CollateralReportVal_T1_VAL_FAIL as INPUT_ERROR_SEVERITY_5,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_1,
	 ZeroValCheck_CASH_VALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_6,
	 o_ZeroValCheck_CASH_VALUE_NAME as INPUT_ATTRIBUTE_NAME_6,
	 o_ZeroValCheck_CASH_VALUE_VAL_FAIL as INPUT_ERROR_SEVERITY_6,
	 ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as INPUT_ERROR_CODE_6,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as INPUT_ATTRIBUTE_NAME_3,
	 ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as INPUT_ERROR_CODE_2,
	 WATERFALL_NM_NAME as INPUT_ATTRIBUTE_NAME_7,
	 WATERFALL_NM_ERROR_CODE as INPUT_ERROR_CODE_7,
	 o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as INPUT_ATTRIBUTE_NAME_2,
	 ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_2,
	 o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as INPUT_ERROR_SEVERITY_2,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_3,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as INPUT_ERROR_CODE_3,
	 WATERFALL_SRVC_ERROR_CODE as INPUT_ERROR_CODE_8,
	 WATERFALL_SRVC_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_8,
	 WATERFALL_SRVC_FAIL as INPUT_ERROR_SEVERITY_8,
	 WATERFALL_SRVC_NAME as INPUT_ATTRIBUTE_NAME_8,
	 ID_BNKLIAB as INPUT_REFERENCE_RECORD_ID,
	 WORKFLOW_NAME as INPUT_WORKFLOW_NAME,
	 MAPPING_NAME as INPUT_MAPPING_NAME,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as INPUT_ERROR_CODE_1,
	 FILE_GEN_ID as INPUT_BATCH_DETAILS_ID,
	 O_BATCH_BUSINESS_DATE as INPUT_BATCH_BUSINESS_DATE,
	 WATERFALL_NM_FAIL as INPUT_ERROR_SEVERITY_7,
	 O_BATCH_ID as INPUT_BATCH_ID 
From DSR_SC_mplt_DV_PROCESS_ERROR_DETAILS11Out as DSR_SC_mplt_DV_PROCESS_ERROR_DETAILS11Out)

Select 
	ID as ID,
	PROCESS_DATE as PROCESS_DATE,
	REFERENCE_BATCH_ID as REFERENCE_BATCH_ID,
	REFERENCE_PROCESS as REFERENCE_PROCESS,
	REFERENCE_SUB_PROCESS as REFERENCE_SUB_PROCESS,
	REFERENCE_TARGET_NAME as REFERENCE_TARGET_NAME,
	REFERENCE_RECORD_ID as REFERENCE_RECORD_ID,
	REFERENCE_BUSINESS_KEY as REFERENCE_BUSINESS_KEY,
	REFERENCE_ATTRIBUTE_NAME as REFERENCE_ATTRIBUTE_NAME,
	REFERENCE_ATTRIBUTE_VALUE as REFERENCE_ATTRIBUTE_VALUE,
	ERROR_CODE as ERROR_CODE,
	ERROR_SEVERITY as ERROR_SEVERITY,
	ADDITIONAL_DETAILS as ADDITIONAL_DETAILS,
	REFERENCE_BATCH_DETAILS_ID as REFERENCE_BATCH_DETAILS_ID 
From SC_mplt_DV_PROCESS_ERROR_DETAILS11Out as SC_mplt_DV_PROCESS_ERROR_DETAILS11Out