/* Transformation Name ==>SC_PROCESS_ERROR_DETAILS_CASH ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='PROCESS_ERROR_DETAILS',
		schema='EMIR_SHARED',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut as (
	/* SubQuery from Source ==>SQ_SQ_SC_RR_BNK_CASH_COLLATERAL_FACT */
/* transType: "Source" */
Select 
ID,
MNEMONIC,
SUB_ACCOUNT,
EXCHANGE_ID,
EXCHANGE,
CASH_COLLATERAL_CURRENCY_ID,
CASH_COLLATERAL_AMOUNT,
ENTITY_ID,
CASH_COLLATERAL_POST_HAIRCUT
 from 
(SELECT
    A.ID,
    A.MNEMONIC,
    A.SUB_ACCOUNT,
    A.EXCHANGE_ID,
    A.EXCHANGE,
    A.CASH_COLLATERAL_CURRENCY_ID,
    A.CASH_COLLATERAL_AMOUNT,
    A.ENTITY_ID,
    A.CASH_COLLATERAL_POST_HAIRCUT
 FROM
 (SELECT
    CASH.ID,
    CASH.MNEMONIC,
    CASH.SUB_ACCOUNT,
    CASH.EXCHANGE_ID,
    CASH.EXCHANGE,
    CASH.CASH_COLLATERAL_CURRENCY_ID,
    CASH.CASH_COLLATERAL_AMOUNT,
    CASH.ENTITY_ID,
    CASH.CASH_COLLATERAL_POST_HAIRCUT,
    VW_PRIM_EXCH_SHAREDMNEMONIC.PRIMARY_EXCHANGE
 FROM
    RR_BNK_CASH_COLLATERAL_FACT as CASH
 JOIN
  BATCH_MASTER as BM
 ON
  CASH.BATCH_ID= BM.BATCH_ID
 JOIN
  DW_MART.EXCHANGE_DIM as EXCHN
 ON
  CASH.EXCHANGE_ID= EXCHN.ID
 LEFT OUTER JOIN 
  DW_MART.VW_PRIM_EXCH_SHAREDMNEMONIC
 ON
  CASH.MNEMONIC= VW_PRIM_EXCH_SHAREDMNEMONIC.MNEMONIC
 WHERE  
  BM.BATCH_FEED_INFO LIKE '%BNK%' AND 
  BM.BATCH_STATUS= 'C' AND 
  BM.BATCH_BUSINESS_FROM_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  ( SYSDATE BETWEEN EXCHN.EFFECTIVE_DATE AND NVL ( EXCHN.EXPIRATION_DATE,TO_DATE ( '31-DEC-2099','DD-MON-YYYY') ) ) AND 
  EXCHN.ENTITY= 'LTD' AND 
   CASH.BUSINESS_DATE_ID =
 (SELECT
 distinct
    (ID)
 FROM
{{ source('DW_MART', 'CALENDAR_DIM') }}
 WHERE  
  CAL_DATE= TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') AND 
  TYPE= 'LTD_STD') AND 
  CASH.CASH_COLLATERAL_AMOUNT > 0 AND 
  CASH.SUB_ACCOUNT NOT IN('R','Q') AND 
  CASH.ERROR_INDICATOR  != (DECODE((SELECT STRING_VALUE3 FROM
{{ source('DW_MART', 'APPLICATION_VARIABLES') }} WHERE VARIABLE_NAME= 'BOE_STATIC_CASH_ERROR_IND_VAL' AND ACTIVE_Y_N = 'Y'),'ALL','A','Y')) AND 
   CASH.MNEMONIC NOT IN
 (SELECT
    STRING_VALUE
 FROM
    APPLICATION_VARIABLES
 WHERE 
  VARIABLE_NAME IN('BOE_INTEROP_MNEMONIC','BOE_DMO_MNEMONIC')) AND 
   CASH.EXCHANGE NOT IN
 (SELECT
    STRING_VALUE3
 FROM
    APPLICATION_VARIABLES
 WHERE  
  VARIABLE_NAME= 'BOE_STATIC_EXCHANGE_VAL' AND 
  ACTIVE_Y_N= 'Y')) A
 WHERE  
  (A.PRIMARY_EXCHANGE IS NULL OR A.PRIMARY_EXCHANGE= A.EXCHANGE) AND EXISTS 
 (SELECT
 distinct
    MRG_MNEMONIC
 FROM
{{ source('GRR', 'VW_RDR_MEMBER_DTLS') }}
 WHERE 
  VW_RDR_MEMBER_DTLS.MRG_MNEMONIC= A.MNEMONIC))
 ),

DSR_EXP_CASH_COLOut as (
	/* transType: "Expression" */
Select 
	SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.ID as ID_CASH,
	 SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.MNEMONIC as CC_MNEMONIC,
	 SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.CASH_COLLATERAL_CURRENCY_ID as CC_CASH_COLLATERAL_CURRENCY_ID,
	 SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.SUB_ACCOUNT as CC_SUB_ACCOUNT,
	 SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.EXCHANGE as I_CC_EXCHANGE,
	 SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.EXCHANGE_ID as CC_EXCHANGE_ID,
	 SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.CASH_COLLATERAL_AMOUNT as CC_CASH_COLLATERAL_AMOUNT,
	 SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.ENTITY_ID as CC_ENTITY_ID,
	 SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut.CASH_COLLATERAL_POST_HAIRCUT as CASH_COLLATERAL_POST_HAIRCUT
From SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut as SQ_SC_RR_BNK_CASH_COLLATERAL_FACTOut),

EXP_CASH_COLOut as (
	/* transType: "Expression" */
Select 
	ID_CASH as ID_CASH,
	 CC_MNEMONIC as CC_MNEMONIC,
	 CC_CASH_COLLATERAL_CURRENCY_ID as CC_CASH_COLLATERAL_CURRENCY_ID,
	 CC_SUB_ACCOUNT as O_CC_SUB_ACCOUNT,
	 DECODE ( I_CC_EXCHANGE,
	 'TQD',
	 'ED2',
	 I_CC_EXCHANGE ) as V_CC_EXCHANGE,
	 V_CC_EXCHANGE as CC_EXCHANGE,
	 CC_CASH_COLLATERAL_AMOUNT as CC_CASH_COLLATERAL_AMOUNT,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_NM as CC_DEFAULT_FUND,
	 v_WATERFALL_SRVC as CC_WATERFALL_SRVC,
	 CC_ENTITY_ID as CC_ENTITY_ID,
	 'Cash' as CC_COLLATERAL_GROUP,
	 1 as ERROR_IND,
	 dsf_2.HOUSE_CLIENT_FLAG as v_HOUSE_CLIENT_FLAG,
	 ( CASE WHEN IN ( SUBSTRING ( CC_SUB_ACCOUNT,
	 1,
	 1 ),
	 'S',
	 'O',
	 'V',
	 'F',
	 'R' ) THEN CC_SUB_ACCOUNT ELSE v_HOUSE_CLIENT_FLAG END ) as v_SUB_ACCOUNT_CHK,
	 CC_MNEMONIC || '_' || v_SUB_ACCOUNT_CHK as v_CC_SUB_ACC,
	 v_SUB_ACCOUNT_CHK as o_SUB_ACCOUNT,
	 v_CC_SUB_ACC as CollateralAccountID,
	 DECODE ( CC_COLLATERAL_GROUP,
	 'ATS',
	 dsf_3.STRING_VALUE2,
	 'ITS',
	 dsf_4.STRING_VALUE2,
	 'XXX',
	 dsf_6.STRING_VALUE2,
	 'YYY',
	 dsf_5.STRING_VALUE2,
	 'Cash' ) as v_AssetType,
	 v_AssetType as AssetType,
	 dsf_7.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 ( CASE WHEN v_AssetType = 'Cash' THEN CC_CASH_COLLATERAL_AMOUNT ELSE NULL END ) as Cash_Value,
	 ( CASE WHEN v_AssetType = 'Cash' THEN v_Ccy ELSE null END ) as Cash_Value_Ccy,
	 ( CASE WHEN v_AssetType = 'Cash' THEN CC_CASH_COLLATERAL_AMOUNT ELSE NULL END ) as ValuePostHaircut,
	 ( CASE WHEN v_AssetType = 'Cash' THEN v_Ccy ELSE null END ) as ValuePostHaircut_Ccy,
	 ( CASE WHEN IN ( CC_SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as CollateralRequirement,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 1 as ENABLE_IND,
	 dsf_10.ID as FILE_GEN_DETAILS_ID,
	 CASH_COLLATERAL_POST_HAIRCUT as CASH_COLLATERAL_POST_HAIRCUT,
	 dsf_11.ACTIVE_Y_N as FX_HAIRCUT_SWITCH
From DSR_EXP_CASH_COLOut as DSR_EXP_CASH_COLOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = CC_EXCHANGE_ID
LEFT JOIN (
SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT FROM (   SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY SUB_ACCOUNT NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        VW_ML_CALYP_SUB_ACCOUNT )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.SUB_ACCOUNT = CC_SUB_ACCOUNT
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = 'ATS'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = 'ITS'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.STRING_VALUE = 'YYY'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_6
ON dsf_6.STRING_VALUE = 'XXX'
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_7
ON dsf_7.ID = CC_CASH_COLLATERAL_CURRENCY_ID
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_8
ON dsf_8.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_8.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_9
ON dsf_9.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_9.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_10
ON dsf_10.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_10.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
LEFT JOIN (
SELECT ACTIVE_Y_N, STRING_VALUE FROM (   SELECT ACTIVE_Y_N, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ACTIVE_Y_N, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_11
ON dsf_11.STRING_VALUE = 'FX_HAIRCUT_SWITCH'
),

EXP_CASH_COLOut1 as (
	/* transType: "Expression" */
Select 
	ID_CASH as ID_CASH,
	 CC_MNEMONIC as CC_MNEMONIC,
	 CC_CASH_COLLATERAL_CURRENCY_ID as CC_CASH_COLLATERAL_CURRENCY_ID,
	 CC_SUB_ACCOUNT as O_CC_SUB_ACCOUNT,
	 DECODE ( I_CC_EXCHANGE,
	 'TQD',
	 'ED2',
	 I_CC_EXCHANGE ) as V_CC_EXCHANGE,
	 V_CC_EXCHANGE as CC_EXCHANGE,
	 CC_CASH_COLLATERAL_AMOUNT as CC_CASH_COLLATERAL_AMOUNT,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_NM as CC_DEFAULT_FUND,
	 v_WATERFALL_SRVC as CC_WATERFALL_SRVC,
	 CC_ENTITY_ID as CC_ENTITY_ID,
	 'Cash' as CC_COLLATERAL_GROUP,
	 1 as ERROR_IND,
	 dsf_2.HOUSE_CLIENT_FLAG as v_HOUSE_CLIENT_FLAG,
	 ( CASE WHEN IN ( SUBSTRING ( CC_SUB_ACCOUNT,
	 1,
	 1 ),
	 'S',
	 'O',
	 'V',
	 'F',
	 'R' ) THEN CC_SUB_ACCOUNT ELSE v_HOUSE_CLIENT_FLAG END ) as v_SUB_ACCOUNT_CHK,
	 CC_MNEMONIC || '_' || v_SUB_ACCOUNT_CHK as v_CC_SUB_ACC,
	 v_SUB_ACCOUNT_CHK as o_SUB_ACCOUNT,
	 v_CC_SUB_ACC as CollateralAccountID,
	 DECODE ( CC_COLLATERAL_GROUP,
	 'ATS',
	 dsf_3.STRING_VALUE2,
	 'ITS',
	 dsf_4.STRING_VALUE2,
	 'XXX',
	 dsf_6.STRING_VALUE2,
	 'YYY',
	 dsf_5.STRING_VALUE2,
	 'Cash' ) as v_AssetType,
	 v_AssetType as AssetType,
	 dsf_7.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 ( CASE WHEN v_AssetType = 'Cash' THEN CC_CASH_COLLATERAL_AMOUNT ELSE NULL END ) as Cash_Value,
	 ( CASE WHEN v_AssetType = 'Cash' THEN v_Ccy ELSE null END ) as Cash_Value_Ccy,
	 ( CASE WHEN v_AssetType = 'Cash' THEN CC_CASH_COLLATERAL_AMOUNT ELSE NULL END ) as ValuePostHaircut,
	 ( CASE WHEN v_AssetType = 'Cash' THEN v_Ccy ELSE null END ) as ValuePostHaircut_Ccy,
	 ( CASE WHEN IN ( CC_SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as CollateralRequirement,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 1 as ENABLE_IND,
	 dsf_10.ID as FILE_GEN_DETAILS_ID,
	 CASH_COLLATERAL_POST_HAIRCUT as CASH_COLLATERAL_POST_HAIRCUT,
	 dsf_11.ACTIVE_Y_N as FX_HAIRCUT_SWITCH
From DSR_EXP_CASH_COLOut as DSR_EXP_CASH_COLOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = CC_EXCHANGE_ID
LEFT JOIN (
SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT FROM (   SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY SUB_ACCOUNT NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        VW_ML_CALYP_SUB_ACCOUNT )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.SUB_ACCOUNT = CC_SUB_ACCOUNT
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = 'ATS'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = 'ITS'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.STRING_VALUE = 'YYY'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_6
ON dsf_6.STRING_VALUE = 'XXX'
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_7
ON dsf_7.ID = CC_CASH_COLLATERAL_CURRENCY_ID
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_8
ON dsf_8.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_8.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_9
ON dsf_9.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_9.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_10
ON dsf_10.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_10.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
LEFT JOIN (
SELECT ACTIVE_Y_N, STRING_VALUE FROM (   SELECT ACTIVE_Y_N, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ACTIVE_Y_N, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_11
ON dsf_11.STRING_VALUE = 'FX_HAIRCUT_SWITCH'
),

EXP_CASH_COLOut2 as (
	/* transType: "Expression" */
Select 
	ID_CASH as ID_CASH,
	 CC_MNEMONIC as CC_MNEMONIC,
	 CC_CASH_COLLATERAL_CURRENCY_ID as CC_CASH_COLLATERAL_CURRENCY_ID,
	 CC_SUB_ACCOUNT as O_CC_SUB_ACCOUNT,
	 DECODE ( I_CC_EXCHANGE,
	 'TQD',
	 'ED2',
	 I_CC_EXCHANGE ) as V_CC_EXCHANGE,
	 V_CC_EXCHANGE as CC_EXCHANGE,
	 CC_CASH_COLLATERAL_AMOUNT as CC_CASH_COLLATERAL_AMOUNT,
	 dsf_1.DF_NAME as v_WATERFALL_LKP,
	 SUBSTRING ( v_WATERFALL_LKP,
	 1,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) -1 ) as v_WATERFALL_NM,
	 SUBSTRING ( v_WATERFALL_LKP,
	 REGEXP_INSTR ( v_WATERFALL_LKP,
	 '~' ) + 1 ) as v_WATERFALL_SRVC,
	 v_WATERFALL_NM as CC_DEFAULT_FUND,
	 v_WATERFALL_SRVC as CC_WATERFALL_SRVC,
	 CC_ENTITY_ID as CC_ENTITY_ID,
	 'Cash' as CC_COLLATERAL_GROUP,
	 1 as ERROR_IND,
	 dsf_2.HOUSE_CLIENT_FLAG as v_HOUSE_CLIENT_FLAG,
	 ( CASE WHEN IN ( SUBSTRING ( CC_SUB_ACCOUNT,
	 1,
	 1 ),
	 'S',
	 'O',
	 'V',
	 'F',
	 'R' ) THEN CC_SUB_ACCOUNT ELSE v_HOUSE_CLIENT_FLAG END ) as v_SUB_ACCOUNT_CHK,
	 CC_MNEMONIC || '_' || v_SUB_ACCOUNT_CHK as v_CC_SUB_ACC,
	 v_SUB_ACCOUNT_CHK as o_SUB_ACCOUNT,
	 v_CC_SUB_ACC as CollateralAccountID,
	 DECODE ( CC_COLLATERAL_GROUP,
	 'ATS',
	 dsf_3.STRING_VALUE2,
	 'ITS',
	 dsf_4.STRING_VALUE2,
	 'XXX',
	 dsf_6.STRING_VALUE2,
	 'YYY',
	 dsf_5.STRING_VALUE2,
	 'Cash' ) as v_AssetType,
	 v_AssetType as AssetType,
	 dsf_7.CURRENCY_MNEMONIC as v_Ccy,
	 v_Ccy as o_Ccy,
	 ( CASE WHEN v_AssetType = 'Cash' THEN CC_CASH_COLLATERAL_AMOUNT ELSE NULL END ) as Cash_Value,
	 ( CASE WHEN v_AssetType = 'Cash' THEN v_Ccy ELSE null END ) as Cash_Value_Ccy,
	 ( CASE WHEN v_AssetType = 'Cash' THEN CC_CASH_COLLATERAL_AMOUNT ELSE NULL END ) as ValuePostHaircut,
	 ( CASE WHEN v_AssetType = 'Cash' THEN v_Ccy ELSE null END ) as ValuePostHaircut_Ccy,
	 ( CASE WHEN IN ( CC_SUB_ACCOUNT,
	 'F',
	 'R' ) THEN 'DFLT' ELSE 'MGIN' END ) as CollateralRequirement,
	 SUBSTRING ( TO_DATE ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'YYYY-MM-DD' ),
	 'YYYY-MM-DD' ),
	 1,
	 10 ) || 'T' || SUBSTRING ( TO_TIMESTAMP ( TO_VARCHAR ( TO_TIMESTAMP ( '{{ var("BATCH_START_DATE") }}',
	 'DD-MON-YYYY HH24:MI:SS' ),
	 'HH24MISS' ),
	 'HH24MISS' ),
	 12 ) as v_Date,
	 TO_VARCHAR ( TO_DATE ( '{{ var("BATCH_BUSINESS_DATE") }}',
	 'YYYYMMDD' ),
	 'YYYY-MM-DD' ) as v_AS_OF_DATE,
	 :LKP.SC_LKP_APPLICATION_VARIABLES_BOE ( PMSessionName,
	 'BOE_STATIC_VAL' ) as v_APP_REP_ID,
	 :LKP.SC_LKP_FILE_GENERATED_DETAILS_DIM_VERSION ( '{{ var("BATCH_ID") }}',
	 v_APP_REP_ID ) as v_Version,
	 ( CASE WHEN v_Version IS NULL THEN 1 ELSE ( TO_NUMBER ( v_Version ) + 1 ) END ) as v_initial_value_handle,
	 '{{ var("CCP_CODE") }}' || '_' || v_AS_OF_DATE || '_' || 'CCPCollRpt_' || v_Date || '_V' || v_initial_value_handle || '.XML' as v_FILENAME,
	 v_FILENAME as FILENAME,
	 1 as ENABLE_IND,
	 dsf_10.ID as FILE_GEN_DETAILS_ID,
	 CASH_COLLATERAL_POST_HAIRCUT as CASH_COLLATERAL_POST_HAIRCUT,
	 dsf_11.ACTIVE_Y_N as FX_HAIRCUT_SWITCH
From DSR_EXP_CASH_COLOut as DSR_EXP_CASH_COLOut
LEFT JOIN (
SELECT DF_NAME, ID FROM (   SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT DF_NAME, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        EXCHANGE_DIM.ID as ID,        EXCHANGE_DIM.DEFAULT_FUND || '~' || EXCHANGE_DIM.NAME as DF_NAME  FROM        EXCHANGE_DIM  WHERE       TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') >= EFFECTIVE_DATE AND      TO_DATE('{{ var("BATCH_BUSINESS_DATE") }}','YYYYMMDD') <= NVL(EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.ID = CC_EXCHANGE_ID
LEFT JOIN (
SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT FROM (   SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT HOUSE_CLIENT_FLAG, SUB_ACCOUNT,   ROW_NUMBER() OVER (PARTITION BY SUB_ACCOUNT ORDER BY SUB_ACCOUNT NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        VW_ML_CALYP_SUB_ACCOUNT )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.SUB_ACCOUNT = CC_SUB_ACCOUNT
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.STRING_VALUE = 'ATS'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_4
ON dsf_4.STRING_VALUE = 'ITS'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_5
ON dsf_5.STRING_VALUE = 'YYY'
LEFT JOIN (
SELECT STRING_VALUE2, STRING_VALUE FROM (   SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE2, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,        APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE  FROM        APPLICATION_VARIABLES  WHERE     VARIABLE_NAME= 'BOE_STATIC_VAL' )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_6
ON dsf_6.STRING_VALUE = 'XXX'
LEFT JOIN (
SELECT CURRENCY_MNEMONIC, ID FROM (   SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT CURRENCY_MNEMONIC, ID,   ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        CURRENCY_DIM )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_7
ON dsf_7.ID = CC_CASH_COLLATERAL_CURRENCY_ID
LEFT JOIN (
SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME FROM (   SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT STRING_VALUE3, STRING_VALUE, VARIABLE_NAME,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE, VARIABLE_NAME ORDER BY STRING_VALUE, VARIABLE_NAME NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_8
ON dsf_8.STRING_VALUE = '{{ var("PMSessionName") }}' AND dsf_8.VARIABLE_NAME = 'BOE_STATIC_VAL'
LEFT JOIN (
SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT VERSION_NO, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        MAX(NVL(FILE_GENERATED_DETAILS_DIM.VERSION_NO,0)) as VERSION_NO,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.STATUS= 'C' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}'  GROUP BY        FILE_GENERATED_DETAILS_DIM.BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_9
ON dsf_9.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_9.APPLICATION_REPORT_ID = v_APP_REP_ID
LEFT JOIN (
SELECT ID, BATCH_ID, APPLICATION_REPORT_ID FROM (   SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ID, BATCH_ID, APPLICATION_REPORT_ID,   ROW_NUMBER() OVER (PARTITION BY BATCH_ID, APPLICATION_REPORT_ID ORDER BY BATCH_ID, APPLICATION_REPORT_ID NULLS LAST) AS rnk_fst     FROM ( SELECT        FILE_GENERATED_DETAILS_DIM.ID as ID,        FILE_GENERATED_DETAILS_DIM.BATCH_ID as BATCH_ID,        FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID as APPLICATION_REPORT_ID  FROM        FILE_GENERATED_DETAILS_DIM  INNER JOIN      BATCH_MASTER   ON    FILE_GENERATED_DETAILS_DIM.BATCH_ID= BATCH_MASTER.BATCH_ID AND     FILE_GENERATED_DETAILS_DIM.BATCH_ID= '{{ var("BATCH_ID") }}' AND     FILE_GENERATED_DETAILS_DIM.APPLICATION_REPORT_ID= '{{ var("REPORT_ID") }}' AND     DATE_TRUNC('DAY',FILE_GENERATED_DETAILS_DIM.FILE_GEN_START_DATETIME)= DATE_TRUNC('DAY',TO_DATE('{{ var("BATCH_START_DATE") }}','DD-MON-YYYY'))  ORDER BY        TRUNC ( FILE_GEN_START_DATETIME ) DESC )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_10
ON dsf_10.BATCH_ID = '{{ var("BATCH_ID") }}' AND dsf_10.APPLICATION_REPORT_ID = '{{ var("REPORT_ID") }}'
LEFT JOIN (
SELECT ACTIVE_Y_N, STRING_VALUE FROM (   SELECT ACTIVE_Y_N, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst   FROM (     SELECT ACTIVE_Y_N, STRING_VALUE,   ROW_NUMBER() OVER (PARTITION BY STRING_VALUE ORDER BY STRING_VALUE NULLS LAST) AS rnk_fst     FROM ( SELECT        *  FROM        APPLICATION_VARIABLES )   ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_11
ON dsf_11.STRING_VALUE = 'FX_HAIRCUT_SWITCH'
),

DSR_SC_mplt_DV_BOE_FIXMLOut as (
	/* transType: "Expression" */
Select 
	EXP_CASH_COLOut2.ENABLE_IND as GenericIdentificationType1Code_T1_I_ENABLE_IND,
	 EXP_CASH_COLOut2.o_Ccy as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 EXP_CASH_COLOut2.ValuePostHaircut as AssetTypeCheck_T1_I_ValuePostHaircut,
	 EXP_CASH_COLOut2.CC_WATERFALL_SRVC as I_WATERFALL_SRVC,
	 EXP_CASH_COLOut2.CollateralAccountID as CollateralReport_T1_ACCT_ID,
	 EXP_CASH_COLOut2.ENABLE_IND as CollateralReport_ENABLE_IND,
	 EXP_CASH_COLOut2.AssetType as AssetTypeCheck_T1_I_ASSET_TYPE,
	 EXP_CASH_COLOut2.CC_DEFAULT_FUND as I_WATERFALL_NM,
	 EXP_CASH_COLOut2.ENABLE_IND as I_WATERFALL_NM_ENABLE_IND,
	 EXP_CASH_COLOut2.ENABLE_IND as I_WATERFALL_SRVC_ENABLE_IND,
	 EXP_CASH_COLOut2.Cash_Value as AssetTypeCheck_T1_I_Cash_Value,
	 EXP_CASH_COLOut2.CC_CASH_COLLATERAL_AMOUNT as ZeroValCheck_T1_I_Cash_Value,
	 EXP_CASH_COLOut2.o_SUB_ACCOUNT as COL_RPT_VAL_SUB_ACC,
	 EXP_CASH_COLOut2.CC_MNEMONIC as COL_RPT_VAL_MNE,
	 EXP_CASH_COLOut2.ENABLE_IND as AssetTypeCheck_T1_I_ENABLE_IND,
	 EXP_CASH_COLOut2.CollateralRequirement as CollateralRequirementType1Code_T1_I_COLL_REQ_TYPE,
	 EXP_CASH_COLOut2.ENABLE_IND as ZeroValCheck_T1_I_Cash_Value_ENABLE_IND,
	 EXP_CASH_COLOut2.CC_EXCHANGE as COL_RPT_VAL_SERVICE,
	 EXP_CASH_COLOut2.ENABLE_IND as CollateralRequirementType1Code_T1_I_ENABLE_IND,
	 EXP_CASH_COLOut2.ENABLE_IND as COL_RPT_VAL_EN_IND,
	 EXP_CASH_COLOut2.ENABLE_IND as ActiveCurrencyCode_T7_I_ENABLE_IND
From EXP_CASH_COLOut as EXP_CASH_COLOut),

SC_mplt_DV_BOE_FIXMLOut as (
	/* transType: "MAPPLET" */
Select 
	ENABLE_IND as GenericIdentificationType1Code_T1_I_ENABLE_IND,
	 o_Ccy as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 ValuePostHaircut as AssetTypeCheck_T1_I_ValuePostHaircut,
	 CC_WATERFALL_SRVC as I_WATERFALL_SRVC,
	 CollateralAccountID as CollateralReport_T1_ACCT_ID,
	 ENABLE_IND as CollateralReport_ENABLE_IND,
	 AssetType as AssetTypeCheck_T1_I_ASSET_TYPE,
	 CC_DEFAULT_FUND as I_WATERFALL_NM,
	 ENABLE_IND as I_WATERFALL_NM_ENABLE_IND,
	 ENABLE_IND as I_WATERFALL_SRVC_ENABLE_IND,
	 Cash_Value as AssetTypeCheck_T1_I_Cash_Value,
	 CC_CASH_COLLATERAL_AMOUNT as ZeroValCheck_T1_I_Cash_Value,
	 o_SUB_ACCOUNT as COL_RPT_VAL_SUB_ACC,
	 CC_MNEMONIC as COL_RPT_VAL_MNE,
	 ENABLE_IND as AssetTypeCheck_T1_I_ENABLE_IND,
	 CollateralRequirement as CollateralRequirementType1Code_T1_I_COLL_REQ_TYPE,
	 ENABLE_IND as ZeroValCheck_T1_I_Cash_Value_ENABLE_IND,
	 CC_EXCHANGE as COL_RPT_VAL_SERVICE,
	 ENABLE_IND as CollateralRequirementType1Code_T1_I_ENABLE_IND,
	 ENABLE_IND as COL_RPT_VAL_EN_IND,
	 ENABLE_IND as ActiveCurrencyCode_T7_I_ENABLE_IND,
	 ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 Sender_Scheme_Name as Sender_Scheme_Name,
	 Sender_LEI as Sender_LEI,
	 o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 Receiver_Scheme_Name as Receiver_Scheme_Name,
	 O_AccountIDScheme as CollateralAccountIDType,
	 Msg_Def_Id as Msg_Def_Id,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 ActiveCurrencyCode_T7_I_CURR_MNE_CASH1 as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 Receiver_LEI as Receiver_LEI,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE 
From DSR_SC_mplt_DV_BOE_FIXMLOut as DSR_SC_mplt_DV_BOE_FIXMLOut),

SC_mplt_DV_BOE_FIXML_master as (
  Select
  	SC_mplt_DV_BOE_FIXMLOut.Msg_Def_Id as Msg_Def_Id,
	 SC_mplt_DV_BOE_FIXMLOut.Receiver_Scheme_Name as Receiver_Scheme_Name,
	 SC_mplt_DV_BOE_FIXMLOut.Receiver_LEI as Receiver_LEI,
	 SC_mplt_DV_BOE_FIXMLOut.Sender_Scheme_Name as Sender_Scheme_Name,
	 SC_mplt_DV_BOE_FIXMLOut.Sender_LEI as Sender_LEI,
	 SC_mplt_DV_BOE_FIXMLOut.O_AccountIDScheme as CollateralAccountIDType,
	 SC_mplt_DV_BOE_FIXMLOut.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXMLOut.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXMLOut.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXMLOut.AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 SC_mplt_DV_BOE_FIXMLOut.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXMLOut.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXMLOut.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 SC_mplt_DV_BOE_FIXMLOut.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXMLOut.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXMLOut.ActiveCurrencyCode_T7_I_CURR_MNE_CASH1 as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 SC_mplt_DV_BOE_FIXMLOut.ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 SC_mplt_DV_BOE_FIXMLOut.ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 SC_mplt_DV_BOE_FIXMLOut.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXMLOut.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXMLOut.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXMLOut.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXMLOut.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXMLOut.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXMLOut.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXMLOut.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXMLOut.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXMLOut.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXMLOut.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 SC_mplt_DV_BOE_FIXMLOut.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXMLOut.o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 SC_mplt_DV_BOE_FIXMLOut.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXMLOut.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXMLOut.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXMLOut.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL
  From SC_mplt_DV_BOE_FIXMLOut as SC_mplt_DV_BOE_FIXMLOut
),
dsJoiner_EXP_CASH0Out as (
	/* transType: "Joiner" */
Select 
	SC_mplt_DV_BOE_FIXML_master.Msg_Def_Id as Msg_Def_Id,
	 SC_mplt_DV_BOE_FIXML_master.Receiver_Scheme_Name as Receiver_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML_master.Receiver_LEI as Receiver_LEI,
	 SC_mplt_DV_BOE_FIXML_master.Sender_Scheme_Name as Sender_Scheme_Name,
	 SC_mplt_DV_BOE_FIXML_master.Sender_LEI as Sender_LEI,
	 EXP_CASH_COLOut.CollateralAccountID as CollateralAccountID,
	 SC_mplt_DV_BOE_FIXML_master.CollateralAccountIDType as CollateralAccountIDType,
	 EXP_CASH_COLOut.AssetType as AssetType,
	 EXP_CASH_COLOut.Cash_Value_Ccy as Cash_Value_Ccy,
	 EXP_CASH_COLOut.CollateralRequirement as CollateralRequirement,
	 EXP_CASH_COLOut.FILENAME as FILENAME,
	 SC_mplt_DV_BOE_FIXML_master.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML_master.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML_master.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML_master.AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 SC_mplt_DV_BOE_FIXML_master.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML_master.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML_master.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 SC_mplt_DV_BOE_FIXML_master.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML_master.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML_master.ActiveCurrencyCode_T7_I_CURR_MNE_CASH as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 SC_mplt_DV_BOE_FIXML_master.ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 SC_mplt_DV_BOE_FIXML_master.ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 SC_mplt_DV_BOE_FIXML_master.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML_master.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML_master.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML_master.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML_master.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML_master.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 SC_mplt_DV_BOE_FIXML_master.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML_master.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML_master.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML_master.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML_master.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 SC_mplt_DV_BOE_FIXML_master.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML_master.o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 SC_mplt_DV_BOE_FIXML_master.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML_master.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML_master.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 SC_mplt_DV_BOE_FIXML_master.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 EXP_CASH_COLOut.ID_CASH as ID_CASH,
	 EXP_CASH_COLOut.ValuePostHaircut_Ccy as ValuePostHaircut_Ccy,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
SC_mplt_DV_BOE_FIXML_master as SC_mplt_DV_BOE_FIXML_master inner JOIN EXP_CASH_COLOut as EXP_CASH_COLOut 
ON
EXP_CASH_COLOut.jkey = SC_mplt_DV_BOE_FIXML_master.jkey 
),

EXP_CASHOut as (
	/* transType: "Expression" */
Select 
	Msg_Def_Id as Msg_Def_Id,
	 Receiver_Scheme_Name as Receiver_Scheme_Name,
	 Receiver_LEI as Receiver_LEI,
	 Sender_Scheme_Name as Sender_Scheme_Name,
	 Sender_LEI as Sender_LEI,
	 CollateralAccountID as CollateralAccountID,
	 CollateralAccountIDType as CollateralAccountIDType,
	 AssetType as AssetType,
	 Cash_Value_Ccy as Cash_Value_Ccy,
	 CollateralRequirement as CollateralRequirement,
	 FILENAME as FILENAME,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 ActiveCurrencyCode_T7_I_CURR_MNE_CASH as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 WATERFALL_NM_VAL as WATERFALL_NM_VAL,
	 WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 WATERFALL_SRVC_VAL as WATERFALL_SRVC_VAL,
	 WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 ( CASE WHEN o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL = 1 OR ( o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL = 1 ) OR o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL = 1 OR o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL = 1 OR o_ZeroValCheck_CASH_VALUE_VAL_FAIL = 1 OR o_CollateralReportVal_T1_VAL_FAIL = 1 OR WATERFALL_NM_FAIL = 1 OR WATERFALL_SRVC_FAIL = 1 THEN 'Y' ELSE 'N' END ) as ERROR_IND,
	 '{{ var("PMWorkflowName") }}' as WORKFLOW_NAME,
	 '{{ var("PMMappingName") }}' as MAPPING_NAME,
	 '{{ var("BATCH_ID") }}' as O_BATCH_ID,
	 TO_DATE ( LTRIM ( RTRIM ( '{{ var("BATCH_BUSINESS_DATE") }}' ) ),
	 'YYYYMMDD' ) as O_BATCH_BUSINESS_DATE,
	 ID_CASH as ID_CASH,
	 ValuePostHaircut_Ccy as ValuePostHaircut_Ccy
From dsJoiner_EXP_CASH0Out as dsJoiner_EXP_CASH0Out),

EXP_CASH_COL_master as (
  Select
  	EXP_CASH_COLOut.FILE_GEN_DETAILS_ID as FILE_GEN_ID
  From EXP_CASH_COLOut as EXP_CASH_COLOut
),

EXP_CASH_details as (
  Select
  	EXP_CASHOut.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 EXP_CASHOut.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 EXP_CASHOut.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 EXP_CASHOut.ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 EXP_CASHOut.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 EXP_CASHOut.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 EXP_CASHOut.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 EXP_CASHOut.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 EXP_CASHOut.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 EXP_CASHOut.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 EXP_CASHOut.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 EXP_CASHOut.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 EXP_CASHOut.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 EXP_CASHOut.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 EXP_CASHOut.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 EXP_CASHOut.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 EXP_CASHOut.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 EXP_CASHOut.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 EXP_CASHOut.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 EXP_CASHOut.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 EXP_CASHOut.ActiveCurrencyCode_T7_I_CURR_MNE_CASH as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 EXP_CASHOut.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 EXP_CASHOut.ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 EXP_CASHOut.FILENAME as FILENAME,
	 EXP_CASHOut.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 EXP_CASHOut.ERROR_IND as ERROR_IND,
	 EXP_CASHOut.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 EXP_CASHOut.ID_CASH as ID_CASH,
	 EXP_CASHOut.o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 EXP_CASHOut.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 EXP_CASHOut.O_BATCH_BUSINESS_DATE as o_BATCH_BUSINESS_DATE,
	 EXP_CASHOut.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 EXP_CASHOut.MAPPING_NAME as MAPPING_NAME,
	 EXP_CASHOut.O_BATCH_ID as o_BATCH_ID,
	 EXP_CASHOut.AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 EXP_CASHOut.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 EXP_CASHOut.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 EXP_CASHOut.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 EXP_CASHOut.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 EXP_CASHOut.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_CASHOut.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 EXP_CASHOut.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 EXP_CASHOut.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT
  From EXP_CASHOut as EXP_CASHOut
),
dsJoiner_FIL_CASH_ERR_RECS0Out as (
	/* transType: "Joiner" */
Select 
	EXP_CASH_COL_master.FILE_GEN_ID as FILE_GEN_ID,
	 EXP_CASH_details.WATERFALL_SRVC_COMB_INPUT as WATERFALL_SRVC_COMB_INPUT,
	 EXP_CASH_details.WATERFALL_NM_FAIL as WATERFALL_NM_FAIL,
	 EXP_CASH_details.WATERFALL_SRVC_NAME as WATERFALL_SRVC_NAME,
	 EXP_CASH_details.ActiveCurrencyCode_T7_I_ENABLE_IND1 as ActiveCurrencyCode_T7_I_ENABLE_IND1,
	 EXP_CASH_details.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL,
	 EXP_CASH_details.WATERFALL_SRVC_ERROR_CODE as WATERFALL_SRVC_ERROR_CODE,
	 EXP_CASH_details.WATERFALL_SRVC_FAIL as WATERFALL_SRVC_FAIL,
	 EXP_CASH_details.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT,
	 EXP_CASH_details.CollateralReportVal_ERROR_CODE as CollateralReportVal_ERROR_CODE,
	 EXP_CASH_details.o_CollateralReportVal_NAME as o_CollateralReportVal_NAME,
	 EXP_CASH_details.CollateralReportVal_T1_I_COMB_INPUT as CollateralReportVal_T1_I_COMB_INPUT,
	 EXP_CASH_details.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL,
	 EXP_CASH_details.o_AssetTypeCheck_ASSET_TYPE_NAME as o_AssetTypeCheck_ASSET_TYPE_NAME,
	 EXP_CASH_details.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as o_GenericIdentificationType1Code_ACCT_TYPE_NAME,
	 EXP_CASH_details.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME,
	 EXP_CASH_details.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE,
	 EXP_CASH_details.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE,
	 EXP_CASH_details.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT,
	 EXP_CASH_details.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL,
	 EXP_CASH_details.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL,
	 EXP_CASH_details.ActiveCurrencyCode_T7_I_CURR_MNE_CASH as ActiveCurrencyCode_T7_I_CURR_MNE_CASH,
	 EXP_CASH_details.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT,
	 EXP_CASH_details.ActiveCurrencyCode_T7_O_CURR_MNE_CASH as ActiveCurrencyCode_T7_O_CURR_MNE_CASH,
	 EXP_CASH_details.FILENAME as FILENAME,
	 EXP_CASH_details.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE,
	 EXP_CASH_details.ERROR_IND as ERROR_IND,
	 EXP_CASH_details.o_CollateralReportVal_T1_VAL_FAIL as o_CollateralReportVal_T1_VAL_FAIL,
	 EXP_CASH_details.ID_CASH as ID_CASH,
	 EXP_CASH_details.o_ZeroValCheck_CASH_VALUE_NAME as o_ZeroValCheck_CASH_VALUE_NAME,
	 EXP_CASH_details.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as ZeroValCheck_CASH_VALUE_I_COMB_INPUT,
	 EXP_CASH_details.o_BATCH_BUSINESS_DATE as o_BATCH_BUSINESS_DATE,
	 EXP_CASH_details.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE,
	 EXP_CASH_details.MAPPING_NAME as MAPPING_NAME,
	 EXP_CASH_details.o_BATCH_ID as o_BATCH_ID,
	 EXP_CASH_details.AssetTypeCheck_T1_I_ASSET_TYPE1 as AssetTypeCheck_T1_I_ASSET_TYPE1,
	 EXP_CASH_details.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as AssetTypeCheck_ASSET_TYPE_ERROR_CODE,
	 EXP_CASH_details.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as o_ActiveCurrencyCode_CURR_MNE_CASH_NAME,
	 EXP_CASH_details.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as o_ZeroValCheck_CASH_VALUE_VAL_FAIL,
	 EXP_CASH_details.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT,
	 EXP_CASH_details.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_CASH_details.WATERFALL_NM_NAME as WATERFALL_NM_NAME,
	 EXP_CASH_details.WATERFALL_NM_ERROR_CODE as WATERFALL_NM_ERROR_CODE,
	 EXP_CASH_details.WATERFALL_NM_COMB_INPUT as WATERFALL_NM_COMB_INPUT,
	 ROW_NUMBER ( ) OVER ( ORDER BY 1 ) as jkey 
From
EXP_CASH_COLOut1 as EXP_CASH_COLOut1 inner JOIN EXP_CASH_details as EXP_CASH_details 
ON
EXP_CASH_details.jkey = EXP_CASH_COLOut1.jkey 
),

DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut as (
	/* transType: "Expression" */
Select 
	FIL_CASH_ERR_RECSOut.o_BATCH_ID as INPUT_BATCH_ID,
	 FIL_CASH_ERR_RECSOut.o_BATCH_BUSINESS_DATE as INPUT_BATCH_BUSINESS_DATE,
	 FIL_CASH_ERR_RECSOut.AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_1,
	 FIL_CASH_ERR_RECSOut.o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_1,
	 FIL_CASH_ERR_RECSOut.o_GenericIdentificationType1Code_ACCT_TYPE_NAME as INPUT_ATTRIBUTE_NAME_4,
	 FIL_CASH_ERR_RECSOut.WATERFALL_NM_FAIL as INPUT_ERROR_SEVERITY_7,
	 FIL_CASH_ERR_RECSOut.GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_4,
	 FIL_CASH_ERR_RECSOut.WATERFALL_NM_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_7,
	 FIL_CASH_ERR_RECSOut.CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_3,
	 FIL_CASH_ERR_RECSOut.WATERFALL_NM_NAME as INPUT_ATTRIBUTE_NAME_7,
	 FIL_CASH_ERR_RECSOut.WATERFALL_SRVC_NAME as INPUT_ATTRIBUTE_NAME_8,
	 FIL_CASH_ERR_RECSOut.MAPPING_NAME as INPUT_MAPPING_NAME,
	 FIL_CASH_ERR_RECSOut.WATERFALL_SRVC_ERROR_CODE as INPUT_ERROR_CODE_8,
	 FIL_CASH_ERR_RECSOut.CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as INPUT_ERROR_CODE_3,
	 FIL_CASH_ERR_RECSOut.WATERFALL_SRVC_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_8,
	 FIL_CASH_ERR_RECSOut.CollateralReportVal_ERROR_CODE as INPUT_ERROR_CODE_5,
	 FIL_CASH_ERR_RECSOut.o_CollateralReportVal_NAME as INPUT_ATTRIBUTE_NAME_5,
	 FIL_CASH_ERR_RECSOut.CollateralReportVal_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_5,
	 FIL_CASH_ERR_RECSOut.ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as INPUT_ERROR_CODE_6,
	 FIL_CASH_ERR_RECSOut.o_AssetTypeCheck_ASSET_TYPE_NAME as INPUT_ATTRIBUTE_NAME_1,
	 FIL_CASH_ERR_RECSOut.AssetTypeCheck_ASSET_TYPE_ERROR_CODE as INPUT_ERROR_CODE_1,
	 FIL_CASH_ERR_RECSOut.ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as INPUT_ERROR_CODE_2,
	 FIL_CASH_ERR_RECSOut.FILENAME as INPUT_TARGET_NAME,
	 FIL_CASH_ERR_RECSOut.o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_3,
	 FIL_CASH_ERR_RECSOut.WATERFALL_NM_ERROR_CODE as INPUT_ERROR_CODE_7,
	 FIL_CASH_ERR_RECSOut.WATERFALL_SRVC_FAIL as INPUT_ERROR_SEVERITY_8,
	 FIL_CASH_ERR_RECSOut.o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as INPUT_ATTRIBUTE_NAME_3,
	 FIL_CASH_ERR_RECSOut.o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_4,
	 FIL_CASH_ERR_RECSOut.o_CollateralReportVal_T1_VAL_FAIL as INPUT_ERROR_SEVERITY_5,
	 FIL_CASH_ERR_RECSOut.GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as INPUT_ERROR_CODE_4,
	 FIL_CASH_ERR_RECSOut.o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as INPUT_ATTRIBUTE_NAME_2,
	 FIL_CASH_ERR_RECSOut.o_ZeroValCheck_CASH_VALUE_NAME as INPUT_ATTRIBUTE_NAME_6,
	 FIL_CASH_ERR_RECSOut.o_ZeroValCheck_CASH_VALUE_VAL_FAIL as INPUT_ERROR_SEVERITY_6,
	 FIL_CASH_ERR_RECSOut.FILE_GEN_ID as INPUT_BATCH_DETAILS_ID,
	 FIL_CASH_ERR_RECSOut.ZeroValCheck_CASH_VALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_6,
	 FIL_CASH_ERR_RECSOut.o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as INPUT_ERROR_SEVERITY_2,
	 FIL_CASH_ERR_RECSOut.ID_CASH as INPUT_REFERENCE_RECORD_ID,
	 FIL_CASH_ERR_RECSOut.WORKFLOW_NAME as INPUT_WORKFLOW_NAME,
	 FIL_CASH_ERR_RECSOut.ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_2 
From dsJoiner_FIL_CASH_ERR_RECS0Out as dsJoiner_FIL_CASH_ERR_RECS0Out Where ERROR_IND = 'N'),

SC_mplt_DV_PROCESS_ERROR_DETAILSOut as (
	/* transType: "MAPPLET" */
Select 
	ERROR_SEVERITY as ERROR_SEVERITY,
	 PROCESS_DATE as PROCESS_DATE,
	 ADDITIONAL_DETAILS as ADDITIONAL_DETAILS,
	 REFERENCE_SUB_PROCESS as REFERENCE_SUB_PROCESS,
	 REFERENCE_BATCH_DETAILS_ID as REFERENCE_BATCH_DETAILS_ID,
	 REFERENCE_PROCESS as REFERENCE_PROCESS,
	 REFERENCE_TARGET_NAME as REFERENCE_TARGET_NAME,
	 REFERENCE_BATCH_ID as REFERENCE_BATCH_ID,
	 ID as ID,
	 REFERENCE_ATTRIBUTE_VALUE as REFERENCE_ATTRIBUTE_VALUE,
	 REFERENCE_RECORD_ID as REFERENCE_RECORD_ID,
	 REFERENCE_BUSINESS_KEY as REFERENCE_BUSINESS_KEY,
	 REFERENCE_ATTRIBUTE_NAME as REFERENCE_ATTRIBUTE_NAME,
	 ERROR_CODE as ERROR_CODE,
	 o_BATCH_ID as INPUT_BATCH_ID,
	 o_BATCH_BUSINESS_DATE as INPUT_BATCH_BUSINESS_DATE,
	 AssetTypeCheck_ASSET_TYPEE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_1,
	 o_AssetTypeCheck_ASSET_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_1,
	 o_GenericIdentificationType1Code_ACCT_TYPE_NAME as INPUT_ATTRIBUTE_NAME_4,
	 WATERFALL_NM_FAIL as INPUT_ERROR_SEVERITY_7,
	 GenericIdentificationType1Code_T1_I_ACCT_TYPE_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_4,
	 WATERFALL_NM_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_7,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_3,
	 WATERFALL_NM_NAME as INPUT_ATTRIBUTE_NAME_7,
	 WATERFALL_SRVC_NAME as INPUT_ATTRIBUTE_NAME_8,
	 MAPPING_NAME as INPUT_MAPPING_NAME,
	 WATERFALL_SRVC_ERROR_CODE as INPUT_ERROR_CODE_8,
	 CollateralRequirementType1Code_COLL_REQ_TYPE_ERROR_CODE as INPUT_ERROR_CODE_3,
	 WATERFALL_SRVC_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_8,
	 CollateralReportVal_ERROR_CODE as INPUT_ERROR_CODE_5,
	 o_CollateralReportVal_NAME as INPUT_ATTRIBUTE_NAME_5,
	 CollateralReportVal_T1_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_5,
	 ZeroValCheck_CASH_VALUE_NAME_ERROR_CODE as INPUT_ERROR_CODE_6,
	 o_AssetTypeCheck_ASSET_TYPE_NAME as INPUT_ATTRIBUTE_NAME_1,
	 AssetTypeCheck_ASSET_TYPE_ERROR_CODE as INPUT_ERROR_CODE_1,
	 ActiveCurrencyCode_CURR_MNE_CASH_ERROR_CODE as INPUT_ERROR_CODE_2,
	 FILENAME as INPUT_TARGET_NAME,
	 o_CollateralRequirementType1Code_T1_O_COLL_REQ_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_3,
	 WATERFALL_NM_ERROR_CODE as INPUT_ERROR_CODE_7,
	 WATERFALL_SRVC_FAIL as INPUT_ERROR_SEVERITY_8,
	 o_CollateralRequirementType1Code_COLL_REQ_TYPE_NAME as INPUT_ATTRIBUTE_NAME_3,
	 o_GenericIdentificationType1Code_T1_O_ACCT_TYPE_VAL_FAIL as INPUT_ERROR_SEVERITY_4,
	 o_CollateralReportVal_T1_VAL_FAIL as INPUT_ERROR_SEVERITY_5,
	 GenericIdentificationType1Code_ACCT_TYPE_ERROR_CODE as INPUT_ERROR_CODE_4,
	 o_ActiveCurrencyCode_CURR_MNE_CASH_NAME as INPUT_ATTRIBUTE_NAME_2,
	 o_ZeroValCheck_CASH_VALUE_NAME as INPUT_ATTRIBUTE_NAME_6,
	 o_ZeroValCheck_CASH_VALUE_VAL_FAIL as INPUT_ERROR_SEVERITY_6,
	 FILE_GEN_ID as INPUT_BATCH_DETAILS_ID,
	 ZeroValCheck_CASH_VALUE_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_6,
	 o_ActiveCurrencyCode_T7_CURR_MNE_VAL_FAIL as INPUT_ERROR_SEVERITY_2,
	 ID_CASH as INPUT_REFERENCE_RECORD_ID,
	 WORKFLOW_NAME as INPUT_WORKFLOW_NAME,
	 ActiveCurrencyCode_CURR_MNE_T7_I_COMB_INPUT as INPUT_ATTRIBUTE_VALUE_2 
From DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut as DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut)

Select 
	ID as ID,
	PROCESS_DATE as PROCESS_DATE,
	REFERENCE_BATCH_ID as REFERENCE_BATCH_ID,
	REFERENCE_PROCESS as REFERENCE_PROCESS,
	REFERENCE_SUB_PROCESS as REFERENCE_SUB_PROCESS,
	REFERENCE_TARGET_NAME as REFERENCE_TARGET_NAME,
	REFERENCE_RECORD_ID as REFERENCE_RECORD_ID,
	REFERENCE_BUSINESS_KEY as REFERENCE_BUSINESS_KEY,
	REFERENCE_ATTRIBUTE_NAME as REFERENCE_ATTRIBUTE_NAME,
	REFERENCE_ATTRIBUTE_VALUE as REFERENCE_ATTRIBUTE_VALUE,
	ERROR_CODE as ERROR_CODE,
	ERROR_SEVERITY as ERROR_SEVERITY,
	ADDITIONAL_DETAILS as ADDITIONAL_DETAILS,
	REFERENCE_BATCH_DETAILS_ID as REFERENCE_BATCH_DETAILS_ID 
From SC_mplt_DV_PROCESS_ERROR_DETAILSOut as SC_mplt_DV_PROCESS_ERROR_DETAILSOut