{{
  config(
    materialized='incremental',
    alias='SWP_CLEARED_PRODUCTS_DIM',
    schema='',
    pre_hook="",
    post_hook="",
    incremental_strategy='merge',
    unique_key=['ID'],
    merge_update_columns=['EXPIRATION_DATE']
  )
}}
With SQ_SC_SWP_CLEARED_PRODUCTS_DIMOut as (
	/* transType: "Source" */
Select ID, 
		BATCH_ID, 
		BATCH_DETAILS_ID, 
		EFFECTIVE_DATE, 
		EXPIRATION_DATE, 
		VENUE, 
		ASSET_CLASS, 
		BASE_PRODUCT, 
		SUB_PRODUCT, 
		ISDA_PRODUCT_TYPE, 
		INDEX_1_MUREX_NAME, 
		INDEX_1_PAY_FREQ, 
		INDEX_1_TENOR_CCY, 
		INDEX_1_DAY_COUNT, 
		INDEX_2_MUREX_NAME, 
		INDEX_2_PAY_FREQ, 
		INDEX_2_TENOR_CCY, 
		INDEX_2_DAY_COUNT, 
		MAX_CONTRACT_TENOR_VALUE, 
		MAX_CONTRACT_TENOR_UNIT, 
		PROPAGATE_INDICATOR, 
		ERROR_INDICATOR, 
		LCH_PRODUCT_TYPE, 
		BOE_INDEX_1_DAY_COUNT, 
		BOE_INDEX_2_PAY_FREQ, 
		BOE_INDEX_2_DAY_COUNT, 
		BOE_INDEX_1_PAY_FREQ, 
		BOE_CONTRACT_TENOR_VALUE, 
		BOE_CONTRACT_TENOR_UNIT, 
		TENOR_KEY
 from 
{{ source ('SC_SWP_CLEARED_PRODUCTS_DIM','SWP_CLEARED_PRODUCTS_DIM') }} 
 ),

EXP_INTOut as (
	/* transType: "Expression" */
Select 
	ID as ID,
	 EXPIRATION_DATE as EXPIRATION_DATE,
	 TO_DATE ( '01-JAN-99',
	 'DD-MON-YY' ) as O_EXPIRATION_DATE,
	 TO_TIMESTAMP ( TO_VARCHAR ( EXPIRATION_DATE,
	 'DD-MON-YYYY HH24:SS:MI' ),
	 'DD-MON-YYYY HH24:SS:MI' ) as V_EXPIRATION_DATE,
	 TO_TIMESTAMP ( '12-DEC-2300 00:00:00',
	 'DD-MON-YYYY HH24:SS:MI' ) as V_EXPIRATION_DATE_UPD,
	 ( CASE WHEN V_EXPIRATION_DATE = V_EXPIRATION_DATE_UPD THEN 'Y' ELSE 'N' END ) as UPDATE_FLAG
From SQ_SC_SWP_CLEARED_PRODUCTS_DIMOut as SQ_SC_SWP_CLEARED_PRODUCTS_DIMOut),

FIL_UPD_EXPIRATION_DATEOut as (
	/* transType: "Filter" */
Select 
 * 
From EXP_INTOut as EXP_INTOut Where UPDATE_FLAG = 'Y')

Select 
	ID as ID,
	O_EXPIRATION_DATE as EXPIRATION_DATE 
From FIL_UPD_EXPIRATION_DATEOut as FIL_UPD_EXPIRATION_DATEOut