/* Transformation Name ==>SC_PROCESS_ERROR_DETAILS ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='PROCESS_ERROR_DETAILS',
		schema='EMIR_SHARED',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut as (
	Select BUSINESSDATE, 
		EODIND, 
		RUNID, 
		MEMBERMNEMONIC, 
		MARGINACCOUNTCATEGORY, 
		ISIN, 
		AGENTCODE, 
		CURRENCYCODE, 
		INTENDEDSETTLEMENTDATE, 
		VARIATIONMARGIN, 
		EXCLUSIONIND, 
		CFDMTM, 
		PRODUCTCODE, 
		MARGIN_ACCOUNT_REFERENCE, 
		MARGIN_AGG_ACCOUNT, 
		CLIENTPROTECTED, 
		CLIENTIDENTIFIERTYPE, 
		CurrentlyProcessedFileName
 from 
{{ source('snowflake_databricks_test_0', 'IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsv') }} 
 ),

SC_SEQ_RR_ECL_VARIATION_MARGIN_FACTOut as (
	Select 
	SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.CFDMTM as CFDMTM,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.VARIATIONMARGIN as VARIATIONMARGIN,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.MEMBERMNEMONIC as MEMBERMNEMONIC,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.PRODUCTCODE as PRODUCTCODE,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.MARGIN_ACCOUNT_REFERENCE as MARGIN_ACCOUNT_REFERENCE,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.CLIENTIDENTIFIERTYPE as CLIENTIDENTIFIERTYPE,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.INTENDEDSETTLEMENTDATE as INTENDEDSETTLEMENTDATE,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.CLIENTPROTECTED as CLIENTPROTECTED,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.RUNID as RUNID,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.EXCLUSIONIND as EXCLUSIONIND,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.MARGIN_AGG_ACCOUNT as MARGIN_AGG_ACCOUNT,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.CURRENCYCODE as CURRENCYCODE,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.MARGINACCOUNTCATEGORY as MARGINACCOUNTCATEGORY,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.BUSINESSDATE as BUSINESSDATE,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.ISIN as ISIN,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.EODIND as EODIND,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.AGENTCODE as AGENTCODE,
	 SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut.CurrentlyProcessedFileName as CurrentlyProcessedFileName 
FROM SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut as SQ_SC_IH_ECL_variationmarginbyisd_YYYYMMDD_ITD_runidcsvOut),

Target_Table_Name_SK_Max_Value AS (
  SELECT
    MAX(GEN_SEQ) AS max_gen_seq
  FROM {{ this }}
),

 EXP_TRIM_TRAILING_SPACES_variableOut as (
	
Select 
(SELECT max_gen_seq FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER() AS GEN_SEQ,
BUSINESSDATE as BUSINESSDATE,
EODIND as EODIND,
RUNID as RUNID,
MEMBERMNEMONIC as MEMBERMNEMONIC,
MARGINACCOUNTCATEGORY as MARGINACCOUNTCATEGORY,
ISIN as ISIN,
AGENTCODE as AGENTCODE,
CURRENCYCODE as CURRENCYCODE,
INTENDEDSETTLEMENTDATE as INTENDEDSETTLEMENTDATE,
VARIATIONMARGIN as VARIATIONMARGIN,
EXCLUSIONIND as EXCLUSIONIND,
CFDMTM as CFDMTM,
PRODUCTCODE as PRODUCTCODE,
MARGIN_ACCOUNT_REFERENCE as MARGIN_ACCOUNT_REFERENCE,
CLIENTPROTECTED as CLIENTPROTECTED,
CLIENTIDENTIFIERTYPE as CLIENTIDENTIFIERTYPE,
CurrentlyProcessedFileName as CurrentlyProcessedFileName,
MARGIN_AGG_ACCOUNT as MARGIN_AGG_ACCOUNT,
LPAD ( GEN_SEQ,
9,
'0' ) as v_SEQ_LPAD_TO_9,
DATEDIFF ( SECOND,
TO_TIMESTAMP ( '01/01/1970 00:00:00',
'DD-MM-YYYY HH24:MI:SS' ),
CURRENT_TIMESTAMP ) as v_EPOC_TIME,
v_EPOC_TIME || v_SEQ_LPAD_TO_9 as v_CONCATE_ID,
DATE_TRUNC ( 'DAY',
TO_DATE ( LTRIM ( RTRIM ( BUSINESSDATE ) ),
'YYYYMMDD' ) ) as v_BUSINESSDATE,
dsf_1.ID as v_EXCHANGE_ID,
LTRIM ( RTRIM ( EODIND ) ) as v_EODIND,
dsf_2.ID as v_MEMBER_COUNTERPARTY_ID,
( CASE WHEN v_MEMBER_COUNTERPARTY_ID IS NULL THEN -2 ELSE v_MEMBER_COUNTERPARTY_ID END ) as v_MEMBER_COUNTERPARTY_ID_Deri,
LTRIM ( RTRIM ( MARGINACCOUNTCATEGORY ) ) as v_MARGINACCOUNTCATEGORY,
LTRIM ( RTRIM ( AGENTCODE ) ) as v_AGENTCODE,
TO_DATE ( LTRIM ( RTRIM ( SUBSTRING ( INTENDEDSETTLEMENTDATE,
1,
8 ) ) ),
'YYYYMMDD' ) as v_INTENDEDSETTLEMENTDATE,
LTRIM ( RTRIM ( VARIATIONMARGIN ) ) as v_VARIATIONMARGIN,
LTRIM ( RTRIM ( EXCLUSIONIND ) ) as v_EXCLUSIONIND,
LTRIM ( RTRIM ( CFDMTM ) ) as v_CFDMTM,
LTRIM ( RTRIM ( CurrentlyProcessedFileName ) ) as v_CurrentlyProcessedFileName,
SUBSTRING ( dsf_3.LEI_OR_CICI,
1,
REGEXP_INSTR ( dsf_3.LEI_OR_CICI,
'\\|',
1,
1 ) -1 ) as v_COUNTERPARTY_LEI,
SUBSTRING ( dsf_3.LEI_OR_CICI,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_3.LEI_OR_CICI ),
'\\|',
-1,
1 ) > 0,
length ( dsf_3.LEI_OR_CICI ) - REGEXP_INSTR ( REVERSE ( dsf_3.LEI_OR_CICI ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) as v_COUNTERPARTY_CICI,
( CASE WHEN ( v_COUNTERPARTY_LEI IS NULL OR v_COUNTERPARTY_LEI = '' ) THEN v_COUNTERPARTY_CICI ELSE v_COUNTERPARTY_LEI END ) as v_LEI_OR_CICI,
TO_VARCHAR ( v_VARIATIONMARGIN ) as v_VARIATIONMARGIN_str,
( CASE WHEN REGEXP_INSTR ( v_VARIATIONMARGIN_str || '0',
'.' ) > 1 THEN RTRIM ( RTRIM ( v_VARIATIONMARGIN_str || '',
'0' ),
'.' ) ELSE v_VARIATIONMARGIN_str || '' END ) as v_VARIATIONMARGIN_IAOV,
TO_VARCHAR ( v_EXCLUSIONIND ) as v_EXCLUSIONIND_str,
( CASE WHEN REGEXP_INSTR ( v_EXCLUSIONIND_str || '0',
'.' ) > 1 THEN RTRIM ( RTRIM ( v_EXCLUSIONIND_str || '',
'0' ),
'.' ) ELSE v_EXCLUSIONIND_str || '' END ) as v_EXCLUSIONIND_IAOV,
TO_VARCHAR ( v_CFDMTM ) as v_CFDMTM_str,
( CASE WHEN REGEXP_INSTR ( v_CFDMTM_str || '0',
'.' ) > 1 THEN RTRIM ( RTRIM ( v_CFDMTM_str || '',
'0' ),
'.' ) ELSE v_CFDMTM_str || '' END ) as v_CFDMTM_IAOV
From SC_SEQ_RR_ECL_VARIATION_MARGIN_FACTOut as SC_SEQ_RR_ECL_VARIATION_MARGIN_FACTOut
LEFT JOIN (
SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE FROM (  SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE ORDER BY EXCHANGE_MNEMONIC, EFFECTIVE_DATE, EXPIRATION_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    EXCHANGE_DIM.ID || '_' || EXCHANGE_DIM.ENTITY as ID,    EXCHANGE_DIM.NAME as NAME,    EXCHANGE_DIM.DEFAULT_FUND as DEFAULT_FUND,    EXCHANGE_DIM.ENTITY as ENTITY,    EXCHANGE_DIM.EXCHANGE_MNEMONIC as EXCHANGE_MNEMONIC,    EXCHANGE_DIM.EFFECTIVE_DATE as EFFECTIVE_DATE,    NVL(EXCHANGE_DIM.EXPIRATION_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EXPIRATION_DATE FROM    EXCHANGE_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.EXCHANGE_MNEMONIC = 'ECL' AND dsf_1.EFFECTIVE_DATE <= v_BUSINESSDATE AND dsf_1.EXPIRATION_DATE >= v_BUSINESSDATE
LEFT JOIN (
SELECT ID, EXCHANGE_MNEMONIC, LCH_UNIQUE_ID, CLEARING_MEMBER_MNEMONIC, EFFECTIVE_FROM_DATE, EFFECTIVE_TO_DATE FROM (  SELECT ID, EXCHANGE_MNEMONIC, LCH_UNIQUE_ID, CLEARING_MEMBER_MNEMONIC, EFFECTIVE_FROM_DATE, EFFECTIVE_TO_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, LCH_UNIQUE_ID, CLEARING_MEMBER_MNEMONIC, EFFECTIVE_FROM_DATE, EFFECTIVE_TO_DATE ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, EXCHANGE_MNEMONIC, LCH_UNIQUE_ID, CLEARING_MEMBER_MNEMONIC, EFFECTIVE_FROM_DATE, EFFECTIVE_TO_DATE,  ROW_NUMBER() OVER (PARTITION BY EXCHANGE_MNEMONIC, LCH_UNIQUE_ID, CLEARING_MEMBER_MNEMONIC, EFFECTIVE_FROM_DATE, EFFECTIVE_TO_DATE ORDER BY EXCHANGE_MNEMONIC, LCH_UNIQUE_ID, CLEARING_MEMBER_MNEMONIC, EFFECTIVE_FROM_DATE, EFFECTIVE_TO_DATE NULLS LAST) AS rnk_fst   FROM ( SELECT    COUNTERPARTIES_DIM.ID as ID,    COUNTERPARTIES_DIM.EXCHANGE_MNEMONIC as EXCHANGE_MNEMONIC,    COUNTERPARTIES_DIM.LCH_UNIQUE_ID as LCH_UNIQUE_ID,    COUNTERPARTIES_DIM.CLEARING_MEMBER_MNEMONIC as CLEARING_MEMBER_MNEMONIC,    COUNTERPARTIES_DIM.EFFECTIVE_FROM_DATE as EFFECTIVE_FROM_DATE,    NVL(COUNTERPARTIES_DIM.EFFECTIVE_TO_DATE,TO_DATE('31-DEC-2099','DD-MON-YYYY')) as EFFECTIVE_TO_DATE FROM    COUNTERPARTIES_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_2
ON dsf_2.EXCHANGE_MNEMONIC = -2 AND dsf_2.LCH_UNIQUE_ID = -2 AND dsf_2.CLEARING_MEMBER_MNEMONIC = MEMBERMNEMONIC AND dsf_2.EFFECTIVE_FROM_DATE <= TO_DATE('{{ var("batch_business_date") }}' AND dsf_2.EFFECTIVE_TO_DATE >= TO_DATE('{{ var("batch_business_date") }}'
LEFT JOIN (
SELECT LEI_OR_CICI, ID FROM (  SELECT LEI_OR_CICI, ID,  ROW_NUMBER() OVER (PARTITION BY ID ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT LEI_OR_CICI, ID,  ROW_NUMBER() OVER (PARTITION BY ID ORDER BY ID NULLS LAST) AS rnk_fst   FROM ( SELECT    COUNTERPARTIES_DIM.LEGAL_ENTITY_IDENTIFIER || '|' || COUNTERPARTIES_DIM.CFTC_INTERIM_COMPLIANT_ID as LEI_OR_CICI,    COUNTERPARTIES_DIM.LEGAL_ENTITY_IDENTIFIER as LEGAL_ENTITY_IDENTIFIER,    COUNTERPARTIES_DIM.CFTC_INTERIM_COMPLIANT_ID as CFTC_INTERIM_COMPLIANT_ID,    COUNTERPARTIES_DIM.ID as ID FROM    COUNTERPARTIES_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_3
ON dsf_3.ID = v_MEMBER_COUNTERPARTY_ID_Deri
),

EXP_TRIM_TRAILING_SPACESOut as (
	
Select 
v_CONCATE_ID as O_ID,
'{{ var("batch_id") }}' as o_BATCH_ID,
DATE_TRUNC ( 'DAY',
TO_DATE ( LTRIM ( RTRIM ( BUSINESSDATE ) ),
'YYYYMMDD' ) ) as o_BUSINESSDATE,
'LTD_STD' as CAL_TYPE,
1 as VERSION_ID,
'ECL' as EXCHANGE,
SUBSTRING ( v_EXCHANGE_ID,
1,
REGEXP_INSTR ( v_EXCHANGE_ID,
'_' ) -1 ) as EXCHANGE_ID,
'LCH.' || SUBSTRING ( v_EXCHANGE_ID,
REGEXP_INSTR ( v_EXCHANGE_ID,
'_' ) + 1 ) as ENTITY_NAME,
v_EODIND as o_EODIND,
LTRIM ( RTRIM ( RUNID ) ) as o_RUNID,
LTRIM ( RTRIM ( MEMBERMNEMONIC ) ) as o_MEMBERMNEMONIC,
v_MEMBER_COUNTERPARTY_ID_Deri as o_MEMBER_COUNTERPARTY_ID,
v_MARGINACCOUNTCATEGORY as o_MARGINACCOUNTCATEGORY,
LTRIM ( RTRIM ( ISIN ) ) as o_ISIN,
v_AGENTCODE as o_AGENTCODE,
dsf_1.ID as CURRENCYCODE_ID,
LTRIM ( RTRIM ( CURRENCYCODE ) ) as o_CURRENCYCODE_NAME,
v_INTENDEDSETTLEMENTDATE as o_INTENDEDSETTLEMENTDATE,
v_VARIATIONMARGIN as o_VARIATIONMARGIN,
v_EXCLUSIONIND as o_EXCLUSIONIND,
v_CFDMTM as o_CFDMTM,
LTRIM ( RTRIM ( PRODUCTCODE ) ) as o_PRODUCTCODE,
LTRIM ( RTRIM ( MARGIN_ACCOUNT_REFERENCE ) ) as o_MARGIN_ACCOUNT_REFERENCE,
LTRIM ( RTRIM ( CLIENTPROTECTED ) ) as o_CLIENTPROTECTED,
LTRIM ( RTRIM ( CLIENTIDENTIFIERTYPE ) ) as o_CLIENTIDENTIFIERTYPE,
( CASE WHEN SUBSTRING ( v_CurrentlyProcessedFileName,
REGEXP_INSTR ( v_CurrentlyProcessedFileName,
'/',
1,
7 ) + 1,
2 ) = 'IH' THEN 'ECL' ELSE ( CASE WHEN SUBSTRING ( v_CurrentlyProcessedFileName,
REGEXP_INSTR ( v_CurrentlyProcessedFileName,
'/',
1,
7 ) + 1,
3 ) = 'ECL' THEN 'MCCP' ELSE null END ) END ) as o_DATA_ORIGIN,
'{{ var("source_name") }}' as SRC_NAME,
'{{ var("target_name") }}' as TARGET_NAME,
1 as ENABLE_INDICATOR,
LTRIM ( RTRIM ( MARGIN_AGG_ACCOUNT ) ) as o_MARGIN_AGG_ACCOUNT,
LTRIM ( RTRIM ( RUNID ) ) as LINKID,
'CE' as CE_TCFD_FLAG,
'EODIND' as IAN_EODIND,
'ERR_VARMRG_EODIND' as EC_EODIND,
( CASE WHEN v_EODIND IS NULL THEN NULL ELSE ( CASE WHEN IN ( v_EODIND,
'E',
'I' ) = 1 THEN 'NO_ERROR' ELSE NULL END ) END ) as IAV_EODIND,
'EODIND' || ':' || EODIND as IAOV_EODIND,
'VAR_MRG_LEGAL_ENTITY_IDENTIFIER' as IAN_LEGAL_ENTITY_IDENTIFIER,
'ERR_VARMRG_LEI_BLANK_OR_WIDTH_NON_CONFORMANCE' as EC_LEGAL_ENTITY_IDENTIFIER,
( CASE WHEN ( v_LEI_OR_CICI IS NULL OR v_LEI_OR_CICI = '' OR LENGTH ( v_LEI_OR_CICI )  !=  20 ) THEN NULL ELSE 'NO_ERROR' END ) as IAV_LEGAL_ENTITY_IDENTIFIER,
'LEGAL_ENTITY_IDENTIFIER' || ':' || v_COUNTERPARTY_LEI || '/' || 'CFTC_INTERIM_COMPLIANT_ID' || ':' || v_COUNTERPARTY_CICI || '/' || 'MEMBER_COUNTERPARTY_ID' || ':' || v_MEMBER_COUNTERPARTY_ID_Deri as IAOV_LEGAL_ENTITY_IDENTIFIER,
'MARGINACCOUNTCATEGORY' as IAN_MRG_ACCT_CTGRY,
'ERR_VARMRG_MRG_ACCT_CATG' as EC_MRG_ACCT_CTGRY,
( CASE WHEN v_MARGINACCOUNTCATEGORY IS NULL THEN NULL ELSE ( CASE WHEN IN ( v_MARGINACCOUNTCATEGORY,
'H',
'C',
'IC' ) = 1 THEN 'NO_ERROR' ELSE NULL END ) END ) as IAV_MRG_ACCT_CTGRY,
'MARGINACCOUNTCATEGORY' || ':' || v_MARGINACCOUNTCATEGORY as IAOV_MRG_ACCT_CTGRY,
'VARIATIONMARGIN' as IAN_VARIATIONMARGIN,
'ERR_VARMRG_VARIATIONMARGIN' as EC_VARIATIONMARGIN,
( CASE WHEN '{{ var("batch_type") }}' = 'EOD' THEN ( CASE WHEN v_VARIATIONMARGIN IS NULL THEN NULL ELSE 'NO_ERROR' END ) ELSE 'NO_ERROR' END ) as IAV_VARIATIONMARGIN,
'VARIATIONMARGIN' || ':' || v_VARIATIONMARGIN_IAOV as IAOV_VARIATIONMARGIN,
'EXCLUSIONIND' as IAN_EXCLUSIONIND,
'ERR_VARMRG_EXCLUSIONIND' as EC_EXCLUSIONIND,
( CASE WHEN v_EXCLUSIONIND IS NULL THEN NULL ELSE ( CASE WHEN IN ( v_EXCLUSIONIND,
0,
1 ) = 1 THEN 'NO_ERROR' ELSE NULL END ) END ) as IAV_EXCLUSIONIND,
'EXCLUSIONIND' || ':' || v_EXCLUSIONIND_IAOV as IAOV_EXCLUSIONIND,
'AGENTCODE' as IAN_AGENTCODE,
'ERR_VARMRG_AGENTCODE' as EC_AGENTCODE,
( CASE WHEN v_AGENTCODE IS NULL THEN NULL ELSE 'NO_ERROR' END ) as IAV_AGENTCODE,
'AGENTCODE' || ':' || v_AGENTCODE as IAOV_AGENTCODE,
'INTENDEDSETTLEMENTDATE' as IAN_INTENDEDSETTLEMENTDATE,
'ERR_VARMRG_INTENDEDSETTLEMENTDATE' as EC_INTENDEDSETTLEMENTDATE,
( CASE WHEN v_INTENDEDSETTLEMENTDATE IS NULL THEN NULL ELSE 'NO_ERROR' END ) as IAV_INTENDEDSETTLEMENTDATE,
'INTENDEDSETTLEMENTDATE' || ':' || v_INTENDEDSETTLEMENTDATE as IAOV_INTENDEDSETTLEMENTDATE,
'CFDMTM' as IAN_CFDMTM,
'ERR_VARMRG_CFDMTM' as EC_CFDMTM,
( CASE WHEN v_CFDMTM IS NOT NULL THEN NULL ELSE 'NO_ERROR' END ) as IAV_CFDMTM,
'CFDMTM' || ':' || v_CFDMTM_IAOV as IAOV_CFDMTM,
'MEM_CPARTY_ID' as IAN_MEMBER_COUNTERPARTY_ID,
'E175_BLANK_FIELD_OR_LKUP_FAIL' as EC_MEMBER_COUNTERPARTY_ID,
( CASE WHEN v_MEMBER_COUNTERPARTY_ID_Deri = -2 THEN NULL ELSE 'NO_ERROR' END ) as IAV_MEMBER_COUNTERPARTY_ID,
'MEM_CPARTY_ID :' || v_MEMBER_COUNTERPARTY_ID_Deri as IAOV_MEMBER_COUNTERPARTY_ID
From EXP_TRIM_TRAILING_SPACES_variableOut as EXP_TRIM_TRAILING_SPACES_variableOut
LEFT JOIN (
SELECT ID, CURRENCY_MNEMONIC FROM (  SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY rnk_fst DESC NULLS LAST) AS rnk_lst  FROM (   SELECT ID, CURRENCY_MNEMONIC,  ROW_NUMBER() OVER (PARTITION BY CURRENCY_MNEMONIC ORDER BY CURRENCY_MNEMONIC NULLS LAST) AS rnk_fst   FROM ( SELECT    * FROM    CURRENCY_DIM )  ) lkp_inner ) lkp_outer WHERE rnk_lst = 1
) dsf_1
ON dsf_1.CURRENCY_MNEMONIC = CURRENCYCODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_variableOut as (
	
Select 
IAN_EODIND as INPUT_ATTRIBUTE_NAME,
EC_EODIND as INPUT_ERROR_CODE,
IAV_EODIND as INPUT_ATTRIBUTE_VALUE,
IAOV_EODIND as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_variableOut as (
	
Select 
IAN_MEMBER_COUNTERPARTY_ID as INPUT_ATTRIBUTE_NAME,
EC_MEMBER_COUNTERPARTY_ID as INPUT_ERROR_CODE,
IAV_MEMBER_COUNTERPARTY_ID as INPUT_ATTRIBUTE_VALUE,
IAOV_MEMBER_COUNTERPARTY_ID as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_variableOut as (
	
Select 
IAN_LEGAL_ENTITY_IDENTIFIER as INPUT_ATTRIBUTE_NAME,
EC_LEGAL_ENTITY_IDENTIFIER as INPUT_ERROR_CODE,
IAV_LEGAL_ENTITY_IDENTIFIER as INPUT_ATTRIBUTE_VALUE,
IAOV_LEGAL_ENTITY_IDENTIFIER as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_variableOut as (
	
Select 
IAN_INTENDEDSETTLEMENTDATE as INPUT_ATTRIBUTE_NAME,
EC_INTENDEDSETTLEMENTDATE as INPUT_ERROR_CODE,
IAV_INTENDEDSETTLEMENTDATE as INPUT_ATTRIBUTE_VALUE,
IAOV_INTENDEDSETTLEMENTDATE as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_variableOut as (
	
Select 
IAN_VARIATIONMARGIN as INPUT_ATTRIBUTE_NAME,
EC_VARIATIONMARGIN as INPUT_ERROR_CODE,
IAV_VARIATIONMARGIN as INPUT_ATTRIBUTE_VALUE,
IAOV_VARIATIONMARGIN as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_variableOut as (
	
Select 
IAN_EXCLUSIONIND as INPUT_ATTRIBUTE_NAME,
EC_EXCLUSIONIND as INPUT_ERROR_CODE,
IAV_EXCLUSIONIND as INPUT_ATTRIBUTE_VALUE,
IAOV_EXCLUSIONIND as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_variableOut as (
	
Select 
IAN_CFDMTM as INPUT_ATTRIBUTE_NAME,
EC_CFDMTM as INPUT_ERROR_CODE,
IAV_CFDMTM as INPUT_ATTRIBUTE_VALUE,
IAOV_CFDMTM as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_variableOut as (
	
Select 
IAN_MRG_ACCT_CTGRY as INPUT_ATTRIBUTE_NAME,
EC_MRG_ACCT_CTGRY as INPUT_ERROR_CODE,
IAV_MRG_ACCT_CTGRY as INPUT_ATTRIBUTE_VALUE,
IAOV_MRG_ACCT_CTGRY as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_variableOut as (
	
Select 
IAN_AGENTCODE as INPUT_ATTRIBUTE_NAME,
EC_AGENTCODE as INPUT_ERROR_CODE,
IAV_AGENTCODE as INPUT_ATTRIBUTE_VALUE,
IAOV_AGENTCODE as INPUT_ATTRIBUTE_ORIG_VALUE,
( CASE WHEN SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) IS NULL THEN 'N' ELSE SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) END ) as ACTIVE_Y_N
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

DSR_SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut as (
	
Select 
EXP_TRIM_TRAILING_SPACESOut.ENABLE_INDICATOR as CAL_DIM_EN_IND,
EXP_TRIM_TRAILING_SPACESOut.ENABLE_INDICATOR as ENTTY_DIM_EN_IND,
EXP_TRIM_TRAILING_SPACESOut.ENABLE_INDICATOR as CURR_DIM_EN_IND,
EXP_TRIM_TRAILING_SPACESOut.o_BUSINESSDATE as CAL_DIM_CAL_DATE_I,
EXP_TRIM_TRAILING_SPACESOut.ENTITY_NAME as ENTTY_DIM_NAME_I,
EXP_TRIM_TRAILING_SPACESOut.CAL_TYPE as CAL_DIM_TYPE_I,
EXP_TRIM_TRAILING_SPACESOut.CURRENCYCODE_ID as CURRENCY_ID_NAME,
EXP_TRIM_TRAILING_SPACESOut.o_CURRENCYCODE_NAME as CURR_DIM_CURR_MNE_I,
EXP_TRIM_TRAILING_SPACESOut.o_BUSINESSDATE as ENTTY_DIM_BUS_DATE_I,
EXP_TRIM_TRAILING_SPACESOut.o_BATCH_ID as BATCH_ID,
EXP_TRIM_TRAILING_SPACESOut.SRC_NAME as SRC_FILE_NAME,
EXP_TRIM_TRAILING_SPACESOut.TARGET_NAME as TARGET_TABLE_NAME
From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODINDOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_IDOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICIOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATEOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGINOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONINDOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTMOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRYOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODEOut as (
	
Select 
INPUT_ATTRIBUTE_NAME as INPUT_ATTRIBUTE_NAME,
INPUT_ERROR_CODE as INPUT_ERROR_CODE,
INPUT_ATTRIBUTE_VALUE as INPUT_ATTRIBUTE_VALUE,
INPUT_ATTRIBUTE_ORIG_VALUE as INPUT_ATTRIBUTE_ORIG_VALUE,
SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) + 1,
REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
2 ) - REGEXP_INSTR ( dsf_1.ACTIVE_Y_N_STR_VL,
'\\|',
1,
1 ) -1 ) as DV_ERROR_CODE,
( CASE WHEN INPUT_ATTRIBUTE_NAME IS NULL THEN 0 ELSE ( CASE WHEN UPPER ( LTRIM ( RTRIM ( ACTIVE_Y_N ) ) ) = 'Y' AND ( IN ( UPPER ( LTRIM ( RTRIM ( INPUT_ATTRIBUTE_VALUE ) ) ),
'NOT APPLICABLE',
'NOT FOUND',
'NF',
'N/A',
'NA' ) OR INPUT_ATTRIBUTE_VALUE = '' OR INPUT_ATTRIBUTE_VALUE IS NULL ) THEN TO_NUMBER ( SUBSTRING ( dsf_1.ACTIVE_Y_N_STR_VL,
IFF ( REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) > 0,
length ( dsf_1.ACTIVE_Y_N_STR_VL ) - REGEXP_INSTR ( REVERSE ( dsf_1.ACTIVE_Y_N_STR_VL ),
'\\|',
-1,
1 ) + 1,
0 ) + 1 ) ) ELSE 0 END ) END ) as BLANK_FIELD_OR_LKUP_FAIL,
ACTIVE_Y_N as ACTIVE_FLAG
From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_variableOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_variableOut
LEFT JOIN (
SELECT    APPLICATION_VARIABLES.ACTIVE_Y_N || '|' || APPLICATION_VARIABLES.STRING_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE || '|' || APPLICATION_VARIABLES.NUMBER_VALUE2 as ACTIVE_Y_N_STR_VL,    APPLICATION_VARIABLES.STRING_VALUE2 as STRING_VALUE2,    APPLICATION_VARIABLES.STRING_VALUE as STRING_VALUE FROM    APPLICATION_VARIABLES WHERE    VARIABLE_NAME= 'GENERIC_ERROR_MASTER' AND   ACTIVE_Y_N= 'Y'
) dsf_1
ON dsf_1.STRING_VALUE2 = INPUT_ATTRIBUTE_NAME AND dsf_1.STRING_VALUE = INPUT_ERROR_CODE
),

SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut as (
	Select 
	BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 ENABLE_INDICATOR as CAL_DIM_EN_IND,
	 ENABLE_INDICATOR as ENTTY_DIM_EN_IND,
	 ENABLE_INDICATOR as CURR_DIM_EN_IND,
	 o_BUSINESSDATE as CAL_DIM_CAL_DATE_I,
	 ENTITY_NAME as ENTTY_DIM_NAME_I,
	 CAL_TYPE as CAL_DIM_TYPE_I,
	 CURRENCYCODE_ID as CURRENCY_ID_NAME,
	 o_CURRENCYCODE_NAME as CURR_DIM_CURR_MNE_I,
	 o_BUSINESSDATE as ENTTY_DIM_BUS_DATE_I,
	 o_BATCH_ID as BATCH_ID,
	 SRC_NAME as SRC_FILE_NAME,
	 TARGET_NAME as TARGET_TABLE_NAME,
	 MEM_CPARTY_ID_LKP_FAIL as MEM_CPARTY_ID_LKP_FAIL,
	 CURR_DIM_LKP_FAIL as CURR_DIM_LKP_FAIL,
	 CAL_DIM_BUS_DATE_ID_LKP_FAIL as CAL_DIM_BUS_DATE_ID_LKP_FAIL,
	 CAL_DIM_CAL_ID_O as CAL_DIM_CAL_ID,
	 CAL_DIM_BUS_DATE_ID_NAME as CAL_DIM_BUS_DATE_ID_NAME,
	 CAL_DIM_BUS_DATE_ID_COMB_IN_STR as CAL_DIM_BUS_DATE_ID_COMB_IN_STR,
	 CAL_DIM_BUS_DATE_ID_EC as CAL_DIM_BUS_DATE_ID_EC,
	 CAL_DIM_BUS_DATE_ID_LKP_FAIL as CAL_DIM_BUS_DATE_ID_LKP_FAIL,
	 CURR_DIM_CURR_ID_O as CURR_DIM_CURR_ID,
	 CURR_DIM_CURR_ID_NAME as CURR_DIM_CURR_ID_NAME,
	 CURR_DIM_COMB_IN_STR as CURR_DIM_COMB_IN_STR,
	 CURR_DIM_CURR_ID_EC as CURR_DIM_CURR_ID_EC,
	 CURR_DIM_LKP_FAIL as CURR_DIM_LKP_FAIL,
	 ENTTY_DIM_ENTTY_ID_O as ENTTY_DIM_ENTTY_ID,
	 ENTTY_DIM_ENTITY_ID_NAME as ENTTY_DIM_ENTITY_ID_NAME,
	 ENTTY_DIM_COMB_IN_STR as ENTTY_DIM_COMB_IN_STR,
	 ENTTY_DIM_ENTITY_ID_EC as ENTTY_DIM_ENTITY_ID_EC,
	 ENTTY_DIM_LKP_FAIL as ENTTY_DIM_LKP_FAIL,
	 BATCH_DETAILS_ID as BATCH_DETAILS_ID 
From DSR_SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut as DSR_SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut),

EXP_TRIM_TRAILING_SPACES_master as (
  Select
  	EXP_TRIM_TRAILING_SPACESOut.o_BATCH_ID as BATCH_ID,
	 EXP_TRIM_TRAILING_SPACESOut.o_MEMBER_COUNTERPARTY_ID as MEM_CPARTY_ID
  From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODINDOut.INPUT_ATTRIBUTE_NAME as IAN_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODINDOut.INPUT_ATTRIBUTE_VALUE as IAV_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODINDOut.INPUT_ATTRIBUTE_ORIG_VALUE as IAOV_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODINDOut.DV_ERROR_CODE as EC_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODINDOut.BLANK_FIELD_OR_LKUP_FAIL as DV_RL_FLG_EODIND
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODINDOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODINDOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_IDOut.INPUT_ATTRIBUTE_NAME as MEM_CPARTY_ID_NAME,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_IDOut.INPUT_ATTRIBUTE_ORIG_VALUE as MEM_CPARTY_ID_COMB_IN_STR,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_IDOut.DV_ERROR_CODE as MEM_CPARTY_ID_ERROR_CODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_IDOut.BLANK_FIELD_OR_LKUP_FAIL as MEM_CPARTY_ID_LKP_FAIL
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_IDOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_IDOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGINOut.INPUT_ATTRIBUTE_NAME as IAN_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGINOut.INPUT_ATTRIBUTE_VALUE as IAV_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGINOut.INPUT_ATTRIBUTE_ORIG_VALUE as IAOV_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGINOut.DV_ERROR_CODE as EC_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGINOut.BLANK_FIELD_OR_LKUP_FAIL as DV_RL_FLG_VARIATIONMARGIN
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGINOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGINOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICIOut.INPUT_ATTRIBUTE_NAME as IAN_LEGAL_ENTITY_IDENTIFIER,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICIOut.INPUT_ATTRIBUTE_VALUE as IAV_LEGAL_ENTITY_IDENTIFIER,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICIOut.INPUT_ATTRIBUTE_ORIG_VALUE as IAOV_LEGAL_ENTITY_IDENTIFIER,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICIOut.DV_ERROR_CODE as EC_LEGAL_ENTITY_IDENTIFIER,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICIOut.BLANK_FIELD_OR_LKUP_FAIL as DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICIOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICIOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONINDOut.INPUT_ATTRIBUTE_NAME as IAN_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONINDOut.INPUT_ATTRIBUTE_VALUE as IAV_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONINDOut.INPUT_ATTRIBUTE_ORIG_VALUE as IAOV_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONINDOut.DV_ERROR_CODE as EC_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONINDOut.BLANK_FIELD_OR_LKUP_FAIL as DV_RL_FLG_EXCLUSIONIND
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONINDOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONINDOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTMOut.INPUT_ATTRIBUTE_NAME as IAN_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTMOut.INPUT_ATTRIBUTE_VALUE as IAV_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTMOut.INPUT_ATTRIBUTE_ORIG_VALUE as IAOV_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTMOut.DV_ERROR_CODE as EC_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTMOut.BLANK_FIELD_OR_LKUP_FAIL as DV_RL_FLG_CFDMTM
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTMOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTMOut
),

SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details as (
  Select
  	SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CAL_DIM_CAL_ID_O as CAL_DIM_CAL_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CAL_DIM_BUS_DATE_ID_NAME as CAL_DIM_BUS_DATE_ID_NAME,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CAL_DIM_BUS_DATE_ID_COMB_IN_STR as CAL_DIM_BUS_DATE_ID_COMB_IN_STR,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CAL_DIM_BUS_DATE_ID_EC as CAL_DIM_BUS_DATE_ID_EC,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CAL_DIM_BUS_DATE_ID_LKP_FAIL as CAL_DIM_BUS_DATE_ID_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CURR_DIM_CURR_ID_O as CURR_DIM_CURR_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CURR_DIM_CURR_ID_NAME as CURR_DIM_CURR_ID_NAME,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CURR_DIM_COMB_IN_STR as CURR_DIM_COMB_IN_STR,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CURR_DIM_CURR_ID_EC as CURR_DIM_CURR_ID_EC,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.CURR_DIM_LKP_FAIL as CURR_DIM_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.ENTTY_DIM_ENTTY_ID_O as ENTTY_DIM_ENTTY_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.ENTTY_DIM_ENTITY_ID_NAME as ENTTY_DIM_ENTITY_ID_NAME,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.ENTTY_DIM_COMB_IN_STR as ENTTY_DIM_COMB_IN_STR,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.ENTTY_DIM_ENTITY_ID_EC as ENTTY_DIM_ENTITY_ID_EC,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.ENTTY_DIM_LKP_FAIL as ENTTY_DIM_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID
  From SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut as SC_mplt_DV_BOE_BNK_CALYPSO_GENERICOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODEOut.INPUT_ATTRIBUTE_NAME as IAN_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODEOut.INPUT_ATTRIBUTE_VALUE as IAV_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODEOut.INPUT_ATTRIBUTE_ORIG_VALUE as IAOV_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODEOut.DV_ERROR_CODE as EC_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODEOut.BLANK_FIELD_OR_LKUP_FAIL as DV_RL_FLG_AGENTCODE
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODEOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODEOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRYOut.INPUT_ATTRIBUTE_NAME as IAN_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRYOut.INPUT_ATTRIBUTE_VALUE as IAV_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRYOut.INPUT_ATTRIBUTE_ORIG_VALUE as IAOV_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRYOut.DV_ERROR_CODE as EC_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRYOut.BLANK_FIELD_OR_LKUP_FAIL as DV_RL_FLG_MRG_ACCT_CTGRY
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRYOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRYOut
),

expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details as (
  Select
  	expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATEOut.INPUT_ATTRIBUTE_NAME as IAN_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATEOut.INPUT_ATTRIBUTE_VALUE as IAV_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATEOut.INPUT_ATTRIBUTE_ORIG_VALUE as IAOV_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATEOut.DV_ERROR_CODE as EC_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATEOut.BLANK_FIELD_OR_LKUP_FAIL as DV_RL_FLG_INTENDEDSETTLEMENTDATE
  From expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATEOut as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATEOut
),
dsJoiner_EXP_ERROR_VAL0Out as (
Select 
	EXP_TRIM_TRAILING_SPACES_master.BATCH_ID as BATCH_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CAL_DIM_CAL_ID as CAL_DIM_CAL_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CAL_DIM_BUS_DATE_ID_NAME as CAL_DIM_BUS_DATE_ID_NAME,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CAL_DIM_BUS_DATE_ID_COMB_IN_STR as CAL_DIM_BUS_DATE_ID_COMB_IN_STR,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CAL_DIM_BUS_DATE_ID_EC as CAL_DIM_BUS_DATE_ID_EC,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CAL_DIM_BUS_DATE_ID_LKP_FAIL as CAL_DIM_BUS_DATE_ID_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CURR_DIM_CURR_ID as CURR_DIM_CURR_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CURR_DIM_CURR_ID_NAME as CURR_DIM_CURR_ID_NAME,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CURR_DIM_COMB_IN_STR as CURR_DIM_COMB_IN_STR,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CURR_DIM_CURR_ID_EC as CURR_DIM_CURR_ID_EC,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.CURR_DIM_LKP_FAIL as CURR_DIM_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.ENTTY_DIM_ENTTY_ID as ENTTY_DIM_ENTTY_ID,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.ENTTY_DIM_ENTITY_ID_NAME as ENTTY_DIM_ENTITY_ID_NAME,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.ENTTY_DIM_COMB_IN_STR as ENTTY_DIM_COMB_IN_STR,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.ENTTY_DIM_ENTITY_ID_EC as ENTTY_DIM_ENTITY_ID_EC,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.ENTTY_DIM_LKP_FAIL as ENTTY_DIM_LKP_FAIL,
	 EXP_TRIM_TRAILING_SPACES_master.MEM_CPARTY_ID as MEM_CPARTY_ID,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_details.MEM_CPARTY_ID_NAME as MEM_CPARTY_ID_NAME,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_details.MEM_CPARTY_ID_COMB_IN_STR as MEM_CPARTY_ID_COMB_IN_STR,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_details.MEM_CPARTY_ID_ERROR_CODE as MEM_CPARTY_ID_ERROR_CODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_details.MEM_CPARTY_ID_LKP_FAIL as MEM_CPARTY_ID_LKP_FAIL,
	 SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details.IAN_EODIND as IAN_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details.IAV_EODIND as IAV_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details.IAOV_EODIND as IAOV_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details.EC_EODIND as EC_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details.DV_RL_FLG_EODIND as DV_RL_FLG_EODIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details.IAN_MRG_ACCT_CTGRY as IAN_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details.IAV_MRG_ACCT_CTGRY as IAV_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details.IAOV_MRG_ACCT_CTGRY as IAOV_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details.EC_MRG_ACCT_CTGRY as EC_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details.DV_RL_FLG_MRG_ACCT_CTGRY as DV_RL_FLG_MRG_ACCT_CTGRY,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details.IAN_VARIATIONMARGIN as IAN_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details.IAV_VARIATIONMARGIN as IAV_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details.IAOV_VARIATIONMARGIN as IAOV_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details.EC_VARIATIONMARGIN as EC_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details.DV_RL_FLG_VARIATIONMARGIN as DV_RL_FLG_VARIATIONMARGIN,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details.IAN_EXCLUSIONIND as IAN_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details.IAV_EXCLUSIONIND as IAV_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details.IAOV_EXCLUSIONIND as IAOV_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details.EC_EXCLUSIONIND as EC_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details.DV_RL_FLG_EXCLUSIONIND as DV_RL_FLG_EXCLUSIONIND,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details.IAN_AGENTCODE as IAN_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details.IAV_AGENTCODE as IAV_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details.IAOV_AGENTCODE as IAOV_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details.EC_AGENTCODE as EC_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details.DV_RL_FLG_AGENTCODE as DV_RL_FLG_AGENTCODE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details.IAN_INTENDEDSETTLEMENTDATE as IAN_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details.IAV_INTENDEDSETTLEMENTDATE as IAV_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details.IAOV_INTENDEDSETTLEMENTDATE as IAOV_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details.EC_INTENDEDSETTLEMENTDATE as EC_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details.DV_RL_FLG_INTENDEDSETTLEMENTDATE as DV_RL_FLG_INTENDEDSETTLEMENTDATE,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details.IAN_CFDMTM as IAN_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details.IAV_CFDMTM as IAV_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details.IAOV_CFDMTM as IAOV_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details.EC_CFDMTM as EC_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details.DV_RL_FLG_CFDMTM as DV_RL_FLG_CFDMTM,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details.IAN_LEGAL_ENTITY_IDENTIFIER as IAN_LEGAL_ENTITY_IDENTIFIER,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details.IAV_LEGAL_ENTITY_IDENTIFIER as IAV_LEGAL_ENTITY_IDENTIFIER,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details.IAOV_LEGAL_ENTITY_IDENTIFIER as IAOV_LEGAL_ENTITY_IDENTIFIER,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details.EC_LEGAL_ENTITY_IDENTIFIER as EC_LEGAL_ENTITY_IDENTIFIER,
	 expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details.DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER as DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER,
	 EXP_TRIM_TRAILING_SPACES_master.jkey as jkey 
From
EXP_TRIM_TRAILING_SPACES_master as EXP_TRIM_TRAILING_SPACES_master INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EODIND_details.jkey
 INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_M_CPARTY_ID_details.jkey
 INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_VARIATIONMARGIN_details.jkey
 INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_LEI_OR_CICI_details.jkey
 INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_EXCLUSIONIND_details.jkey
 INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_CFDMTM_details.jkey
 INNER JOIN SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details as SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = SC_mplt_DV_BOE_BNK_CALYPSO_GENERIC_details.jkey
 INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_AGENTCODE_details.jkey
 INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_MRG_ACCT_CTGRY_details.jkey
 INNER JOIN expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details as expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details 
ON
EXP_TRIM_TRAILING_SPACES_master.jkey = expr_EMIR_DV_BLANK_FIELD_OR_LKP_FAIL_V2_INTENDEDSETTLEMENTDATE_details.jkey
 
),

EXP_ERROR_VALOut as (
	
Select 
TO_DATE ( LTRIM ( RTRIM ( '{{ var("batch_business_date") }}' ) ),
'YYYYMMDD' ) as BATCH_BUSINESS_DATE,
BATCH_ID as BATCH_ID,
'{{ var("pmworkflowname") }}' as WORKFLOW_NAME,
'{{ var("pmmappingname") }}' as MAPPING_NAME,
'{{ var("target_name") }}' as TARGET_NAME,
CAL_DIM_CAL_ID as CAL_DIM_CAL_ID,
CAL_DIM_BUS_DATE_ID_NAME as CAL_DIM_BUS_DATE_ID_NAME,
CAL_DIM_BUS_DATE_ID_COMB_IN_STR as CAL_DIM_BUS_DATE_ID_COMB_IN_STR,
CAL_DIM_BUS_DATE_ID_EC as CAL_DIM_BUS_DATE_ID_EC,
CAL_DIM_BUS_DATE_ID_LKP_FAIL as CAL_DIM_BUS_DATE_ID_LKP_FAIL,
CURR_DIM_CURR_ID as CURR_DIM_CURR_ID,
CURR_DIM_CURR_ID_NAME as CURR_DIM_CURR_ID_NAME,
CURR_DIM_COMB_IN_STR as CURR_DIM_COMB_IN_STR,
CURR_DIM_CURR_ID_EC as CURR_DIM_CURR_ID_EC,
CURR_DIM_LKP_FAIL as CURR_DIM_LKP_FAIL,
ENTTY_DIM_ENTTY_ID as ENTTY_DIM_ENTTY_ID,
ENTTY_DIM_ENTITY_ID_NAME as ENTTY_DIM_ENTITY_ID_NAME,
ENTTY_DIM_COMB_IN_STR as ENTTY_DIM_COMB_IN_STR,
ENTTY_DIM_ENTITY_ID_EC as ENTTY_DIM_ENTITY_ID_EC,
ENTTY_DIM_LKP_FAIL as ENTTY_DIM_LKP_FAIL,
MEM_CPARTY_ID as MEM_CPARTY_ID,
MEM_CPARTY_ID_NAME as MEM_CPARTY_ID_NAME,
MEM_CPARTY_ID_COMB_IN_STR as MEM_CPARTY_ID_COMB_IN_STR,
MEM_CPARTY_ID_ERROR_CODE as MEM_CPARTY_ID_ERROR_CODE,
MEM_CPARTY_ID_LKP_FAIL as MEM_CPARTY_ID_LKP_FAIL,
BATCH_DETAILS_ID as BATCH_DETAILS_ID,
IAN_EODIND as IAN_EODIND,
IAV_EODIND as IAV_EODIND,
IAOV_EODIND as IAOV_EODIND,
EC_EODIND as EC_EODIND,
DV_RL_FLG_EODIND as DV_RL_FLG_EODIND,
IAN_MRG_ACCT_CTGRY as IAN_MRG_ACCT_CTGRY,
IAV_MRG_ACCT_CTGRY as IAV_MRG_ACCT_CTGRY,
IAOV_MRG_ACCT_CTGRY as IAOV_MRG_ACCT_CTGRY,
EC_MRG_ACCT_CTGRY as EC_MRG_ACCT_CTGRY,
DV_RL_FLG_MRG_ACCT_CTGRY as DV_RL_FLG_MRG_ACCT_CTGRY,
IAN_VARIATIONMARGIN as IAN_VARIATIONMARGIN,
IAV_VARIATIONMARGIN as IAV_VARIATIONMARGIN,
IAOV_VARIATIONMARGIN as IAOV_VARIATIONMARGIN,
EC_VARIATIONMARGIN as EC_VARIATIONMARGIN,
DV_RL_FLG_VARIATIONMARGIN as DV_RL_FLG_VARIATIONMARGIN,
IAN_EXCLUSIONIND as IAN_EXCLUSIONIND,
IAV_EXCLUSIONIND as IAV_EXCLUSIONIND,
IAOV_EXCLUSIONIND as IAOV_EXCLUSIONIND,
EC_EXCLUSIONIND as EC_EXCLUSIONIND,
DV_RL_FLG_EXCLUSIONIND as DV_RL_FLG_EXCLUSIONIND,
IAN_AGENTCODE as IAN_AGENTCODE,
IAV_AGENTCODE as IAV_AGENTCODE,
IAOV_AGENTCODE as IAOV_AGENTCODE,
EC_AGENTCODE as EC_AGENTCODE,
DV_RL_FLG_AGENTCODE as DV_RL_FLG_AGENTCODE,
IAN_INTENDEDSETTLEMENTDATE as IAN_INTENDEDSETTLEMENTDATE,
IAV_INTENDEDSETTLEMENTDATE as IAV_INTENDEDSETTLEMENTDATE,
IAOV_INTENDEDSETTLEMENTDATE as IAOV_INTENDEDSETTLEMENTDATE,
EC_INTENDEDSETTLEMENTDATE as EC_INTENDEDSETTLEMENTDATE,
DV_RL_FLG_INTENDEDSETTLEMENTDATE as DV_RL_FLG_INTENDEDSETTLEMENTDATE,
IAN_CFDMTM as IAN_CFDMTM,
IAV_CFDMTM as IAV_CFDMTM,
IAOV_CFDMTM as IAOV_CFDMTM,
EC_CFDMTM as EC_CFDMTM,
DV_RL_FLG_CFDMTM as DV_RL_FLG_CFDMTM,
IAN_LEGAL_ENTITY_IDENTIFIER as IAN_LEGAL_ENTITY_IDENTIFIER,
IAV_LEGAL_ENTITY_IDENTIFIER as IAV_LEGAL_ENTITY_IDENTIFIER,
IAOV_LEGAL_ENTITY_IDENTIFIER as IAOV_LEGAL_ENTITY_IDENTIFIER,
EC_LEGAL_ENTITY_IDENTIFIER as EC_LEGAL_ENTITY_IDENTIFIER,
DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER as DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER,
( CASE WHEN CAL_DIM_BUS_DATE_ID_LKP_FAIL  !=  0 OR CURR_DIM_LKP_FAIL  !=  0 OR MEM_CPARTY_ID_LKP_FAIL  !=  0 OR CAL_DIM_CAL_ID = 2 OR CAL_DIM_CAL_ID = -2 OR CURR_DIM_CURR_ID = 2 OR CURR_DIM_CURR_ID = -2 OR MEM_CPARTY_ID = 2 OR MEM_CPARTY_ID = -2 OR IAV_EODIND IS NULL OR IAV_MRG_ACCT_CTGRY IS NULL OR IAV_VARIATIONMARGIN IS NULL OR IAV_EXCLUSIONIND IS NULL OR IAV_AGENTCODE IS NULL OR IAV_INTENDEDSETTLEMENTDATE IS NULL OR IAV_CFDMTM IS NULL OR IAV_LEGAL_ENTITY_IDENTIFIER IS NULL THEN 'Y' ELSE 'N' END ) as ERROR_IND
From dsJoiner_EXP_ERROR_VAL0Out as dsJoiner_EXP_ERROR_VAL0Out),

EXP_TRIM_TRAILING_SPACES_master as (
  Select
  	EXP_TRIM_TRAILING_SPACESOut.O_ID as NEXTVAL
  From EXP_TRIM_TRAILING_SPACESOut as EXP_TRIM_TRAILING_SPACESOut
),

EXP_ERROR_VAL_details as (
  Select
  	EXP_ERROR_VALOut.IAOV_MRG_ACCT_CTGRY as IAOV_MRG_ACCT_CTGRY,
	 EXP_ERROR_VALOut.EC_MRG_ACCT_CTGRY as EC_MRG_ACCT_CTGRY,
	 EXP_ERROR_VALOut.DV_RL_FLG_MRG_ACCT_CTGRY as DV_RL_FLG_MRG_ACCT_CTGRY,
	 EXP_ERROR_VALOut.IAN_VARIATIONMARGIN as IAN_VARIATIONMARGIN,
	 EXP_ERROR_VALOut.IAOV_VARIATIONMARGIN as IAOV_VARIATIONMARGIN,
	 EXP_ERROR_VALOut.EC_VARIATIONMARGIN as EC_VARIATIONMARGIN,
	 EXP_ERROR_VALOut.DV_RL_FLG_VARIATIONMARGIN as DV_RL_FLG_VARIATIONMARGIN,
	 EXP_ERROR_VALOut.IAN_EXCLUSIONIND as IAN_EXCLUSIONIND,
	 EXP_ERROR_VALOut.IAOV_EXCLUSIONIND as IAOV_EXCLUSIONIND,
	 EXP_ERROR_VALOut.EC_EXCLUSIONIND as EC_EXCLUSIONIND,
	 EXP_ERROR_VALOut.DV_RL_FLG_EXCLUSIONIND as DV_RL_FLG_EXCLUSIONIND,
	 EXP_ERROR_VALOut.CAL_DIM_CAL_ID as CAL_DIM_CAL_ID_O,
	 EXP_ERROR_VALOut.CAL_DIM_BUS_DATE_ID_NAME as CAL_DIM_BUS_DATE_ID_NAME,
	 EXP_ERROR_VALOut.CAL_DIM_BUS_DATE_ID_COMB_IN_STR as CAL_DIM_BUS_DATE_ID_COMB_IN_STR,
	 EXP_ERROR_VALOut.IAN_AGENTCODE as IAN_AGENTCODE,
	 EXP_ERROR_VALOut.IAOV_AGENTCODE as IAOV_AGENTCODE,
	 EXP_ERROR_VALOut.EC_AGENTCODE as EC_AGENTCODE,
	 EXP_ERROR_VALOut.DV_RL_FLG_AGENTCODE as DV_RL_FLG_AGENTCODE,
	 EXP_ERROR_VALOut.IAN_INTENDEDSETTLEMENTDATE as IAN_INTENDEDSETTLEMENTDATE,
	 EXP_ERROR_VALOut.IAOV_INTENDEDSETTLEMENTDATE as IAOV_INTENDEDSETTLEMENTDATE,
	 EXP_ERROR_VALOut.EC_INTENDEDSETTLEMENTDATE as EC_INTENDEDSETTLEMENTDATE,
	 EXP_ERROR_VALOut.DV_RL_FLG_INTENDEDSETTLEMENTDATE as DV_RL_FLG_INTENDEDSETTLEMENTDATE,
	 EXP_ERROR_VALOut.IAN_CFDMTM as IAN_CFDMTM,
	 EXP_ERROR_VALOut.IAOV_CFDMTM as IAOV_CFDMTM,
	 EXP_ERROR_VALOut.EC_CFDMTM as EC_CFDMTM,
	 EXP_ERROR_VALOut.CURR_DIM_CURR_ID as CURR_DIM_CURR_ID_O,
	 EXP_ERROR_VALOut.DV_RL_FLG_CFDMTM as DV_RL_FLG_CFDMTM,
	 EXP_ERROR_VALOut.CAL_DIM_BUS_DATE_ID_EC as CAL_DIM_BUS_DATE_ID_EC,
	 EXP_ERROR_VALOut.CAL_DIM_BUS_DATE_ID_LKP_FAIL as CAL_DIM_BUS_DATE_ID_LKP_FAIL,
	 EXP_ERROR_VALOut.CURR_DIM_CURR_ID_NAME as CURR_DIM_CURR_ID_NAME,
	 EXP_ERROR_VALOut.CURR_DIM_COMB_IN_STR as CURR_DIM_COMB_IN_STR,
	 EXP_ERROR_VALOut.CURR_DIM_CURR_ID_EC as CURR_DIM_CURR_ID_EC,
	 EXP_ERROR_VALOut.ERROR_IND as ERROR_IND,
	 EXP_ERROR_VALOut.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_ERROR_VALOut.CURR_DIM_LKP_FAIL as CURR_DIM_LKP_FAIL,
	 EXP_ERROR_VALOut.ENTTY_DIM_ENTTY_ID as ENTTY_DIM_ENTTY_ID_O,
	 EXP_ERROR_VALOut.ENTTY_DIM_ENTITY_ID_NAME as ENTTY_DIM_ENTITY_ID_NAME,
	 EXP_ERROR_VALOut.ENTTY_DIM_COMB_IN_STR as ENTTY_DIM_COMB_IN_STR,
	 EXP_ERROR_VALOut.ENTTY_DIM_ENTITY_ID_EC as ENTTY_DIM_ENTITY_ID_EC,
	 EXP_ERROR_VALOut.ENTTY_DIM_LKP_FAIL as ENTTY_DIM_LKP_FAIL,
	 EXP_ERROR_VALOut.MEM_CPARTY_ID as MEM_CPARTY_ID,
	 EXP_ERROR_VALOut.MEM_CPARTY_ID_NAME as MEM_CPARTY_ID_NAME,
	 EXP_ERROR_VALOut.MEM_CPARTY_ID_COMB_IN_STR as MEM_CPARTY_ID_COMB_IN_STR,
	 EXP_ERROR_VALOut.MEM_CPARTY_ID_ERROR_CODE as MEM_CPARTY_ID_ERROR_CODE,
	 EXP_ERROR_VALOut.MEM_CPARTY_ID_LKP_FAIL as MEM_CPARTY_ID_LKP_FAIL,
	 EXP_ERROR_VALOut.BATCH_ID as BATCH_ID,
	 EXP_ERROR_VALOut.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_ERROR_VALOut.MAPPING_NAME as MAPPING_NAME,
	 EXP_ERROR_VALOut.EC_EODIND as EC_EODIND,
	 EXP_ERROR_VALOut.DV_RL_FLG_EODIND as DV_RL_FLG_EODIND,
	 EXP_ERROR_VALOut.IAN_MRG_ACCT_CTGRY as IAN_MRG_ACCT_CTGRY,
	 EXP_ERROR_VALOut.IAN_LEGAL_ENTITY_IDENTIFIER as IAN_LEGAL_ENTITY_IDENTIFIER,
	 EXP_ERROR_VALOut.IAOV_LEGAL_ENTITY_IDENTIFIER as IAOV_LEGAL_ENTITY_IDENTIFIER,
	 EXP_ERROR_VALOut.EC_LEGAL_ENTITY_IDENTIFIER as EC_LEGAL_ENTITY_IDENTIFIER,
	 EXP_ERROR_VALOut.DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER as DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER,
	 EXP_ERROR_VALOut.TARGET_NAME as TARGET_NAME,
	 EXP_ERROR_VALOut.BATCH_BUSINESS_DATE as BATCH_BUSINESS_DATE,
	 EXP_ERROR_VALOut.IAN_EODIND as IAN_EODIND,
	 EXP_ERROR_VALOut.IAOV_EODIND as IAOV_EODIND
  From EXP_ERROR_VALOut as EXP_ERROR_VALOut
),
dsJoiner_FLT_ERROR_RECORDS0Out as (
Select 
	EXP_TRIM_TRAILING_SPACES_master.NEXTVAL as NEXTVAL,
	 EXP_ERROR_VAL_details.IAOV_MRG_ACCT_CTGRY as IAOV_MRG_ACCT_CTGRY,
	 EXP_ERROR_VAL_details.EC_MRG_ACCT_CTGRY as EC_MRG_ACCT_CTGRY,
	 EXP_ERROR_VAL_details.DV_RL_FLG_MRG_ACCT_CTGRY as DV_RL_FLG_MRG_ACCT_CTGRY,
	 EXP_ERROR_VAL_details.IAN_VARIATIONMARGIN as IAN_VARIATIONMARGIN,
	 EXP_ERROR_VAL_details.IAOV_VARIATIONMARGIN as IAOV_VARIATIONMARGIN,
	 EXP_ERROR_VAL_details.EC_VARIATIONMARGIN as EC_VARIATIONMARGIN,
	 EXP_ERROR_VAL_details.DV_RL_FLG_VARIATIONMARGIN as DV_RL_FLG_VARIATIONMARGIN,
	 EXP_ERROR_VAL_details.IAN_EXCLUSIONIND as IAN_EXCLUSIONIND,
	 EXP_ERROR_VAL_details.IAOV_EXCLUSIONIND as IAOV_EXCLUSIONIND,
	 EXP_ERROR_VAL_details.EC_EXCLUSIONIND as EC_EXCLUSIONIND,
	 EXP_ERROR_VAL_details.DV_RL_FLG_EXCLUSIONIND as DV_RL_FLG_EXCLUSIONIND,
	 EXP_ERROR_VAL_details.CAL_DIM_CAL_ID_O as CAL_DIM_CAL_ID_O,
	 EXP_ERROR_VAL_details.CAL_DIM_BUS_DATE_ID_NAME as CAL_DIM_BUS_DATE_ID_NAME,
	 EXP_ERROR_VAL_details.CAL_DIM_BUS_DATE_ID_COMB_IN_STR as CAL_DIM_BUS_DATE_ID_COMB_IN_STR,
	 EXP_ERROR_VAL_details.IAN_AGENTCODE as IAN_AGENTCODE,
	 EXP_ERROR_VAL_details.IAOV_AGENTCODE as IAOV_AGENTCODE,
	 EXP_ERROR_VAL_details.EC_AGENTCODE as EC_AGENTCODE,
	 EXP_ERROR_VAL_details.DV_RL_FLG_AGENTCODE as DV_RL_FLG_AGENTCODE,
	 EXP_ERROR_VAL_details.IAN_INTENDEDSETTLEMENTDATE as IAN_INTENDEDSETTLEMENTDATE,
	 EXP_ERROR_VAL_details.IAOV_INTENDEDSETTLEMENTDATE as IAOV_INTENDEDSETTLEMENTDATE,
	 EXP_ERROR_VAL_details.EC_INTENDEDSETTLEMENTDATE as EC_INTENDEDSETTLEMENTDATE,
	 EXP_ERROR_VAL_details.DV_RL_FLG_INTENDEDSETTLEMENTDATE as DV_RL_FLG_INTENDEDSETTLEMENTDATE,
	 EXP_ERROR_VAL_details.IAN_CFDMTM as IAN_CFDMTM,
	 EXP_ERROR_VAL_details.IAOV_CFDMTM as IAOV_CFDMTM,
	 EXP_ERROR_VAL_details.EC_CFDMTM as EC_CFDMTM,
	 EXP_ERROR_VAL_details.CURR_DIM_CURR_ID_O as CURR_DIM_CURR_ID_O,
	 EXP_ERROR_VAL_details.DV_RL_FLG_CFDMTM as DV_RL_FLG_CFDMTM,
	 EXP_ERROR_VAL_details.CAL_DIM_BUS_DATE_ID_EC as CAL_DIM_BUS_DATE_ID_EC,
	 EXP_ERROR_VAL_details.CAL_DIM_BUS_DATE_ID_LKP_FAIL as CAL_DIM_BUS_DATE_ID_LKP_FAIL,
	 EXP_ERROR_VAL_details.CURR_DIM_CURR_ID_O_NAME as CURR_DIM_CURR_ID_NAME,
	 EXP_ERROR_VAL_details.CURR_DIM_COMB_IN_STR as CURR_DIM_COMB_IN_STR,
	 EXP_ERROR_VAL_details.CURR_DIM_CURR_ID_O_EC as CURR_DIM_CURR_ID_EC,
	 EXP_ERROR_VAL_details.ERROR_IND as ERROR_IND,
	 EXP_ERROR_VAL_details.BATCH_DETAILS_ID as BATCH_DETAILS_ID,
	 EXP_ERROR_VAL_details.CURR_DIM_LKP_FAIL as CURR_DIM_LKP_FAIL,
	 EXP_ERROR_VAL_details.ENTTY_DIM_ENTTY_ID_O as ENTTY_DIM_ENTTY_ID_O,
	 EXP_ERROR_VAL_details.ENTTY_DIM_ENTITY_ID_NAME as ENTTY_DIM_ENTITY_ID_NAME,
	 EXP_ERROR_VAL_details.ENTTY_DIM_COMB_IN_STR as ENTTY_DIM_COMB_IN_STR,
	 EXP_ERROR_VAL_details.ENTTY_DIM_ENTITY_ID_EC as ENTTY_DIM_ENTITY_ID_EC,
	 EXP_ERROR_VAL_details.ENTTY_DIM_LKP_FAIL as ENTTY_DIM_LKP_FAIL,
	 EXP_ERROR_VAL_details.MEM_CPARTY_ID as MEM_CPARTY_ID,
	 EXP_ERROR_VAL_details.MEM_CPARTY_ID_NAME as MEM_CPARTY_ID_NAME,
	 EXP_ERROR_VAL_details.MEM_CPARTY_ID_COMB_IN_STR as MEM_CPARTY_ID_COMB_IN_STR,
	 EXP_ERROR_VAL_details.MEM_CPARTY_ID_ERROR_CODE as MEM_CPARTY_ID_ERROR_CODE,
	 EXP_ERROR_VAL_details.MEM_CPARTY_ID_LKP_FAIL as MEM_CPARTY_ID_LKP_FAIL,
	 EXP_ERROR_VAL_details.BATCH_ID as BATCH_ID,
	 EXP_ERROR_VAL_details.WORKFLOW_NAME as WORKFLOW_NAME,
	 EXP_ERROR_VAL_details.MAPPING_NAME as MAPPING_NAME,
	 EXP_ERROR_VAL_details.EC_EODIND as EC_EODIND,
	 EXP_ERROR_VAL_details.DV_RL_FLG_EODIND as DV_RL_FLG_EODIND,
	 EXP_ERROR_VAL_details.IAN_MRG_ACCT_CTGRY as IAN_MRG_ACCT_CTGRY,
	 EXP_ERROR_VAL_details.IAN_LEGAL_ENTITY_IDENTIFIER as IAN_LEGAL_ENTITY_IDENTIFIER,
	 EXP_ERROR_VAL_details.IAOV_LEGAL_ENTITY_IDENTIFIER as IAOV_LEGAL_ENTITY_IDENTIFIER,
	 EXP_ERROR_VAL_details.EC_LEGAL_ENTITY_IDENTIFIER as EC_LEGAL_ENTITY_IDENTIFIER,
	 EXP_ERROR_VAL_details.DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER as DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER,
	 EXP_ERROR_VAL_details.TARGET_NAME as TARGET_NAME,
	 EXP_ERROR_VAL_details.BATCH_BUSINESS_DATE as BATCH_BUSINESS_DATE,
	 EXP_ERROR_VAL_details.IAN_EODIND as IAN_EODIND,
	 EXP_ERROR_VAL_details.IAOV_EODIND as IAOV_EODIND,
	 EXP_TRIM_TRAILING_SPACES_master.jkey as jkey 
From
EXP_TRIM_TRAILING_SPACES_master as EXP_TRIM_TRAILING_SPACES_master inner JOIN EXP_ERROR_VAL_details as EXP_ERROR_VAL_details 
ON
EXP_ERROR_VAL_details.jkey = EXP_TRIM_TRAILING_SPACES_master.jkey 
),

Target_Table_Name_SK_Max_Value AS (
  SELECT
    MAX(INPUT_REFERENCE_RECORD_ID) AS max_input_reference_record_id
  FROM {{ this }}
),

 DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut as (
	
Select 
FLT_ERROR_RECORDSOut.CURR_DIM_CURR_ID_EC as INPUT_ERROR_CODE_2,
FLT_ERROR_RECORDSOut.CURR_DIM_LKP_FAIL as INPUT_ERROR_SEVERITY_2,
FLT_ERROR_RECORDSOut.BATCH_BUSINESS_DATE as INPUT_BATCH_BUSINESS_DATE,
FLT_ERROR_RECORDSOut.BATCH_ID as INPUT_BATCH_ID,
FLT_ERROR_RECORDSOut.CAL_DIM_BUS_DATE_ID_LKP_FAIL as INPUT_ERROR_SEVERITY_1,
FLT_ERROR_RECORDSOut.MEM_CPARTY_ID_NAME as INPUT_ATTRIBUTE_NAME_3,
FLT_ERROR_RECORDSOut.WORKFLOW_NAME as INPUT_WORKFLOW_NAME,
FLT_ERROR_RECORDSOut.MAPPING_NAME as INPUT_MAPPING_NAME,
FLT_ERROR_RECORDSOut.BATCH_DETAILS_ID as INPUT_BATCH_DETAILS_ID,
FLT_ERROR_RECORDSOut.TARGET_NAME as INPUT_TARGET_NAME,
FLT_ERROR_RECORDSOut.(SELECT max_input_reference_record_id FROM Target_Table_Name_SK_Max_Value) + ROW_NUMBER() OVER() AS INPUT_REFERENCE_RECORD_ID,
FLT_ERROR_RECORDSOut.CAL_DIM_BUS_DATE_ID_NAME as INPUT_ATTRIBUTE_NAME_1,
FLT_ERROR_RECORDSOut.CAL_DIM_BUS_DATE_ID_COMB_IN_STR as INPUT_ATTRIBUTE_VALUE_1,
FLT_ERROR_RECORDSOut.CAL_DIM_BUS_DATE_ID_EC as INPUT_ERROR_CODE_1,
FLT_ERROR_RECORDSOut.MEM_CPARTY_ID_COMB_IN_STR as INPUT_ATTRIBUTE_VALUE_3,
FLT_ERROR_RECORDSOut.MEM_CPARTY_ID_ERROR_CODE as INPUT_ERROR_CODE_3,
FLT_ERROR_RECORDSOut.MEM_CPARTY_ID_LKP_FAIL as INPUT_ERROR_SEVERITY_3,
FLT_ERROR_RECORDSOut.CURR_DIM_CURR_ID_NAME as INPUT_ATTRIBUTE_NAME_2,
FLT_ERROR_RECORDSOut.CURR_DIM_COMB_IN_STR as INPUT_ATTRIBUTE_VALUE_2,
FLT_ERROR_RECORDSOut.IAN_EODIND as INPUT_ATTRIBUTE_NAME_4,
FLT_ERROR_RECORDSOut.IAOV_EODIND as INPUT_ATTRIBUTE_VALUE_4,
FLT_ERROR_RECORDSOut.EC_EODIND as INPUT_ERROR_CODE_4,
FLT_ERROR_RECORDSOut.DV_RL_FLG_EODIND as INPUT_ERROR_SEVERITY_4,
FLT_ERROR_RECORDSOut.IAN_MRG_ACCT_CTGRY as INPUT_ATTRIBUTE_NAME_5,
FLT_ERROR_RECORDSOut.IAOV_MRG_ACCT_CTGRY as INPUT_ATTRIBUTE_VALUE_5,
FLT_ERROR_RECORDSOut.EC_MRG_ACCT_CTGRY as INPUT_ERROR_CODE_5,
FLT_ERROR_RECORDSOut.DV_RL_FLG_MRG_ACCT_CTGRY as INPUT_ERROR_SEVERITY_5,
FLT_ERROR_RECORDSOut.IAN_VARIATIONMARGIN as INPUT_ATTRIBUTE_NAME_6,
FLT_ERROR_RECORDSOut.IAOV_VARIATIONMARGIN as INPUT_ATTRIBUTE_VALUE_6,
FLT_ERROR_RECORDSOut.EC_VARIATIONMARGIN as INPUT_ERROR_CODE_6,
FLT_ERROR_RECORDSOut.DV_RL_FLG_VARIATIONMARGIN as INPUT_ERROR_SEVERITY_6,
FLT_ERROR_RECORDSOut.IAN_EXCLUSIONIND as INPUT_ATTRIBUTE_NAME_7,
FLT_ERROR_RECORDSOut.IAOV_EXCLUSIONIND as INPUT_ATTRIBUTE_VALUE_7,
FLT_ERROR_RECORDSOut.EC_EXCLUSIONIND as INPUT_ERROR_CODE_7,
FLT_ERROR_RECORDSOut.DV_RL_FLG_EXCLUSIONIND as INPUT_ERROR_SEVERITY_7,
FLT_ERROR_RECORDSOut.IAN_AGENTCODE as INPUT_ATTRIBUTE_NAME_8,
FLT_ERROR_RECORDSOut.IAOV_AGENTCODE as INPUT_ATTRIBUTE_VALUE_8,
FLT_ERROR_RECORDSOut.EC_AGENTCODE as INPUT_ERROR_CODE_8,
FLT_ERROR_RECORDSOut.DV_RL_FLG_AGENTCODE as INPUT_ERROR_SEVERITY_8,
FLT_ERROR_RECORDSOut.IAN_INTENDEDSETTLEMENTDATE as INPUT_ATTRIBUTE_NAME_9,
FLT_ERROR_RECORDSOut.IAOV_INTENDEDSETTLEMENTDATE as INPUT_ATTRIBUTE_VALUE_9,
FLT_ERROR_RECORDSOut.EC_INTENDEDSETTLEMENTDATE as INPUT_ERROR_CODE_9,
FLT_ERROR_RECORDSOut.DV_RL_FLG_INTENDEDSETTLEMENTDATE as INPUT_ERROR_SEVERITY_9,
FLT_ERROR_RECORDSOut.IAN_CFDMTM as INPUT_ATTRIBUTE_NAME_10,
FLT_ERROR_RECORDSOut.IAOV_CFDMTM as INPUT_ATTRIBUTE_VALUE_10,
FLT_ERROR_RECORDSOut.EC_CFDMTM as INPUT_ERROR_CODE_10,
FLT_ERROR_RECORDSOut.DV_RL_FLG_CFDMTM as INPUT_ERROR_SEVERITY_10,
FLT_ERROR_RECORDSOut.IAN_LEGAL_ENTITY_IDENTIFIER as INPUT_ATTRIBUTE_NAME_11,
FLT_ERROR_RECORDSOut.IAOV_LEGAL_ENTITY_IDENTIFIER as INPUT_ATTRIBUTE_VALUE_11,
FLT_ERROR_RECORDSOut.EC_LEGAL_ENTITY_IDENTIFIER as INPUT_ERROR_CODE_11,
FLT_ERROR_RECORDSOut.DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER as INPUT_ERROR_SEVERITY_11 
From dsJoiner_FLT_ERROR_RECORDS0Out as dsJoiner_FLT_ERROR_RECORDS0Out Where ERROR_IND = 'Y'),

SC_mplt_DV_PROCESS_ERROR_DETAILSOut as (
	Select 
	ID as ID,
	 PROCESS_DATE as PROCESS_DATE,
	 REFERENCE_BATCH_ID as REFERENCE_BATCH_ID,
	 REFERENCE_PROCESS as REFERENCE_PROCESS,
	 REFERENCE_SUB_PROCESS as REFERENCE_SUB_PROCESS,
	 REFERENCE_TARGET_NAME as REFERENCE_TARGET_NAME,
	 REFERENCE_RECORD_ID as REFERENCE_RECORD_ID,
	 REFERENCE_BUSINESS_KEY as REFERENCE_BUSINESS_KEY,
	 REFERENCE_ATTRIBUTE_NAME as REFERENCE_ATTRIBUTE_NAME,
	 REFERENCE_ATTRIBUTE_VALUE as REFERENCE_ATTRIBUTE_VALUE,
	 ERROR_CODE as ERROR_CODE,
	 ERROR_SEVERITY as ERROR_SEVERITY,
	 REFERENCE_BATCH_DETAILS_ID as REFERENCE_BATCH_DETAILS_ID,
	 ADDITIONAL_DETAILS as ADDITIONAL_DETAILS,
	 CURR_DIM_CURR_ID_EC as INPUT_ERROR_CODE_2,
	 CURR_DIM_LKP_FAIL as INPUT_ERROR_SEVERITY_2,
	 BATCH_BUSINESS_DATE as INPUT_BATCH_BUSINESS_DATE,
	 BATCH_ID as INPUT_BATCH_ID,
	 CAL_DIM_BUS_DATE_ID_LKP_FAIL as INPUT_ERROR_SEVERITY_1,
	 MEM_CPARTY_ID_NAME as INPUT_ATTRIBUTE_NAME_3,
	 WORKFLOW_NAME as INPUT_WORKFLOW_NAME,
	 MAPPING_NAME as INPUT_MAPPING_NAME,
	 BATCH_DETAILS_ID as INPUT_BATCH_DETAILS_ID,
	 TARGET_NAME as INPUT_TARGET_NAME,
	 NEXTVAL as INPUT_REFERENCE_RECORD_ID,
	 CAL_DIM_BUS_DATE_ID_NAME as INPUT_ATTRIBUTE_NAME_1,
	 CAL_DIM_BUS_DATE_ID_COMB_IN_STR as INPUT_ATTRIBUTE_VALUE_1,
	 CAL_DIM_BUS_DATE_ID_EC as INPUT_ERROR_CODE_1,
	 MEM_CPARTY_ID_COMB_IN_STR as INPUT_ATTRIBUTE_VALUE_3,
	 MEM_CPARTY_ID_ERROR_CODE as INPUT_ERROR_CODE_3,
	 MEM_CPARTY_ID_LKP_FAIL as INPUT_ERROR_SEVERITY_3,
	 CURR_DIM_CURR_ID_NAME as INPUT_ATTRIBUTE_NAME_2,
	 CURR_DIM_COMB_IN_STR as INPUT_ATTRIBUTE_VALUE_2,
	 IAN_EODIND as INPUT_ATTRIBUTE_NAME_4,
	 IAOV_EODIND as INPUT_ATTRIBUTE_VALUE_4,
	 EC_EODIND as INPUT_ERROR_CODE_4,
	 DV_RL_FLG_EODIND as INPUT_ERROR_SEVERITY_4,
	 IAN_MRG_ACCT_CTGRY as INPUT_ATTRIBUTE_NAME_5,
	 IAOV_MRG_ACCT_CTGRY as INPUT_ATTRIBUTE_VALUE_5,
	 EC_MRG_ACCT_CTGRY as INPUT_ERROR_CODE_5,
	 DV_RL_FLG_MRG_ACCT_CTGRY as INPUT_ERROR_SEVERITY_5,
	 IAN_VARIATIONMARGIN as INPUT_ATTRIBUTE_NAME_6,
	 IAOV_VARIATIONMARGIN as INPUT_ATTRIBUTE_VALUE_6,
	 EC_VARIATIONMARGIN as INPUT_ERROR_CODE_6,
	 DV_RL_FLG_VARIATIONMARGIN as INPUT_ERROR_SEVERITY_6,
	 IAN_EXCLUSIONIND as INPUT_ATTRIBUTE_NAME_7,
	 IAOV_EXCLUSIONIND as INPUT_ATTRIBUTE_VALUE_7,
	 EC_EXCLUSIONIND as INPUT_ERROR_CODE_7,
	 DV_RL_FLG_EXCLUSIONIND as INPUT_ERROR_SEVERITY_7,
	 IAN_AGENTCODE as INPUT_ATTRIBUTE_NAME_8,
	 IAOV_AGENTCODE as INPUT_ATTRIBUTE_VALUE_8,
	 EC_AGENTCODE as INPUT_ERROR_CODE_8,
	 DV_RL_FLG_AGENTCODE as INPUT_ERROR_SEVERITY_8,
	 IAN_INTENDEDSETTLEMENTDATE as INPUT_ATTRIBUTE_NAME_9,
	 IAOV_INTENDEDSETTLEMENTDATE as INPUT_ATTRIBUTE_VALUE_9,
	 EC_INTENDEDSETTLEMENTDATE as INPUT_ERROR_CODE_9,
	 DV_RL_FLG_INTENDEDSETTLEMENTDATE as INPUT_ERROR_SEVERITY_9,
	 IAN_CFDMTM as INPUT_ATTRIBUTE_NAME_10,
	 IAOV_CFDMTM as INPUT_ATTRIBUTE_VALUE_10,
	 EC_CFDMTM as INPUT_ERROR_CODE_10,
	 DV_RL_FLG_CFDMTM as INPUT_ERROR_SEVERITY_10,
	 IAN_LEGAL_ENTITY_IDENTIFIER as INPUT_ATTRIBUTE_NAME_11,
	 IAOV_LEGAL_ENTITY_IDENTIFIER as INPUT_ATTRIBUTE_VALUE_11,
	 EC_LEGAL_ENTITY_IDENTIFIER as INPUT_ERROR_CODE_11,
	 DV_RL_FLG_LEGAL_ENTITY_IDENTIFIER as INPUT_ERROR_SEVERITY_11 
From DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut as DSR_SC_mplt_DV_PROCESS_ERROR_DETAILSOut)


Select 
	ID as ID,
	PROCESS_DATE as PROCESS_DATE,
	REFERENCE_BATCH_ID as REFERENCE_BATCH_ID,
	REFERENCE_PROCESS as REFERENCE_PROCESS,
	REFERENCE_SUB_PROCESS as REFERENCE_SUB_PROCESS,
	REFERENCE_TARGET_NAME as REFERENCE_TARGET_NAME,
	REFERENCE_RECORD_ID as REFERENCE_RECORD_ID,
	REFERENCE_BUSINESS_KEY as REFERENCE_BUSINESS_KEY,
	REFERENCE_ATTRIBUTE_NAME as REFERENCE_ATTRIBUTE_NAME,
	REFERENCE_ATTRIBUTE_VALUE as REFERENCE_ATTRIBUTE_VALUE,
	ERROR_CODE as ERROR_CODE,
	ERROR_SEVERITY as ERROR_SEVERITY,
	ADDITIONAL_DETAILS as ADDITIONAL_DETAILS,
	REFERENCE_BATCH_DETAILS_ID as REFERENCE_BATCH_DETAILS_ID 
From SC_mplt_DV_PROCESS_ERROR_DETAILSOut as SC_mplt_DV_PROCESS_ERROR_DETAILSOut