/* Transformation Name ==>EXP_G20_SWP_VALUATIONSOUT_1 ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='EXP_G20_SWP_VALUATIONSOUT_1',
		schema='',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append'
	)
}}

With EXP_G20_SWP_VALUATIONSOUT_1_S4Out as (
	Select SESSION_ID_o, 
		SESSION_ID, 
		USER_ID_o, 
		USER_ID, 
		DEVICE_o, 
		DEVICE, 
		START_TIME, 
		END_TIME, 
		SUCCESS, 
		IP_ADDRESS
 from 
{{ source ('yml_Source_Name','EXP_G20_SWP_VALUATIONSOUT_1') }}
 ),

SQ_EXP_G20_SWP_VALUATIONSOUT_3011Out as (
	Select SESSION_ID, 
		USER_ID, 
		DEVICE, 
		START_TIME, 
		END_TIME, 
		SUCCESS, 
		IP_ADDRESS
 from 
{{ source ('yml_Source_Name','EXP_G20_SWP_VALUATIONSOUT_301') }} 
 ),

EXPTRANS1Out as (
	Select 
	SESSION_ID as SESSION_ID,
	 LOWER ( 'SESSION_ID_o' ) as SESSION_ID_o,
	 USER_ID as USER_ID,
	 LENGTH ( 'USER_ID_o' ) as USER_ID_o,
	 DEVICE as DEVICE,
	 UPPER ( 'DEVICE_o' ) as DEVICE_o 
From SQ_EXP_G20_SWP_VALUATIONSOUT_3011Out as SQ_EXP_G20_SWP_VALUATIONSOUT_3011Out),

LKPTRANS1Out as (
	Select 
	EXPTRANS1Out.SESSION_ID_o as SESSION_ID_o,
	 EXP_G20_SWP_VALUATIONSOUT_1_S4Out.SESSION_ID as SESSION_ID,
	 EXPTRANS1Out.USER_ID_o as USER_ID_o,
	 EXP_G20_SWP_VALUATIONSOUT_1_S4Out.USER_ID as USER_ID,
	 EXPTRANS1Out.DEVICE_o as DEVICE_o,
	 EXP_G20_SWP_VALUATIONSOUT_1_S4Out.DEVICE as DEVICE,
	 EXP_G20_SWP_VALUATIONSOUT_1_S4Out.START_TIME as START_TIME,
	 EXP_G20_SWP_VALUATIONSOUT_1_S4Out.END_TIME as END_TIME,
	 EXP_G20_SWP_VALUATIONSOUT_1_S4Out.SUCCESS as SUCCESS,
	 EXP_G20_SWP_VALUATIONSOUT_1_S4Out.IP_ADDRESS as IP_ADDRESS 
FROM
	 EXPTRANS1Out as EXPTRANS1Out 
 LEFT JOIN EXP_G20_SWP_VALUATIONSOUT_1_S4Out as EXP_G20_SWP_VALUATIONSOUT_1_S4Out 
ON
	 EXPTRANS1Out.SESSION_ID_o = EXP_G20_SWP_VALUATIONSOUT_1_S4Out.SESSION_ID And EXPTRANS1Out.USER_ID_o = EXP_G20_SWP_VALUATIONSOUT_1_S4Out.USER_ID And EXPTRANS1Out.DEVICE_o = EXP_G20_SWP_VALUATIONSOUT_1_S4Out.DEVICE
),

DSR_EXP_G20_SWP_VALUATIONSOUT_1Out as (
	Select 
	LKPTRANS1Out.SESSION_ID_o as SESSION_ID,
	 LKPTRANS1Out.USER_ID_o as USER_ID,
	 LKPTRANS1Out.DEVICE_o as DEVICE,
	 LKPTRANS1Out.START_TIME as START_TIME 
From LKPTRANS1Out as LKPTRANS1Out)



Select 
	SESSION_ID as SESSION_ID,
	USER_ID as USER_ID,
	DEVICE as DEVICE,
	START_TIME as START_TIME,
	null as END_TIME,
	null as SUCCESS,
	null as IP_ADDRESS 
From DSR_EXP_G20_SWP_VALUATIONSOUT_1Out as DSR_EXP_G20_SWP_VALUATIONSOUT_1Out