{{ config(
    materialized='incremental',
    alias='EXP_G20_SWP_VALUATIONSOUT_2',
    schema='FIVETRAN_DB',
    pre_hook="",
    post_hook="",
    incremental_strategy='append'
) }}

WITH EXP_G20_SWP_VALUATIONSOUTOut AS (
    SELECT ...
),
SQ_EXP_G20_SWP_VALUATIONSOUTOut AS (
    SELECT ...
),
EXPTRANSOut AS (
    SELECT ...
),
DSR_FILTRANSOut AS (
    SELECT ...
),
FILTRANSOut AS (
    SELECT ...
),
LKPTRANSOut AS (
    SELECT ...
)
SELECT
    _FIVETRAN_ID AS _FIVETRAN_ID,
    VALUATION_METHOD,
    VALUATION_TIMESTAMP,
    NULL AS PARTY_CODE_DISPLAY,
    NULL AS _FIVETRAN_DELETED,
    NULL AS ACTION_TYPE,
    NULL AS O_UPI,
    NULL AS NPV,
    NULL AS CURRENCY_CODE,
    NULL AS PARTY_CODE_PREFIX_ALT_DISPLAY,
    NULL AS UTI,
    NULL AS PROPRIETARY_UTI_INDICATOR,
    NULL AS O_LEGAL_ENTITY_IDENTIFIER,
    NULL AS _FIVETRAN_SYNCED
FROM LKPTRANSOut AS LKPTRANSOut
WHERE dsCheckIsNotNull(_FIVETRAN_ID);   -- ✅ WHERE comes before semicolon
