{{ config(
    materialized='incremental',
    alias='EXP_G20_SWP_VALUATIONSOUT_1',
    schema='FIVETRAN_DB',
    pre_hook="",
    post_hook="",
    incremental_strategy='append'
) }}

WITH SQ_EXP_G20_SWP_VALUATIONSOUT_301Out AS (
    SELECT SESSION_ID, USER_ID, DEVICE, START_TIME, END_TIME, SUCCESS, IP_ADDRESS
    FROM {{ source('sn_sn_c25', 'EXP_G20_SWP_VALUATIONSOUT_301') }}
),
EXP_G20_SWP_VALUATIONSOUT_1_S10Out AS (
    SELECT SESSION_ID_o, SESSION_ID, USER_ID_o, USER_ID, DEVICE_o, DEVICE, START_TIME, END_TIME, SUCCESS, IP_ADDRESS
    FROM {{ source('sn_sn_c25', 'EXP_G20_SWP_VALUATIONSOUT_1') }}
),
EXPTRANS1Out AS (
    SELECT SESSION_ID,
           LOWER(SESSION_ID) AS SESSION_ID_o,
           USER_ID,
           LENGTH(USER_ID) AS USER_ID_o,
           DEVICE,
           UPPER(DEVICE) AS DEVICE_o
    FROM SQ_EXP_G20_SWP_VALUATIONSOUT_301Out
),
LKPTRANS1Out AS (
    SELECT
        EXPTRANS1Out.SESSION_ID_o,
        EXP_G20_SWP_VALUATIONSOUT_1_S10Out.SESSION_ID,
        EXPTRANS1Out.USER_ID_o,
        EXP_G20_SWP_VALUATIONSOUT_1_S10Out.USER_ID,
        EXPTRANS1Out.DEVICE_o,
        EXP_G20_SWP_VALUATIONSOUT_1_S10Out.DEVICE,
        EXP_G20_SWP_VALUATIONSOUT_1_S10Out.START_TIME,
        EXP_G20_SWP_VALUATIONSOUT_1_S10Out.END_TIME,
        EXP_G20_SWP_VALUATIONSOUT_1_S10Out.SUCCESS,
        EXP_G20_SWP_VALUATIONSOUT_1_S10Out.IP_ADDRESS
    FROM EXPTRANS1Out
    LEFT JOIN EXP_G20_SWP_VALUATIONSOUT_1_S10Out
      ON EXPTRANS1Out.SESSION_ID_o = EXP_G20_SWP_VALUATIONSOUT_1_S10Out.SESSION_ID
     AND EXPTRANS1Out.USER_ID_o = EXP_G20_SWP_VALUATIONSOUT_1_S10Out.USER_ID
     AND EXPTRANS1Out.DEVICE_o = EXP_G20_SWP_VALUATIONSOUT_1_S10Out.DEVICE
),
DSR_EXP_G20_SWP_VALUATIONSOUT_1Out AS (
    SELECT
        LKPTRANS1Out.SESSION_ID_o AS SESSION_ID,
        LKPTRANS1Out.USER_ID_o AS USER_ID,
        LKPTRANS1Out.DEVICE_o AS DEVICE,
        LKPTRANS1Out.START_TIME,
        LKPTRANS1Out.END_TIME,
        LKPTRANS1Out.SUCCESS,
        LKPTRANS1Out.IP_ADDRESS
    FROM LKPTRANS1Out
)
SELECT
    IP_ADDRESS,
    END_TIME,
    START_TIME,
    SUCCESS,
    SESSION_ID,
    USER_ID,
    DEVICE
FROM DSR_EXP_G20_SWP_VALUATIONSOUT_1Out;
