/* Transformation Name ==>EXP_G20_SWP_VALUATION ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='EXP_G20_SWP_VALUATION',
		schema='',
		pre_hook ="",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_EXP_G20_SWP_VALUATIONSOUT1Out as (
	/* transType: "Source" */
Select _FIVETRAN_ID, 
		VALUATION_METHOD, 
		VALUATION_TIMESTAMP, 
		PARTY_CODE_DISPLAY, 
		_FIVETRAN_DELETED, 
		ACTION_TYPE, 
		O_UPI, 
		NPV, 
		CURRENCY_CODE, 
		PARTY_CODE_PREFIX_ALT_DISPLAY, 
		UTI, 
		PROPRIETARY_UTI_INDICATOR, 
		O_LEGAL_ENTITY_IDENTIFIER, 
		_FIVETRAN_SYNCED
 from 
{{ source ('EXP_G20_SWP_VALUATIONSOUT','EXP_G20_SWP_VALUATIONSOUT') }} 
 ),

EXP_G20_SWP_VALUATIONSOUTOut as (
	/* transType: "LookupSource" */
Select _FIVETRAN_ID_i, 
		_FIVETRAN_ID, 
		VALUATION_METHOD_i, 
		VALUATION_METHOD, 
		VALUATION_TIMESTAMP_i, 
		VALUATION_TIMESTAMP, 
		PARTY_CODE_DISPLAY_i, 
		PARTY_CODE_DISPLAY, 
		_FIVETRAN_DELETED_i, 
		_FIVETRAN_DELETED, 
		ACTION_TYPE, 
		ACTION_TYPE_i, 
		O_UPI, 
		O_UPI_i, 
		NPV, 
		CURRENCY_CODE, 
		PARTY_CODE_PREFIX_ALT_DISPLAY, 
		UTI, 
		PROPRIETARY_UTI_INDICATOR, 
		O_LEGAL_ENTITY_IDENTIFIER, 
		_FIVETRAN_SYNCED
 from 
{{ source ('LKPTRANS_1','EXP_G20_SWP_VALUATIONSOUT') }}
 ),

EXPTRANSOut as (
	/* transType: "Expression" */
Select 
	_FIVETRAN_ID as _FIVETRAN_ID,
	 LOWER ( _FIVETRAN_ID ) as _FIVETRAN_ID_o,
	 VALUATION_METHOD as VALUATION_METHOD,
	 UPPER ( 'VALUATION_METHOD_o' ) as VALUATION_METHOD_o,
	 VALUATION_TIMESTAMP as VALUATION_TIMESTAMP,
	 PARTY_CODE_DISPLAY as PARTY_CODE_DISPLAY,
	 LENGTH ( 'PARTY_CODE_DISPLAY_o' ) as PARTY_CODE_DISPLAY_o
From SQ_EXP_G20_SWP_VALUATIONSOUT1Out as SQ_EXP_G20_SWP_VALUATIONSOUT1Out),

DSR_FILTRANSOut as (
	/* transType: "Expression" */
Select 
	EXPTRANSOut._FIVETRAN_ID_o as _FIVETRAN_ID,
	 EXPTRANSOut.PARTY_CODE_DISPLAY_o as PARTY_CODE_DISPLAY_o,
	 EXPTRANSOut.VALUATION_TIMESTAMP as VALUATION_TIMESTAMP,
	 EXPTRANSOut.VALUATION_METHOD as VALUATION_METHOD
From EXPTRANSOut as EXPTRANSOut),

FILTRANSOut as (
	/* transType: "Filter" */
Select 
 * 
From DSR_FILTRANSOut as DSR_FILTRANSOut Where _FIVETRAN_ID IS NOT NULL),

LKPTRANSOut as (
	/* transType: "Lookup Procedure" */
Select 
	_FIVETRAN_ID as _FIVETRAN_ID,
	 VALUATION_METHOD as VALUATION_METHOD,
	 VALUATION_TIMESTAMP as VALUATION_TIMESTAMP,
	 PARTY_CODE_DISPLAY as PARTY_CODE_DISPLAY,
	 _FIVETRAN_DELETED as _FIVETRAN_DELETED,
	 ACTION_TYPE as ACTION_TYPE,
	 O_UPI as O_UPI,
	 NPV as NPV,
	 CURRENCY_CODE as CURRENCY_CODE,
	 PARTY_CODE_PREFIX_ALT_DISPLAY as PARTY_CODE_PREFIX_ALT_DISPLAY,
	 UTI as UTI,
	 PROPRIETARY_UTI_INDICATOR as PROPRIETARY_UTI_INDICATOR,
	 O_LEGAL_ENTITY_IDENTIFIER as O_LEGAL_ENTITY_IDENTIFIER,
	 _FIVETRAN_SYNCED as _FIVETRAN_SYNCED,
	 FILTRANS._FIVETRAN_ID AS _FIVETRAN_ID_i,
	 FILTRANS.VALUATION_METHOD AS VALUATION_METHOD_i,
	 FILTRANS.VALUATION_TIMESTAMP AS VALUATION_TIMESTAMP_i 
FROM
	EXP_G20_SWP_VALUATIONSOUTOut as EXP_G20_SWP_VALUATIONSOUTOut 
 LEFT JOIN EXP_G20_SWP_VALUATIONSOUTOut
ON
	_FIVETRAN_ID = _FIVETRAN_ID_i
	AND VALUATION_METHOD = VALUATION_METHOD_i
	AND VALUATION_TIMESTAMP = VALUATION_TIMESTAMP_i
	AND PARTY_CODE_DISPLAY = PARTY_CODE_DISPLAY_i
	AND ACTION_TYPE = ACTION_TYPE_i
 
)

Select 
	_FIVETRAN_ID as _FIVETRAN_ID,
	VALUATION_METHOD as VALUATION_METHOD,
	VALUATION_TIMESTAMP as VALUATION_TIMESTAMP,
	PARTY_CODE_DISPLAY as PARTY_CODE_DISPLAY,
	_FIVETRAN_DELETED as _FIVETRAN_DELETED,
	ACTION_TYPE as ACTION_TYPE,
	O_UPI as O_UPI,
	NPV as NPV,
	CURRENCY_CODE as CURRENCY_CODE 
From LKPTRANSOut as LKPTRANSOut