/* Transformation Name ==>SC_STG_SCM_LEVEL_OUTPUT_39_19_VM ,Transformation Type ==>Target */

{{
	config(
		materialized='incremental',
		alias='STG_SCM_LEVEL_OUTPUT_39_19_VM',
		schema='CFTC_SHARED',
		pre_hook ="ALTER TABLE STG_SCM_LEVEL_OUTPUT_39_19_VM TRUNCATE TABLE PARTITION P_STGSCMOP3919VM_'{{ var("region") }}' ",
		post_hook ="",
		incremental_strategy='append')
}}

With SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out as (
	Select BUSINESS_DATE, 
		MEMBER_MNEMONIC, 
		PORTFOLIO_TYPE, 
		IS_FCM, 
		CURRENCY_CODE, 
		NPV, 
		NPV_PREVIOUS_EOD, 
		NPV_CHANGE, 
		COUPON, 
		CONSIDERATION, 
		PAI, 
		ACCRUED_COUPON, 
		CONSIDERATION_PV, 
		PORTFOLIO_MARGIN_FLAG, 
		IRS_XM_PNL_AMT
 from 
{{ source('s3_to_databricks_connection', 'REGULATORY_CASHFLOW_SUMMARY') }} 
 Where REGULATORY_CASHFLOW_SUMMARY.BUSINESS_DATE = TO_DATE('{{ var("as_of_date") }}','YYYYMMDD')
 ),

SQ_SC_REGULATORY_IM_SUMMARY1Out as (
	Select BUSINESS_DATE, 
		MEMBER_MNEMONIC, 
		PORTFOLIO_TYPE, 
		IS_FCM, 
		CURRENCY_CODE, 
		IM_DF39_19, 
		ADDITIONAL_MARGIN_DF39_19, 
		IM, 
		BASIS_RISK_MARGIN, 
		CREDIT_MARGIN, 
		LIQUIDITY_MARGIN, 
		ADDITIONAL_MARGIN, 
		MINIMUM_EXCESS_REQ, 
		PORTFOLIO_MARGIN_FLAG, 
		DIVERSITY_MRGN, 
		MODEL_UNC_MRGN
 from 
{{ source('s3_to_databricks_connection', 'REGULATORY_IM_SUMMARY') }} 
 Where REGULATORY_IM_SUMMARY.BUSINESS_DATE = TO_DATE('{{ var("as_of_date") }}','YYYYMMDD')
 ),

DSR_EXP_IM_DEFAULTOut as (
	
Select 
SQ_SC_REGULATORY_IM_SUMMARY1Out.BUSINESS_DATE as BUSINESS_DATE,
SQ_SC_REGULATORY_IM_SUMMARY1Out.MEMBER_MNEMONIC as MEMBER_MNEMONIC,
SQ_SC_REGULATORY_IM_SUMMARY1Out.PORTFOLIO_TYPE as PORTFOLIO_TYPE,
SQ_SC_REGULATORY_IM_SUMMARY1Out.CURRENCY_CODE as CURRENCY_CODE,
SQ_SC_REGULATORY_IM_SUMMARY1Out.PORTFOLIO_MARGIN_FLAG as in_PORTFOLIO_MARGIN_FLAG
From SQ_SC_REGULATORY_IM_SUMMARY1Out as SQ_SC_REGULATORY_IM_SUMMARY1Out),

DSR_EXP_VM_TRIMOut as (
	
Select 
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.BUSINESS_DATE as BUSINESS_DATE,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.MEMBER_MNEMONIC as MEMBER_MNEMONIC,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.PORTFOLIO_TYPE as PORTFOLIO_TYPE,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.IS_FCM as IS_FCM,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.CURRENCY_CODE as CURRENCY_CODE,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.NPV as VM_NPV,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.NPV_PREVIOUS_EOD as VM_NPV_PREVIOUS_EOD,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.NPV_CHANGE as VM_NPV_CHANGE,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.COUPON as VM_COUPON,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.CONSIDERATION as VM_CONSIDERATION,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.PAI as VM_PAI,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.ACCRUED_COUPON as VM_ACCRUED_COUPON,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.CONSIDERATION_PV as VM_CONSIDERATION_PV,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.PORTFOLIO_MARGIN_FLAG as in_PORTFOLIO_MARGIN_FLAG,
SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out.IRS_XM_PNL_AMT as VM_IRS_XM_PNL_AMT
From SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out as SQ_SC_REGULATORY_CASHFLOW_SUMMARY1Out),

EXP_IM_DEFAULTOut as (
	
Select 
CAST ( BUSINESS_DATE,
'DD/MM/YYYY' AS STRING ) as IM_BUSINESS_DATE,
LTRIM ( RTRIM ( MEMBER_MNEMONIC ) ) as IM_MEMBER_MNEMONIC,
LTRIM ( RTRIM ( PORTFOLIO_TYPE ) ) as IM_PORTFOLIO_TYPE,
'USD' as IM_CURRENCY_CODE,
0 as IM_NPV,
0 as IM_NPV_PREVIOUS_EOD,
0 as IM_NPV_CHANGE,
0 as IM_COUPON,
0 as IM_CONSIDERATION,
0 as IM_PAI,
0 as IM_ACCRUED_COUPON,
0 as IM_CONSIDERATION_PV,
dsIff ( REGION = 'UK',
in_PORTFOLIO_MARGIN_FLAG,
'N' ) as IM_PORTFOLIO_MARGIN_FLAG
From DSR_EXP_IM_DEFAULTOut as DSR_EXP_IM_DEFAULTOut),

EXP_VM_TRIMOut as (
	
Select 
CAST ( BUSINESS_DATE,
'DD/MM/YYYY' AS STRING ) as VM_BUSINESS_DATE,
LTRIM ( RTRIM ( MEMBER_MNEMONIC ) ) as VM_MEMBER_MNEMONIC,
LTRIM ( RTRIM ( PORTFOLIO_TYPE ) ) as VM_PORTFOLIO_TYPE,
LTRIM ( RTRIM ( IS_FCM ) ) as VM_IS_FCM,
LTRIM ( RTRIM ( CURRENCY_CODE ) ) as VM_CURRENCY_CODE,
VM_NPV,
VM_NPV_PREVIOUS_EOD,
VM_NPV_CHANGE,
VM_COUPON,
VM_CONSIDERATION,
VM_PAI,
VM_ACCRUED_COUPON,
VM_CONSIDERATION_PV,
dsIff ( REGION = 'UK',
in_PORTFOLIO_MARGIN_FLAG,
'N' ) as VM_PORTFOLIO_MARGIN_FLAG,
VM_IRS_XM_PNL_AMT
From DSR_EXP_VM_TRIMOut as DSR_EXP_VM_TRIMOut),

JNR_VMIM_FOJOINOut as (
Select 
	EXP_VM_TRIMOut.VM_BUSINESS_DATE as VM_BUSINESS_DATE,
	 EXP_VM_TRIMOut.VM_MEMBER_MNEMONIC as VM_MEMBER_MNEMONIC,
	 EXP_VM_TRIMOut.VM_PORTFOLIO_TYPE as VM_PORTFOLIO_TYPE,
	 EXP_VM_TRIMOut.VM_IS_FCM as VM_IS_FCM,
	 EXP_VM_TRIMOut.VM_CURRENCY_CODE as VM_CURRENCY_CODE,
	 EXP_VM_TRIMOut.VM_NPV as VM_NPV,
	 EXP_VM_TRIMOut.VM_NPV_PREVIOUS_EOD as VM_NPV_PREVIOUS_EOD,
	 EXP_VM_TRIMOut.VM_NPV_CHANGE as VM_NPV_CHANGE,
	 EXP_VM_TRIMOut.VM_COUPON as VM_COUPON,
	 EXP_VM_TRIMOut.VM_CONSIDERATION as VM_CONSIDERATION,
	 EXP_VM_TRIMOut.VM_PAI as VM_PAI,
	 EXP_VM_TRIMOut.VM_ACCRUED_COUPON as VM_ACCRUED_COUPON,
	 EXP_VM_TRIMOut.VM_CONSIDERATION_PV as VM_CONSIDERATION_PV,
	 EXP_IM_DEFAULTOut.IM_BUSINESS_DATE as IM_BUSINESS_DATE,
	 EXP_IM_DEFAULTOut.IM_MEMBER_MNEMONIC as IM_MEMBER_MNEMONIC,
	 EXP_IM_DEFAULTOut.IM_PORTFOLIO_TYPE as IM_PORTFOLIO_TYPE,
	 EXP_IM_DEFAULTOut.IM_CURRENCY_CODE as IM_CURRENCY_CODE,
	 EXP_IM_DEFAULTOut.IM_NPV as IM_NPV,
	 EXP_IM_DEFAULTOut.IM_NPV_PREVIOUS_EOD as IM_NPV_PREVIOUS_EOD,
	 EXP_IM_DEFAULTOut.IM_NPV_CHANGE as IM_NPV_CHANGE,
	 EXP_IM_DEFAULTOut.IM_COUPON as IM_COUPON,
	 EXP_IM_DEFAULTOut.IM_CONSIDERATION as IM_CONSIDERATION,
	 EXP_IM_DEFAULTOut.IM_PAI as IM_PAI,
	 EXP_IM_DEFAULTOut.IM_ACCRUED_COUPON as IM_ACCRUED_COUPON,
	 EXP_IM_DEFAULTOut.IM_CONSIDERATION_PV as IM_CONSIDERATION_PV,
	 EXP_VM_TRIMOut.VM_PORTFOLIO_MARGIN_FLAG as VM_PORTFOLIO_MARGIN_FLAG,
	 EXP_IM_DEFAULTOut.IM_PORTFOLIO_MARGIN_FLAG as IM_PORTFOLIO_MARGIN_FLAG,
	 EXP_VM_TRIMOut.VM_IRS_XM_PNL_AMT as VM_IRS_XM_PNL_AMT,
	 EXP_IM_DEFAULTOut.jkey as jkey 
From
EXP_VM_TRIMOut as EXP_VM_TRIMOut full JOIN EXP_VM_TRIMOut as EXP_VM_TRIMOut 
ON
EXP_VM_TRIMOut.VM_BUSINESS_DATE = EXP_IM_DEFAULTOut.IM_BUSINESS_DATE And EXP_VM_TRIMOut.VM_MEMBER_MNEMONIC = EXP_IM_DEFAULTOut.IM_MEMBER_MNEMONIC And EXP_VM_TRIMOut.VM_PORTFOLIO_TYPE = EXP_IM_DEFAULTOut.IM_PORTFOLIO_TYPE And EXP_VM_TRIMOut.VM_CURRENCY_CODE = EXP_IM_DEFAULTOut.IM_PORTFOLIO_MARGIN_FLAG And EXP_VM_TRIMOut.VM_PORTFOLIO_MARGIN_FLAG = EXP_IM_DEFAULTOut.IM_PORTFOLIO_MARGIN_FLAG 
),

DSR_EXP_VM_TRANSFORMOut as (
	
Select 
JNR_VMIM_FOJOINOut.VM_BUSINESS_DATE as VM_BUSINESS_DATE,
JNR_VMIM_FOJOINOut.IM_BUSINESS_DATE as IM_BUSINESS_DATE,
JNR_VMIM_FOJOINOut.VM_MEMBER_MNEMONIC as VM_MEMBER_MNEMONIC,
JNR_VMIM_FOJOINOut.IM_MEMBER_MNEMONIC as IM_MEMBER_MNEMONIC,
JNR_VMIM_FOJOINOut.VM_PORTFOLIO_TYPE as VM_PORTFOLIO_TYPE,
JNR_VMIM_FOJOINOut.IM_PORTFOLIO_TYPE as IM_PORTFOLIO_TYPE,
JNR_VMIM_FOJOINOut.VM_IS_FCM as VM_IS_FCM,
JNR_VMIM_FOJOINOut.VM_CURRENCY_CODE as VM_CURRENCY_CODE,
JNR_VMIM_FOJOINOut.IM_CURRENCY_CODE as IM_CURRENCY_CODE,
JNR_VMIM_FOJOINOut.VM_NPV as VM_NPV,
JNR_VMIM_FOJOINOut.IM_NPV as IM_NPV,
JNR_VMIM_FOJOINOut.VM_NPV_PREVIOUS_EOD as VM_NPV_PREVIOUS_EOD,
JNR_VMIM_FOJOINOut.IM_NPV_PREVIOUS_EOD as IM_NPV_PREVIOUS_EOD,
JNR_VMIM_FOJOINOut.VM_NPV_CHANGE as VM_NPV_CHANGE,
JNR_VMIM_FOJOINOut.IM_NPV_CHANGE as IM_NPV_CHANGE,
JNR_VMIM_FOJOINOut.VM_COUPON as VM_COUPON,
JNR_VMIM_FOJOINOut.IM_COUPON as IM_COUPON,
JNR_VMIM_FOJOINOut.VM_CONSIDERATION as VM_CONSIDERATION,
JNR_VMIM_FOJOINOut.IM_CONSIDERATION as IM_CONSIDERATION,
JNR_VMIM_FOJOINOut.VM_PAI as VM_PAI,
JNR_VMIM_FOJOINOut.IM_PAI as IM_PAI,
JNR_VMIM_FOJOINOut.VM_ACCRUED_COUPON as VM_ACCRUED_COUPON,
JNR_VMIM_FOJOINOut.IM_ACCRUED_COUPON as IM_ACCRUED_COUPON,
JNR_VMIM_FOJOINOut.VM_CONSIDERATION_PV as VM_CONSIDERATION_PV,
JNR_VMIM_FOJOINOut.IM_CONSIDERATION_PV as IM_CONSIDERATION_PV,
JNR_VMIM_FOJOINOut.VM_PORTFOLIO_MARGIN_FLAG as in_VM_PORTFOLIO_MARGIN_FLAG,
JNR_VMIM_FOJOINOut.IM_PORTFOLIO_MARGIN_FLAG as in_IM_PORTFOLIO_MARGIN_FLAG,
JNR_VMIM_FOJOINOut.VM_IRS_XM_PNL_AMT as VM_IRS_XM_PNL_AMT
From JNR_VMIM_FOJOINOut as JNR_VMIM_FOJOINOut),

EXP_VM_TRANSFORMOut as (
	
Select 
DECODE ( TRUE,
dsCheckIsNotNull ( VM_MEMBER_MNEMONIC ),
VM_MEMBER_MNEMONIC,
IM_MEMBER_MNEMONIC ) as MNEMONIC,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_PORTFOLIO_TYPE ),
VM_PORTFOLIO_TYPE,
IM_PORTFOLIO_TYPE ) as ACCOUNT_TYPE,
VM_IS_FCM,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_CURRENCY_CODE ),
VM_CURRENCY_CODE,
IM_CURRENCY_CODE ) as CURRENCY_CODE,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_NPV ),
VM_NPV,
dsIff ( IM_NPV IS NULL,
0,
IM_NPV ) ) as NPV,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_NPV_PREVIOUS_EOD ),
VM_NPV_PREVIOUS_EOD,
dsIff ( IM_NPV_PREVIOUS_EOD IS NULL,
0,
IM_NPV_PREVIOUS_EOD ) ) as NPV_PREVIOUS_EOD,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_NPV_CHANGE ),
VM_NPV_CHANGE,
dsIff ( IM_NPV_CHANGE IS NULL,
0,
IM_NPV_CHANGE ) ) as NPV_CHANGE,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_COUPON ),
VM_COUPON,
dsIff ( IM_COUPON IS NULL,
0,
IM_COUPON ) ) as COUPON,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_CONSIDERATION ),
VM_CONSIDERATION,
dsIff ( IM_CONSIDERATION IS NULL,
0,
IM_CONSIDERATION ) ) as CONSIDERATION,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_PAI ),
VM_PAI,
dsIff ( IM_PAI IS NULL,
0,
IM_PAI ) ) as PAI,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_ACCRUED_COUPON ),
VM_ACCRUED_COUPON,
dsIff ( IM_ACCRUED_COUPON IS NULL,
0,
IM_ACCRUED_COUPON ) ) as ACCRUED_COUPON,
DECODE ( TRUE,
dsCheckIsNotNull ( VM_CONSIDERATION_PV ),
VM_CONSIDERATION_PV,
dsIff ( IM_CONSIDERATION_PV IS NULL,
0,
IM_CONSIDERATION_PV ) ) as CONSIDERATION_PV,
NULL as DCO_IDENTIFIER,
NULL as IRS_VARTN_MRGN,
NULL as IRS_NET_CF,
NULL as IRS_PAI,
NULL as IRS_OTHER_PAYMENTS,
NULL as IRS_NET_CPN_PAYMENT,
NULL as IRS_NET_COUPON_PAY_AMT,
TO_DATE ( AS_OF_DATE,
'YYYYMMDD' ) as MD_AS_OF_DATE,
REGION as MD_REGION,
WORKFLOW_ID as MD_WORKFLOW_RUN_ID,
dsSysVarSESSSTARTTIME as MD_LAST_DML_DATE,
DECODE ( TRUE,
dsCheckIsNotNull ( in_VM_PORTFOLIO_MARGIN_FLAG ),
in_VM_PORTFOLIO_MARGIN_FLAG,
dsIff ( in_IM_PORTFOLIO_MARGIN_FLAG IS NULL,
'N',
in_IM_PORTFOLIO_MARGIN_FLAG ) ) as VM_PORTFOLIO_MARGIN_FLAG,
VM_IRS_XM_PNL_AMT
From DSR_EXP_VM_TRANSFORMOut as DSR_EXP_VM_TRANSFORMOut),

DSR_AGG_VM_TRANSOut as (
	
Select 
EXP_VM_TRANSFORMOut.MNEMONIC as MNEMONIC,
EXP_VM_TRANSFORMOut.ACCOUNT_TYPE as ACCOUNT_TYPE,
EXP_VM_TRANSFORMOut.CURRENCY_CODE as CURRENCY_CODE,
EXP_VM_TRANSFORMOut.VM_PORTFOLIO_MARGIN_FLAG as VM_PORTFOLIO_MARGIN_FLAG,
EXP_VM_TRANSFORMOut.NPV as IN_NPV,
EXP_VM_TRANSFORMOut.NPV_PREVIOUS_EOD as IN_NPV_PREVIOUS_EOD,
EXP_VM_TRANSFORMOut.ACCRUED_COUPON as IN_ACCRUED_COUPON,
EXP_VM_TRANSFORMOut.CONSIDERATION_PV as IN_CONSIDERATION_PV,
EXP_VM_TRANSFORMOut.MD_AS_OF_DATE as MD_AS_OF_DATE,
EXP_VM_TRANSFORMOut.MD_REGION as MD_REGION,
EXP_VM_TRANSFORMOut.MD_WORKFLOW_RUN_ID as MD_WORKFLOW_RUN_ID,
EXP_VM_TRANSFORMOut.MD_LAST_DML_DATE as MD_LAST_DML_DATE,
EXP_VM_TRANSFORMOut.VM_IRS_XM_PNL_AMT as VM_IRS_XM_PNL_AMT
From EXP_VM_TRANSFORMOut as EXP_VM_TRANSFORMOut),

AGG_VM_TRANSOut as (
	with 
AGG_VM_TRANS_Out as (
 select 
	MNEMONIC as MNEMONIC,
	 ACCOUNT_TYPE as ACCOUNT_TYPE,
	 CURRENCY_CODE as CURRENCY_CODE,
	 VM_PORTFOLIO_MARGIN_FLAG as VM_PORTFOLIO_MARGIN_FLAG,
	 SUM ( IN_NPV ) as NPV,
	 SUM ( IN_NPV_PREVIOUS_EOD ) as NPV_PREVIOUS_EOD,
	 SUM ( IN_ACCRUED_COUPON ) as ACCRUED_COUPON,
	 SUM ( IN_CONSIDERATION_PV ) as CONSIDERATION_PV
 from DSR_AGG_VM_TRANSOut
 group by MNEMONIC, ACCOUNT_TYPE, CURRENCY_CODE, VM_PORTFOLIO_MARGIN_FLAG
),
AGG_VM_TRANS_NonGroupBy as (
 select 
  	MNEMONIC,
	 ACCOUNT_TYPE,
	 CURRENCY_CODE,
	 VM_PORTFOLIO_MARGIN_FLAG,
	 MD_AS_OF_DATE,
	 MD_REGION,
	 MD_WORKFLOW_RUN_ID,
	 MD_LAST_DML_DATE,
	 VM_IRS_XM_PNL_AMT
 from (
  select 
   	MNEMONIC,
	 ACCOUNT_TYPE,
	 CURRENCY_CODE,
	 VM_PORTFOLIO_MARGIN_FLAG,
	 MD_AS_OF_DATE,
	 MD_REGION,
	 MD_WORKFLOW_RUN_ID,
	 MD_LAST_DML_DATE,
	 VM_IRS_XM_PNL_AMT,
   ROW_NUMBER() OVER (
    PARTITION BY MNEMONIC, ACCOUNT_TYPE, CURRENCY_CODE, VM_PORTFOLIO_MARGIN_FLAG
    ORDER BY MNEMONIC, ACCOUNT_TYPE, CURRENCY_CODE, VM_PORTFOLIO_MARGIN_FLAG
   ) as rnk_lst
  from DSR_AGG_VM_TRANSOut
 ) t
 where rnk_lst = 1
),
AGG_VM_TRANSOut as (
 select 
	dsf_1.MNEMONIC,
	 dsf_1.ACCOUNT_TYPE,
	 dsf_1.CURRENCY_CODE,
	 dsf_1.VM_PORTFOLIO_MARGIN_FLAG,
	 dsf_1.NPV,
	 dsf_1.NPV_PREVIOUS_EOD,
	 dsf_1.ACCRUED_COUPON,
	 dsf_1.CONSIDERATION_PV,
	 dsf_2.MD_AS_OF_DATE,
	 dsf_2.MD_REGION,
	 dsf_2.MD_WORKFLOW_RUN_ID,
	 dsf_2.MD_LAST_DML_DATE,
	 dsf_2.VM_IRS_XM_PNL_AMT
 from AGG_VM_TRANS_Out dsf_1
 inner join AGG_VM_TRANS_NonGroupBy dsf_2 on dsf_1.MNEMONIC = dsf_2.MNEMONIC AND dsf_1.ACCOUNT_TYPE = dsf_2.ACCOUNT_TYPE AND dsf_1.CURRENCY_CODE = dsf_2.CURRENCY_CODE AND dsf_1.VM_PORTFOLIO_MARGIN_FLAG = dsf_2.VM_PORTFOLIO_MARGIN_FLAG
)
select * from agg_final),

EXP_VM_PASSOut as (
	
Select 
MNEMONIC,
ACCOUNT_TYPE,
CURRENCY_CODE,
NPV,
NPV_PREVIOUS_EOD,
ACCRUED_COUPON,
CONSIDERATION_PV,
MD_AS_OF_DATE,
MD_REGION,
MD_WORKFLOW_RUN_ID,
MD_LAST_DML_DATE,
VM_IRS_XM_PNL_AMT,
VM_PORTFOLIO_MARGIN_FLAG
From AGG_VM_TRANSOut as AGG_VM_TRANSOut),

DSR_SC_STG_SCM_LEVEL_OUTPUT_39_19_VMOut as (
	
Select 
EXP_VM_PASSOut.MNEMONIC as MNEMONIC,
EXP_VM_PASSOut.ACCOUNT_TYPE as ACCOUNT_TYPE,
EXP_VM_PASSOut.CURRENCY_CODE as IRS_CURRENCY,
EXP_VM_PASSOut.NPV as IRS_NPV,
EXP_VM_PASSOut.NPV_PREVIOUS_EOD as IRS_NPV_PREV,
EXP_VM_PASSOut.CONSIDERATION_PV as IRS_OTHR_PYMNT_PV,
EXP_VM_PASSOut.ACCRUED_COUPON as IRS_NET_ACCRD_COUPON,
EXP_VM_PASSOut.MD_AS_OF_DATE as MD_AS_OF_DATE,
EXP_VM_PASSOut.MD_REGION as MD_REGION,
EXP_VM_PASSOut.MD_WORKFLOW_RUN_ID as MD_WORKFLOW_RUN_ID,
EXP_VM_PASSOut.MD_LAST_DML_DATE as MD_LAST_DML_DATE,
EXP_VM_PASSOut.VM_PORTFOLIO_MARGIN_FLAG as PORTFOLIO_MARGIN_FLAG,
EXP_VM_PASSOut.VM_IRS_XM_PNL_AMT as IRS_XM_PNL_AMT
From EXP_VM_PASSOut as EXP_VM_PASSOut)


Select 
	MNEMONIC as MNEMONIC,
	ACCOUNT_TYPE as ACCOUNT_TYPE,
	IRS_CURRENCY as IRS_CURRENCY,
	IRS_NPV as IRS_NPV,
	IRS_NPV_PREV as IRS_NPV_PREV,
	IRS_OTHR_PYMNT_PV as IRS_OTHR_PYMNT_PV,
	IRS_NET_ACCRD_COUPON as IRS_NET_ACCRD_COUPON,
	MD_AS_OF_DATE as MD_AS_OF_DATE,
	MD_REGION as MD_REGION,
	MD_WORKFLOW_RUN_ID as MD_WORKFLOW_RUN_ID,
	MD_LAST_DML_DATE as MD_LAST_DML_DATE,
	PORTFOLIO_MARGIN_FLAG as PORTFOLIO_MARGIN_FLAG,
	IRS_XM_PNL_AMT as IRS_XM_PNL_AMT 
From DSR_SC_STG_SCM_LEVEL_OUTPUT_39_19_VMOut as DSR_SC_STG_SCM_LEVEL_OUTPUT_39_19_VMOut