SELECT
    'LEI_' || LPAD('abc', 5, '0') AS O_LEGAL_ENTITY_IDENTIFIER,
    PARTY_CODE_DISPLAY,
    PARTY_CODE_PREFIX_ALT_DISPLAY,
    UTI,
    o_UPI,
    NPV,
    LENGTH(CURRENCY_CODE) AS CURRENCY_CODE_LENGTH,  
    CURRENCY_CODE,                                  
    VALUATION_METHOD,
    VALUATION_TIMESTAMP,
    ACTION_TYPE,
    Proprietary_UTI_indicator
FROM
    EXP_G20_SWP_VALUATIONSOut;
