version: 2

sources:
	- name: LKPTRANS_1
		tables: 
			- name: EXP_G20_SWP_VALUATIONSOUT
	- name: EXP_G20_SWP_VALUATIONSOUT_301
		tables: 
			- name: EXP_G20_SWP_VALUATIONSOUT_301
	- name: LKPTRANS1_1
		tables: 
			- name: EXP_G20_SWP_VALUATIONSOUT_1
	- name: EXP_G20_SWP_VALUATIONSOUT
		tables: 
models:
	- name: LKPTRANSOut
	  description: " Transformation Name ->LKPTRANS, Transformation Type ->Lookup Procedure"	
	- name: EXPTRANS1Out
	  description: " Transformation Name ->EXPTRANS1, Transformation Type ->Expression"	
	- name: EXP_G20_SWP_VALUATIONSOUT_1Out
	  description: " Transformation Name ->EXP_G20_SWP_VALUATIONSOUT_1, Transformation Type ->Target"	
	- name: SQ_EXP_G20_SWP_VALUATIONSOUT1Out
	  description: " Transformation Name ->SQ_EXP_G20_SWP_VALUATIONSOUT1, Transformation Type ->Source"	
	- name: DSR_FILTRANSOut
	  description: " Transformation Name ->DSR_FILTRANS, Transformation Type ->Expression"	
	- name: EXP_G20_SWP_VALUATIONSOUTOut
	  description: " Transformation Name ->EXP_G20_SWP_VALUATIONSOUT, Transformation Type ->LookupSource"	
	- name: LKPTRANS1Out
	  description: " Transformation Name ->LKPTRANS1, Transformation Type ->Lookup Procedure"	
	- name: EXP_G20_SWP_VALUATIONSOUT_1_S4Out
	  description: " Transformation Name ->EXP_G20_SWP_VALUATIONSOUT_1_S4, Transformation Type ->LookupSource"	
	- name: FILTRANSOut
	  description: " Transformation Name ->FILTRANS, Transformation Type ->Filter"	
	- name: EXPTRANSOut
	  description: " Transformation Name ->EXPTRANS, Transformation Type ->Expression"	
	- name: EXP_G20_SWP_VALUATIONOut
	  description: " Transformation Name ->EXP_G20_SWP_VALUATION, Transformation Type ->Target"	
	- name: DSR_EXP_G20_SWP_VALUATIONSOUT_1Out
	  description: " Transformation Name ->DSR_EXP_G20_SWP_VALUATIONSOUT_1, Transformation Type ->Expression"	
	- name: SQ_EXP_G20_SWP_VALUATIONSOUT_3011Out
	  description: " Transformation Name ->SQ_EXP_G20_SWP_VALUATIONSOUT_3011, Transformation Type ->Source"	
