version: 2

sources:
  - name: sn_sn_f12
    database: FIVETRAN_DB
    schema: SN_SN_F12_DEMO_SCHEMA
    tables:
      - name: LKPTRANS_1
      - name: DSR_EXP_G20_SWP_VALUATIONSOUT_1Out
      - name: EXP_G20_SWP_VALUATIONSOUT_1
      - name: EXP_G20_SWP_VALUATIONSOUT_301
      - name: LKPTRANS1_1
      - name: FILTRANSOut
      - name: EXP_G20_SWP_VALUATIONSOUT1
      - name: sn_sn_cn7
      - name: sn_sn_c29
      - name: EXP_G20_SWP_VALUATIONSOUT_1_S10Out
      - name: sn_sn_cn
      - name: sn_sn_cm
      - name: LKPTRANSOut
      - name: SQ_EXP_G20_SWP_VALUATIONSOUT_301Out
      - name: sn_sn_f11
      - name: sn_sn_f10
      - name: EXPTRANSOut
      - name: EXP_G20_SWP_VALUATIONSOUTOut
      - name: SQ_EXP_G20_SWP_VALUATIONSOUTOut
      - name: LKPTRANS1Out
      - name: sn_sn_cn23
      - name: sn_sn_cn01
      - name: EXP_G20_SWP_VALUATIONSOUT
      - name: DSR_FILTRANSOut
      - name: sn_sn_cn02
      - name: EXPTRANS1Out
      - name: sn_sn_c40
      - name: EXP_G20_SWP_VALUATIONSOUT2Out
      - name: EXP_G20_SWP_VALUATIONSOUT_1Out

  - name: sn_sn_f13
    database: FIVETRAN_DB
    schema: SN_SN_F13_ABC
    tables:
      - name: LKPTRANS_1
      - name: DSR_EXP_G20_SWP_VALUATIONSOUT_1Out
      - name: EXP_G20_SWP_VALUATIONSOUT_1
      - name: EXP_G20_SWP_VALUATIONSOUT_301
      - name: LKPTRANS1_1
      - name: FILTRANSOut
      - name: EXP_G20_SWP_VALUATIONSOUT1
      - name: sn_sn_cn7
      - name: sn_sn_c29
      - name: EXP_G20_SWP_VALUATIONSOUT_1_S10Out
      - name: sn_sn_cn
      - name: sn_sn_cm
      - name: LKPTRANSOut
      - name: SQ_EXP_G20_SWP_VALUATIONSOUT_301Out
      - name: sn_sn_f11
      - name: sn_sn_f10
      - name: EXPTRANSOut
      - name: EXP_G20_SWP_VALUATIONSOUTOut
      - name: SQ_EXP_G20_SWP_VALUATIONSOUTOut
      - name: LKPTRANS1Out
      - name: sn_sn_cn23
      - name: sn_sn_cn01
      - name: EXP_G20_SWP_VALUATIONSOUT
      - name: DSR_FILTRANSOut
      - name: sn_sn_cn02
      - name: EXPTRANS1Out
      - name: sn_sn_c40
      - name: EXP_G20_SWP_VALUATIONSOUT2Out
      - name: EXP_G20_SWP_VALUATIONSOUT_1Out

