version: 2

sources:
  - name: sn_sn_c07
    database: FIVETRAN_DB
    schema: SN_SN_C07_DEMO_SCHEMA
    tables:
      - name: EXP_G20_SWP_VALUATIONSOUT_1
      - name: EXP_G20_SWP_VALUATIONSOUT_301
      - name: LKPTRANS1_1
      - name: EXP_G20_SWP_VALUATIONSOUT1
      - name: EXP_G20_SWP_VALUATIONSOUT

  - name: sn_sn_c08
    database: FIVETRAN_DB
    schema: SN_SN_C08_ABC
    tables:
      - name: EXP_G20_SWP_VALUATIONSOUT_1
      - name: EXP_G20_SWP_VALUATIONSOUT_301
      - name: LKPTRANS1_1
      - name: EXP_G20_SWP_VALUATIONSOUT1
      - name: EXP_G20_SWP_VALUATIONSOUT

models:
	- name: LKPTRANSOut
	  description: " Transformation Name ->LKPTRANS, Transformation Type ->Lookup Procedure"	
	- name: EXPTRANS1Out
	  description: " Transformation Name ->EXPTRANS1, Transformation Type ->Expression"	
	- name: EXP_G20_SWP_VALUATIONSOUT_1Out
	  description: " Transformation Name ->EXP_G20_SWP_VALUATIONSOUT_1, Transformation Type ->Target"	
	- name: SQ_EXP_G20_SWP_VALUATIONSOUT_301Out
	  description: " Transformation Name ->SQ_EXP_G20_SWP_VALUATIONSOUT_301, Transformation Type ->Source"	
	- name: EXP_G20_SWP_VALUATIONSOUT2Out
	  description: " Transformation Name ->EXP_G20_SWP_VALUATIONSOUT2, Transformation Type ->Target"	
	- name: DSR_FILTRANSOut
	  description: " Transformation Name ->DSR_FILTRANS, Transformation Type ->Expression"	
	- name: EXP_G20_SWP_VALUATIONSOUTOut
	  description: " Transformation Name ->EXP_G20_SWP_VALUATIONSOUT, Transformation Type ->LookupSource"	
	- name: LKPTRANS1Out
	  description: " Transformation Name ->LKPTRANS1, Transformation Type ->Lookup Procedure"	
	- name: FILTRANSOut
	  description: " Transformation Name ->FILTRANS, Transformation Type ->Filter"	
	- name: EXPTRANSOut
	  description: " Transformation Name ->EXPTRANS, Transformation Type ->Expression"	
	- name: DSR_EXP_G20_SWP_VALUATIONSOUT_1Out
	  description: " Transformation Name ->DSR_EXP_G20_SWP_VALUATIONSOUT_1, Transformation Type ->Expression"	
	- name: EXP_G20_SWP_VALUATIONSOUT_1_S10Out
	  description: " Transformation Name ->EXP_G20_SWP_VALUATIONSOUT_1_S10, Transformation Type ->LookupSource"	
	- name: SQ_EXP_G20_SWP_VALUATIONSOUTOut
	  description: " Transformation Name ->SQ_EXP_G20_SWP_VALUATIONSOUT, Transformation Type ->Source"	
